"""Regras de segurança para ABAP (SAP) — 9 regras (ABAP-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ABAP_RULES: list[Rule] = [
    Rule(
        id="ABAP-001",
        name="SQL Dinâmico via EXEC SQL com Input Externo",
        description="EXEC SQL com tokens dinâmicos construídos a partir de input do usuário permite SQL injection direta no banco de dados SAP (geralmente Oracle ou HANA). Diferente de Open SQL, EXEC SQL não tem camada de abstração SAP e opera diretamente no banco de dados com acesso nativo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.ABAP,
        pattern=r'\bEXEC\s+SQL\b',
        remediation="Substitua EXEC SQL por Open SQL com binding parameters: SELECT * FROM mara INTO TABLE lt_mara WHERE matnr = @lv_matnr. Use ADBC (ABAP Database Connectivity) com prepared statements se SQL nativo for necessário. Valide e sanitize todos os inputs com ABAP_ALPHANUM ou regex antes de usar.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ABAP-002",
        name="Injeção via CALL TRANSACTION com Nome Dinâmico",
        description="CALL TRANSACTION com nome de transação construído dinamicamente de input do usuário permite que um atacante execute qualquer transação SAP para a qual tenha autorização. Combinado com perfis amplos, pode resultar em acesso não autorizado a funcionalidades críticas do sistema.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ABAP,
        pattern=r'\bCALL\s+TRANSACTION\s+(?![\'"[A-Z])',
        remediation="Valide o nome da transação contra uma whitelist: IF tcode NOT IN lt_allowed_tcodes. RAISE EXCEPTION TYPE cx_unauthorized. ENDIF. Use AUTHORITY-CHECK OBJECT 'S_TCODE' FIELD 'TCD' VALUE tcode antes de executar. Evite nomes dinâmicos de transação.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ABAP-003",
        name="Injeção de Programa via SUBMIT com Nome Dinâmico",
        description="SUBMIT com nome de programa construído dinamicamente de input do usuário permite execução de relatórios e programas ABAP arbitrários. Um atacante pode executar programas de manutenção, extração de dados ou utilitários de sistema com os privilégios do usuário atual.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ABAP,
        pattern=r'\bSUBMIT\s+\([^)]*\)',
        remediation="Use SUBMIT com nome de programa literal sempre que possível. Para programas dinâmicos, implemente whitelist: IF prog_name NOT IN lt_allowed_programs. RAISE cx_unauthorized. ENDIF. Verifique AUTHORITY-CHECK para o objeto S_PROGRAM antes de submeter.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ABAP-004",
        name="SELECT Dinâmico com WHERE Construído de Input Externo",
        description="SELECT ... FROM ... WHERE (dynamic_where) em ABAP Open SQL com cláusula WHERE construída por concatenação de input do usuário é vulnerável a SQL injection. A sintaxe de parenteses em Open SQL aceita strings dinâmicas como cláusulas WHERE completas.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.ABAP,
        pattern=r'\bSELECT\b[^.]*\bWHERE\s+\([a-zA-Z_][a-zA-Z0-9_]*\)',
        remediation="Construa a cláusula WHERE com partes hardcoded e valores bindados: DATA(lv_where) = |matnr = '{ cl_abap_dyn_prog=>escape_string( lv_matnr ) }'|. Use cl_abap_dyn_prog=>check_whitelist_tab() para validar nomes de campo e tabela dinâmicos.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ABAP-005",
        name="Ausência de AUTHORITY-CHECK antes de Operação Sensível",
        description="Operações que acessam ou modificam dados críticos sem AUTHORITY-CHECK OBJECT correspondente violam o modelo de autorização SAP. Em sistemas configurados com perfis amplos (SAP_ALL), a ausência de checagem de autorização expõe funcionalidades a todos os usuários do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.ABAP,
        pattern=r'(?:MODIFY|DELETE|INSERT|UPDATE)\s+(?:DATABASE\s+)?[A-Z][A-Z0-9_]+',
        negative_pattern=r'AUTHORITY-CHECK',
        remediation="Adicione AUTHORITY-CHECK antes de cada operação crítica: AUTHORITY-CHECK OBJECT 'S_TABU_DIS' ID 'DICBERCLS' FIELD 'SS' ID 'ACTVT' FIELD '02'. IF sy-subrc <> 0. RAISE EXCEPTION TYPE cx_sy_no_authorization. ENDIF.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ABAP-006",
        name="Acesso Irrestrito via RFC_READ_TABLE",
        description="RFC_READ_TABLE é uma função RFC que permite leitura de qualquer tabela SAP. Exposta sem controles adequados, permite que sistemas externos ou usuários com acesso RFC leiam tabelas de configuração, dados de usuário (USR02 com hash de senha), e dados de negócio sensíveis.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.ABAP,
        pattern=r'RFC_READ_TABLE|CALL\s+FUNCTION\s+[\'"]RFC_READ_TABLE[\'"]',
        remediation="Desabilite RFC_READ_TABLE para usuários externos. Crie funções RFC específicas com AUTHORITY-CHECK implementado para cada tabela que precisa ser exposta. Use listas de controle de acesso RFC (SM59, PFCG) para restringir quais sistemas podem chamar esta função.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ABAP-007",
        name="Abertura de Arquivo com Caminho Externo — Path Traversal",
        description="OPEN DATASET com nome de arquivo construído de input do usuário permite path traversal no servidor de aplicação SAP. Um atacante pode acessar ou modificar arquivos fora do diretório esperado, incluindo arquivos de configuração SAP, logs e dados de interface.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.ABAP,
        pattern=r'\bOPEN\s+DATASET\s+(?![\'"])',
        remediation="Valide o caminho de arquivo contra um diretório base aprovado: IF NOT lv_filepath CS lv_base_dir OR lv_filepath CS '..'. RAISE EXCEPTION TYPE cx_invalid_path. ENDIF. Use FILE_GET_NAME para construir caminhos seguros a partir de parâmetros individuais validados.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ABAP-008",
        name="PERFORM Dinâmico com Nome de Form Externo",
        description="PERFORM (form_name) IN PROGRAM (prog_name) com valores dinâmicos derivados de input do usuário permite execução de rotinas ABAP arbitrárias. Pode ser usado para bypassar controles de acesso executando formas internas de outros programas.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.ABAP,
        pattern=r'\bPERFORM\s*\([a-zA-Z_][a-zA-Z0-9_]*\)',
        remediation="Elimine PERFORM dinâmico com input externo. Para despacho dinâmico legítimo, use uma tabela de despacho com whitelist de form names permitidos. Implemente AUTHORITY-CHECK para verificar que o usuário pode executar a operação representada pelo form.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ABAP-009",
        name="Cliente HTTP sem Verificação de Certificado SSL",
        description="cl_http_client=>create_by_url() com configurações padrão pode aceitar certificados SSL inválidos dependendo da configuração do servidor SAP. Chamadas HTTP a sistemas externos com verify_certificate = 'X' omitido ou desabilitado permitem ataques Man-in-the-Middle.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ABAP,
        pattern=r'cl_http_client\s*=>\s*create(?:_by_url|_by_destination)?\s*\(',
        remediation="Configure a classe de proxy SSL correta e verifique que ssl_id está configurado com um PSE válido. Use cl_http_client=>create_by_destination com destino RFC configurado com SSL ativo no SM59. Implemente verificação de certificado no callback handle_request.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
]
