"""Regras de segurança para Android Manifest (XML) — 9 regras (AXML-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ANDROID_MANIFEST_RULES: list[Rule] = [
    Rule(
        id="AXML-001",
        name="android:debuggable=\"true\" — App Depurável em Produção",
        description="'android:debuggable=\"true\"' no elemento <application> permite que o Android Debug Bridge (adb) se conecte ao app em produção. Um atacante com acesso físico ou USB ao dispositivo pode usar adb para inspecionar memória, extrair dados do app sandbox, injetar código e contornar controles de segurança.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'android:debuggable\s*=\s*["\']true["\']',
        remediation="Remova android:debuggable do AndroidManifest.xml. O Gradle build system define automaticamente debuggable=true para debug builds e false para release. Nunca defina explicitamente android:debuggable='true'. Verifique com: apktool d app.apk && grep -r debuggable smali/.",
        cwe="CWE-94",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="AXML-002",
        name="android:exported=\"true\" sem android:permission — Exposição de Componente",
        description="Activities, Services, BroadcastReceivers e ContentProviders com 'android:exported=\"true\"' sem 'android:permission' definida são acessíveis a qualquer app no dispositivo. Apps maliciosos podem invocar esses componentes sem autenticação, potencialmente bypassando o flow de autenticação.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.XML,
        pattern=r'android:exported\s*=\s*["\']true["\'](?![^>]*android:permission)',
        remediation="Adicione android:permission para restringir acesso: android:exported='true' android:permission='com.myapp.PERMISSION'. Ou defina uma permission customizada: <permission android:name='com.myapp.ACCESS' android:protectionLevel='signature'/>. Para componentes internos, use android:exported='false'.",
        cwe="CWE-284",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="AXML-003",
        name="android:usesCleartextTraffic=\"true\" — Tráfego HTTP Permitido",
        description="'android:usesCleartextTraffic=\"true\"' permite que o app faça conexões HTTP não criptografadas. Em Android 9+, o padrão é false. Habilitar cleartext traffic permite MITM em redes Wi-Fi públicas, interceptação de tokens de sessão e dados pessoais transmitidos sem TLS.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.XML,
        pattern=r'android:usesCleartextTraffic\s*=\s*["\']true["\']',
        remediation="Remova android:usesCleartextTraffic='true'. Configure Network Security Config para permitir cleartext apenas em desenvolvimento: <domain-config cleartextTrafficPermitted='false'><domain>api.example.com</domain></domain-config>. Migre todas as URLs de http:// para https://.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="AXML-004",
        name="android:allowBackup=\"true\" — Backup Permite Extração de Dados",
        description="'android:allowBackup=\"true\"' (padrão até Android 11) permite que dados do app sejam incluídos em backups do ADB e Google Drive. Um atacante com acesso USB pode extrair o backup completo do app: adb backup -f backup.ab com.target.app, obtendo dados de banco SQLite, shared preferences e arquivos privados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.XML,
        pattern=r'android:allowBackup\s*=\s*["\']true["\']',
        remediation="Defina android:allowBackup='false' para apps com dados sensíveis. Se backup é necessário, use Android Auto Backup com exclusões: <full-backup-content><exclude domain='sharedpref' path='credentials.xml'/></full-backup-content>. Nunca armazene credenciais em SharedPreferences sem criptografia.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="AXML-005",
        name="Permissão Perigosa Declarada sem Justificativa",
        description="Permissões como READ_SMS, READ_CALL_LOG, READ_CONTACTS, RECORD_AUDIO, CAMERA, ACCESS_FINE_LOCATION declaradas sem necessidade funcional clara representam coleta excessiva de dados. Apps com permissões desnecessárias têm superfície maior de ataque e violam o princípio de minimização de dados (LGPD/GDPR).",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.XML,
        pattern=r'<uses-permission\s+android:name\s*=\s*"android\.permission\.(?:READ_SMS|READ_CALL_LOG|PROCESS_OUTGOING_CALLS|RECORD_AUDIO|READ_CONTACTS|WRITE_CONTACTS)"',
        remediation="Remova permissões não essenciais. Para cada permissão, valide se existe uma funcionalidade que realmente requer ela. Use alternatives menos invasivas quando possível: CallScreeningService em vez de READ_CALL_LOG, Speech Recognition API em vez de RECORD_AUDIO direto. Documente o uso de cada permissão.",
        cwe="CWE-250",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="AXML-006",
        name="Intent-Filter sem Validação de Data — Deep Link Hijacking",
        description="Activities com <intent-filter> para deep links (scheme customizado ou http/https) sem 'android:autoVerify=\"true\"' e verificação de App Links permitem que apps maliciosos registrem o mesmo scheme e interceptem deep links. URLs como myapp://reset-password?token=X podem ser interceptadas.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.XML,
        pattern=r'<intent-filter>(?:[^<]|<(?!android:autoVerify))*<data\s+android:scheme',
        negative_pattern=r'android:autoVerify\s*=\s*["\']true["\']',
        remediation="Use Android App Links: adicione android:autoVerify='true' no intent-filter e publique o arquivo assetlinks.json em https://yourdomain.com/.well-known/assetlinks.json. Nunca passe tokens sensíveis em deep link URLs. Valide sempre o intent na Activity antes de processar.",
        cwe="CWE-924",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="AXML-007",
        name="android:sharedUserId — Compartilhamento de UID entre Apps",
        description="'android:sharedUserId' permite que múltiplos apps compartilhem o mesmo Linux UID, podendo acessar dados privados uns dos outros. Qualquer app assinado com o mesmo certificado pode declarar o mesmo sharedUserId e acessar todos os arquivos, shared preferences e bancos de dados dos outros apps.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.XML,
        pattern=r'android:sharedUserId\s*=\s*["\'][^"\']+["\']',
        remediation="Remova android:sharedUserId. Esta feature está deprecated desde Android 29 e será removida em versões futuras. Para compartilhar dados entre apps do mesmo publisher, use Content Providers com permissões de assinatura, Account Manager para autenticação compartilhada, ou um backend comum.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="AXML-008",
        name="minSdkVersion Muito Baixo — Dispositivos com Vulnerabilidades Conhecidas",
        description="'android:minSdkVersion' abaixo de 21 (Android 5.0) suporta dispositivos com vulnerabilidades críticas não corrigidas: Stagefright, CVE-2015-3824 e centenas de outras. Versões abaixo de 28 (Android 9) não têm TLS enforcement e permitem cleartext traffic por padrão.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'android:minSdkVersion\s*=\s*["\']?(?:[1-9]|1\d|20)["\']?',
        remediation="Eleve android:minSdkVersion para pelo menos 24 (Android 7.0/Nougat, ~2016) que tem N-tier network security, certificate pinning melhorado e mTLS. Para apps corporativos/financeiros, considere 26+ para biometric API. Monitore a distribuição real de versões dos seus usuários via Firebase Analytics.",
        cwe="CWE-1188",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="AXML-009",
        name="networkSecurityConfig Ausente — Configuração de Rede Padrão",
        description="Ausência de 'android:networkSecurityConfig' usa a configuração padrão do Android, que pode permitir HTTP em versões antigas, não configura certificate pinning e não define CAs confiáveis customizadas. Apps financeiros e de saúde devem ter configuração de rede explícita e restritiva.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'<application(?![^>]*android:networkSecurityConfig)',
        remediation="Adicione android:networkSecurityConfig='@xml/network_security_config' e crie res/xml/network_security_config.xml: <network-security-config><domain-config cleartextTrafficPermitted='false'><domain>api.example.com</domain><pin-set expiration='2026-01-01'><pin digest='SHA-256'>BASE64_HASH</pin></pin-set></domain-config></network-security-config>.",
        cwe="CWE-295",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
]
