"""Regras de segurança para Ansible — 9 regras (ANSIBLE-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ANSIBLE_RULES: list[Rule] = [
    Rule(
        id="ANSIBLE-001",
        name="Módulo shell/command em vez de Módulos Nativos Ansible",
        description="O uso de 'shell:' ou 'command:' para tarefas que têm módulos Ansible dedicados (apt, yum, service, file, copy) bypassa a idempotência, o tratamento de erros e as proteções contra injeção de comandos do módulo nativo. Com variáveis interpoladas em shell commands, há risco de command injection.",
        severity=Severity.MEDIUM,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.YAML,
        pattern=r'(?:shell|command)\s*:\s*(?:apt|yum|dnf|systemctl|service|mkdir|rm|chmod|chown|cp|mv|find)\b',
        remediation="Use módulos nativos: apt: {name: nginx, state: present} em vez de shell: apt-get install -y nginx. Módulos nativos são idempotentes, verificam estado antes de agir e retornam erros estruturados. Para casos sem módulo, use command: com args: para evitar shell expansion.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ANSIBLE-002",
        name="no_log: false em Task com Dados Sensíveis",
        description="'no_log: false' (explícito) ou ausência de 'no_log: true' em tasks que lidam com senhas, tokens ou chaves resultam em logging de dados sensíveis nos output do Ansible (stdout, logs de CI/CD, arquivos de log). Qualquer sistema de logging que captura output do Ansible armazena as credenciais.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'no_log\s*:\s*false',
        remediation="Use 'no_log: true' em qualquer task que processa credenciais: tasks: - name: Set password; user: { name: deploy, password: '{{ secret_password }}' }; no_log: true. Configure no_log globalmente para plays sensíveis. Use Ansible Vault para criptografar variáveis sensíveis em repouso.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ANSIBLE-003",
        name="Credencial Hardcoded em Variável Ansible",
        description="Variáveis como 'ansible_password', 'ansible_ssh_pass', 'ansible_become_pass' ou 'db_password' definidas com valores literais em playbooks, inventory files ou group_vars armazenam credenciais em plaintext no repositório git, acessíveis a todos com acesso ao código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.YAML,
        pattern=r'(?:ansible_(?:password|ssh_pass|become_pass|private_key)|password|secret|token|api_key)\s*:\s*["\']?[A-Za-z0-9+/=_\-!@#$%^&*]{8,}["\']?',
        remediation="Use Ansible Vault para criptografar secrets: ansible-vault encrypt_string 'my_password' --name 'db_password'. Armazene apenas !vault | $ANSIBLE_VAULT;1.1;AES256;... no repositório. Para CI/CD, use variáveis do sistema de CI injetadas em runtime. Considere HashiCorp Vault integration.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="ANSIBLE-004",
        name="Download via HTTP sem Verificação de Checksum",
        description="'get_url:' com URL 'http://' sem 'checksum:' baixa arquivos sem criptografia (MITM possível) e sem verificação de integridade. Um atacante na posição de MITM pode substituir o arquivo por malware. Sem checksum, qualquer arquivo alterado é aceito silenciosamente.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'get_url\s*:.*url\s*:\s*["\']?http://',
        remediation="Use HTTPS e checksum: get_url: { url: 'https://downloads.example.com/app.tar.gz', dest: /tmp/app.tar.gz, checksum: 'sha256:abc123...' }. O módulo verifica o hash após download e falha se não conferir. Para packages, prefira módulos de package manager (apt, pip, npm) que têm verificação built-in.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ANSIBLE-005",
        name="become: true sem Restrição de become_user",
        description="'become: true' sem 'become_user: specific_user' faz o Ansible escalar para root (padrão). Tasks de provisionamento que precisam instalar pacotes devem escalar para root apenas minimamente. Escalonamento desnecessário amplia o impacto de um playbook comprometido.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.YAML,
        pattern=r'become\s*:\s*(?:true|yes)(?!\s*\n\s*become_user\s*:)',
        remediation="Especifique sempre o usuário alvo: become: true; become_user: deploy_user. Aplique become no menor escopo possível (task, não play). Configure sudoers com comandos específicos: deploy_user ALL=(root) NOPASSWD: /usr/bin/systemctl restart myapp. Audite uso de become com '--check'.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ANSIBLE-006",
        name="ignore_errors: true em Tasks Críticas",
        description="'ignore_errors: true' faz o Ansible continuar mesmo quando a task falha, incluindo falhas de verificação de segurança, erros de configuração ou serviços que não iniciaram. Tasks críticas de segurança (configuração de firewall, instalação de certificados) devem sempre falhar o playbook se derem erro.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'ignore_errors\s*:\s*(?:true|yes)',
        remediation="Remova 'ignore_errors: true'. Para lidar com estados esperados de erro, use 'failed_when:': failed_when: result.rc not in [0, 1]. Use 'register:' e verifique o resultado explicitamente. Para tasks de limpeza, use 'ignore_errors: true' apenas em tasks de limpeza após failed.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ANSIBLE-007",
        name="Permissão de Arquivo 0777 — Acesso Universal",
        description="'mode: \"0777\"' ou 'mode: \"a+rwx\"' em módulos file, copy ou template cria arquivos/diretórios com permissão de leitura, escrita e execução para todos os usuários do sistema. Arquivos de configuração, scripts e dados com 0777 podem ser modificados por qualquer processo comprometido no sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'mode\s*:\s*["\']?0?777["\']?',
        remediation="Use permissões mínimas necessárias: mode: '0644' para arquivos de config (owner read/write, outros read-only), mode: '0755' para scripts executáveis, mode: '0600' para chaves e arquivos sensíveis. Configure owner: e group: apropriados. Audite com 'find / -perm -o+w -type f'.",
        cwe="CWE-732",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ANSIBLE-008",
        name="uri: com verify_ssl: false — Ignora Certificado TLS",
        description="'validate_certs: false' ou 'verify_ssl: false' em módulos uri, get_url ou outros módulos de rede desabilita verificação de certificado TLS. Isso elimina a proteção contra ataques MITM, permitindo que um atacante intercepte e modifique comunicações HTTPS em silêncio.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.YAML,
        pattern=r'validate_certs\s*:\s*(?:false|no)|verify_ssl\s*:\s*(?:false|no)',
        remediation="Nunca desabilite validação de certificados em produção. Se o problema é um certificado self-signed interno, configure a CA raiz no sistema: update-ca-certificates e adicione o bundle via 'ca_path:'. Configure ANSIBLE_SSL_CA_CERT na variável de ambiente para apontar para seu bundle de CAs internas.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ANSIBLE-009",
        name="vars_prompt sem private: yes — Senha Visível no Terminal",
        description="'vars_prompt:' sem 'private: yes' exibe os caracteres digitados em texto claro no terminal enquanto o operador digita senhas ou tokens. Qualquer pessoa que esteja vendo a tela ou gravação do terminal vê as credenciais. Terminais gravados em session recording mostrarão as senhas.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'vars_prompt\s*:\s*\n(?:\s+-[^\n]+\n)*(?:\s+[^\n]+\n)*(?!\s+private\s*:\s*yes)',
        remediation="Adicione 'private: yes' em todos os prompts de senha: vars_prompt: - { name: db_password, prompt: 'Database password', private: yes }. Prefira usar Ansible Vault ou variáveis de ambiente injetadas pelo sistema de CI/CD em vez de prompts interativos, especialmente em automação.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
]
