"""Regras de segurança para Apex (Salesforce) — 10 regras (APEX-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

APEX_RULES: list[Rule] = [
    Rule(
        id="APEX-001",
        name="Injeção SOQL via Concatenação de String Dinâmica",
        description="Construção de queries SOQL com concatenação de string em Apex: 'SELECT Id FROM Contact WHERE Name = \\'' + userInput + '\\'' é vulnerável a SOQL injection. Diferente de SQL padrão, SOQL injection pode bypassar filtros de acesso a registros, expondo dados de outros tenants ou objetos não autorizados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.APEX,
        pattern=r"(?:Database\.query|Database\.queryWithBinds|\.query)\s*\(\s*'[^']*'\s*\+",
        remediation="Use binding variables com colchetes: String name = userInput; List<Contact> contacts = [SELECT Id FROM Contact WHERE Name = :name]. Ou use String.escapeSingleQuotes() para sanitizar: String safe = String.escapeSingleQuotes(userInput). Evite Database.query() com strings dinâmicas.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-002",
        name="Injeção SOSL via Consulta de Busca Dinâmica",
        description="Search.query() ou [FIND :searchTerm IN...] com input do usuário permite SOSL injection. Um atacante pode modificar os termos de busca para retornar dados de objetos não intencionados ou bypassar filtros de visibilidade de dados no Salesforce.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.APEX,
        pattern=r'Search\.query\s*\(\s*["\']FIND\s*\{?\s*\+|Search\.query\s*\(\s*[a-zA-Z_]\w*\s*\+',
        remediation="Use binding variables em SOSL: String term = userInput; List<List<SObject>> results = [FIND :term IN ALL FIELDS RETURNING Account(Name)]. Sanitize com String.escapeSingleQuotes() para queries dinâmicas inevitáveis.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-003",
        name="Classe Apex without sharing — Bypass de Controle de Acesso",
        description="'without sharing' em classes Apex ignora as regras de compartilhamento do Salesforce e as permissões de nível de campo (FLS). A classe pode acessar e modificar QUALQUER registro do org, independente das permissões do usuário logado, violando o modelo de segurança do Salesforce.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.APEX,
        pattern=r'\bwithout\s+sharing\b',
        remediation="Use 'with sharing' em todas as classes que processam dados de usuários. Reserve 'without sharing' apenas para processos de sistema que genuinamente precisam acesso elevado e documente claramente o motivo. Considere 'inherited sharing' para classes de utilidade.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-004",
        name="DML sem Verificação de FLS / CRUD",
        description="Operações DML (insert, update, delete) em Apex sem verificar Field-Level Security (Schema.DescribeFieldResult.isCreateable(), isUpdateable()) viola o princípio de menor privilégio. O usuário logado pode não ter permissão para criar/atualizar campos específicos.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.APEX,
        pattern=r'(?:insert|update|upsert|delete)\s+(?:new\s+\w+|[a-zA-Z_]\w*)\s*;',
        remediation="Verifique permissões antes de DML: if (!Schema.sObjectType.Account.isCreateable()) { throw new AuraHandledException('Sem permissão'); }. Use o Security.stripInaccessible() do Apex Security Library para remover campos inacessíveis automaticamente antes de DML.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="APEX-005",
        name="Endpoint Hardcoded em Classe Apex / Callout",
        description="URLs hardcoded em HttpRequest.setEndpoint() tornam o código difícil de manter e podem expor URLs de sistemas internos ou de homologação que ficam no histórico git. Além disso, a URL não pode ser alterada sem deploy.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.APEX,
        pattern=r'setEndpoint\s*\(\s*["\']https?://',
        remediation="Use Custom Metadata Types ou Custom Settings para armazenar endpoints: String endpoint = Config__mdt.getInstance('API').Endpoint__c. Configure Named Credentials no Salesforce Setup para autenticação automática e endpoints gerenciados administrativamente.",
        cwe="CWE-284",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="APEX-006",
        name="Callout HTTP Não Criptografado",
        description="HttpRequest com endpoint http:// em Apex transmite dados em texto puro entre o Salesforce e sistemas externos. Salesforce requer HTTPS para Named Credentials, mas callouts diretos com http:// são possíveis e inseguros.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.APEX,
        pattern=r'setEndpoint\s*\(\s*["\']http://',
        remediation="Use sempre https:// em callouts Apex. Configure certificados SSL/TLS nos Remote Site Settings do Salesforce. Use Named Credentials com autenticação OAuth ou JWT para callouts seguros com gerenciamento centralizado de credenciais.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-007",
        name="Open Redirect via PageReference com Input Externo",
        description="new PageReference(userUrl) em Apex Visualforce cria um redirect para a URL fornecida. Sem validação, permite open redirect que leva usuários Salesforce para sites de phishing que imitam a interface do Salesforce para capturar credenciais.",
        severity=Severity.HIGH,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.APEX,
        pattern=r'new\s+PageReference\s*\(\s*(?!PageReference|Schema|\'|")',
        remediation="Valide que a URL de redirect pertence ao org Salesforce: String base = URL.getSalesforceBaseUrl().toExternalForm(); if (!userUrl.startsWith(base)) { throw new IllegalArgumentException('URL não permitida'); }. Prefira IDs de página/tab em vez de URLs brutas.",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="APEX-008",
        name="XSS via outputText sem Escape em Visualforce",
        description="<apex:outputText value=\"{!userInput}\" escape=\"false\"/> em páginas Visualforce renderiza HTML/JavaScript do usuário sem sanitização. Permite injeção de scripts que executam no contexto do Salesforce, podendo roubar sessões, modificar dados ou escalar privilégios.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.APEX,
        pattern=r'escape\s*=\s*["\']false["\']',
        remediation="Remova escape=\"false\" ou altere para escape=\"true\" (padrão). Para renderizar HTML intencional, use HTMLENCODE() em vez de escape=false: <apex:outputText value=\"{!HTMLENCODE(safeHtml)}\"/>. Sanitize HTML com uma allowlist de tags antes de marcar como safe.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-009",
        name="DML dentro de Loop For — Vulnerabilidade de Governador Limit",
        description="Operações DML (insert, update, delete) dentro de loops for em Apex consomem um limite de governador por iteração. O limite padrão é 150 operações DML por transação. Com conjuntos de dados grandes, a transação falha com 'Too many DML statements', causando negação de serviço parcial.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.APEX,
        pattern=r'for\s*\([^)]+\)\s*\{[^}]*(?:insert|update|upsert|delete)\s',
        remediation="Colete registros em uma lista fora do loop e execute DML em bulk após o loop: List<Contact> toUpdate = new List<Contact>(); for (Contact c : contacts) { c.Status__c = 'Active'; toUpdate.add(c); } update toUpdate; Isso usa apenas 1 operação DML.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="APEX-010",
        name="Credencial Hardcoded em Classe Apex",
        description="Senhas, tokens de API ou chaves de acesso como constantes String em classes Apex são armazenados em metadados do Salesforce, visíveis para administradores com acesso ao Developer Console, e incluídos em backups/exports de org.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.APEX,
        pattern=r'(?:private|public|global|protected)?\s*(?:static\s+)?(?:final\s+)?String\s+\w*(?:password|secret|token|apiKey|api_key|key)\w*\s*=\s*["\'][^"\']{6,}["\']',
        remediation="Use Custom Metadata Types criptografados ou Protected Custom Settings para armazenar segredos. Para integrações OAuth, use Named Credentials que gerenciam tokens automaticamente. Para outros segredos, use um serviço de secrets como AWS Secrets Manager via External Credentials.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
