"""
Regras de violações arquiteturais e estruturais.
Baseadas em: Clean Architecture (Martin), The Architecture of Open Source Applications,
Domain-Driven Design (Evans), Microservices Patterns (Richardson),
12-Factor App, Cloud Design Patterns (Microsoft).
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ARCHITECTURE_RULES: list[Rule] = [
    # ── Violação de Camadas ───────────────────────────────────────────────────
    Rule(
        id="ARCH-001",
        name="Acesso Direto ao Banco de Dados em Camada de Apresentação",
        description="Controller, View ou Handler acessando banco de dados diretamente. Viola a separação entre camadas de apresentação e persistência — acoplamento que torna testes e mudanças de tecnologia muito caros.",
        severity=Severity.HIGH,
        category=VulnCategory.LAYER_VIOLATION,
        language=Language.GENERIC,
        pattern=r'(?:Controller|View|Handler|Presenter)\b[^{]*\{[^}]*(?:SELECT|INSERT|UPDATE|DELETE|executeQuery|createQuery|\.query\()',
        remediation="Mova acesso a dados para a camada de repositório. Controllers devem orquestrar, não persistir. Use o padrão Repository + Service.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="ARCH-002",
        name="Lógica de Negócio em Controller",
        description="Controller contendo if/else com regras de negócio, cálculos ou validações de domínio. Controllers devem apenas receber input, chamar um serviço e retornar output.",
        severity=Severity.HIGH,
        category=VulnCategory.LAYER_VIOLATION,
        language=Language.GENERIC,
        pattern=r'(?:@?(?:Get|Post|Put|Delete|Patch)Mapping|@?app\.(?:get|post|put|delete)|router\.(?:get|post|put|delete))[^{]*\{[^}]*(?:if\s*\(.{20,}\)|for\s*\([^)]+\)\s*\{)',
        remediation="Extraia a lógica para um Service/UseCase. Controller = input validation + service call + response mapping.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ARCH-003",
        name="Import Circular entre Módulos",
        description="Módulo A importa B que importa A. Cria acoplamento bidirecional que impede evolução independente dos módulos e indica design problemático.",
        severity=Severity.HIGH,
        category=VulnCategory.COUPLING,
        language=Language.PYTHON,
        pattern=r'^from\s+\.\s*import|\bfrom\s+\.\.\s+import',
        remediation="Quebra ciclos extraindo código comum para um terceiro módulo sem dependências dos dois. Use inversão de dependência para eliminar a circularidade.",
        cwe="CWE-1047",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-004",
        name="Serialização/Deserialização sem Schema Validation",
        description="Deserialização de dados externos (JSON, XML, CSV) sem validação de schema. Permite entrada de dados malformados que causam erros em runtime ou exploração de campos não esperados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ARCHITECTURE,
        language=Language.GENERIC,
        pattern=r'(?:JSON\.parse|json\.loads|json_decode|fromJson|deserialize|JsonConvert\.DeserializeObject)\s*\(',
        negative_pattern=r'(?:schema|validate|validator|Schema|Validator|zod|joi|yup)',
        remediation="Valide dados externos contra schema antes de usar. Use bibliotecas: Zod/Joi (JS), Pydantic (Python), Bean Validation (Java), FluentValidation (.NET).",
        cwe="CWE-20",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-005",
        name="Comunicação Síncrona para Processos de Longa Duração",
        description="Operação de longa duração (envio de email, processamento de arquivo, integração externa) executada de forma síncrona no request-response cycle. Degrada UX e esgota recursos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ARCHITECTURE,
        language=Language.GENERIC,
        pattern=r'(?:sendEmail|send_email|SmtpClient|processFile|generateReport|uploadToS3|sendSMS)\s*\(',
        negative_pattern=r'(?:async|await|\.delay|celery|queue|worker|background|Job|task)',
        remediation="Use processamento assíncrono: Celery (Python), Hangfire (.NET), Spring Batch (Java), Bull (Node). Retorne 202 Accepted imediatamente e processe em background.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-006",
        name="Microserviço Chamando Banco de Dados de Outro Serviço",
        description="Padrão anti-microserviços: serviço acessa diretamente o banco de dados de outro serviço. Cria acoplamento de deployment, dados e schema impossível de escalar independentemente.",
        severity=Severity.CRITICAL,
        category=VulnCategory.ARCHITECTURE,
        language=Language.GENERIC,
        pattern=r'(?:jdbc|postgresql|mysql|mongodb)\s*://[^/]+/(?:users_db|orders_db|payments_db|inventory_db)',
        remediation="Cada serviço deve ter seu próprio banco de dados. Comunicação entre serviços via APIs ou eventos (event-driven), nunca via banco compartilhado.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ARCH-007",
        name="Ausência de Rate Limiting em Endpoint Público",
        description="Endpoint HTTP público sem proteção de rate limiting. Vulnerável a brute-force, abuso de API, DoS, e scraping excessivo.",
        severity=Severity.HIGH,
        category=VulnCategory.API_DESIGN,
        language=Language.GENERIC,
        pattern=r'(?:@?(?:Get|Post)Mapping|router\.(?:get|post))\s*\([^)]*(?:/api/|/auth/|/login|/register)',
        negative_pattern=r'(?:RateLimit|Throttle|rateLimiter|throttle|rate_limit)',
        remediation="Implemente rate limiting: Spring Rate Limiter, express-rate-limit, ASP.NET Rate Limiting Middleware. Para autenticação, limite tentativas e use backoff exponencial.",
        cwe="CWE-307",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-008",
        name="API Sem Versionamento",
        description="Endpoint de API sem indicador de versão (/v1/, /v2/, Accept: application/vnd.api+v1). Mudanças breaking na API quebram todos os clientes simultaneamente.",
        severity=Severity.LOW,
        category=VulnCategory.API_DESIGN,
        language=Language.GENERIC,
        pattern=r'["\']\/api\/(?!v\d+\/)(?!version)',
        remediation="Use versionamento na URL (/api/v1/), no header (Accept: application/vnd.company.v1+json) ou query string (?version=1). Mantenha versões antigas por período definido.",
        cwe="CWE-1109",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-009",
        name="Segredo/Configuração em Código de Configuração Commitable",
        description="Valores sensíveis em arquivos de configuração que tipicamente são versionados (application.properties, appsettings.json, config.py).",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:db\.password|database\.password|spring\.datasource\.password|ConnectionStrings\.|redis\.password)\s*[=:]\s*(?![$%@{<])\S+',
        remediation="Use variáveis de ambiente, Azure Key Vault, AWS Secrets Manager, HashiCorp Vault, ou Kubernetes Secrets. Arquivos de config devem conter apenas placeholders.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="ARCH-010",
        name="Ausência de Tratamento de Erro em Ponto de Integração",
        description="Chamada a serviço externo (HTTP, MQ, gRPC, DB) sem tratamento de falha. Serviços externos falham — sem tratamento, a falha propaga para o usuário ou trava o sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.GENERIC,
        pattern=r'(?:requests\.\w+|fetch\s*\(|axios\.\w+|RestTemplate|WebClient|HttpClient)\s*\([^;]*\)\s*;?\s*$',
        negative_pattern=r'(?:try|catch|except|\.catch|\.on\s*\(["\']error)',
        remediation="Sempre trate falhas em integrações: timeout, retry com backoff exponencial, circuit breaker (Resilience4j, Polly, Hystrix), fallback strategy.",
        cwe="CWE-755",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-011",
        name="Ausência de Idempotência em Operação de Escrita",
        description="Endpoint de criação/atualização sem mecanismo de idempotência. Re-tentativas de rede (network retries) causam criação duplicada de recursos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.API_DESIGN,
        language=Language.GENERIC,
        pattern=r'@?Post(?:Mapping)?\s*\([^)]*\)\s*\n[^{]*\{[^}]*(?:save|create|insert|persist)\s*\(',
        negative_pattern=r'(?:idempotent|Idempotency-Key|X-Request-Id|idempotencyKey)',
        remediation="Use chave de idempotência: o cliente envia X-Idempotency-Key único; o servidor detecta re-tentativas e retorna o resultado da primeira operação.",
        cwe="CWE-694",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ARCH-012",
        name="Transação de Banco Abrangendo Chamada Remota",
        description="Transação de banco de dados iniciada antes de chamada HTTP/RPC a serviço externo. Se o serviço remoto demorar, a transação fica aberta consumindo conexões do pool.",
        severity=Severity.HIGH,
        category=VulnCategory.ARCHITECTURE,
        language=Language.GENERIC,
        pattern=r'@?Transactional[^{]*\{[^}]*(?:http|requests|fetch|axios|RestTemplate|WebClient)',
        remediation="Nunca misture transações de banco com chamadas remotas. Complete a transação DB antes, ou use Saga Pattern para transações distribuídas.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
]
