"""Regras de segurança para Azure ARM Templates e Bicep — 9 regras (ARM-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ARM_RULES: list[Rule] = [
    Rule(
        id="ARM-001",
        name="Azure Storage Account com Acesso Público a Blobs",
        description="'allowBlobPublicAccess: true' em Microsoft.Storage/storageAccounts permite que qualquer pessoa na internet acesse blobs públicos sem autenticação. Dados de backup, logs de aplicação, exports de banco e outros dados sensíveis em containers públicos ficam expostos.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JSON,
        pattern=r'allowBlobPublicAccess["\s]*:\s*true',
        remediation="Defina 'allowBlobPublicAccess: false'. Para servir conteúdo estático públicamente, use Azure CDN com Shared Access Signatures (SAS) com expiração ou Azure Front Door com autenticação. Audite containers existentes com 'az storage container list --account-name <name> --query [].properties.publicAccess'.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-002",
        name="Azure SQL com allowAllWindowsAzureIps Habilitado",
        description="'allowAzureServices: true' ou a regra de firewall '0.0.0.0' a '0.0.0.0' em Microsoft.Sql/servers/firewallRules permite que qualquer serviço Azure (de qualquer cliente ou tenant) acesse o SQL Server. Inclui recursos de outros clientes Azure, não apenas os seus.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JSON,
        pattern=r'"startIpAddress"\s*:\s*"0\.0\.0\.0"',
        remediation="Substitua pela regra de firewall com IPs específicos: startIpAddress: '<IP_DO_APP_SERVICE>', endIpAddress: '<IP_DO_APP_SERVICE>'. Use Azure Private Endpoint para conectividade privada sem exposição pública. Configure Virtual Network Rules para permitir apenas sua VNet.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-003",
        name="TLS Mínimo 1.0 ou 1.1 Configurado",
        description="'minimumTlsVersion: TLS1_0' ou 'TLS1_1' em Storage Accounts, App Services ou SQL Servers permite protocolos TLS deprecated com vulnerabilidades conhecidas: BEAST, POODLE, SWEET32, CRIME. TLS 1.0 foi descontinuado pelo PCI-DSS em 2018.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.JSON,
        pattern=r'minimumTlsVersion["\s]*:\s*"TLS1_[01]"',
        remediation="Configure 'minimumTlsVersion: TLS1_2'. Para novos recursos, TLS 1.3 onde suportado. Habilite HTTPS-only: supportsHttpsTrafficOnly: true. Use Azure Policy para reforçar versão mínima TLS em todo o tenant: 'Storage accounts should use minimum TLS version of TLS 1.2'.",
        cwe="CWE-326",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-004",
        name="Azure Key Vault sem Soft Delete Habilitado",
        description="Key Vaults sem 'enableSoftDelete: true' permitem deleção permanente e imediata de secrets, keys e certificados. Um erro operacional ou ataque pode destruir credenciais críticas (chaves de criptografia, certificados TLS, connection strings) sem possibilidade de recuperação.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JSON,
        pattern=r'"enableSoftDelete"\s*:\s*false',
        remediation="Habilite 'enableSoftDelete: true' e 'enablePurgeProtection: true'. Com purge protection, items deletados ficam em retenção por 7-90 dias (configurável) antes da deleção permanente. Note que enableSoftDelete é obrigatório e não pode ser desabilitado em novos Key Vaults.",
        cwe="CWE-400",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-005",
        name="Azure Redis Cache sem SSL Obrigatório",
        description="'enableNonSslPort: true' em Microsoft.Cache/Redis abre a porta 6379 (não criptografada) além da porta SSL 6380. Conexões Redis sem TLS transmitem todos os comandos, dados e credenciais em plaintext, incluindo o password do Redis e todos os dados em cache.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.JSON,
        pattern=r'enableNonSslPort["\s]*:\s*true',
        remediation="Defina 'enableNonSslPort: false'. Todas as conexões devem usar SSL (porta 6380). Configure 'minimumTlsVersion: 1.2'. Em aplicações, use a connection string SSL: rediss://:password@host:6380. Azure SDK e StackExchange.Redis suportam SSL nativamente.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-006",
        name="Azure App Service sem HTTPS Only",
        description="'httpsOnly: false' em Microsoft.Web/sites permite requisições HTTP não criptografadas ao App Service. Credentials, session tokens e dados de usuário transmitidos via HTTP são interceptáveis. Mixed content pode expor tokens mesmo em páginas HTTPS se assets forem carregados via HTTP.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.JSON,
        pattern=r'"httpsOnly"\s*:\s*false',
        remediation="Defina 'httpsOnly: true' para forçar redirect de HTTP para HTTPS. Configure HSTS no App Service (HTTP response header: Strict-Transport-Security). Use Azure Front Door ou Application Gateway para terminação TLS centralizada com certificados gerenciados.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-007",
        name="Network Security Group com Porta Administrativa Aberta",
        description="NSGs com regras que permitem portas 22 (SSH), 3389 (RDP) ou 5985/5986 (WinRM) de qualquer origem ('*' ou '0.0.0.0/0') expõem servidores a ataques de força bruta, credential stuffing e exploração de vulnerabilidades RDP/SSH como BlueKeep ou Log4Shell via exposição direta.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JSON,
        pattern=r'"access"\s*:\s*"Allow"[^}]*"destinationPortRange"\s*:\s*"(?:22|3389|5985|5986)"[^}]*"sourceAddressPrefix"\s*:\s*"\*"',
        remediation="Remova regras que permitem SSH/RDP da internet. Use Azure Bastion para acesso administrativo seguro sem exposição de portas. Para acesso emergencial, use Just-in-Time VM Access com aprovação. Restrinja source address para IPs conhecidos da VPN corporativa.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
        flags=re.DOTALL,
    ),
    Rule(
        id="ARM-008",
        name="Azure Storage sem Transferência HTTPS Obrigatória",
        description="'supportsHttpsTrafficOnly: false' em Storage Accounts permite acesso HTTP não criptografado a blobs, filas e tabelas. Dados sendo carregados ou baixados via HTTP (SDK, AzCopy, navegador) são transmitidos em plaintext, sujeitos a interceptação.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.JSON,
        pattern=r'supportsHttpsTrafficOnly["\s]*:\s*false',
        remediation="Defina 'supportsHttpsTrafficOnly: true'. Atualize todas as connection strings de aplicações para usar 'https://' em vez de 'http://'. Use Azure Policy para auditoria: 'Secure transfer to storage accounts should be enabled'. Aplique no nível de Management Group.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ARM-009",
        name="Azure Managed Disk sem Criptografia Customizada",
        description="Managed Disks sem 'encryptionSettingsCollection' ou 'diskEncryptionSetId' usam apenas criptografia padrão da Azure (com chave gerenciada pela Microsoft). Para compliance (HIPAA, PCI-DSS), dados em repouso devem usar chaves gerenciadas pelo cliente (CMK) no Azure Key Vault.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.JSON,
        pattern=r'"Microsoft\.Compute/disks"',
        negative_pattern=r'diskEncryptionSetId|encryptionSettingsCollection',
        remediation="Configure Customer-Managed Keys: encryptionSettingsCollection: { enabled: true, encryptionSettings: [{ diskEncryptionKey: { sourceVault: { id: keyVaultId }, secretUrl: secretUrl } }] }. Para discos OS/data em VMs, use Azure Disk Encryption com chaves no Key Vault.",
        cwe="CWE-311",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
]
