import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

C_CPP_RULES: list[Rule] = [
    Rule(
        id="C-001",
        name="gets() — Unbounded Buffer Overflow",
        description="gets() reads input without bounds checking, causing stack buffer overflows. It has been removed from C11 and C++14.",
        severity=Severity.CRITICAL,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bgets\s*\(',
        remediation="Replace gets() with fgets(buf, sizeof(buf), stdin) to enforce a buffer size limit.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="C-002",
        name="strcpy() — Buffer Overflow Risk",
        description="strcpy() copies a string without checking if the destination buffer is large enough, enabling stack/heap overflow.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bstrcpy\s*\(',
        remediation="Replace with strlcpy(dst, src, sizeof(dst)) or strncpy with explicit size. Ensure null termination.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="C-003",
        name="strcat() — Buffer Overflow Risk",
        description="strcat() concatenates without bounds checking. The destination buffer may overflow if too small.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bstrcat\s*\(',
        remediation="Replace with strlcat(dst, src, sizeof(dst)) or snprintf(). Track buffer remaining capacity.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="C-004",
        name="sprintf() — Buffer Overflow Risk",
        description="sprintf() writes formatted output to a buffer without size checking. Overflow leads to memory corruption.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bsprintf\s*\(',
        remediation="Replace with snprintf(buf, sizeof(buf), ...) which enforces a maximum output size.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="C-005",
        name="scanf() without Field Width — Buffer Overflow",
        description="%s in scanf() without a field width reads unbounded input into a fixed-size buffer.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bscanf\s*\(\s*["\'][^"\']*%s',
        remediation="Use field-width specifiers: scanf(\"%255s\", buf) or use fgets() for line input.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="C-006",
        name="Format String Vulnerability",
        description="printf(user_input) passes user input as the format string. Attackers can use %n to write arbitrary memory or %s to read the stack.",
        severity=Severity.CRITICAL,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\b(?:printf|fprintf|sprintf|snprintf|wprintf)\s*\(\s*(?!s*["\'])',
        remediation="Always use a literal format string: printf(\"%s\", user_input). Never pass user data as the format argument.",
        cwe="CWE-134",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="C-007",
        name="system() Command Injection",
        description="system() executes a shell command string. User-controlled input leads to command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.C,
        pattern=r'\bsystem\s*\(',
        remediation="Use execv() or execve() with a fixed path and separated argument array. Never pass user data to system().",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="C-008",
        name="malloc() Without NULL Check",
        description="Not checking the return value of malloc() leads to null pointer dereference if allocation fails.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bmalloc\s*\([^;]+;\s*(?!\s*if\s*\()',
        remediation="Always check: if (ptr == NULL) { handle_error(); } immediately after malloc().",
        cwe="CWE-476",
        owasp="A06:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="C-009",
        name="memcpy() / memmove() Without Bounds Check",
        description="memcpy() without validating the size parameter can overflow destination buffers.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bmemcpy\s*\(',
        remediation="Validate that n <= sizeof(dst) before calling memcpy(). Use static analysis tools to enforce.",
        cwe="CWE-120",
        owasp="A06:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="C-010",
        name="strncpy() Without Null Termination",
        description="strncpy() does not null-terminate the destination if the source is longer than n. This causes undefined behavior when the string is later used.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.C,
        pattern=r'\bstrncpy\s*\(',
        remediation="Always null-terminate explicitly: dst[sizeof(dst)-1] = '\\0'; or use strlcpy() which guarantees termination.",
        cwe="CWE-170",
        owasp="A06:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="C-011",
        name="strtok() — Not Thread-Safe",
        description="strtok() uses static state and is not thread-safe. Race conditions in multi-threaded code corrupt its internal state.",
        severity=Severity.LOW,
        category=VulnCategory.RACE_CONDITION,
        language=Language.C,
        pattern=r'\bstrtok\s*\(',
        negative_pattern=r'\bstrtok_r\s*\(',
        remediation="Use the reentrant strtok_r() which takes an explicit state pointer.",
        cwe="CWE-362",
        owasp="A06:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="C-012",
        name="Use of Deprecated/Insecure tmpnam()",
        description="tmpnam() creates predictable temp file names, enabling TOCTOU race conditions and symlink attacks.",
        severity=Severity.MEDIUM,
        category=VulnCategory.RACE_CONDITION,
        language=Language.C,
        pattern=r'\btmpnam\s*\(',
        remediation="Use mkstemp() which creates and opens a unique file atomically.",
        cwe="CWE-377",
        owasp="A06:2021",
        confidence=Confidence.HIGH,
    ),
]
