"""Regras de segurança para Cairo (StarkNet) — 8 regras (CAIRO-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CAIRO_RULES: list[Rule] = [
    Rule(
        id="CAIRO-001",
        name="StorageVar sem Controle de Acesso",
        description="Funções @external em Cairo que escrevem em @storage_var sem verificar o caller (get_caller_address) permitem que qualquer conta modifique o estado do contrato. Em StarkNet, qualquer conta pode chamar funções @external — controle de acesso deve ser implementado manualmente.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.CAIRO,
        pattern=r'@external\s*\nfunc\s+\w+[^{]*\{[^}]*\}[^{]*\{[^}]*\w+\.write\s*\(',
        negative_pattern=r'assert_only_owner|let\s+caller\s*=\s*get_caller_address|assert\s+caller\b',
        remediation="Verifique o caller em todas as funções write: let caller = get_caller_address(); let owner = Ownable.owner(); assert(caller == owner, 'Not owner'). Use OpenZeppelin Cairo contracts: use openzeppelin::access::ownable::Ownable. Implemente roles com AccessControl para permissões granulares.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CAIRO-002",
        name="felt252 Overflow em Aritmética",
        description="Cairo usa felt252 (field element de 252 bits) para aritmética. Operações que excedem o campo primo resultam em wrap-around silencioso. Comparações com valores grandes podem ter resultados inesperados: felt252 não é um inteiro convencional — é um elemento de campo finito.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.CAIRO,
        pattern=r'let\s+\w+\s*:\s*felt252\s*=\s*\w+\s*[+\-\*]\s*\w+',
        remediation="Use u256 ou u128 para valores que podem ser grandes: let amount: u256 = ...; Implemente overflow checks com assert!: assert!(a + b >= a, 'Overflow'). Use integer types do Cairo: u8, u16, u32, u64, u128, u256 que têm semântica de overflow clara. Reserve felt252 para hashes e field operations.",
        cwe="CWE-190",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CAIRO-003",
        name="Proxy Upgradeable sem Controle de Acesso de Upgrade",
        description="Contratos proxy em Cairo/StarkNet com função de upgrade (replace_class_hash) sem verificação de autorização permitem que qualquer conta faça upgrade da implementação. Um atacante pode substituir a implementação por um contrato malicioso que drena os fundos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.CAIRO,
        pattern=r'replace_class_hash\s*\(',
        negative_pattern=r'assert_only_owner|assert_only_admin|only_owner',
        remediation="Proteja o upgrade com multisig e timelock: func upgrade(new_class: ClassHash) { assert_only_owner(); TimelockController.schedule(replace_class_hash, new_class, delay=7_days); }. Use OpenZeppelin StarkNet Upgrades component que inclui controle de acesso. Emita evento de upgrade para transparência.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CAIRO-004",
        name="Evento Emitido com Dados Sensíveis",
        description="Eventos em StarkNet são permanentemente armazenados na blockchain e indexados publicamente. Emitir dados sensíveis (chaves privadas, seeds, dados pessoais, valores de saldo de usuários individuais) em eventos expõe essas informações permanentemente e de forma pública.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.CAIRO,
        pattern=r'self\.emit\s*\([^)]*(?:password|secret|private_key|seed|ssn|credit_card)',
        remediation="Nunca emita dados sensíveis em eventos. Para auditoria de transferências, emita apenas sender, recipient e amount — nunca balances. Use commitments criptográficos (hash do dado) em vez do dado em si se precisar de auditabilidade sem exposição. Revise todos os eventos para compliance com LGPD/GDPR.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CAIRO-005",
        name="get_block_timestamp para Lógica de Segurança",
        description="'get_block_timestamp()' em StarkNet retorna o timestamp do bloco L2, que é derivado do timestamp L1 com alguma variação. Sequenciadores StarkNet têm alguma liberdade no ordering e timing de transações. Para leilões, votações e locks temporais críticos, essa imprecisão pode ser explorada.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.CAIRO,
        pattern=r'get_block_timestamp\s*\(\s*\)',
        remediation="Use block_number como referência de tempo mais determinística: let block = get_block_info().block_number. Para locks temporais em DeFi, considere usar o timestamp L1 via L1 message ou oráculos de tempo como Pragma. Adicione margem de segurança de pelo menos 1 bloco em verificações de deadline.",
        cwe="CWE-330",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CAIRO-006",
        name="Validação de Input Ausente em Função External",
        description="Funções @external em Cairo que aceitam felt252, u256 ou arrays de input sem validação podem receber valores malformados ou fora de range. Em Cairo, valores like u128::MAX + 1 que ultrapassam o tipo causam panic. Inputs de usuário devem sempre ser validados antes de processamento.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.CAIRO,
        pattern=r'@external\s*\nfunc\s+\w+\s*\([^)]*ref\s+\w+\s*:\s*\w+[^)]*\)',
        negative_pattern=r'assert\s*\(|require\s*\(',
        remediation="Valide todos os inputs externos: assert!(amount > 0, 'Amount must be positive'); assert!(amount <= MAX_AMOUNT, 'Amount too large'); assert!(recipient != ContractAddress(0), 'Invalid recipient'). Use traits TryInto para conversões seguras de tipos. Documente precondições em @view functions que retornam se input é válido.",
        cwe="CWE-20",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CAIRO-007",
        name="Endereço Zero como Destinatário",
        description="Enviar tokens ou transferir ownership para 'ContractAddress(0)' ou '0' em Cairo queima os ativos permanentemente. Sem verificação explícita de address != zero, erros de programação ou inputs maliciosos de usuário podem resultar em perda irreversível de tokens ou ownership.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.CAIRO,
        pattern=r'(?:transfer|send|transfer_ownership|approve)\s*\([^)]*,\s*(?:0|ContractAddress\s*\(\s*0\s*\))',
        remediation="Sempre verifique recipient != zero: assert!(recipient.is_non_zero(), 'Cannot transfer to zero address'). Adicione validação na entrada da função: fn transfer(recipient: ContractAddress, amount: u256) { assert!(recipient.is_non_zero(), 'Invalid recipient'); ... }. Implemente verificação consistente em todas as transfer functions.",
        cwe="CWE-20",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CAIRO-008",
        name="Reentrância via L1-L2 Message Handler",
        description="Handlers de mensagens L1->L2 em Cairo (@l1_handler) que interagem com outros contratos antes de atualizar estado local podem ser vulneráveis a reentrância via mensagens L1 subsequentes. Múltiplas mensagens L1 pendentes podem ser processadas em ordem inesperada pelo sequenciador.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.CAIRO,
        pattern=r'@l1_handler\s*\nfunc\s+\w+[^{]*\{[^}]*\}[^{]*\{(?:[^}])*IERC20',
        negative_pattern=r'ReentrancyGuard|reentrancy_guard',
        remediation="Siga o padrão Checks-Effects-Interactions em l1_handlers: (1) valide o sender L1, (2) atualize estado interno, (3) faça calls externas. Use ReentrancyGuard do OpenZeppelin Cairo. Para mint/burn de tokens em resposta a mensagens L1, finalize todas as atualizações de estado antes de qualquer call externa.",
        cwe="CWE-362",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
]
