"""Regras de segurança para Clojure — 9 regras (CLOJ-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CLOJURE_RULES: list[Rule] = [
    Rule(
        id="CLOJ-001",
        name="Execução de Código Dinâmico via (eval ...)",
        description="(eval ...) em Clojure executa formas Clojure arbitrárias em runtime no namespace atual. Com dados externos convertidos em formas via read-string, um atacante pode executar qualquer código Clojure, incluindo chamadas de sistema, acesso a JVM e exfiltração de dados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.CLOJURE,
        pattern=r'\(\s*eval\s+',
        remediation="Nunca use (eval) com dados externos. Para DSLs dinâmicas, defina um conjunto de funções permitidas e use um dispatcher: (def allowed-ops {'add + 'mul *}). ((allowed-ops op) a b). Para templates, use Selmer ou Hiccup com escape automático.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CLOJ-002",
        name="Injeção de Código via (load-string ...)",
        description="(load-string ...) compila e executa uma string como código Clojure completo, similar ao eval mas em contexto mais amplo. Com strings de input externo, permite execução arbitrária de código Clojure com acesso total ao namespace e JVM.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.CLOJURE,
        pattern=r'\(\s*load-string\s+',
        remediation="Elimine load-string com input externo. Reestruture a lógica para usar multiméthods ou protocols Clojure para despacho dinâmico seguro. Use (load) apenas para carregar arquivos .clj de locais confiáveis e fixos.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CLOJ-003",
        name="Injeção de Comando via clojure.java.shell/sh",
        description="(clojure.java.shell/sh \"cmd\" arg) em Clojure executa programas externos. O primeiro argumento é o executável (sem shell por padrão), mas argumentos construídos dinamicamente de input externo podem explorar comportamentos específicos do executável chamado.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.CLOJURE,
        pattern=r'\(\s*(?:sh|clojure\.java\.shell/sh)\s+',
        remediation="Valide cada argumento contra uma whitelist: (sh \"git\" \"clone\" (validate-url user-url)). Implemente validate-url que verifica protocolo (somente https), hostname e caracteres permitidos. Use bibliotecas Clojure como babashka.process para melhor controle.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CLOJ-004",
        name="Leitura de Dados Não Confiáveis via (read-string ...)",
        description="(read-string ...) em Clojure lê e avalia estruturas de dados Clojure de strings. Diferente do JSON, o formato de dados Clojure inclui construções que podem executar código arbitrário (tagged literals, #= reader macro em versões antigas). Com Clojure 1.4-, era possível executar código via read-string.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.CLOJURE,
        pattern=r'\(\s*read-string\s+',
        remediation="Use (clojure.edn/read-string ...) que é seguro e não executa código: (edn/read-string user-input). O leitor EDN não processa #= (execute) ou outras construções de execução de código. Para JSON, use clojure.data.json/read-str ou Cheshire.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CLOJ-005",
        name="Injeção SQL via Concatenação em clojure.java.jdbc / next.jdbc",
        description="(jdbc/query db (str \"SELECT * FROM users WHERE name = '\" input \"'\")) em Clojure é SQL injection clássico. As libraries de banco de dados Clojure (clojure.java.jdbc, next.jdbc, HoneySQL) suportam parâmetros bindados, mas uso direto de str/format com input externo bypassa essa proteção.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.CLOJURE,
        pattern=r'\(\s*(?:jdbc/query|jdbc/execute!|jdbc/find-by-keys|next\.jdbc/execute!)\s+\w+\s+\[\s*\(\s*str',
        remediation="Use parâmetros posicionais: (jdbc/query db [\"SELECT * FROM users WHERE name = ?\" user-name]). Com HoneySQL: (jdbc/query db (hsql/format {:select :* :from :users :where [:= :name user-name]})). Nunca construa SQL com str/format e input externo.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CLOJ-006",
        name="SSRF via (slurp url) com URL Externa",
        description="(slurp url) em Clojure faz uma requisição HTTP e retorna o conteúdo como string. Com URL construída de input do usuário, permite SSRF: acesso a metadados de cloud (169.254.169.254), serviços internos não expostos publicamente, ou scan de rede interna.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.CLOJURE,
        pattern=r'\(\s*slurp\s+(?!["\'])',
        remediation="Valide URLs antes de slurp: (defn safe-slurp [url] (let [parsed (java.net.URL. url) host (.getHost parsed)] (when-not (allowed-host? host) (throw (ex-info \"SSRF blocked\" {:host host}))) (slurp url))). Implemente allowlist de domínios e bloqueie IPs privados.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CLOJ-007",
        name="Path Traversal via (load-file ...) com Caminho Externo",
        description="(load-file path) carrega e executa um arquivo Clojure. Com caminho construído de input externo, permite tanto path traversal (ler/executar arquivos fora do diretório esperado) quanto execução de código arbitrário se o arquivo contiver código Clojure malicioso.",
        severity=Severity.CRITICAL,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.CLOJURE,
        pattern=r'\(\s*load-file\s+(?!["\'])',
        remediation="Use load-file somente com caminhos absolutamente fixos e hardcoded. Para carregar configurações, use (edn/read-string (slurp path)) com validação do caminho. Nunca permita que input externo determine qual arquivo será carregado ou executado.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CLOJ-008",
        name="Requisição HTTP sem Verificação SSL via clj-http",
        description="(client/get url {:insecure? true}) em clj-http desabilita verificação de certificado TLS. Torna a aplicação vulnerável a ataques Man-in-the-Middle. Frequentemente adicionado para contornar certificados self-signed em desenvolvimento e esquecido em produção.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.CLOJURE,
        pattern=r':insecure\?\s*true',
        remediation="Remova :insecure? true de todas as requisições de produção. Para certificados self-signed em desenvolvimento, configure um trust store específico: (client/get url {:keystore (KeyStore/getInstance ...) :keystore-pass \"...\"}). Use certificados válidos em todos os ambientes.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CLOJ-009",
        name="Credencial Hardcoded em Código Clojure",
        description="def/defn com valores literais de senhas, tokens ou chaves API em código Clojure. Namespaces de configuração frequentemente contêm esses valores e são incluídos em arquivos .clj versionados no repositório.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.CLOJURE,
        pattern=r'\(\s*def\w*\s+\w*(?:password|secret|api-key|token|auth)\w*\s+["\'][^"\']{6,}["\']',
        remediation="Use variáveis de ambiente: (def api-key (System/getenv \"API_KEY\")). Use bibliotecas como aero ou cprop para gerenciamento de configuração que lê de variáveis de ambiente. Para produção, use Vault ou AWS Secrets Manager com o SDK Java.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
