"""Regras de segurança para AWS CloudFormation — 9 regras (CFN-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CFN_RULES: list[Rule] = [
    Rule(
        id="CFN-001",
        name="S3 Bucket com ACL Pública",
        description="S3 Buckets com 'AccessControl: PublicRead', 'PublicReadWrite' ou 'AuthenticatedRead' tornam objetos publicamente acessíveis. Dados sensíveis (backups, logs, configurações) em buckets públicos são indexados por motores de busca e ferramentas como GrayhatWarfare e Shodan.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'AccessControl\s*:\s*(?:PublicRead|PublicReadWrite|AuthenticatedRead)',
        remediation="Use 'AccessControl: Private' e configure políticas de bucket. Habilite Block Public Access: PublicAccessBlockConfiguration: { BlockPublicAcls: true, BlockPublicPolicy: true, IgnorePublicAcls: true, RestrictPublicBuckets: true }. Use CloudFront com OAC para servir conteúdo público com controle.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-002",
        name="Security Group com Ingresso 0.0.0.0/0",
        description="Security Groups com 'CidrIp: 0.0.0.0/0' ou 'CidrIpv6: ::/0' em inbound rules expõem a porta para toda a internet. Portas como 22 (SSH), 3389 (RDP), 5432 (PostgreSQL), 3306 (MySQL) expostas publicamente são alvos constantes de scanners automatizados e ataques de força bruta.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'CidrIp\s*:\s*0\.0\.0\.0/0|CidrIpv6\s*:\s*::/0',
        remediation="Restrinja CIDRs ao mínimo necessário. Para administração, use VPN ou AWS Systems Manager Session Manager (zero portas abertas). Para serviços web, use apenas 443/80. Referencie outros Security Groups em vez de IPs: SourceSecurityGroupId: !Ref AppSecurityGroup.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-003",
        name="IAM com Action: '*' ou Resource: '*'",
        description="Políticas IAM com 'Action: *' ou 'Resource: *' concedem acesso irrestrito a todos os serviços AWS e recursos. Qualquer comprometimento da entidade (EC2 instance, Lambda function, usuário) com essa política resulta em controle total da conta AWS.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.YAML,
        pattern=r'Action\s*:\s*["\']?\*["\']?|Resource\s*:\s*["\']?\*["\']?',
        remediation="Aplique princípio de menor privilégio: Action: [s3:GetObject, s3:PutObject]; Resource: !Sub 'arn:aws:s3:::${BucketName}/*'. Use IAM Access Analyzer para detectar excessive permissions. Revise políticas com AWS IAM Policy Simulator. Nunca use AdministratorAccess em roles de aplicação.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-004",
        name="RDS Instance Publicamente Acessível",
        description="'PubliclyAccessible: true' em DBInstance ou DBCluster expõe o banco de dados à internet com um endpoint DNS público. Bancos de dados nunca devem ser diretamente acessíveis pela internet — todo acesso deve passar por aplicações ou bastion hosts dentro da VPC.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'PubliclyAccessible\s*:\s*true',
        remediation="Defina 'PubliclyAccessible: false'. Coloque RDS em subnets privadas sem route para internet gateway. Use AWS RDS Proxy ou Application Load Balancer para acesso externo controlado. Para acesso de desenvolvimento, use AWS SSM Session Manager com port forwarding.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-005",
        name="KMS Key sem Rotação Automática Habilitada",
        description="Chaves KMS sem 'EnableKeyRotation: true' nunca têm o material criptográfico rotacionado. Se a chave for comprometida (ex: via funcionário desonesto com acesso ao HSM da AWS), todos os dados criptografados com ela permanecem em risco. Best practices exigem rotação anual de chaves.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.YAML,
        pattern=r'Type\s*:\s*AWS::KMS::Key(?!\n(?:\s+[^\n]+\n)*\s+EnableKeyRotation\s*:\s*true)',
        remediation="Habilite rotação: Properties: { EnableKeyRotation: true }. A rotação automática ocorre anualmente e é transparente para aplicações — dados existentes podem ser decriptados com versões antigas da chave. Para chaves assimétricas, faça rotação manual criando nova chave e migrando.",
        cwe="CWE-320",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CFN-006",
        name="EC2 sem IMDSv2 (Metadata Service v2)",
        description="EC2 instances com 'HttpTokens: optional' permitem requisições IMDSv1 não autenticadas. SSRF vulnerabilities no código da aplicação podem ser usadas para acessar o endpoint de metadados (169.254.169.254), obtendo credenciais IAM temporárias do instance role — o vetor do ataque Capital One (2019).",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'HttpTokens\s*:\s*optional',
        remediation="Force IMDSv2: MetadataOptions: { HttpTokens: required, HttpEndpoint: enabled }. IMDSv2 requer um token PUT com TTL antes de qualquer acesso GET. Isso previne SSRF pois o header de token não é enviado por navegadores. Configure em account-level com AWS Config rule.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-007",
        name="CloudTrail com IsLogging: false",
        description="'IsLogging: false' em AWS::CloudTrail::Trail desabilita auditoria de todas as ações na conta AWS. Sem CloudTrail, atividade maliciosa (exfiltração de dados, criação de recursos, alteração de políticas) não fica registrada. Compliance como PCI-DSS, SOC2 e HIPAA requerem auditoria contínua.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'IsLogging\s*:\s*false',
        remediation="Mantenha 'IsLogging: true' sempre. Configure Multi-Region trail para cobrir toda a conta. Habilite Log File Validation: EnableLogFileValidation: true. Envie logs para S3 com MFA Delete e para CloudWatch Logs com metric filters para alertas de atividade suspeita.",
        cwe="CWE-778",
        owasp="A09:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFN-008",
        name="S3 sem Block Public Access Configurado",
        description="Buckets S3 sem 'PublicAccessBlockConfiguration' explícita podem ter acesso público habilitado por políticas de bucket ou ACLs. A configuração Block Public Access deve ser habilitada explicitamente em cada bucket, independente de settings account-level que podem ser sobrescritos.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'Type\s*:\s*AWS::S3::Bucket(?!\n(?:\s+[^\n]+\n)*\s+PublicAccessBlockConfiguration)',
        remediation="Adicione explicitamente: PublicAccessBlockConfiguration: { BlockPublicAcls: true, BlockPublicPolicy: true, IgnorePublicAcls: true, RestrictPublicBuckets: true }. Habilite também no account level via AWS Config rule 's3-account-level-public-access-blocks'.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CFN-009",
        name="DeletionPolicy: Delete em Recursos Críticos",
        description="'DeletionPolicy: Delete' (padrão) em recursos como RDS, DynamoDB, S3 permite que um 'aws cloudformation delete-stack' destrua dados permanentemente. Erro humano ou comprometimento de credenciais CI/CD pode resultar em perda irreversível de dados de produção.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'DeletionPolicy\s*:\s*Delete',
        remediation="Use 'DeletionPolicy: Retain' para recursos com dados persistentes. Para RDS, use 'DeletionPolicy: Snapshot' para criar um snapshot antes da deleção. Configure UpdateReplacePolicy separadamente. Implemente termination protection no stack: EnableTerminationProtection: true.",
        cwe="CWE-400",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
]
