import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

COBOL_RULES: list[Rule] = [
    Rule(
        id="COB-001",
        name="Hardcoded Password in COBOL",
        description="Password or credential appears hardcoded as a literal value in COBOL source.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.COBOL,
        pattern=r'(?:PASSWORD|PASSWD|PWD)\s+(?:PIC|VALUE\s+)[^\n]*["\'][^"\']{3,}["\']',
        remediation="Load credentials from secure external configuration or environment variables at runtime.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="COB-002",
        name="Hardcoded Database Credentials",
        description="Database username or password defined as a literal constant in COBOL.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.COBOL,
        pattern=r'(?:DB-PASSWORD|DB-USER|CONNECT-STRING)\s+(?:PIC|VALUE)',
        remediation="Retrieve credentials from a secure secrets store or parameter file protected by OS-level access controls.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="COB-003",
        name="SQL Injection in COBOL EXEC SQL",
        description="EXEC SQL statement building queries using MOVE or STRING with external input may allow SQL injection in mainframe applications.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.COBOL,
        pattern=r'EXEC\s+SQL\s+(?:EXECUTE\s+IMMEDIATE|PREPARE\s+\w+\s+FROM)',
        remediation="Use parameterized SQL with EXEC SQL PREPARE and parameter markers (?). Never concatenate user data into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="COB-004",
        name="Sensitive Data in DISPLAY Statement",
        description="DISPLAY statements outputting password, SSN, or card number fields may expose sensitive data in logs or terminals.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.COBOL,
        pattern=r'DISPLAY\s+\w*(?:PASSWORD|SSN|CARD-NUMBER|ACCOUNT)\w*',
        remediation="Mask or omit sensitive fields before logging. Apply data classification and control DISPLAY output.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="COB-005",
        name="Missing Authentication Check in CICS Program",
        description="CICS programs that do not verify user credentials or authorization may allow unauthorized access to mainframe resources.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.COBOL,
        pattern=r'EXEC\s+CICS\s+(?:RECEIVE|SEND|READ|WRITE)',
        negative_pattern=r'EXEC\s+CICS\s+VERIFY\s+PASSWORD',
        remediation="Implement EXEC CICS VERIFY PASSWORD or use RACF/TOP SECRET security calls to authenticate users before processing.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="COB-006",
        name="Unencrypted Network Communication",
        description="CICS or MQ communication without TLS/SSL encryption exposes data in transit.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.COBOL,
        pattern=r'EXEC\s+CICS\s+(?:CONNECT\s+PROCESS|SEND\s+MAP)',
        negative_pattern=r'SSL|TLS|SECURE',
        remediation="Configure CICS to use AT-TLS (Application Transparent TLS) for all external communications.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
