"""Regras de segurança para CoffeeScript — 9 regras (COFFEE-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

COFFEE_RULES: list[Rule] = [
    Rule(
        id="COFFEE-001",
        name="Execução de Código Dinâmico via eval()",
        description="eval() em CoffeeScript compila para JavaScript e herda todos os riscos do eval() do JavaScript. Como CoffeeScript é compilado, o eval pode ser menos óbvio — strings interpoladas passadas para eval são especialmente perigosas pois parecem templates seguros mas executam código arbitrário.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.COFFEESCRIPT,
        pattern=r'\beval\s*[\(\s]',
        remediation="Elimine eval() completamente. Para parsing de JSON, use JSON.parse(). Para expressões matemáticas, use uma biblioteca de parsing segura. Em templates CoffeeScript, valide e escape input do usuário antes de qualquer avaliação.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="COFFEE-002",
        name="Interpolação de JavaScript Literal via Backtick",
        description="Em CoffeeScript, code entre backticks (`) é inserido literalmente como JavaScript sem ser processado pelo compilador CoffeeScript. Isso bypassa as proteções de sintaxe do CoffeeScript e pode ocultar código JavaScript ofuscado ou malicioso em projetos que verificam a qualidade do código CoffeeScript.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.COFFEESCRIPT,
        pattern=r'`[^`]{3,}`',
        remediation="Evite backticks literais em CoffeeScript. Qualquer JavaScript que precise ser incorporado deve ser reescrito em CoffeeScript nativo ou movido para um arquivo .js separado e claramente documentado. Nunca use backticks com input externo.",
        cwe="CWE-94",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="COFFEE-003",
        name="Injeção de Comando via child_process.exec em Node.js CoffeeScript",
        description="exec() e execSync() do módulo child_process executam comandos via shell quando chamados com string única. Em aplicações Node.js escritas em CoffeeScript, este padrão é frequente em scripts de build e ferramentas CLI onde o input pode vir de arguments do processo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.COFFEESCRIPT,
        pattern=r'(?:exec|execSync)\s*[(\s]["\']|require\s*\([\'"]child_process[\'"]\).*exec',
        remediation="Use execFile() ou spawn() com array de argumentos: {execFile} = require 'child_process'; execFile 'git', ['clone', userUrl], (err, stdout) -> ... Isso evita interpretação shell. Valide todos os argumentos antes de passar.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="COFFEE-004",
        name="XSS via Atribuição Direta a innerHTML",
        description="element.innerHTML = userInput em CoffeeScript/JavaScript renderiza HTML incluindo scripts sem sanitização. A natureza concisa do CoffeeScript pode tornar estas atribuições menos óbvias — $ '#div' .html userInput é igualmente perigoso.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.COFFEESCRIPT,
        pattern=r'\.innerHTML\s*=\s*(?!["\']<(?:br|hr|p|div|span|ul|li|a)[>"\']\s*$)|\.html\s*\(\s*(?!["\']\s*["\']\s*\))',
        remediation="Use textContent em vez de innerHTML: element.textContent = userInput. Para jQuery, use .text() em vez de .html() para conteúdo de usuário. Quando HTML é necessário, sanitize com DOMPurify: element.innerHTML = DOMPurify.sanitize(userInput).",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="COFFEE-005",
        name="XSS via document.write() com Conteúdo Dinâmico",
        description="document.write() em CoffeeScript insere HTML diretamente no documento. Com input do usuário, permite injeção de HTML e JavaScript. Além do XSS, document.write() após o carregamento da página sobrescreve o DOM completamente, causando perda de conteúdo.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.COFFEESCRIPT,
        pattern=r'\bdocument\.write\s*\(',
        remediation="Nunca use document.write() em código moderno. Use document.createElement() e appendChild(), ou manipule innerHTML/textContent diretamente. Para injeção de scripts dinâmicos, use DOM APIs seguras: script = document.createElement 'script'; script.src = trustedUrl; document.head.appendChild script.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="COFFEE-006",
        name="XSS via $.html() / jQuery com Input do Usuário",
        description="$('#element').html(userInput) ou $(userInput) no jQuery renderiza HTML fornecido pelo usuário. Em aplicações CoffeeScript com jQuery (padrão em aplicações Rails/Backbone), este padrão é ubíquo e frequentemente inseguro.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.COFFEESCRIPT,
        pattern=r'\$\s*\([^)]+\)\s*\.html\s*\(\s*[a-zA-Z_$]',
        remediation="Use .text() para conteúdo de texto puro. Para HTML seguro, sanitize antes: $el.html DOMPurify.sanitize(content). Para templating, use Handlebars ou Mustache com escape automático em vez de jQuery .html() manual.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="COFFEE-007",
        name="Requisição AJAX/Fetch para URL HTTP Não Criptografada",
        description="$.ajax, fetch() ou XMLHttpRequest com URLs http:// em CoffeeScript transmitem dados em texto puro. Mixed content (HTTP em página HTTPS) é bloqueado por browsers modernos, mas código server-side CoffeeScript (Node.js) pode fazer requisições http:// sem restrição.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.COFFEESCRIPT,
        pattern=r'(?:fetch|ajax|\$\.get|\$\.post|XMLHttpRequest)\s*[(\s]["\']http://',
        remediation="Use https:// em todas as URLs de produção. Para APIs internas, configure TLS mesmo em redes privadas. Em desenvolvimento, use http://localhost mas garanta que as URLs de produção usem variáveis de ambiente que nunca contenham http://.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="COFFEE-008",
        name="require() com Caminho Dinâmico de Input Externo",
        description="require() com caminho construído de input externo em CoffeeScript/Node.js permite carregamento de módulos arbitrários do sistema de arquivos. Um atacante pode carregar módulos Node.js built-in (fs, child_process) ou scripts de caminhos inesperados.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.COFFEESCRIPT,
        pattern=r'\brequire\s*\(\s*[a-zA-Z_$][a-zA-Z0-9_$]*\s*[\+\<]',
        remediation="Use require() somente com strings literais fixas. Implemente uma factory com whitelist de módulos: loadPlugin = (name) -> allowed = {utils: true, helpers: true}; throw Error('not allowed') unless allowed[name]; require(\"./plugins/#{name}\").",
        cwe="CWE-94",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="COFFEE-009",
        name="Credencial Exposta em process.env ou Hardcoded",
        description="Variáveis de ambiente com nomes sensíveis (PASSWORD, SECRET, TOKEN) acessadas diretamente no código CoffeeScript, ou strings literais contendo credenciais. Arquivos .coffee em repositórios frequentemente contêm configurações que migram de desenvolvimento para produção sem sanitização.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.COFFEESCRIPT,
        pattern=r'(?:password|secret|api_key|token|auth)\s*[=:]\s*["\'][^"\'$\{]{6,}["\']',
        remediation="Use variáveis de ambiente via process.env: apiKey = process.env.API_KEY or throw Error 'API_KEY required'. Para aplicações Rails com CoffeeScript, use o mecanismo de secrets do Rails (config/credentials.yml.enc). Nunca comite .env files.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
