"""
Regras de anti-patterns de concorrência e programação assíncrona.
Baseadas em: Java Concurrency in Practice (Goetz), The Art of Multiprocessor Programming,
Concurrency in Go, async/await best practices.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CONCURRENCY_RULES: list[Rule] = [
    Rule(
        id="CONC-001",
        name="Campo Estático Mutável Compartilhado sem Sincronização",
        description="Campo static mutável acessado por múltiplas threads sem sincronização. Causa race condition: leituras e escritas concorrentes produzem resultados indefinidos.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.JAVA,
        pattern=r'\bprivate\s+static\s+(?!final)\s*(?!volatile)\s*(?:int|long|double|List|Map|Set|String|boolean)\s+\w+\s*[=;]',
        remediation="Use AtomicInteger/AtomicLong, ConcurrentHashMap, CopyOnWriteArrayList, ou sincronize com synchronized/ReentrantLock. Declare volatile para visibilidade.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CONC-002",
        name="Double-Checked Locking sem volatile (Broken DCL)",
        description="Padrão Double-Checked Locking sem declarar o campo como volatile. Em Java, o compilador pode reordenar instruções, tornando DCL sem volatile incorreto e inseguro.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.JAVA,
        pattern=r'if\s*\(\s*\w+\s*==\s*null\s*\)\s*\{\s*synchronized\s*\([^)]+\)\s*\{\s*if\s*\(\s*\w+\s*==\s*null\s*\)',
        remediation="Declare o campo como volatile: private volatile Singleton instance; Ou use Initialization-on-demand holder idiom que é thread-safe sem sincronização.",
        cwe="CWE-362",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CONC-003",
        name="Thread.sleep() como Mecanismo de Sincronização",
        description="Usar Thread.sleep() para aguardar condição de outro thread. Busy waiting com sleep é impreciso, desperdiça recursos e cria race windows.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.JAVA,
        pattern=r'Thread\.sleep\s*\(\d+\)',
        remediation="Use primitivas de sincronização adequadas: CountDownLatch, Semaphore, CyclicBarrier, BlockingQueue, ou java.util.concurrent locks.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CONC-004",
        name="Uso de HashMap em Contexto Concorrente",
        description="HashMap não é thread-safe. Uso concorrente sem sincronização causa corrupção estrutural interna, ciclos infinitos em resize e dados perdidos silenciosamente.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.JAVA,
        pattern=r'\bHashMap\s*<|new\s+HashMap\s*\(',
        remediation="Use ConcurrentHashMap para acesso concorrente. Para Map imutável compartilhado: Collections.unmodifiableMap() ou Map.of().",
        cwe="CWE-362",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CONC-005",
        name="async/await Dentro de forEach (JS/TS)",
        description="await dentro de Array.forEach() não funciona como esperado — forEach não respeita async/await e não espera as promises resolverem.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'\.forEach\s*\(\s*async\s+',
        remediation="Use for...of com await, ou Promise.all() para paralelismo: await Promise.all(arr.map(async item => { ... }))",
        cwe="CWE-362",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CONC-006",
        name="Promise.all() sem Tratamento de Rejeição",
        description="Promise.all() rejeita imediatamente ao primeiro erro, deixando promises pendentes sem tratamento. Promise.allSettled() é mais robusto para a maioria dos casos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVASCRIPT,
        pattern=r'\bPromise\.all\s*\(',
        negative_pattern=r'\.catch\s*\(',
        remediation="Use Promise.allSettled() para aguardar todas, ou adicione .catch() para tratar rejeição individual. Lembre que .catch() final captura a primeira rejeição.",
        cwe="CWE-755",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CONC-007",
        name="Goroutine sem Mecanismo de Cancelamento (Go)",
        description="Goroutine iniciada sem contexto com deadline/cancel. Goroutines órfãs consomem recursos indefinidamente se o processo pai não termina.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CONCURRENCY,
        language=Language.GO,
        pattern=r'\bgo\s+func\s*\(\s*\)',
        negative_pattern=r'(?:context\.WithCancel|context\.WithTimeout|context\.WithDeadline|ctx\.Done)',
        remediation="Passe context.Context para goroutines: go func(ctx context.Context) { select { case <-ctx.Done(): return } }(ctx)",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CONC-008",
        name="Variável de Closure em Loop sem Captura Explícita",
        description="Em JS/Go/Python, variável de loop capturada em closure referencía a última iteração, não a iteração atual. Bug clássico de closure + loop.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'for\s*\(\s*var\s+\w+\s*=',
        remediation="Use let em vez de var: for (let i = 0; ...) — let tem escopo de bloco. Ou crie IIFE: (function(i) { ... })(i);",
        cwe="CWE-362",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CONC-009",
        name="Lock sem Timeout (Potencial Deadlock)",
        description="Aquisição de lock/mutex sem timeout pode bloquear indefinidamente se o thread que segura o lock falhar ou criar deadlock com outro lock.",
        severity=Severity.HIGH,
        category=VulnCategory.DEADLOCK,
        language=Language.JAVA,
        pattern=r'\.lock\s*\(\s*\)',
        negative_pattern=r'\.tryLock\s*\(',
        remediation="Use tryLock com timeout: if (lock.tryLock(5, TimeUnit.SECONDS)) { try { ... } finally { lock.unlock(); } } Sempre use finally para unlock.",
        cwe="CWE-833",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CONC-010",
        name="GIL Bypass Inadequado com Threads Python para CPU-Bound",
        description="Uso de threading.Thread para trabalho CPU-bound em Python. O GIL impede paralelismo real em threads Python para operações CPU-bound — threads Python são para I/O.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'\bthreading\.Thread\s*\([^)]*target\s*=\s*\w+',
        remediation="Para CPU-bound: use multiprocessing.Pool ou concurrent.futures.ProcessPoolExecutor. Para I/O-bound: threads são adequadas, ou use asyncio.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CONC-011",
        name="Task.Run() sem Await (Fire-and-Forget não Rastreável)",
        description="Task.Run() sem await cria task 'fire and forget'. Exceções são silenciadas, não é possível aguardar conclusão e impede graceful shutdown.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CSHARP,
        pattern=r'Task\.Run\s*\([^;]+\)\s*;(?!\s*//)',
        negative_pattern=r'(?:await\s+Task\.Run|\.ContinueWith|\.ConfigureAwait)',
        remediation="Use await Task.Run() para aguardar. Para background jobs: use IHostedService/BackgroundService com CancellationToken para shutdown limpo.",
        cwe="CWE-755",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CONC-012",
        name="Variável Compartilhada sem atomic em Go",
        description="Variável acessada por múltiplas goroutines sem sync/mutex ou atomic. Go race detector detecta isso como data race.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.GO,
        pattern=r'\bvar\s+\w+\s+(?:int|int64|bool|string)\s*$',
        negative_pattern=r'(?:sync\.Mutex|sync\.RWMutex|atomic\.|sync\.Map)',
        remediation="Use sync.Mutex para proteção: var mu sync.Mutex; mu.Lock(); defer mu.Unlock(). Ou atomic.AddInt64 para contadores simples.",
        cwe="CWE-362",
        confidence=Confidence.LOW,
    ),
]
