"""
Regras de segurança para arquivos de configuração: YAML, TOML, INI, JSON, .env.
Detecta credenciais, chaves e configurações inseguras hardcoded em config files.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CONFIG_RULES: list[Rule] = [
    Rule(
        id="CFG-001",
        name="Senha/Credencial em Arquivo YAML de Configuração",
        description="Chaves password, secret ou passwd com valor literal em YAML. Arquivos de configuração são frequentemente commitados no repositório, expondo credenciais para todos com acesso ao código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.YAML,
        pattern=r'(?:password|passwd|secret|api_key|apikey|access_key)\s*:\s*(?!""\s*$|null\b|\$\{|\{\{)["\']?[A-Za-z0-9!@#$%^&*+/=_.\-]{6,}["\']?',
        remediation="Use variáveis de ambiente: password: ${DB_PASSWORD}. Configure .gitignore para excluir arquivos de configuração com segredos. Use HashiCorp Vault ou similar.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CFG-002",
        name="Token / Chave Privada em YAML",
        description="Campos como token, private_key, access_token, refresh_token com valores literais em YAML. Tokens OAuth, JWT secrets e API keys não devem ficar em arquivos versionados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.YAML,
        pattern=r'(?:token|private_key|access_token|refresh_token|jwt_secret|signing_key)\s*:\s*["\']?[A-Za-z0-9+/=_.\-]{16,}["\']?',
        remediation="Exclua arquivos com segredos do git. Use variáveis de ambiente ou secrets manager. Para Kubernetes, use Secrets (base64) com encriptação at-rest habilitada.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CFG-003",
        name="Credencial em Arquivo TOML",
        description="Password, secret ou token com valor literal em Cargo.toml, pyproject.toml, config.toml. Amplamente usado em projetos Rust, Python e outros — credenciais não devem estar nesses arquivos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.TOML,
        pattern=r'(?:password|passwd|secret|api_key|token)\s*=\s*["\'][^"\'${}]{6,}["\']',
        remediation="Use variáveis de ambiente referenciadas no TOML: password = \"${DB_PASSWORD}\". Ou configure via arquivo separado não versionado.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CFG-004",
        name="Credencial em Arquivo INI / .properties / .env",
        description="Chaves password=, secret=, api_key= em arquivos .ini, .properties ou .env com valores literais. Arquivos .env frequentemente são commitados acidentalmente, especialmente por desenvolvedores iniciantes.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.INI,
        pattern=r'(?:password|passwd|secret|api_key|apikey|token|private_key)\s*=\s*(?!\$)[^\s\n]{4,}',
        remediation="Adicione .env ao .gitignore imediatamente. Use .env.example com valores fictícios para documentar variáveis necessárias. Verifique histórico git e rotacione credenciais expostas.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CFG-005",
        name="Credencial em JSON de Configuração",
        description="Campos password, secret, api_key com valores literais em JSON. Especialmente perigoso em package.json, appsettings.json e arquivos de configuração de CI/CD.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.JSON,
        pattern=r'"(?:password|passwd|secret|api_key|apikey|token|private_key)"\s*:\s*"[^"${}]{6,}"',
        remediation="Substitua valores por placeholders e passe via variáveis de ambiente em runtime. Use Azure Key Vault, AWS SSM Parameter Store, ou equivalente.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="CFG-006",
        name="Debug Mode Habilitado em Configuração de Produção",
        description="debug: true, DEBUG=True, ou APP_ENV=development em configuração que parece ser de produção. Debug mode expõe stack traces, configurações internas e frequentemente desabilita proteções de segurança.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'(?:debug|DEBUG)\s*:\s*(?:true|True|1|yes|YES)',
        remediation="Defina debug: false em configurações de produção. Use variáveis de ambiente para controlar o modo: DEBUG=${APP_DEBUG:-false}",
        cwe="CWE-94",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CFG-007",
        name="Chave SSH / PEM Privada em Arquivo de Config",
        description="-----BEGIN PRIVATE KEY----- ou -----BEGIN RSA PRIVATE KEY----- hardcoded em arquivos de configuração. Chaves privadas nunca devem ser commitadas em repositórios.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----|-----BEGIN\s+EC\s+PRIVATE',
        remediation="Remova IMEDIATAMENTE a chave do repositório. Gere uma nova chave. Revogue a chave comprometida. Use git-secrets ou pre-commit hooks para prevenir commits de chaves.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFG-008",
        name="URL de Banco de Dados com Credenciais Embutidas",
        description="postgresql://user:senha@host/db, mysql://root:pass@... em arquivos de configuração expõem credenciais de banco em texto simples.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:postgresql|mysql|mongodb|redis|mssql|oracle)\s*://[^:@/\s]+:[^@\s]{3,}@',
        remediation="Use URLs sem credenciais e configure autenticação separadamente via variáveis de ambiente ou IAM roles. Nunca coloque senha na connection string em configuração versionada.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFG-009",
        name="CORS Allow-All (*) em Configuração",
        description="Access-Control-Allow-Origin: * ou cors: origins: ['*'] em produção permite que qualquer site faça requisições autenticadas para a API, bypassando proteções CSRF.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r"(?:origins|allow-origins|allowed_origins)\s*:\s*[\"']?\*[\"']?",
        remediation="Especifique origens explícitas: origins: ['https://app.example.com']. Nunca use * em produção para endpoints autenticados.",
        cwe="CWE-942",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CFG-010",
        name="Webhook Secret ou Callback URL com Token na Config",
        description="Webhook secrets, callback URLs com tokens, ou chaves de integração de terceiros hardcoded em arquivos de configuração YAML/JSON/TOML.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.YAML,
        pattern=r'(?:webhook_secret|callback_secret|signing_secret|github_token|slack_token|discord_token)\s*:\s*["\']?[A-Za-z0-9_.\-/+]{16,}["\']?',
        remediation="Mova para variáveis de ambiente. Rotacione os tokens expostos imediatamente via dashboards das respectivas plataformas.",
        cwe="CWE-798",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
