"""Regras de segurança para Crystal — 9 regras (CRYSTAL-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CRYSTAL_RULES: list[Rule] = [
    Rule(
        id="CRYSTAL-001",
        name="Injeção de Comando via system() / Process.run",
        description="system() e Process.run() em Crystal executam comandos externos. Com strings construídas de input externo, metacaracteres shell permitem injeção de comandos. Crystal compila para binários nativos eficientes — vulnerabilidades de injeção têm impacto direto no sistema host.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.CRYSTAL,
        pattern=r'\bsystem\s*\(\s*(?!["\'](?:ls|pwd|echo|cat|grep|find)\b)|Process\.run\s*\(\s*(?!["\'])',
        remediation="Use Process.run com array de argumentos para evitar interpretação shell: Process.run(\"git\", [\"clone\", user_url], output: Process::Redirect::Pipe). Valide user_url com URI.parse antes de usar. Nunca construa strings de comando com interpolação de input externo.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CRYSTAL-002",
        name="Execução de Comando via Backtick / `cmd`",
        description="Expressões com backtick em Crystal (`ls -la #{path}`) executam comandos via shell e retornam a saída. Com interpolação de variáveis externas (#{path}), permitem injeção de comandos completa incluindo todos os metacaracteres shell.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.CRYSTAL,
        pattern=r'`[^`]*#\{',
        remediation="Substitua backticks por Process.run com array de argumentos: output = IO::Memory.new; Process.run(\"ls\", [\"-la\", safe_path], output: output); output.to_s. Nunca interpole variáveis externas em backticks Crystal.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CRYSTAL-003",
        name="Ponteiro Bruto via Pointer.new — Acesso Direto à Memória",
        description="Pointer(T).new(address) em Crystal cria um ponteiro para um endereço de memória arbitrário. Sem validação, o endereço pode ser nulo, fora dos limites alocados ou em região de memória de outro processo. Crystal é memory-safe por padrão — o uso de Pointer bypassa essas garantias.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.CRYSTAL,
        pattern=r'Pointer\s*\(\s*\w+\s*\)\s*\.new\s*\(',
        remediation="Evite Pointer.new com endereços dinâmicos. Para interoperabilidade C, use os tipos de ponteiro gerados automaticamente pelo binding: lib MyLib; fun func(x : Int32) : Int32*; end. Use Pointer.null para ponteiros nulos e verifique pointer.null? antes de desreferenciar.",
        cwe="CWE-119",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CRYSTAL-004",
        name="Binding LibC sem Verificação de Retorno de Erro",
        description="Chamadas a funções C via LibC em Crystal sem verificar valores de retorno de erro. Funções C retornam NULL, -1 ou setam errno para indicar falha. Ignorar esses erros resulta em uso de ponteiros nulos, dados inválidos ou comportamento indefinido.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CRYSTAL,
        pattern=r'\bLibC\.\w+\s*\(',
        remediation="Verifique retornos de erro: result = LibC.open(path, LibC::O_RDONLY, 0); if result < 0; raise Errno.new(\"open failed\"); end. Use Errno.value para acessar errno. Para ponteiros, verifique null: ptr = LibC.malloc(size); raise \"malloc failed\" if ptr.null?",
        cwe="CWE-252",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CRYSTAL-005",
        name="Path Traversal via File.read / File.open com Input Externo",
        description="File.read(path), File.open(path) ou File::Info.new(path) em Crystal com caminhos construídos de input externo permitem path traversal. Sequências ../ acessam arquivos fora do diretório base esperado, incluindo arquivos de configuração, chaves e dados privados.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.CRYSTAL,
        pattern=r'File\.(?:read|open|write|delete|rename)\s*\(\s*(?!["\'])',
        remediation="Normalize e valide caminhos: base = Path[\"/safe/uploads\"].expand; target = (base / user_input).expand; unless target.to_s.starts_with?(base.to_s); raise \"path traversal\"; end; File.read(target). Use Path#expand para resolver .. e symlinks.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CRYSTAL-006",
        name="Conexão HTTP Não Criptografada via HTTP::Client",
        description="HTTP::Client.get(\"http://...\") ou new HTTP::Client(URI.parse(\"http://...\")) em Crystal transmite dados sem criptografia. Em microserviços Crystal de alta performance, credenciais de API e dados sensíveis em HTTP são facilmente interceptáveis.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.CRYSTAL,
        pattern=r'HTTP::Client\.\w+\s*\(\s*["\']http://|new\s+HTTP::Client\s*\(\s*URI\.parse\s*\(\s*["\']http://',
        remediation="Use https:// em todas as URLs: HTTP::Client.get(\"https://api.example.com/data\"). Configure TLS: context = OpenSSL::SSL::Context::Client.new; client = HTTP::Client.new(\"api.example.com\", tls: context). Nunca desabilite verificação de certificado em produção.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CRYSTAL-007",
        name="Tratamento de Erros em spawn Sem Rescue",
        description="spawn { codigo_que_pode_falhar } em Crystal cria uma fiber (coroutine) que executa concorrentemente. Exceções não capturadas dentro de um spawn terminam a fiber silenciosamente sem propagar para a fiber pai. Isso pode causar estado inconsistente e falhas silenciosas em servidores Crystal.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CRYSTAL,
        pattern=r'\bspawn\s*\{[^}]*\}',
        negative_pattern=r'rescue|begin',
        remediation="Capture exceções dentro do spawn: spawn do; begin; risky_operation; rescue ex : Exception; Log.error(exception: ex) { \"Fiber falhou\" }; end; end. Para comunicação entre fibers, use Channel(Exception?) para propagar erros de volta ao código chamador.",
        cwe="CWE-390",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="CRYSTAL-008",
        name="YAML.parse sem Validação de Tipo — Anchor Bomb",
        description="YAML.parse(user_input) em Crystal processa YAML completo incluindo anchors e aliases. O ataque 'Billion Laughs' usa aliases YAML exponenciais (um anchor referenciado 9x criando 1 bilhão de objetos) para causar DoS por esgotamento de memória durante o parsing.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.CRYSTAL,
        pattern=r'YAML\.parse\s*\(\s*(?!["\'])',
        remediation="Limite o tamanho do YAML antes de parsear: raise \"too large\" if input.bytesize > MAX_YAML_SIZE. Use YAML::PullParser para controle granular. Considere JSON em vez de YAML para dados externos — JSON não tem anchors/aliases. Valide o schema após parsing.",
        cwe="CWE-400",
        owasp="A06:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CRYSTAL-009",
        name="Credencial Hardcoded em Código Crystal",
        description="Constantes ou variáveis com senhas, tokens ou chaves API definidos como strings literais em código Crystal. Binários Crystal compilados podem ser inspecionados com strings(1) para extrair literais string, incluindo credenciais hardcoded.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.CRYSTAL,
        pattern=r'(?:PASSWORD|SECRET|API_KEY|TOKEN|AUTH)\s*=\s*["\'][^"\']{6,}["\']|(?:password|secret|api_key|token)\s*=\s*["\'][^"\'$#\{]{6,}["\']',
        remediation="Use variáveis de ambiente: api_key = ENV[\"API_KEY\"]? || raise \"API_KEY not set\". Para aplicações Crystal com configuração, use o shard crenv ou yaml-config que lê arquivos .env. Configure secrets no sistema de CI/CD sem expor em código.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
]
