import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

CSHARP_RULES: list[Rule] = [
    Rule(
        id="CS-001",
        name="SQL Injection via String Concatenation",
        description="SqlCommand constructed with string concatenation allows SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.CSHARP,
        pattern=r'new\s+SqlCommand\s*\(\s*["\'][^"\']*["\'\s]\s*\+',
        remediation="Use parameterized queries: cmd.Parameters.AddWithValue(\"@param\", userInput); Never concatenate user input.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-002",
        name="SQL Injection via CommandText Concatenation",
        description="Assigning a concatenated string to SqlCommand.CommandText enables SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.CSHARP,
        pattern=r'\.CommandText\s*=\s*["\'][^"\']*["\'\s]*\+',
        remediation="Use SqlParameter objects: cmd.Parameters.Add(new SqlParameter(\"@id\", userId));",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-003",
        name="Command Injection via Process.Start()",
        description="Process.Start() with user-controlled arguments enables OS command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.CSHARP,
        pattern=r'Process\.Start\s*\(',
        remediation="Validate and allowlist all arguments. Use ProcessStartInfo with a fixed FileName and controlled Arguments.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CS-004",
        name="Insecure Deserialization (BinaryFormatter)",
        description="BinaryFormatter is insecure and deserialization of attacker-controlled data leads to Remote Code Execution. Microsoft has deprecated it.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.CSHARP,
        pattern=r'\bBinaryFormatter\b',
        remediation="Replace BinaryFormatter with System.Text.Json or MessagePack. BinaryFormatter is officially deprecated and disabled by default in .NET 5+.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-005",
        name="Insecure Deserialization (NetDataContractSerializer)",
        description="NetDataContractSerializer deserializes type information from the stream, allowing attackers to craft malicious payloads.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.CSHARP,
        pattern=r'\bNetDataContractSerializer\b',
        remediation="Use DataContractSerializer with a known-types allowlist, or prefer System.Text.Json.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-006",
        name="Weak Cryptographic Hash (MD5)",
        description="MD5CryptoServiceProvider and MD5.Create() produce MD5 hashes which are cryptographically broken.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.CSHARP,
        pattern=r'\b(?:MD5CryptoServiceProvider|MD5\.Create)\b',
        remediation="Use SHA256.Create() or SHA512.Create(). For passwords use PasswordHasher<T> (ASP.NET Core Identity).",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-007",
        name="Weak Cryptographic Hash (SHA1)",
        description="SHA1Managed / SHA1CryptoServiceProvider produce SHA-1 hashes which are cryptographically weak.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.CSHARP,
        pattern=r'\b(?:SHA1Managed|SHA1CryptoServiceProvider|SHA1\.Create)\b',
        remediation="Upgrade to SHA256, SHA384, or SHA512.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-008",
        name="Weak Cipher (DES/3DES/RC2)",
        description="DES, TripleDES, and RC2 are deprecated symmetric ciphers. DES has a 56-bit key easily brute-forced.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.CSHARP,
        pattern=r'\b(?:DESCryptoServiceProvider|TripleDESCryptoServiceProvider|RC2CryptoServiceProvider)\b',
        remediation="Use AesGcm or AesCcm (System.Security.Cryptography) with a 256-bit key.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-009",
        name="Insecure Randomness (System.Random)",
        description="System.Random is a non-cryptographic PRNG. Output is predictable and must not be used for security purposes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.CSHARP,
        pattern=r'\bnew\s+Random\s*\(',
        remediation="Use RandomNumberGenerator.GetBytes() or RNGCryptoServiceProvider for cryptographic randomness.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="CS-010",
        name="XSS via Response.Write() with User Input",
        description="Writing request parameters directly to HTTP response without encoding enables XSS.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.CSHARP,
        pattern=r'Response\.Write\s*\(\s*(?:Request|context\.Request)',
        remediation="Use Html.Encode() (WebForms) or Razor's automatic encoding (@variable). Never write raw request values to response.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-011",
        name="Path Traversal via File Access",
        description="File operations with user-controlled path components enable path traversal.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.CSHARP,
        pattern=r'(?:File\.|FileInfo|StreamReader|FileStream)\s*(?:Read|Write|Open|Create)?\s*\(\s*(?:Request|HttpContext)',
        remediation="Use Path.GetFullPath() and verify the result starts with the expected base directory.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="CS-012",
        name="Hardcoded Password or Connection String",
        description="Hardcoded password or connection string found in C# source code.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.CSHARP,
        pattern=r'(?:string\s+\w*[Pp]assword\w*\s*=\s*["\'][^"\']{3,}["\']|Password\s*=\s*[^;{}\s]{3,}(?:;|$))',
        remediation="Use IConfiguration or Secret Manager (dotnet user-secrets). Store production secrets in Azure Key Vault.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        negative_pattern=r'(?:Configuration\[|GetConnectionString|Environment\.GetEnvironmentVariable)',
    ),
    Rule(
        id="CS-013",
        name="Missing ValidateAntiForgeryToken (CSRF)",
        description="POST controller action without [ValidateAntiForgeryToken] attribute is vulnerable to CSRF attacks.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CSRF,
        language=Language.CSHARP,
        pattern=r'\[HttpPost\](?!\s*\[ValidateAntiForgeryToken\])',
        remediation="Add [ValidateAntiForgeryToken] before every [HttpPost] action. Use the AntiForgeryToken() HTML helper in forms.",
        cwe="CWE-352",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
]
