"""Regras de segurança para Dart / Flutter."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

DART_RULES: list[Rule] = [
    Rule(
        id="DART-001",
        name="URL HTTP sem TLS em App Flutter",
        description="Requisição para endpoint HTTP (não HTTPS) expõe dados do usuário a interceptação em redes abertas. Em Android, cleartext HTTP é bloqueado por padrão na NetworkSecurityConfig.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.DART,
        pattern=r"'http://(?!localhost|127\.0\.0\.1)|\"http://(?!localhost|127\.0\.0\.1)",
        remediation="Use HTTPS em todos os endpoints. Configure android:usesCleartextTraffic=false no AndroidManifest.xml. Em desenvolvimento, use localhost via tunnel HTTPS.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DART-002",
        name="SharedPreferences para Dados Sensíveis",
        description="SharedPreferences armazena dados como XML/JSON em texto simples, legível por outros apps em dispositivos rooteados ou em backups. Não use para tokens, senhas ou PII.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.DART,
        pattern=r'SharedPreferences\b|prefs\.setString\s*\(\s*["\'][^"\']*(?:token|password|key|secret|auth|credential)',
        remediation="Use flutter_secure_storage (encripta com Keychain no iOS e EncryptedSharedPreferences no Android) para dados sensíveis.",
        cwe="CWE-312",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DART-003",
        name="debugPrint em Código de Produção",
        description="debugPrint imprime no console de debug. Ao contrário de print(), não é automaticamente removido em builds release. Dados sensíveis aparecem nos logs da app.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.DART,
        pattern=r'\bdebugPrint\s*\(',
        remediation="Remova debugPrint de código de produção. Use if (kDebugMode) { print(...) } ou um framework de logging como logger com controle de nível.",
        cwe="CWE-532",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DART-004",
        name="Hardcoded API Key em Dart/Flutter",
        description="API keys e tokens hardcoded no código Dart são facilmente extraídos do APK/IPA compilado via decompilação. Qualquer usuário pode obter a chave.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.DART,
        pattern=r"(?:const|final|var)\s+\w*(?:key|secret|token|password|api)\w*\s*=\s*['\"][A-Za-z0-9+/=_\-]{16,}['\"]",
        remediation="Use variáveis de ambiente via flutter_dotenv com arquivo .env fora do controle de versão. Para segredos críticos, faça proxy pelo servidor backend — nunca exponha diretamente no app.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DART-005",
        name="Certificate Verification Desabilitada (badCertificateCallback)",
        description="Retornar true em badCertificateCallback desabilita toda verificação de certificado TLS, permitindo ataques MITM. Código de debug que vai para produção.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.DART,
        pattern=r'badCertificateCallback\s*[=:]\s*\([^)]*\)\s*(?:=>|{)\s*true',
        remediation="Remova completamente badCertificateCallback em produção. Para desenvolvimento local com certificados self-signed, use apenas em builds DEBUG explicitamente.",
        cwe="CWE-295",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DART-006",
        name="Uso de dart:io Process sem Sanitização",
        description="Process.run() ou Process.start() com argumentos derivados de input do usuário pode executar comandos arbitrários no sistema operacional subjacente.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.DART,
        pattern=r'Process\.(?:run|start|runSync)\s*\(',
        remediation="Valide e sanitize todos os argumentos. Use uma allowlist de comandos permitidos. Evite interpolar input do usuário em chamadas de processo.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DART-007",
        name="WebView sem Restrição de URL (Flutter WebView)",
        description="WebView carregando URLs arbitrárias sem validação pode carregar conteúdo malicioso com acesso a APIs nativas via JavaScript channels.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.DART,
        pattern=r'WebView\b|WebViewController\b|InAppWebView\b',
        remediation="Valide URLs antes de carregar no WebView. Desabilite JavaScript se não necessário. Implemente NavigationDelegate ou ShouldOverrideUrlLoading.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="DART-008",
        name="Path Traversal via Concatenação de Caminho",
        description="Construção de caminhos de arquivo com input do usuário sem sanitização permite acesso a arquivos fora do diretório esperado.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.DART,
        pattern=r"File\s*\(\s*['\"]?\s*\$\{?[a-zA-Z]",
        remediation="Use path.normalize() e verifique se o caminho resultante está dentro do diretório permitido. Rejeite caminhos com '..' ou separadores absolutos.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
]
