"""Regras de segurança para Dockerfile."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

DOCKER_RULES: list[Rule] = [
    Rule(
        id="DOCK-001",
        name="Container Executando como Root (Sem USER)",
        description="Sem instrução USER, o container executa como root (UID 0). Se explorado, o atacante tem controle total sobre o container e potencial escape para o host.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'^\s*(?:FROM|ENTRYPOINT|CMD)\b',
        negative_pattern=r'^\s*USER\s+(?!root\b)(?!0\b)\S',
        remediation="Adicione USER appuser antes de CMD/ENTRYPOINT. Crie um usuário sem privilégios: RUN addgroup -S app && adduser -S app -G app && USER app",
        cwe="CWE-269",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="DOCK-002",
        name="USER root Explícito — Container com Privilégio Total",
        description="USER root instrui o container a executar como superusuário. Combina com privilege escalation exploits para escape do container.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'^\s*USER\s+(?:root|0)\s*$',
        remediation="Substitua USER root por um usuário sem privilégios: USER 1001 ou USER appuser. Estruture a imagem para não precisar de root em runtime.",
        cwe="CWE-269",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-003",
        name="Tag :latest — Imagem Base Mutável e Não Reproduzível",
        description="FROM image:latest aponta para a versão mais recente que muda a cada push. Builds tornam-se não reproduzíveis e vulnerabilidades podem ser introduzidas silenciosamente.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.DOCKERFILE,
        pattern=r'^\s*FROM\s+\S+:latest\b',
        remediation="Use digest SHA256 ou tags imutáveis: FROM ubuntu:22.04 ou FROM ubuntu@sha256:abc123... Atualize imagens base através de PRs revisados.",
        cwe="CWE-1104",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-004",
        name="FROM sem Tag — Usa :latest Implicitamente",
        description="FROM image sem tag usa :latest implicitamente, com todos os riscos de não-reprodutibilidade e introdução silenciosa de vulnerabilidades.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.DOCKERFILE,
        pattern=r'^\s*FROM\s+[a-zA-Z0-9][a-zA-Z0-9._/\-]*\s*$',
        remediation="Sempre especifique uma tag ou digest: FROM node:18.19.0-alpine3.19 ou FROM node@sha256:...",
        cwe="CWE-1104",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DOCK-005",
        name="Segredo em Variável ENV — Exposto em Inspeção da Imagem",
        description="Segredos definidos com ENV ficam embarcados nos metadados da imagem (docker inspect) e em todas as camadas intermediárias do Dockerfile. Acessíveis a qualquer usuário com acesso à imagem.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.DOCKERFILE,
        pattern=r'^\s*ENV\s+\w*(?:PASSWORD|SECRET|KEY|TOKEN|API_KEY|PASSWD)\w*\s*=?\s*\S{4,}',
        remediation="Nunca passe segredos via ENV no Dockerfile. Use Docker Secrets (--secret), variáveis de ambiente em runtime (não na imagem), ou vault integrations.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-006",
        name="ADD em vez de COPY — Comportamento Implícito Perigoso",
        description="ADD tem comportamento implícito além de copiar arquivos: extrai archives (tar, zip) automaticamente e pode baixar URLs remotas. Isso torna builds imprevisíveis e pode introduzir supply chain attacks.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.DOCKERFILE,
        pattern=r'^\s*ADD\s+(?!--chown)',
        remediation="Use COPY para copiar arquivos locais. Use RUN curl | tar para downloads explícitos com verificação de hash. ADD só é aceitável para extração intencional de arquivos locais.",
        cwe="CWE-1104",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DOCK-007",
        name="EXPOSE 22 — SSH no Container",
        description="Expor a porta 22 (SSH) no container vai contra o modelo de container imutável e seguro. SSH no container implica estado mutável, gerenciamento de chaves e superfície de ataque extra.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'^\s*EXPOSE\s+22\b',
        remediation="Remova SSH do container. Use kubectl exec, docker exec, ou ferramentas como telepresence para acesso de debug. Containers devem ser imutáveis e sem acesso SSH direto.",
        cwe="CWE-284",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-008",
        name="RUN sem --no-cache (apt/apk) — Cache Stale de Pacotes",
        description="apt-get install sem apt-get update na mesma instrução RUN pode usar cache desatualizado do Docker com versões antigas de pacotes com vulnerabilidades conhecidas.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'^\s*RUN\s+apt-get\s+install\b',
        negative_pattern=r'apt-get\s+update',
        remediation="Combine sempre: RUN apt-get update && apt-get install -y --no-install-recommends pacote && rm -rf /var/lib/apt/lists/* para manter pacotes atualizados e imagem enxuta.",
        cwe="CWE-1104",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="DOCK-009",
        name="Arquivo .env ou Credenciais Copiados para Imagem",
        description="COPY .env ou COPY credentials* inclui segredos na imagem Docker. A imagem pode ser inspecionada, exportada ou compartilhada acidentalmente expondo todos os segredos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.DOCKERFILE,
        pattern=r'^\s*COPY\s+(?:\.env|credentials|secrets|\.aws|\.ssh)',
        remediation="Adicione .env e arquivos de credenciais ao .dockerignore. Passe segredos em runtime via variáveis de ambiente, Docker Secrets, ou mount de arquivos secretos.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-010",
        name="Ausência de HEALTHCHECK",
        description="Container sem HEALTHCHECK não tem mecanismo de auto-diagnóstico. Orquestradores como Kubernetes dependem de health checks para reiniciar containers defeituosos.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'^\s*CMD\s',
        negative_pattern=r'^\s*HEALTHCHECK\s',
        remediation="Adicione HEALTHCHECK para serviços web: HEALTHCHECK --interval=30s --timeout=3s CMD curl -f http://localhost/health || exit 1",
        cwe="CWE-778",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="DOCK-011",
        name="Download sem Verificação de Hash (curl | bash)",
        description="RUN curl URL | bash ou wget URL | sh executa código remoto sem verificar integridade. Um atacante que comprometa o servidor de download injeta código malicioso.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.DOCKERFILE,
        pattern=r'RUN\s+.*(?:curl|wget)\s+.*\|\s*(?:bash|sh|python|ruby|perl)',
        remediation="Baixe o arquivo, verifique o hash SHA256 explicitamente, depois execute: curl -fsSL URL -o install.sh && echo \"HASH  install.sh\" | sha256sum -c && bash install.sh",
        cwe="CWE-494",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="DOCK-012",
        name="Execução com Privilégios Elevados (--privileged)",
        description="--privileged em runtime dá ao container acesso total ao host, equivalente a root sem container. Permite escape trivial do container e comprometimento do host.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.DOCKERFILE,
        pattern=r'--privileged\b',
        remediation="Nunca use --privileged em produção. Use --cap-add para adicionar apenas as capabilities necessárias. Implemente seccomp profiles e AppArmor/SELinux.",
        cwe="CWE-269",
        confidence=Confidence.HIGH,
    ),
]
