"""Regras de segurança para Elixir — 9 regras (ELIXIR-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ELIXIR_RULES: list[Rule] = [
    Rule(
        id="ELIXIR-001",
        name="Execução de Código Dinâmico com Code.eval_string/2",
        description="Code.eval_string/2 e Code.eval_quoted/2 executam código Elixir arbitrário em runtime. Se o argumento contém input do usuário, um atacante pode executar qualquer operação Elixir/Erlang, incluindo chamadas ao sistema, leitura de arquivos e encerramento do processo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.ELIXIR,
        pattern=r'Code\.eval_(?:string|quoted|file)\s*\(',
        remediation="Nunca avalie código vindo de input externo. Para templates dinâmicos, use EEx com sandboxing. Para expressões matemáticas, use uma biblioteca segura. Valide e whitelist toda expressão antes de qualquer avaliação.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-002",
        name="Injeção de Comando OS via System.cmd/2",
        description="System.cmd/2 executa um binário do sistema. Se o nome do comando ou os argumentos são construídos a partir de input do usuário sem validação, resulta em injeção de comando. System.cmd não usa shell, mas argumentos maliciosos podem ainda ser perigosos dependendo do comando.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ELIXIR,
        pattern=r'System\.cmd\s*\(\s*(?!["\']\w+["\']\s*,\s*\[\s*\])',
        remediation="Use System.cmd/3 com lista de argumentos fixos: System.cmd(\"git\", [\"clone\", user_url], stderr_to_stdout: true). Valide os argumentos contra uma lista permitida. Nunca construa o nome do executável dinamicamente.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ELIXIR-003",
        name="Injeção de Comando via :os.cmd/1 do Erlang",
        description=":os.cmd/1 executa o argumento através do shell do sistema operacional (usa /bin/sh -c no Unix). Com input externo, permite injeção de comandos completa com metacaracteres shell (;, |, &&, $(), etc.).",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ELIXIR,
        pattern=r':os\.cmd\s*\(',
        remediation="Substitua :os.cmd por System.cmd/2 que NÃO usa shell: System.cmd(\"ls\", [\"-la\", path]). Se :os.cmd for necessário, escape rigorosamente o input com :shell_utils.shell_escape/1 ou equivalente, e valide contra uma whitelist.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-004",
        name="Esgotamento de Átomos via String.to_atom/1",
        description="String.to_atom/1 converte qualquer string em um átomo Elixir. Átomos NÃO são coletados pelo garbage collector — o limite padrão é 1.048.576 átomos. Criar átomos a partir de input externo leva a crash do node BEAM por esgotamento do atom table.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.ELIXIR,
        pattern=r'String\.to_atom\s*\(',
        remediation="Use String.to_existing_atom/1 que só converte átomos já existentes (lança ArgumentError para desconhecidos). Para valores dinâmicos de usuário, mantenha como String ou Binary. Em rotas Phoenix, use :binary_id em vez de converter params para átomos.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-005",
        name="Credencial Exposta em Logger",
        description="Logger.info/debug/warn/error com dados que contêm senhas, tokens ou chaves. Em aplicações Phoenix/Plug, logs de requisição podem capturar automaticamente parâmetros do corpo HTTP, expondo credenciais se o filtro de parâmetros não estiver configurado.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ELIXIR,
        pattern=r'Logger\.(?:info|debug|warn|warning|error)\s*\(.*(?:password|passwd|secret|token|api_key|credential)',
        remediation="Em config/config.exs, configure Phoenix para filtrar parâmetros sensíveis: config :phoenix, :filter_parameters, [\"password\", \"secret\", \"token\"]. Nunca logue structs completas que podem conter credenciais. Use inspect(struct, only: [:id, :email]) para logar seletivamente.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="ELIXIR-006",
        name="Injeção SQL via Fragmento Raw no Ecto",
        description="Ecto.Query.fragment/1 com interpolação de string ou Repo.query/2 com SQL concatenado permite injeção SQL. O ORM Ecto é seguro quando usado corretamente com parâmetros bindados, mas uso direto de fragmentos dinâmicos bypassa as proteções.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.ELIXIR,
        pattern=r'fragment\s*\(\s*["\'][^"\']*<>\s*|Repo\.query\s*\(\s*["\'][^"\']*<>|Ecto\.Adapters\.SQL\.query\s*\([^,]+,\s*["\'][^"\']*<>',
        remediation="Use parâmetros posicionais no Ecto: from(u in User, where: u.name == ^user_name). Para queries complexas, use fragment com $1, $2 placeholders: fragment(\"LOWER(?) = LOWER(?)\", u.name, ^input). Nunca concatene strings (<>) em queries.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-007",
        name="Path Traversal via File.read!/1 com Input Externo",
        description="File.read!/1, File.stream!/1 ou File.open/2 com caminhos construídos de parâmetros HTTP ou outros inputs externos. Sem normalização de caminho, sequências ../ permitem leitura de arquivos fora do diretório esperado.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.ELIXIR,
        pattern=r'File\.(?:read!?|stream!?|open|write!?)\s*\(\s*(?:params|conn\.params|Map\.get|System\.get_env)',
        remediation="Normalize o caminho e verifique que está dentro do diretório base: base = Path.expand(\"/safe/uploads\"). target = Path.expand(Path.join(base, user_input)). if String.starts_with?(target, base), do: File.read!(target), else: {:error, :forbidden}",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-008",
        name="Verificação SSL Desabilitada em HTTPoison / Finch / Mint",
        description="ssl: [{:verify, :verify_none}] ou verify: :verify_none em clientes HTTP Elixir desabilita a validação do certificado TLS. Torna a aplicação vulnerável a ataques Man-in-the-Middle onde um certificado falso não é detectado.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ELIXIR,
        pattern=r'verify:\s*:verify_none|verify_peer:\s*false|ssl:\s*\[.*:verify_none',
        remediation="Remova a opção verify: :verify_none. Em desenvolvimento com certificados self-signed, use cacerts: :public_key.cacerts_get() ou especifique o CA bundle. Em produção, nunca desabilite verificação de certificado.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELIXIR-009",
        name="Proteção CSRF Desabilitada no Plug / Phoenix",
        description="Plug.CSRFProtection.delete_csrf_token() ou :skip_csrf_protection no pipeline Phoenix remove a proteção contra Cross-Site Request Forgery. Em aplicações com sessões baseadas em cookie, isso permite que sites maliciosos façam requisições autenticadas em nome do usuário.",
        severity=Severity.HIGH,
        category=VulnCategory.CSRF,
        language=Language.ELIXIR,
        pattern=r'skip_csrf_protection\b|Plug\.CSRFProtection\.delete_csrf_token\s*\(',
        remediation="Mantenha Plug.CSRFProtection no pipeline. Para APIs REST com tokens JWT (sem cookie), o CSRF não se aplica — use pipeline separado sem CSRF para rotas de API. Para webhooks externos, use verificação de HMAC-SHA256 no lugar do CSRF token.",
        cwe="CWE-352",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
]
