"""Regras de segurança para Elm — 8 regras (ELM-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ELM_RULES: list[Rule] = [
    Rule(
        id="ELM-001",
        name="Debug.log em Código de Produção",
        description="Debug.log em Elm imprime valores na console do browser durante a execução. Em produção, pode expor estruturas de dados internas, incluindo tokens de sessão, dados de usuário e estado da aplicação. O compilador Elm avisa sobre Debug em releases, mas pode ser ignorado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.ELM,
        pattern=r'\bDebug\.log\s+',
        remediation="Remova todos os Debug.log antes de builds de produção. Use o flag --optimize do compilador Elm que converte Debug.log em no-ops: elm make --optimize src/Main.elm --output main.js. Configure o CI para falhar em presença de Debug.log no bundle.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELM-002",
        name="Requisição HTTP Não Criptografada via Http.request",
        description="Http.get, Http.post ou Http.request com URLs http:// em Elm transmitem dados sem criptografia. Browsers modernos bloqueiam mixed content em páginas HTTPS, mas aplicações Elm servidas via HTTP (common em intranets) não têm essa proteção automática.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ELM,
        pattern=r'Http\s*\.\s*(?:get|post|request|send)\s*.*["\']http://',
        remediation="Use https:// em todas as URLs de API. Configure o backend para redirecionar http:// para https://. Use Content-Security-Policy upgrade-insecure-requests no servidor que serve a aplicação Elm. Defina URLs base como constantes configuráveis por ambiente.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ELM-003",
        name="Port Expondo Dados Sensíveis para JavaScript",
        description="Ports Elm para JavaScript com nomes que sugerem dados sensíveis (password, token, secret) enviam dados da aplicação Elm tipada para o JavaScript não tipado. Código JavaScript que recebe esses dados pode vazar para analytics, extensões de browser ou código de terceiros.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ELM,
        pattern=r'port\s+\w*(?:password|secret|token|auth|credential)\w*\s*:',
        remediation="Nunca envie credenciais via ports para JavaScript. Mantenha tokens de autenticação no runtime Elm e adicione-os automaticamente nos cabeçalhos das requisições Http. Se interação com JavaScript é necessária para autenticação, use flags de inicialização uma única vez, não ports contínuos.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="ELM-004",
        name="Decodificação JSON sem Tratamento de Erro",
        description="Json.Decode.decodeString decoder input sem tratamento do caso Err em Elm. Embora Elm force tratamento de Result, usar Result.withDefault ou discarding errors silencia falhas de parsing que podem indicar dados malformados ou injeção de dados inesperados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.ELM,
        pattern=r'Json\.Decode\.decodeString\s+\w+\s+\w+\s*\|>\s*Result\.withDefault',
        remediation="Trate explicitamente o caso Err: case Json.Decode.decodeString decoder input of Ok data -> useData data; Err err -> logError (Json.Decode.errorToString err). Nunca descarte erros de decodificação silenciosamente — podem indicar adulteração de dados.",
        cwe="CWE-20",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ELM-005",
        name="LocalStorage via Port sem Menção de Criptografia",
        description="Ports que armazenam dados em localStorage via JavaScript são uma preocupação de segurança. localStorage é acessível a qualquer script da mesma origem, extensões de browser e ferramentas de desenvolvedor. Tokens JWT ou dados sensíveis em localStorage são vulneráveis a XSS.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.ELM,
        pattern=r'port\s+\w*(?:storage|local|store|save|persist)\w*\s*:',
        remediation="Prefira cookies HttpOnly/Secure para tokens de autenticação — inacessíveis via JavaScript. Para dados de estado não sensíveis, localStorage é aceitável. Nunca armazene tokens JWT, senhas ou dados pessoais em localStorage. Use sessionStorage se persistência entre sessões não for necessária.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ELM-006",
        name="Http.send sem Tratamento de Erros de Rede",
        description="Http.send em Elm retorna Result que inclui variantes de erro de rede (Http.NetworkError, Http.Timeout, Http.BadStatus). Ignorar esses erros com _ -> model ou apenas logando pode resultar em estado inconsistente da aplicação ou falhas silenciosas que obscurecem problemas de segurança.",
        severity=Severity.LOW,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.ELM,
        pattern=r'Http\.Error\s*->\s*\(\s*model\s*,\s*Cmd\.none\s*\)',
        remediation="Trate todos os casos de erro HTTP: Http.BadStatus code -> showError (\"Servidor retornou \" ++ String.fromInt code); Http.NetworkError -> showError \"Erro de rede\"; Http.Timeout -> showError \"Timeout\". Implemente retry logic para erros transientes.",
        cwe="CWE-390",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ELM-007",
        name="Navigation.load com URL Controlada pelo Usuário",
        description="Browser.Navigation.load url em Elm navega para a URL fornecida, potencialmente redirecionando para um site externo. Com URL derivada de parâmetros de query ou state, permite open redirect para phishing ou download de conteúdo malicioso.",
        severity=Severity.HIGH,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.ELM,
        pattern=r'Navigation\.load\s+',
        remediation="Valide URLs antes de navegar: if String.startsWith config.allowedBase url then Navigation.load url else (model, Cmd.none). Para redirects pós-login, use rotas internas (Navigation.pushUrl) em vez de URLs absolutas. Nunca redirecione para URLs externas sem validação explícita.",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ELM-008",
        name="Random.generate com Semente Constante / Previsível",
        description="Random.initialSeed com valor fixo ou derivado de tempo do cliente em Elm produz sequências previsíveis. Para features de segurança (tokens CSRF, IDs de sessão, códigos de verificação), números previsíveis comprometem a proteção.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.ELM,
        pattern=r'Random\.initialSeed\s+\d+',
        remediation="Para aleatoriedade de segurança, gere tokens no servidor e envie para a aplicação Elm via flags ou API. Nunca use Random.initialSeed com constante para dados sensíveis. O módulo Random do Elm é adequado para jogos/UI, não para criptografia.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
]
