"""Regras de segurança para Erlang — 8 regras (ERLANG-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ERLANG_RULES: list[Rule] = [
    Rule(
        id="ERLANG-001",
        name="Esgotamento de Átomos via list_to_atom/1",
        description="list_to_atom/1 e binary_to_atom/2 criam novos átomos em uma tabela de tamanho fixo (padrão: 1.048.576). Átomos nunca são coletados pelo garbage collector. Criar átomos a partir de input externo pode crashar a VM BEAM por esgotamento da atom table, causando negação de serviço total do nó.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.ERLANG,
        pattern=r'\blist_to_atom\s*\(|binary_to_atom\s*\([^,]+,\s*utf8\s*\)',
        remediation="Use list_to_existing_atom/1 que lança badarg para átomos desconhecidos. Para dados externos, mantenha como binaries ou strings. Se precisar converter, implemente um módulo de controle que valide contra um conjunto fixo de valores permitidos.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ERLANG-002",
        name="Chamada Dinâmica de Função via apply/3",
        description="erlang:apply(Mod, Fun, Args) com Módulo e/ou Função derivados de input externo permite chamada de qualquer função de qualquer módulo carregado na VM. Um atacante pode invocar os:cmd/1, erlang:halt/0 ou funções privadas de módulos internos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.ERLANG,
        pattern=r'\bapply\s*\(\s*(?![\w]+\s*,\s*[\w]+)',
        remediation="Implemente um dispatcher com whitelist: allowed_calls() -> [{my_module, my_function, 1}]. Valide que {Mod, Fun, Arity} está na lista antes de chamar apply/3. Considere usar function references explícitas (fun Mod:Fun/Arity) em vez de apply dinâmico.",
        cwe="CWE-470",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ERLANG-003",
        name="Carregamento Dinâmico de Módulo via code:load_file/1",
        description="code:load_file/1, code:load_binary/3 e code:atomic_load/1 carregam módulos Erlang compilados em runtime. Com caminhos ou binaries controlados pelo atacante, é possível substituir módulos existentes ou carregar código malicioso com acesso total à VM.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.ERLANG,
        pattern=r'\bcode:(?:load_file|load_binary|atomic_load|add_path|replace_path)\s*\(',
        remediation="Restrinja carregamento dinâmico a caminhos pré-aprovados. Use code:add_pathz/1 somente com diretórios absolutamente confiáveis. Para plugins, implemente verificação de assinatura digital dos .beam files antes de carregar.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ERLANG-004",
        name="Execução de Shell via erlang:open_port com spawn",
        description="open_port({spawn, Command}, ...) executa Command através do shell. Com Command derivado de input externo, permite injeção de comandos OS. Ao contrário de {spawn_executable, Path}, o modo spawn usa /bin/sh e interpreta metacaracteres shell.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ERLANG,
        pattern=r'open_port\s*\(\s*\{spawn,',
        remediation="Use {spawn_executable, Path} com {args, ArgList} para evitar interpretação pelo shell: open_port({spawn_executable, \"/usr/bin/git\"}, [{args, [\"clone\", UserUrl]}, exit_status]). Valide Path contra uma lista de executáveis permitidos.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ERLANG-005",
        name="Injeção de Comando via os:cmd/1",
        description="os:cmd/1 executa um comando via shell do sistema operacional e retorna a saída como string. Qualquer input não sanitizado no argumento pode ser explorado com operadores shell (;, |, &&, `backtick`) para executar comandos arbitrários.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ERLANG,
        pattern=r'\bos:cmd\s*\(',
        remediation="Substitua os:cmd por open_port com {spawn_executable} para evitar shell. Se os:cmd for necessário, construa o comando somente com valores hardcoded, nunca com input do usuário. Escape com shell_utils:shell_escape/1 se disponível.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ERLANG-006",
        name="Erlang Distribuído Exposto — rpc:call sem Autenticação",
        description="rpc:call/4 e net_adm:ping/1 interagem com nós Erlang distribuídos. Por padrão, o protocolo de distribuição Erlang usa apenas um \"cookie\" como autenticação, sem TLS. Nós acessíveis na rede permitem execução remota de código por qualquer nó com o mesmo cookie.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.ERLANG,
        pattern=r'\brpc:(?:call|cast|multicall)\s*\(|net_adm:ping\s*\(',
        remediation="Habilite TLS para distribuição Erlang: configure -proto_dist inet_tls e use arquivos de certificado. Restrinja portas de distribuição (EPMD) no firewall. Use erlang:set_cookie com cookies fortes. Considere usar VPN ou rede privada para comunicação entre nós.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ERLANG-007",
        name="Hash MD5 Criptograficamente Fraco via crypto:hash",
        description="crypto:hash(md5, Data) e crypto:md5/1 (deprecated) produzem hashes MD5 que são criptograficamente quebrados. Colisões podem ser geradas em segundos. Não deve ser usado para checksums de segurança, MACs ou derivação de chaves.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.ERLANG,
        pattern=r'crypto:(?:hash\s*\(\s*md5|md5\s*\()',
        remediation="Use crypto:hash(sha256, Data) ou crypto:hash(sha3_256, Data). Para MACs, use crypto:mac(hmac, sha256, Key, Data). Para senhas, use pbkdf2_hmac: crypto:pbkdf2_hmac(sha256, Password, Salt, Iterations, 32).",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="ERLANG-008",
        name="Desserialização Insegura via binary_to_term/1",
        description="erlang:binary_to_term/1 sem a opção [safe] desserializa qualquer termo Erlang, incluindo referências a átomos arbitrários (exaustão da atom table) e PIDs de processos externos. Dados externos não confiáveis desserializados sem restrição podem crashar o nó.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.ERLANG,
        pattern=r'binary_to_term\s*\(\s*(?!\w+,\s*\[safe\])',
        remediation="Use binary_to_term/2 com a opção [safe]: binary_to_term(Data, [safe]). O modo safe proíbe a criação de novos átomos e referências externas. Para comunicação entre serviços, prefira JSON, MessagePack ou Protobuf.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.MEDIUM,
    ),
]
