"""Regras de segurança para Flutter/Dart — 8 regras (FLUTTER-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

FLUTTER_RULES: list[Rule] = [
    Rule(
        id="FLUTTER-001",
        name="SharedPreferences com Dados Sensíveis",
        description="SharedPreferences em Flutter/Android e UserDefaults em iOS (acessados via shared_preferences package) armazenam dados em XML/texto claro no filesystem. Tokens de autenticação, senhas ou dados pessoais armazenados assim são acessíveis em dispositivos com root/jailbreak e em backups.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.DART,
        pattern=r'prefs\.setString\s*\(\s*["\'][^"\']*(?:password|token|secret|auth|key|credential)[^"\']*["\']',
        remediation="Use flutter_secure_storage para dados sensíveis: const storage = FlutterSecureStorage(); await storage.write(key: 'auth_token', value: token). Em iOS usa Keychain, Android usa Keystore. SharedPreferences é aceitável para preferências não sensíveis como tema e idioma.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="FLUTTER-002",
        name="http.Client sem TLS — Requisição HTTP Insegura",
        description="'http.get(Uri.parse(\"http://\"))' ou 'http.Client().get()' com URLs http:// em Flutter transmite dados sem criptografia. Em redes Wi-Fi públicas ou com captive portals, dados sensíveis (tokens, dados do usuário) são interceptáveis. Flutter não força HTTPS por padrão.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.DART,
        pattern=r'http\s*\.\s*(?:get|post|put|delete|patch)\s*\(\s*Uri\.parse\s*\(\s*["\']http://',
        remediation="Use sempre https://: http.get(Uri.parse('https://api.example.com/data')). Configure HttpClient com certificate pinning para producção: final client = HttpClient()..badCertificateCallback = (cert, host, port) => false. Use o package dio com interceptors para adicionar headers de autenticação automaticamente.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FLUTTER-003",
        name="badCertificateCallback Retornando true — Ignora Certificado",
        description="'badCertificateCallback: (cert, host, port) => true' em HttpClient ou 'onBadCertificate: (_) => true' desabilita a verificação de certificado TLS. Isso elimina a proteção contra ataques MITM — qualquer certificado, incluindo de atacantes, é aceito silenciosamente.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CRYPTO,
        language=Language.DART,
        pattern=r'badCertificateCallback\s*(?:=|:)\s*\([^)]*\)\s*(?:=>|{)\s*true',
        remediation="Nunca retorne true em badCertificateCallback. Para desenvolvimento com certificados self-signed, configure o certificado da CA raiz: SecurityContext context = SecurityContext.defaultContext; context.setTrustedCertificatesBytes(certBytes). Para certificate pinning: use http_certificate_pinning ou flutter_ssl_pinning.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FLUTTER-004",
        name="debugPrint em Código de Produção com Dados Sensíveis",
        description="'debugPrint()' em Flutter imprime no console apenas em modo debug, mas 'print()' imprime sempre, incluindo em release. Dados sensíveis em print() aparecem em logs do dispositivo (Android logcat, iOS Console.app) acessíveis a outros apps com permissão de log reading.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.DART,
        pattern=r'\bprint\s*\([^)]*(?:password|token|secret|key|auth|email|cpf|credit)[^)]*\)',
        remediation="Substitua print() por debugPrint() para logs de desenvolvimento (desabilitado em release). Para logging de produção, use o package logger com levels: final logger = Logger(); logger.d('Debug msg'); logger.e('Error', error: e). Configure para não logar dados sensíveis em produção.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="FLUTTER-005",
        name="Platform.environment Acessado em Widget",
        description="Platform.environment em código de widget Flutter expõe variáveis de ambiente do processo. Em apps mobile, variáveis de ambiente podem conter paths do SDK, configurações de build e, em alguns casos, tokens de CI/CD se o build não foi limpo. Em apps desktop, expõe variáveis do usuário.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.DART,
        pattern=r'Platform\.environment',
        remediation="Nunca use Platform.environment em código de widget. Para configurações de ambiente, use package:flutter_dotenv ou variáveis de build compiladas (--dart-define): String apiUrl = const String.fromEnvironment('API_URL'). Valores de --dart-define são compilados no binário, não acessíveis via Platform.environment.",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="FLUTTER-006",
        name="FlutterError.onError Substituído por null ou Silenciador",
        description="'FlutterError.onError = null' ou assignment que ignora o erro substitui o handler global de erros do Flutter. Isso silencia erros de widget rendering, overflow de layout e outros problemas críticos. Em modo release, erros silenciados nunca chegam ao sistema de crash reporting.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.DART,
        pattern=r'FlutterError\.onError\s*=\s*(?:null|\([^)]*\)\s*(?:=>|{)\s*(?:\{\}|;|\}))',
        remediation="Não substitua o handler de erros. Para integrações de crash reporting, encadeie handlers: FlutterError.onError = (details) { FirebaseCrashlytics.instance.recordFlutterFatalError(details); FlutterError.presentError(details); }. Use runZonedGuarded para capturar erros assíncronos também.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="FLUTTER-007",
        name="Sqflite sem Criptografia — Dados Locais em Texto Claro",
        description="'sqflite' armazena o banco de dados SQLite em texto claro no diretório de dados do app. Em dispositivos com root ou iOS jailbreak, o arquivo .db é diretamente acessível. Para apps com dados sensíveis offline (médicos, financeiros), o banco deve ser criptografado com SQLCipher.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.DART,
        pattern=r"openDatabase\s*\(\s*[^)]*\.db['\"]",
        negative_pattern=r'sqflite_sqlcipher|encrypt|password',
        remediation="Use sqflite_sqlcipher ou drift com SQLCipher para criptografar o banco: openEncryptedDatabase(path, password: encryptionKey). Gere a chave de criptografia com flutter_secure_storage vinculada ao biometric do dispositivo. Considere SQLite apenas para dados não sensíveis; use flutter_secure_storage para dados críticos.",
        cwe="CWE-311",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="FLUTTER-008",
        name="InAppWebView / WebView sem javaScriptMode.disabled",
        description="WebViews em Flutter com JavaScript habilitado (javaScriptMode: JavascriptMode.unrestricted) carregando URLs externas ou conteúdo gerado por usuário são vulneráveis a XSS. Em Flutter WebViews, XSS pode invocar handlers registrados via addJavaScriptChannel, executando código Dart.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.DART,
        pattern=r'javaScriptMode\s*:\s*JavascriptMode\.unrestricted',
        remediation="Use javaScriptMode: JavascriptMode.disabled para conteúdo estático. Para conteúdo dinâmico, valide e sanitize antes de injetar na WebView. Configure allowsInlineMediaPlayback e mediaAutoPlay adequadamente. Use WebViewWidget com flutter_inappwebview e configure ContentBlocker para filtrar scripts indesejados.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
]
