"""Regras de segurança para F# e OCaml — 9 regras (FS-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

_FS = Language.FSHARP
_ML = Language.OCAML

FSHARP_RULES: list[Rule] = [
    Rule(
        id="FS-001",
        name="Desserialização Insegura via BinaryFormatter (.NET / F#)",
        description="System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize() em F# desserializa objetos .NET de um stream binário. Com dados externos, um atacante pode injetar objetos maliciosos que executam código arbitrário via gadget chains .NET disponíveis em qualquer instalação.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=_FS,
        pattern=r'BinaryFormatter\s*\(\s*\)|BinaryFormatter\s*\(\)|\.Deserialize\s*\(\s*\w+\s*\)',
        remediation="Substitua BinaryFormatter por System.Text.Json.JsonSerializer ou MessagePack para F#. O BinaryFormatter está deprecated no .NET 5+ e desabilitado por padrão no .NET 7+. Para tipos complexos, use Thoth.Json ou Newtonsoft.Json com type discrimination controlada.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-002",
        name="Injeção de Comando via System.Diagnostics.Process.Start em F#",
        description="System.Diagnostics.Process.Start(command, arguments) em F# com argumentos derivados de input externo permite injeção de comandos. Argumentos não sanitizados podem explorar comportamentos específicos do executável chamado ou dos interpretadores de script.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=_FS,
        pattern=r'Process\.Start\s*\(\s*(?!ProcessStartInfo)',
        remediation="Use ProcessStartInfo com UseShellExecute = false: let psi = ProcessStartInfo(\"git\", $\"clone {sanitizedUrl}\"); psi.UseShellExecute <- false; Process.Start(psi). Valide todos os argumentos contra uma whitelist. Nunca use UseShellExecute = true com input externo.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="FS-003",
        name="Path Traversal via File.ReadAllText / File.ReadAllLines em F#",
        description="System.IO.File.ReadAllText() ou ReadAllLines() com caminhos construídos de input externo em F#. A natureza funcional do F# pode levar a pipelines que transformam dados do usuário em caminhos de arquivo sem validação explícita.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=_FS,
        pattern=r'File\.ReadAll(?:Text|Lines|Bytes)\s*\(\s*(?!\s*["\'])',
        remediation="Normalize e valide o caminho: let basePath = Path.GetFullPath(\"/safe/dir\"); let fullPath = Path.GetFullPath(Path.Combine(basePath, userInput)); if not (fullPath.StartsWith(basePath)) then failwith \"path traversal\"; File.ReadAllText(fullPath)",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="FS-004",
        name="Hash Criptograficamente Fraco em F# / .NET",
        description="HashAlgorithm.Create(\"MD5\") ou MD5.Create() em F#/.NET produz hash MD5 criptograficamente quebrado. SHA1CryptoServiceProvider e SHA1Managed estão na mesma categoria. Uso para verificação de integridade ou hash de senhas é inadequado.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=_FS,
        pattern=r'MD5\.Create\s*\(\s*\)|HashAlgorithm\.Create\s*\(\s*["\']MD5["\']|SHA1CryptoServiceProvider\s*\(\s*\)|SHA1Managed\s*\(\s*\)',
        remediation="Use SHA256Managed ou SHA256.Create() no mínimo. Para senhas em F#/.NET, use Microsoft.AspNetCore.Identity.PasswordHasher<T> que usa PBKDF2-SHA256 com 100.000 iterações. Ou use Bcrypt.Net-Next: BCrypt.HashPassword(password, workFactor: 12).",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-005",
        name="Requisição HTTP Não Criptografada via WebClient / HttpClient em F#",
        description="WebClient.DownloadString() ou HttpClient.GetAsync() com URLs http:// em F# transmite dados em texto puro. Em pipelines de processamento de dados e serviços F#, credenciais de API e dados sensíveis podem ser interceptados.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=_FS,
        pattern=r'(?:WebClient|HttpClient)\s*\(\s*\).*["\']http://|DownloadString\s*\(\s*["\']http://',
        remediation="Use https:// em todas as URLs. Configure HttpClientHandler para verificação de certificados: let handler = HttpClientHandler(); handler.ServerCertificateCustomValidationCallback <- HttpClientHandler.DangerousAcceptAnyServerCertificateValidator // NUNCA em produção. Use HttpsEnforcer middleware.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-006",
        name="Desserialização Insegura via Marshal.from_string (OCaml)",
        description="Marshal.from_string e Marshal.from_channel em OCaml desserializam qualquer valor OCaml a partir de bytes. Dados maliciosos podem criar objetos que ao serem usados pelo garbage collector ou runtime causam comportamento indefinido, incluindo potencial execução de código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=_ML,
        pattern=r'\bMarshal\.(?:from_string|from_channel|from_bytes)\s*\(',
        remediation="Use JSON (Yojson, Ezjsonm) ou MessagePack para serialização de dados externos. Marshal é adequado apenas para comunicação entre processos OCaml confiáveis. Para RPC, considere Cap'n Proto ou Protobuf com bindings OCaml.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-007",
        name="Injeção de Comando via Sys.command (OCaml)",
        description="Sys.command em OCaml executa o argumento via shell do sistema. Com strings construídas de input externo (argumentos de linha de comando, dados de arquivo, input interativo), metacaracteres shell permitem injeção de comandos completa.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=_ML,
        pattern=r'\bSys\.command\s*\(',
        remediation="Use Unix.create_process com array de argumentos: Unix.create_process \"git\" [|\"git\"; \"clone\"; user_url|] Unix.stdin Unix.stdout Unix.stderr. Isso evita interpretação shell. Valide user_url contra protocolo e caracteres permitidos antes de usar.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-008",
        name="Execução de Processo via Unix.open_process (OCaml)",
        description="Unix.open_process e Unix.open_process_full em OCaml abrem um pipe para um comando shell. Com argumentos dinâmicos, permitem injeção de comandos. O processo filho herda as permissões do processo OCaml pai.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=_ML,
        pattern=r'\bUnix\.open_process(?:_full|_in|_out)?\s*\(',
        remediation="Substitua por Unix.create_process com lista de argumentos explícitos. Para capturar stdout, use pipes Unix explícitos sem passar pelo shell. Valide todos os argumentos contra uma whitelist de valores permitidos.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="FS-009",
        name="Injeção via Scanf.scanf sem Validação (OCaml)",
        description="Scanf.sscanf ou Scanf.scanf com format strings construídas dinamicamente em OCaml. Embora OCaml valide format strings em compile time para literais, uso com strings de runtime contorna essa proteção e pode causar comportamento inesperado na leitura de dados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=_ML,
        pattern=r'\bScantf\.(?:sscanf|scanf|fscanf)\s*\([^,]+,\s*[a-zA-Z_]\w*',
        remediation="Use format strings literais apenas: Scanf.sscanf input \"%d %s\" (fun n s -> ...). Nunca construa format strings dinamicamente. Para parsing de input externo, use angstrom, menhir ou rex para parsing tipado e seguro.",
        cwe="CWE-134",
        confidence=Confidence.LOW,
    ),
]
