import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GENERIC_RULES: list[Rule] = [
    Rule(
        id="GEN-001",
        name="Hardcoded Password",
        description="Hardcoded password found in source code. Attackers with access to the repository gain instant access to protected resources.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:password|passwd|pwd|pass)\s*[=:]\s*["\'][^"\']{3,}["\']',
        remediation="Move credentials to environment variables, a secrets manager (Vault, AWS Secrets Manager, Azure Key Vault) or encrypted config files outside VCS.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
        negative_pattern=r'(?:placeholder|example|changeme|your[_-]?password|<password>|\*{3,}|xxx)',
    ),
    Rule(
        id="GEN-002",
        name="Hardcoded API Key",
        description="Hardcoded API key detected. Exposed API keys enable unauthorized requests and billing fraud.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:api[_-]?key|apikey|api[_-]?secret|client[_-]?secret)\s*[=:]\s*["\'][A-Za-z0-9+/=_\-]{16,}["\']',
        remediation="Store API keys in environment variables or a secure vault. Rotate the exposed key immediately.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GEN-003",
        name="Hardcoded Secret / Signing Key",
        description="Hardcoded secret or signing key found. Used by attackers to forge tokens, bypass HMAC checks, or decrypt data.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:secret[_-]?key|secret_token|auth_secret|signing_key|jwt_secret|app_secret)\s*[=:]\s*["\'][^"\']{8,}["\']',
        remediation="Use environment variables or a secrets manager. Rotate the exposed secret immediately.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
        negative_pattern=r'(?:placeholder|example|changeme|your_secret)',
    ),
    Rule(
        id="GEN-004",
        name="AWS Secret Access Key",
        description="AWS Secret Access Key pattern detected. Exposed AWS credentials give full programmatic access to cloud resources.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'AWS_SECRET_ACCESS_KEY\s*[=:]\s*["\']?[A-Za-z0-9+/]{40}["\']?',
        remediation="Immediately revoke the key in AWS IAM. Use IAM roles for compute resources and AWS Secrets Manager.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-005",
        name="AWS Access Key ID",
        description="AWS Access Key ID pattern detected.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'\b(?:AKIA|ASIA|AROA|AIDA|ANPA|ANVA)[0-9A-Z]{16}\b',
        remediation="Revoke the key pair. Use IAM roles and AWS Secrets Manager instead.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-006",
        name="Private Key in Source Code",
        description="PEM-encoded private key found in source code. Private keys must never be committed to version control.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'-----BEGIN\s+(?:RSA\s+|EC\s+|DSA\s+|OPENSSH\s+|ENCRYPTED\s+)?PRIVATE KEY-----',
        remediation="Remove immediately and rotate the key pair. Use a secrets manager. Add *.pem, *.key to .gitignore.",
        cwe="CWE-321",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-007",
        name="Hardcoded Database Connection String with Credentials",
        description="Database connection string including credentials hardcoded in source.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:jdbc|mysql|postgresql|postgres|mongodb|redis|mssql|sqlserver)\s*://[^@\s\'"]{1,64}:[^@\s\'"]{1,64}@',
        remediation="Store connection strings in environment variables or a configuration manager outside version control.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-008",
        name="GitHub / GitLab Personal Access Token",
        description="A version control platform personal access token was detected.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:gh[pousr]_[A-Za-z0-9]{36}|glpat-[A-Za-z0-9\-_]{20})',
        remediation="Revoke the token immediately on GitHub/GitLab. Use repository secrets or CI/CD environment variables.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-009",
        name="Hardcoded Bearer Token / JWT",
        description="A bearer token or JWT appears to be hardcoded in source code.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:Authorization|Bearer)\s*[=:]\s*["\']?(?:Bearer\s+)?eyJ[A-Za-z0-9_\-]{10,}\.[A-Za-z0-9_\-]{10,}',
        remediation="Never hardcode auth tokens. Use token injection at runtime via environment variables.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GEN-010",
        name="Hardcoded Slack / Discord / Telegram Token",
        description="A messaging platform webhook or bot token was detected in source code.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.GENERIC,
        pattern=r'(?:xox[baprs]-[0-9A-Za-z\-]{10,}|https://hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+)',
        remediation="Revoke the token and use environment variables or a secrets manager.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GEN-011",
        name="Hardcoded Public IP Address",
        description="A public IP address is hardcoded. This can expose infrastructure topology.",
        severity=Severity.LOW,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.GENERIC,
        pattern=r'\b(?:(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]\d|\d)\.){3}(?:25[0-5]|2[0-4]\d|1\d{2}|[1-9]\d|\d)\b',
        negative_pattern=r'127\.0\.0\.|0\.0\.0\.0|255\.255\.|192\.168\.|10\.\d{1,3}\.|172\.(?:1[6-9]|2\d|3[01])\.',
        remediation="Use hostnames or configuration variables instead of hardcoded IPs.",
        cwe="CWE-605",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GEN-012",
        name="TODO / FIXME Security Note",
        description="A security-related TODO or FIXME comment was found. These often indicate known, unresolved vulnerabilities.",
        severity=Severity.INFO,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.GENERIC,
        pattern=r'(?:TODO|FIXME|HACK|XXX|BUG)\s*[:\-]?\s*.*(?:auth|security|vuln|injection|xss|csrf|encrypt|password|secret|token|sanitize|validate)',
        remediation="Address the security concern identified in this comment and remove the TODO.",
        cwe="CWE-1164",
        owasp="A05:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
