"""Regras de segurança para GitLab CI/CD — 9 regras (GLCI-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GITLAB_CI_RULES: list[Rule] = [
    Rule(
        id="GLCI-001",
        name="allow_failure: true em Job de Segurança",
        description="'allow_failure: true' em jobs de SAST, secret detection, dependency scanning ou container scanning faz o pipeline passar mesmo quando vulnerabilidades são detectadas. Isso cria uma ilusão de segurança — o job roda mas suas falhas são silenciadas, permitindo deploy de código vulnerável.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'allow_failure\s*:\s*true',
        remediation="Remova 'allow_failure: true' de jobs de segurança. Se você precisa introduzir scanning gradualmente, use 'rules:' com conditions baseadas em branch: allow_failure: $CI_COMMIT_BRANCH == 'feature'. Configure severity thresholds nos scanners para não bloquear em low severity.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GLCI-002",
        name="Artifacts com Arquivos de Credenciais",
        description="Configurações de artifacts que incluem padrões como '*.key', '*.pem', '.env', 'credentials*' expõem arquivos sensíveis como artifacts GitLab. Esses arquivos ficam disponíveis para download por qualquer membro com acesso ao projeto e são retidos conforme a política de expiração.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'paths\s*:\s*\n(?:\s+-[^\n]+\n)*\s+-\s*["\']?(?:[^"\']*\.(?:key|pem|p12|pfx|env|secret|cred)[^"\']*|\.env)["\']?',
        remediation="Nunca inclua arquivos de credenciais em artifacts. Use CI/CD Variables protegidas e mascaradas para secrets. Se um certificado precisa ser passado entre jobs, use GitLab Vault integration ou armazene em CI/CD Variables do tipo File. Audite artifacts existentes com 'gitlab-ci-lint'.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GLCI-003",
        name="Credencial Hardcoded em Variável CI",
        description="Variáveis definidas diretamente no .gitlab-ci.yml com valores de senha, token ou API key ficam armazenadas em texto claro no repositório git. Qualquer pessoa com acesso ao repositório vê as credenciais, e o histórico git retém os valores mesmo após a remoção.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.YAML,
        pattern=r'variables\s*:\s*\n(?:\s+[^\n]+\n)*\s+(?:PASSWORD|SECRET|TOKEN|API_KEY|PRIVATE_KEY|ACCESS_KEY)\s*:\s*["\']?[A-Za-z0-9+/=_\-]{8,}["\']?',
        remediation="Mova credentials para CI/CD Variables no GitLab UI (Settings > CI/CD > Variables). Marque como 'Protected' (apenas branches protegidas) e 'Masked' (não aparece em logs). Para segredos complexos, use GitLab integration com HashiCorp Vault ou AWS Secrets Manager.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GLCI-004",
        name="Runner Privilegiado (privileged: true) em GitLab",
        description="Runners GitLab com 'privileged: true' na configuração executam containers Docker com flag --privileged. Isso permite escalonamento para o host do runner, acesso a todos os devices, módulos do kernel e capacidade de montar qualquer filesystem — equivalente a acesso root no host.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'privileged\s*:\s*true',
        remediation="Use alternativas ao modo privilegiado: Docker-in-Docker com socket binding (mais arriscado) ou Kaniko para build de imagens sem privilégios. Para runners de build, use runners com executor 'shell' ou 'kubernetes' em vez de 'docker' privilegiado. Configure runners específicos para jobs que precisam de privilégios.",
        cwe="CWE-250",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GLCI-005",
        name="image: latest — Imagem sem Versão Fixa",
        description="'image: python:latest' ou qualquer imagem com ':latest' usa a versão mais recente disponível no registry no momento do job. A imagem pode mudar entre runs sem aviso, introduzindo mudanças incompatíveis ou, em um ataque supply chain, código malicioso injetado na nova versão.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'image\s*:\s*["\']?[\w./-]+:latest["\']?',
        remediation="Fixe versões de imagens: 'image: python:3.12.3-slim'. Melhor ainda, fixe pelo digest: 'image: python@sha256:abc123...'. Configure Renovate ou Dependabot para atualizar versões automaticamente. Use imagens base minimais (distroless, alpine) para reduzir superfície de ataque.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GLCI-006",
        name="before_script com Credencial Inline",
        description="Comandos em 'before_script:' que contêm senhas, tokens ou API keys inline ficam visíveis nos logs do pipeline e no arquivo .gitlab-ci.yml. Mesmo com mascaramento de variáveis, um valor hardcoded em script nunca é mascarado automaticamente.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'before_script\s*:\s*\n(?:\s+-[^\n]+\n)*\s+-\s*.*(?:password|token|secret|api.?key)\s*[=:]\s*["\']?\S{6,}',
        remediation="Use CI/CD Variables: before_script: - export API_KEY=$CI_API_KEY. Marque a variável como 'Masked' no GitLab UI. Para credenciais de registry, use GitLab Registry que usa o CI_REGISTRY_USER e CI_REGISTRY_PASSWORD automáticos sem configuração manual.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GLCI-007",
        name="Cache sem Key Específica — Vazamento entre Branches",
        description="'cache:' sem 'key:' ou com key genérica compartilha cache entre branches, PRs e usuários. Um atacante pode comprometer o cache de uma branch protegida fazendo upload de artefatos maliciosos que serão usados em builds de outras branches, incluindo a branch principal.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'cache\s*:\s*\n(?!\s+key\s*:)',
        remediation="Sempre use key explícita: cache: { key: '$CI_COMMIT_REF_SLUG-node-modules', paths: [node_modules/] }. Para isolamento máximo, use '$CI_COMMIT_SHA' como parte da key. Configure 'policy: pull' em jobs que não devem atualizar o cache. Use GitLab Secure Files para artefatos sensíveis.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GLCI-008",
        name="when: always — Job Executa Mesmo após Falha de Segurança",
        description="'when: always' em jobs de deploy ou produção os faz executar mesmo quando jobs anteriores (incluindo segurança) falharam. Isso permite deploy de código com vulnerabilidades detectadas ou testes falhando, contornando efetivamente todos os gates de qualidade do pipeline.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'when\s*:\s*always',
        remediation="Use 'when: on_success' (padrão) para jobs de deploy. Se você precisa limpar recursos após falha, use 'when: always' apenas para cleanup jobs com 'environment: action: stop'. Configure 'needs:' explícito para garantir que jobs de segurança são pré-requisito dos jobs de deploy.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GLCI-009",
        name="retry: em Jobs de Segurança — Falhas Silenciadas",
        description="'retry: 2' ou 'retry: max: 3' em jobs de SAST ou security scanning pode mascarar falhas intermitentes reais como flakiness. Scanners que falham consistentemente são retentados até passar ou até esgotar retries, possivelmente ocultando problemas de configuração do scanner.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'retry\s*:\s*(?:[2-9]|\d{2,})',
        remediation="Não use retry em jobs de security scanning. Se um scanner falha intermitentemente, investigue e corrija a causa raiz. Use 'retry: { max: 1, when: runner_system_failure }' apenas para lidar com falhas de infraestrutura, não de lógica do scanner.",
        cwe="CWE-390",
        confidence=Confidence.LOW,
    ),
]
