import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GO_RULES: list[Rule] = [
    Rule(
        id="GO-001",
        name="SQL Injection via String Formatting",
        description="SQL query built with fmt.Sprintf() or string concatenation with user data is vulnerable to SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.GO,
        pattern=r'fmt\.Sprintf\s*\(\s*["`][^"`]*(?:SELECT|INSERT|UPDATE|DELETE|WHERE)[^"`]*%',
        remediation="Use database/sql with ? or $N placeholders: db.Query(\"SELECT * FROM users WHERE id = ?\", userID)",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GO-002",
        name="SQL Injection via String Concatenation",
        description="Direct string concatenation in SQL queries with user-controlled variables.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.GO,
        pattern=r'(?:Query|QueryRow|Exec)\s*\(\s*["`][^"`]*["`\s]\s*\+',
        remediation="Always use parameterized queries: db.QueryRow(\"SELECT ... WHERE id = $1\", id)",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-003",
        name="Command Injection via exec.Command()",
        description="exec.Command() with user-controlled arguments enables command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.GO,
        pattern=r'\bexec\.Command\s*\(',
        remediation="Validate and allowlist all command arguments. Avoid running shell commands with user-controlled input.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GO-004",
        name="Weak Cryptographic Hash (MD5)",
        description="crypto/md5 produces MD5 hashes which are cryptographically broken.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.GO,
        pattern=r'\bmd5\.(?:New|Sum)\b|["\']crypto/md5["\']',
        remediation="Use crypto/sha256 or golang.org/x/crypto/sha3. For passwords use golang.org/x/crypto/bcrypt.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-005",
        name="Weak Cryptographic Hash (SHA-1)",
        description="crypto/sha1 produces SHA-1 hashes which are cryptographically weak for security use.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.GO,
        pattern=r'\bsha1\.(?:New|Sum)\b|["\']crypto/sha1["\']',
        remediation="Use sha256 or sha512 from the crypto package.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-006",
        name="Weak Cipher (DES)",
        description="crypto/des implements DES, a cipher with a 56-bit key that is trivially brute-forced.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.GO,
        pattern=r'["\']crypto/des["\']|\bdes\.NewCipher\b',
        remediation="Use AES-256-GCM: crypto/aes with cipher.NewGCM().",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-007",
        name="Insecure Randomness (math/rand)",
        description="math/rand is a non-cryptographic PRNG. Its output is predictable and must not be used for security-sensitive values.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.GO,
        pattern=r'["\']math/rand["\']|\brand\.(?:Int|Intn|Float|Read|New)',
        remediation="Use crypto/rand for all security-sensitive randomness: rand.Reader from crypto/rand.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GO-008",
        name="Path Traversal via User-Controlled Path",
        description="File access with user-supplied path components without validation enables directory traversal.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.GO,
        pattern=r'(?:os\.Open|ioutil\.ReadFile|os\.ReadFile|http\.ServeFile)\s*\([^)]*(?:r\.URL|r\.Form|vars\[)',
        remediation="Use filepath.Clean() and verify the result is within the allowed base directory: strings.HasPrefix(clean, base)",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-009",
        name="Disabled TLS Verification",
        description="InsecureSkipVerify: true disables TLS certificate verification, enabling MITM attacks.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.GO,
        pattern=r'InsecureSkipVerify\s*:\s*true',
        remediation="Never disable TLS verification in production. Configure a proper certificate pool instead.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GO-010",
        name="SSRF via User-Controlled HTTP Request",
        description="Making HTTP requests to user-supplied URLs without validation enables SSRF.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.GO,
        pattern=r'http\.(?:Get|Post|Do)\s*\([^)]*(?:r\.URL|r\.Form|vars\[|Param)',
        remediation="Validate target URLs against an allowlist. Block private IP ranges and cloud metadata endpoints.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GO-011",
        name="Goroutine Leak / Missing Context Cancellation",
        description="Starting goroutines without proper context cancellation can lead to goroutine leaks and resource exhaustion.",
        severity=Severity.LOW,
        category=VulnCategory.OTHER,
        language=Language.GO,
        pattern=r'\bgo\s+func\s*\(\s*\)',
        negative_pattern=r'context\.WithCancel|context\.WithTimeout',
        remediation="Pass a context.Context to goroutines for lifecycle management. Use context.WithCancel or context.WithTimeout.",
        cwe="CWE-400",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
]
