"""Regras de segurança adicionais para GraphQL — 8 regras (GQLS-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GRAPHQL_SECURITY_RULES: list[Rule] = [
    Rule(
        id="GQLS-001",
        name="GraphQL Playground Habilitado em Produção",
        description="'playground: true' ou 'graphiql: true' em configuração de servidor GraphQL expõe uma IDE interativa na rota /graphql que permite qualquer pessoa explorar o schema, testar queries e mutations sem autenticação. Em produção, isso é um vetor de reconhecimento e teste de ataques.",
        severity=Severity.HIGH,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.GRAPHQL,
        pattern=r'(?:playground|graphiql)\s*:\s*true',
        remediation="Desabilite em produção: playground: process.env.NODE_ENV !== 'production'. Configure acesso autenticado ao playground para desenvolvimento: use middleware que verifica JWT antes de servir o playground. Nunca exponha playground com mutations habilitadas a usuários não autenticados.",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GQLS-002",
        name="Persisted Queries Desabilitadas — Queries Arbitrárias",
        description="Sem persisted queries, qualquer cliente pode enviar qualquer query GraphQL de qualquer complexidade. Persisted queries permitem apenas queries pré-aprovadas (whitelisting), eliminando a superfície de ataque de queries dinâmicas maliciosas como depth attacks e complexity bombs.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'persistedQueries\s*:\s*(?:false|disabled)',
        remediation="Habilite persisted queries: persistedQueries: {cache: new InMemoryLRUCache()}. Para produção, use Automatic Persisted Queries (APQ) do Apollo: o cliente envia hash da query; servidor retorna NOT_FOUND na primeira vez; cliente reenvia query completa; servidor a armazena. Blocks queries não registradas.",
        cwe="CWE-20",
        owasp="A04:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GQLS-003",
        name="Aliases GraphQL sem Limite — Amplificação de Queries",
        description="GraphQL permite aliases para chamar o mesmo campo múltiplas vezes em uma query: { a: user(id: 1) { name } b: user(id: 1) { name } ... }. Sem limite de aliases, um atacante pode amplificar o trabalho do servidor N vezes em uma única request, causando DoS.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'type\s+(?:Query|Mutation)\s*\{',
        negative_pattern=r'maxAliasCount|noAliases|aliasLimit',
        remediation="Configure limite de aliases: const noAliasRule = (maxCount) => (context) => { let count = 0; return { Field() { if (++count > maxCount) context.reportError(new GraphQLError('Too many aliases')); } }; }. Use graphql-validation-complexity ou similar. Limite de 10-15 aliases por query é razoável.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQLS-004",
        name="Validação GraphQL Desabilitada",
        description="'skipValidation: true' ou desabilitar regras de validação do GraphQL remove proteções built-in contra queries malformadas, queries sobre campos inexistentes e outras verificações de schema. A validação do GraphQL é uma linha de defesa contra queries inválidas e potencialmente exploratórias.",
        severity=Severity.CRITICAL,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'skipValidation\s*:\s*true|validationRules\s*:\s*\[\s*\]',
        remediation="Nunca desabilite validação. Se você tem regras de validação customizadas que conflitam, refatore-as em vez de desabilitar a validação global. As regras default do graphql-js protegem contra loops infinitos em fragments, referências circulares e outros problemas fundamentais.",
        cwe="CWE-20",
        owasp="A04:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GQLS-005",
        name="CSRF em GraphQL sem Proteção para POST",
        description="APIs GraphQL que aceitam mutations via POST sem verificação de origem (CSRF token, SameSite cookie, custom header) são vulneráveis a Cross-Site Request Forgery. Um site malicioso pode fazer o browser do usuário autenticado executar mutations em seu nome.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.GRAPHQL,
        pattern=r'type\s+Mutation\s*\{',
        negative_pattern=r'csrf|csrfToken|X-Requested-With|SameSite|Origin',
        remediation="Implemente proteção CSRF: (1) Use cookies SameSite=Strict para sessions; (2) Adicione custom header X-GraphQL-Request: true e verifique no servidor; (3) Verifique header Origin/Referer contra allowlist de origens. Para APIs públicas com OAuth, use PKCE para tokens de curta duração.",
        cwe="CWE-352",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQLS-006",
        name="Subscription sem Autorização de Tópico",
        description="Subscriptions GraphQL para eventos específicos (orderUpdated(id: $id), messageReceived(channelId: $id)) sem verificação de que o usuário tem acesso ao recurso subscrito permitem que usuários acessem updates de recursos de outros usuários simplesmente conhecendo o ID.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.GRAPHQL,
        pattern=r'type\s+Subscription\s*\{[^}]*\w+\s*\([^)]*(?:id|channelId|roomId|orderId)',
        negative_pattern=r'context\.user|authorization|canAccess|hasPermission',
        remediation="Verifique autorização em subscriptions: subscribe: async (_, { orderId }, context) => { const order = await Order.findById(orderId); if (order.userId !== context.userId) throw new ForbiddenError(); return pubsub.asyncIterator(ORDER_UPDATED_${orderId}); }. Valide ownership antes de assinar tópico.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQLS-007",
        name="DataLoader não Utilizado — N+1 Query Problem",
        description="Resolvers que buscam dados de banco ou API sem DataLoader causam N+1 queries: para uma lista de 100 usuários, 100 queries separadas são feitas para buscar os posts de cada um. Além do impacto em performance, N+1 pode ser explorado para DoS com queries que expandem dados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'(?:resolve|resolver)\s*[=:]\s*async\s*\([^)]*\)\s*=>\s*\{[^}]*await\s+\w+\.find(?:One|ById|All)?\s*\(',
        negative_pattern=r'DataLoader|dataLoader|loader\.',
        remediation="Use DataLoader para batching: const userLoader = new DataLoader(async (ids) => User.findByIds(ids)); resolver: (parent) => userLoader.load(parent.userId). DataLoader faz batch automático das queries do mesmo tick. Isso reduz N+1 para 1 query por tipo por request.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQLS-008",
        name="Query de Custo Alto sem Rate Limiting por Custo",
        description="APIs GraphQL sem rate limiting baseado em custo de query (apenas por número de requests) permitem que um cliente faça poucas requests de altíssima complexidade que consomem os mesmos recursos que muitas requests simples. Rate limits por IP/token não protegem contra queries expensive.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'rateLimit\s*:\s*\{',
        negative_pattern=r'pointsPerQuery|costPerField|complexityCost',
        remediation="Implemente rate limiting por custo: calcule custo da query antes de executar e desconte de um bucket por usuário. Use graphql-rate-limit: @rateLimit(window: '1m', max: 60, message: 'Too many requests'). Combine com complexity limiting para defesa em profundidade.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
]
