"""Regras de segurança para GraphQL — 10 regras (GQL-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GRAPHQL_RULES: list[Rule] = [
    Rule(
        id="GQL-001",
        name="Introspection GraphQL Habilitada em Produção",
        description="A instrospection do GraphQL expõe o schema completo da API, incluindo todos os tipos, campos, queries e mutations disponíveis. Em produção, isso fornece a um atacante um mapa detalhado de toda a API para planejar ataques direcionados, descobrir endpoints ocultos e identificar campos sensíveis.",
        severity=Severity.HIGH,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.GRAPHQL,
        pattern=r'introspection\s*:\s*true|disableIntrospection\s*:\s*false|__schema\s*\{|__type\s*\(',
        remediation="Desabilite introspection em produção: no Apollo Server: new ApolloServer({introspection: false}). No GraphQL Yoga: createYoga({graphiql: false}). Use graphql-depth-limit e graphql-disable-introspection. Em desenvolvimento, habilite apenas para IPs internos.",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GQL-002",
        name="Ausência de Limite de Profundidade em Queries GraphQL",
        description="Queries GraphQL profundamente aninhadas sem limite de profundidade podem causar DoS exponencial. Uma query maliciosa como { users { friends { friends { friends { ... } } } } } com N níveis causa N consultas ao banco em cada nível, esgotando conexões e memória.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'type\s+Query\s*\{|type\s+Mutation\s*\{',
        negative_pattern=r'depthLimit|maxDepth|queryDepth|ComplexityLimit',
        remediation="Implemente limite de profundidade: const depthLimit = require('graphql-depth-limit'); server = new ApolloServer({validationRules: [depthLimit(5)]}). Configure maxDepth: 7 como padrão. Para operações complexas legítimas, use query whitelisting com persisted queries.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-003",
        name="Ausência de Limite de Complexidade em Queries",
        description="Sem limite de complexidade, um atacante pode construir queries que consultam milhares de objetos por request (query batching ou queries com listas): { users(limit: 10000) { posts(limit: 10000) { comments { ... } } } }. Isso esgota recursos do servidor e banco de dados.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'type\s+(?:Query|Mutation|Subscription)\s*\{',
        negative_pattern=r'complexity|costLimit|rateLimit',
        remediation="Use graphql-query-complexity: const complexity = getComplexity({estimators: [fieldExtensionsEstimator(), simpleEstimator({defaultComplexity: 1})], schema, query, variables}). Defina um limite máximo (ex: 1000) e retorne erro se excedido. Combine com paginação obrigatória.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-004",
        name="Injeção SQL em Resolver GraphQL",
        description="Resolvers GraphQL que constroem queries SQL por concatenação de argumentos da query GraphQL são vulneráveis a SQL injection. O GraphQL valida tipos mas não sanitiza strings — um argumento String pode conter qualquer valor incluindo fragmentos SQL.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.GRAPHQL,
        pattern=r'(?:resolve|resolver)\s*[=:]\s*(?:async\s*)?\([^)]*\)\s*(?:=>|{)[^}]*(?:db|pool|connection)\s*\.query\s*\([`"\']\s*SELECT.*\$\{',
        remediation="Use prepared statements/ORM: return db.query('SELECT * FROM users WHERE id = $1', [args.id]). Com Prisma: return prisma.user.findUnique({where: {id: args.id}}). Nunca interpole args de GraphQL em strings SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GQL-005",
        name="Mutations sem Diretiva de Autenticação",
        description="Mutations GraphQL que modificam dados sem verificação de autenticação no resolver ou via diretiva @auth permitem que usuários não autenticados alterem dados. Em schemas GraphQL públicos, todas as mutations devem verificar a identidade do requisitante.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.GRAPHQL,
        pattern=r'type\s+Mutation\s*\{[^}]*\n\s+\w+(?:\([^)]*\))?\s*:\s*\w+',
        negative_pattern=r'@auth|@authenticated|@requiresAuth|context\.user|context\.userId',
        remediation="Implemente autenticação no context: const context = ({req}) => ({user: getUser(req.headers.authorization)}). Em cada resolver: if (!context.user) throw new AuthenticationError('Not authenticated'). Use graphql-shield para policy-based access control centralizado.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-006",
        name="Batching de Queries sem Rate Limiting",
        description="GraphQL permite enviar múltiplas operações em um único request HTTP via array: [{query: '...'}, {query: '...'}, ...]. Sem limite de operações por batch, um atacante pode enviar milhares de operações em um único request, bypassando rate limits baseados em requisição HTTP.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'batchRequests\s*:\s*true|allowBatchedHttpRequests\s*:\s*true',
        remediation="Desabilite batching em produção ou limite o tamanho do batch: allowBatchedHttpRequests: false. Se batching for necessário, limite a N operações por batch e implemente rate limiting por IP que considera o número de operações, não apenas requests HTTP.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GQL-007",
        name="Upload de Arquivo GraphQL sem Validação de Tipo",
        description="Mutations GraphQL com tipo Upload (graphql-upload) sem validação de MIME type e tamanho permitem upload de arquivos executáveis, scripts ou conteúdo malicioso. A validação de extensão de arquivo no frontend é facilmente bypassada.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.GRAPHQL,
        pattern=r'Upload\b[^#\n]*[^#\n](?!.*(?:mimetype|mimeType|maxSize|allowedTypes))',
        remediation="Valide MIME type com file-type (verifica magic bytes, não extensão): const fileType = await fileTypeFromStream(file.createReadStream()); if (!['image/jpeg', 'image/png'].includes(fileType?.mime)) throw new UserInputError('Tipo não permitido'). Defina limite de tamanho: maxFileSize: 10 * 1024 * 1024.",
        cwe="CWE-434",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-008",
        name="Mascaramento de Erros Desabilitado em Produção",
        description="formatError sem mascaramento em produção expõe stack traces, queries SQL, nomes de arquivo internos e outros detalhes de implementação nos erros da API GraphQL. Isso fornece ao atacante informações valiosas para planejamento de ataques.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.GRAPHQL,
        pattern=r'formatError\s*:\s*(?:err\s*=>|error\s*=>)\s*(?:err|error)\b(?!\s*\.\s*message)',
        remediation="Em produção, mascare detalhes internos: formatError: (err) => { if (err.originalError instanceof UserInputError) return err; return new Error('Internal server error'); }. Logue o erro completo internamente: logger.error(err). Use apollo-server-plugin-base para logging centralizado.",
        cwe="CWE-209",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-009",
        name="Subscription GraphQL sem Autenticação",
        description="Subscriptions GraphQL estabelecem conexões WebSocket persistentes. Sem autenticação no handshake de conexão (onConnect), qualquer cliente pode se inscrever para receber eventos em tempo real, potencialmente incluindo dados de outros usuários.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.GRAPHQL,
        pattern=r'(?:subscriptions|SubscriptionServer|useServer)\s*[=(:][^;{]',
        negative_pattern=r'onConnect|connectionParams|context\.user',
        remediation="Valide autenticação no onConnect: subscriptions: {onConnect: (params) => { const token = params.Authorization; if (!verifyToken(token)) throw new Error('Unauthorized'); return {userId: getUserId(token)}; }}. Use o userId do context em todos os resolvers de subscription.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GQL-010",
        name="Autorização em Nível de Campo Ausente",
        description="Em schemas GraphQL com dados multi-tenant ou com diferentes níveis de acesso, retornar campos sensíveis (salary, ssn, privateNotes) sem verificar se o usuário atual tem permissão para ver aquele campo específico expõe dados de outros usuários.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.GRAPHQL,
        pattern=r'type\s+\w+\s*\{[^}]*(?:salary|ssn|password|secret|private|internal|admin)[^}]*\}',
        negative_pattern=r'@auth|@hasRole|@deprecated|shield|rule',
        remediation="Use graphql-shield para autorização em nível de campo: const permissions = shield({Query: {sensitiveData: isAdmin}, User: {salary: or(isAdmin, isSelf)}}). Ou implemente no resolver: if (context.userId !== user.id && !isAdmin(context)) throw new ForbiddenError('Not authorized').",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
]
