"""Regras de segurança para Groovy — 10 regras (GROOVY-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GROOVY_RULES: list[Rule] = [
    Rule(
        id="GROOVY-001",
        name="Execução de Shell via .execute() em GString",
        description="O método .execute() em Groovy transforma qualquer String em um comando de sistema. Quando aplicado a GStrings com interpolação (\"ls ${userInput}\".execute()), resulta em injeção de comandos OS trivial. É um dos vetores mais comuns em pipelines Groovy/Jenkins.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.GROOVY,
        pattern=r'(?:"[^"]*\$\{[^}]+\}[^"]*"|\'[^\']*\$\{[^}]+\}[^\']*\'|[a-zA-Z_]\w*)\.execute\s*\(',
        remediation="Use listas para evitar shell injection: [\"git\", \"clone\", userUrl].execute(). O Groovy passa cada elemento como argumento separado, sem interpretação shell. Valide e sanitize todos os parâmetros. Para Jenkinsfiles, use sh(['script': cmd, 'returnStdout': true]).",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GROOVY-002",
        name="Avaliação Dinâmica de Código com evaluate()",
        description="O método evaluate() do Groovy executa uma String como código Groovy completo em runtime. Se o conteúdo da string vier de input externo, um atacante pode executar qualquer código no contexto da aplicação, incluindo chamadas de sistema, leitura de arquivos e exfiltração de dados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.GROOVY,
        pattern=r'\bevaluate\s*\(\s*(?!["\']\s*["\'])',
        remediation="Elimine o uso de evaluate() com dados externos. Se precisar de expressões dinâmicas, use Groovy Sandbox (plugin do Jenkins) que restringe operações perigosas, ou defina uma DSL limitada com GroovyShell e CompilerConfiguration restritivo.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GROOVY-003",
        name="GroovyShell.evaluate() — Execução de Código Arbitrário",
        description="new GroovyShell().evaluate() compila e executa código Groovy arbitrário em runtime. É equivalente a um eval() sem sandbox. Em aplicações que aceitam scripts de usuários ou templates dinâmicos, é uma vulnerabilidade de execução remota de código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.GROOVY,
        pattern=r'new\s+GroovyShell\s*\([^)]*\)\.(?:evaluate|run|parse)\s*\(',
        remediation="Use GroovyShell com CompilerConfiguration e SecureASTCustomizer que proíbe imports e chamadas de sistema: def config = new CompilerConfiguration(). config.addCompilationCustomizers(new SecureASTCustomizer(allowedImports: [], allowedStaticImports: [])). Considere Apache Commons JEXL para expressões simples.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GROOVY-004",
        name="Injeção SQL via GString em Groovy SQL",
        description="groovy.sql.Sql.execute() ou eachRow() com GString (\"SELECT * FROM users WHERE name = '${name}'\") interpola variáveis diretamente na query. Embora o Groovy Sql tente detectar parâmetros, GStrings passadas diretamente bypassam o prepared statement.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.GROOVY,
        pattern=r'sql\.(?:execute|eachRow|firstRow|rows|executeUpdate|executeInsert)\s*\(\s*["\'][^"\']*\$\{',
        remediation="Use parâmetros posicionais com listas: sql.eachRow(\"SELECT * FROM users WHERE name = ?\", [name]) { row -> ... }. Ou use parâmetros nomeados: sql.execute(\"SELECT * FROM t WHERE id = :id\", [id: userId]). Nunca use GString para SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GROOVY-005",
        name="Desserialização Insegura via ObjectInputStream",
        description="Groovy herda a vulnerabilidade de desserialização Java. ObjectInputStream.readObject() com dados não confiáveis permite que gadget chains (Apache Commons Collections, Spring Framework, etc.) executem código arbitrário durante a desserialização.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.GROOVY,
        pattern=r'new\s+ObjectInputStream\s*\(|\.readObject\s*\(\s*\)',
        remediation="Use JSON (Jackson, Gson) ou XML sem external entities para serialização. Se ObjectInputStream for necessário, implemente um ObjectInputFilter (Java 9+) com allowlist de classes: ObjectInputFilter.Config.createFilter(\"com.myapp.*;java.util.*;!*\")",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GROOVY-006",
        name="Credencial Exposta em Log (println/log)",
        description="Uso de println, log.info, log.debug com variáveis que contêm senhas, tokens ou chaves. Em Groovy/Grails, logs são frequentemente centralizados em ELK/Splunk, onde qualquer pessoa com acesso pode ver as credenciais.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.GROOVY,
        pattern=r'(?:println|log\.(?:info|debug|warn|error|trace))\s*\(.*(?:password|passwd|secret|token|apiKey|api_key|credential)',
        remediation="Nunca logue dados sensíveis. Mascare antes de logar: log.debug(\"Auth attempt for user: ${username}\") — omitindo password. Use MDC (Mapped Diagnostic Context) para correlação sem expor credenciais. Configure log appenders para filtrar padrões sensíveis.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="GROOVY-007",
        name="SSRF via new URL(...).text",
        description="A expressão Groovy new URL(userInput).text faz uma requisição HTTP para qualquer URL e retorna o conteúdo como String. Com input não validado, um atacante pode fazer a aplicação acessar serviços internos (169.254.169.254, localhost), exfiltrar metadados de cloud ou varrer a rede interna.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.GROOVY,
        pattern=r'new\s+URL\s*\([^"\']\w*\)\s*\.(?:text|bytes|openStream|openConnection)',
        remediation="Valide URLs contra uma allowlist de domínios: assert url.startsWith(\"https://api.trusted.com/\"). Resolva o hostname e verifique que não é IP privado (10.x, 172.16-31.x, 192.168.x, 127.x, ::1). Use um proxy de egresso que restrinja destinos.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GROOVY-008",
        name="Algoritmo de Hash Fraco MD5 / SHA-1 via MessageDigest",
        description="MessageDigest.getInstance(\"MD5\") ou \"SHA-1\" em código Groovy herda o problema Java: ambos são criptograficamente quebrados. Colisões MD5 são triviais. SHA-1 foi demonstradamente colisionável (SHAttered attack, 2017).",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.GROOVY,
        pattern=r'MessageDigest\.getInstance\s*\(\s*["\'](?:MD5|SHA-?1)["\']',
        remediation="Para senhas: use BCrypt (Spring Security BCryptPasswordEncoder). Para checksums/integridade: use SHA-256 no mínimo (MessageDigest.getInstance(\"SHA-256\")). Para assinaturas: use SHA-384 ou SHA-512. Migre hashes MD5 legados com re-hash no próximo login.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GROOVY-009",
        name="Carregamento Dinâmico de Classe via GroovyClassLoader",
        description="GroovyClassLoader.parseClass() com código de fonte externo compila e carrega classes Groovy arbitrárias em runtime. Sem sandbox, código carregado tem acesso total ao ambiente JVM, podendo ler arquivos, fazer conexões de rede e executar comandos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.GROOVY,
        pattern=r'GroovyClassLoader\s*\(\s*\)\.parseClass\s*\(|new\s+GroovyClassLoader\s*\([^)]*\)',
        remediation="Nunca carregue código Groovy de fontes não confiáveis. Para plugins/extensões, defina uma interface Java e use ClassLoader com permissões restritas. Considere usar GraalVM Polyglot com restrições de isolamento se extensibilidade for requisito.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GROOVY-010",
        name="XXE via XmlSlurper / XmlParser sem Proteção",
        description="XmlSlurper e XmlParser do Groovy não desabilitam external entities por padrão em versões antigas. Processamento de XML não confiável pode resultar em leitura de arquivos locais (/etc/passwd), SSRF e DoS via Billion Laughs.",
        severity=Severity.HIGH,
        category=VulnCategory.XXE,
        language=Language.GROOVY,
        pattern=r'new\s+XmlSlurper\s*\(\s*\)|new\s+XmlParser\s*\(\s*\)',
        remediation="Use XmlSlurper com parser seguro: def parser = new XmlSlurper(true, false). O primeiro parâmetro (validating=true) e segundo (namespaceAware=false) previnem XXE em Groovy 2.5+. Para Groovy < 2.5, configure manualmente: parser.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true).",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
]
