"""Regras de segurança para gRPC — 8 regras (GRPC-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

GRPC_RULES: list[Rule] = [
    Rule(
        id="GRPC-001",
        name="gRPC Connection sem TLS — insecure.NewCredentials()",
        description="'insecure.NewCredentials()' em gRPC Go ou 'grpc.insecure_channel()' em Python estabelece conexões gRPC sem criptografia TLS. Todo tráfego — incluindo dados sensíveis, credentials em metadata, e tokens de autenticação — é transmitido em plaintext, sujeito a interceptação.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CRYPTO,
        language=Language.PROTOBUF,
        pattern=r'insecure\.NewCredentials\(\)|insecure_channel\s*\(',
        remediation="Use TLS: credentials.NewClientTLSFromFile(certFile, '') para Go, ou grpc.secure_channel(address, grpc.ssl_channel_credentials()) para Python. Para mTLS (autenticação mútua): credentials.NewTLS com certificado de cliente. Use cert-manager para provisionar certificados automaticamente.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GRPC-002",
        name="grpc.Dial sem TransportCredentials — Canal Inseguro",
        description="'grpc.Dial(address, grpc.WithInsecure())' ou 'grpc.Dial' sem 'grpc.WithTransportCredentials()' cria um channel gRPC sem TLS. 'WithInsecure' foi deprecated mas ainda aceito. A ausência de credentials significa que qualquer dados transmitido está em plaintext na rede.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CRYPTO,
        language=Language.PROTOBUF,
        pattern=r'grpc\.(?:Dial|NewClient)\s*\([^)]*grpc\.WithInsecure\s*\(\s*\)',
        remediation="Substitua grpc.WithInsecure() por grpc.WithTransportCredentials(credentials.NewClientTLSFromFile(caFile, serverName)). Para desenvolvimento local, use credentials.NewTLS(&tls.Config{InsecureSkipVerify: true}) apenas — nunca em produção. Use grpc.WithBlock() com context timeout para fail-fast.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="GRPC-003",
        name="gRPC Server Reflection Habilitada em Produção",
        description="'reflection.Register(grpcServer)' (Go) ou 'from grpc_reflection.v1alpha import reflection' (Python) habilita gRPC Server Reflection, que expõe todos os services, methods e message types sem autenticação. Ferramentas como grpcurl e Postman podem listar e chamar qualquer RPC.",
        severity=Severity.HIGH,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.PROTOBUF,
        pattern=r'reflection\.Register\s*\(|grpc_reflection',
        remediation="Desabilite reflection em produção. Se necessário para debugging, proteja com interceptor de autenticação: use UnaryInterceptor que verifica um token admin antes de responder a chamadas de reflection. Configure por variável de ambiente: if os.getenv('ENABLE_REFLECTION'): reflection.Register(server).",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GRPC-004",
        name="gRPC Interceptor de Autenticação Ausente",
        description="Servidores gRPC sem UnaryInterceptor ou StreamInterceptor de autenticação não verificam a identidade do cliente em nenhuma chamada RPC. Qualquer cliente que conhece o endereço do servidor pode chamar qualquer método sem credenciais.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.PROTOBUF,
        pattern=r'grpc\.NewServer\s*\(\s*\)',
        remediation="Adicione interceptors de autenticação: grpc.NewServer(grpc.UnaryInterceptor(authInterceptor), grpc.StreamInterceptor(authStreamInterceptor)). Implemente JWT validation no interceptor. Use grpc-middleware para composição de interceptors. Configure peer.FromContext para extrair informações do cliente.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GRPC-005",
        name="MaxRecvMsgSize Muito Grande ou Ausente — DoS",
        description="Sem limite de tamanho de mensagem ou com 'MaxRecvMsgSize' muito grande, um cliente pode enviar mensagens gRPC de gigabytes, causando esgotamento de memória no servidor. O valor padrão do gRPC (4MB) pode ser insuficiente para alguns casos e muito grande para outros.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PROTOBUF,
        pattern=r'MaxRecvMsgSize\s*(?::|=)\s*(?:[1-9]\d{8,}|\d+\s*\*\s*\d+\s*\*\s*\d+)',
        remediation="Configure limites razoáveis: grpc.MaxRecvMsgSize(4*1024*1024) para 4MB. Para streaming de arquivos grandes, use streaming RPC com chunks de tamanho controlado em vez de uma única mensagem grande. Combine com rate limiting por cliente via interceptor.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="GRPC-006",
        name="gRPC Call sem Deadline/Timeout",
        description="Chamadas gRPC sem context.WithTimeout() ou context.WithDeadline() podem bloquear indefinidamente se o servidor ficar lento ou não responder. Em sistemas distribuídos, calls sem timeout propagam falhas: um serviço lento causa cascata de goroutines/threads bloqueadas nos clientes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PROTOBUF,
        pattern=r'(?:client|stub|conn)\.\w+\s*\(\s*context\.Background\s*\(\s*\)',
        remediation="Sempre use contexto com deadline: ctx, cancel := context.WithTimeout(ctx, 5*time.Second); defer cancel(); response, err := client.MyRPC(ctx, request). Defina timeouts diferentes por operação (queries simples vs relatórios). Propague o deadline do request upstream via context.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GRPC-007",
        name="mTLS não Configurado — Autenticação de Cliente Ausente",
        description="gRPC com TLS unidirecional (apenas servidor autenticado) não verifica a identidade do cliente. Em microserviços internos, mTLS garante que apenas serviços autorizados possam chamar cada serviço. Sem mTLS, qualquer entidade na rede interna pode fazer chamadas RPC.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.PROTOBUF,
        pattern=r'credentials\.NewServerTLSFromFile\s*\(',
        negative_pattern=r'ClientAuth|RequireAnyClientCert|RequireAndVerifyClientCert',
        remediation="Configure mTLS: tls.Config{ClientAuth: tls.RequireAndVerifyClientCert, ClientCAs: clientCertPool}. Use cert-manager com istio ou SPIFFE/SPIRE para provisionar certificados de serviço automaticamente. Configure certificados de cliente por namespace/serviço para controle granular.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="GRPC-008",
        name="Erro gRPC sem Código de Status Apropriado",
        description="Retornar erros gRPC com 'status.Error(codes.Internal, err.Error())' para todos os erros expõe detalhes internos (mensagens de erro de banco, stack traces) ao cliente. O cliente pode usar essas informações para descobrir a implementação interna e planejar ataques.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.PROTOBUF,
        pattern=r'status\.Error\s*\(\s*codes\.Internal\s*,\s*err\.Error\s*\(\s*\)\s*\)',
        remediation="Mapeie erros para códigos gRPC sem expor detalhes: codes.NotFound para 'recurso não existe', codes.InvalidArgument para input inválido, codes.Internal com mensagem genérica para erros de infra. Logue o erro completo internamente com correlation ID: logger.Error(err); return status.Error(codes.Internal, 'internal error').",
        cwe="CWE-209",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
]
