"""Regras de segurança para Haskell — 9 regras (HASKELL-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

HASKELL_RULES: list[Rule] = [
    Rule(
        id="HASKELL-001",
        name="unsafePerformIO — Efeito IO Fora do Contexto Monádico",
        description="System.IO.Unsafe.unsafePerformIO executa ações IO de forma pura aparente, quebrando as garantias de segurança do sistema de tipos Haskell. Pode causar comportamentos não determinísticos, condições de corrida em programas concorrentes e é impossível de testar adequadamente. Em FFI ou serialização, pode introduzir vulnerabilidades difíceis de rastrear.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.HASKELL,
        pattern=r'\bunsafePerformIO\b',
        remediation="Reestruture o código para manter efeitos IO dentro da mônada IO. Se precisar de inicialização global única, use IORef com atomicModifyIORef ou o padrão Singleton com Data.IORef. Para FFI, considere brackets e finally para garantir segurança de recursos.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="HASKELL-002",
        name="unsafeCoerce — Conversão de Tipo sem Verificação",
        description="Data.Coerce.unsafeCoerce e GHC.Exts.unsafeCoerce# convertem qualquer tipo para outro sem verificação em runtime. Uso incorreto causa corrupção de memória, crashes por violação de representação e comportamento indefinido — especialmente perigoso ao interagir com código FFI/C.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.HASKELL,
        pattern=r'\bunsafeCoerce\b|\bunsafeCoerce#\b',
        remediation="Use coerce de Data.Coerce quando os tipos têm a mesma representação (newtypes). Para conversões entre tipos de larguras diferentes, use fromIntegral, toEnum, fromEnum. Para FFI, use tipos C explícitos de Foreign.C.Types.",
        cwe="CWE-704",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="HASKELL-003",
        name="Path Traversal via readFile com Caminho Externo",
        description="readFile, readBinaryFile ou openFile com caminhos derivados de argumentos de linha de comando, variáveis de ambiente ou entrada do usuário. Sem normalização, sequências ../ permitem leitura arbitrária de arquivos do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.HASKELL,
        pattern=r'readFile\s+\w+|openFile\s+\w+\s+ReadMode',
        remediation="Normalize e valide caminhos: use System.FilePath.normalise e verifique que o resultado começa com o diretório base. Implemente: let safeRead base path = let full = normalise (base </> path) in if base `isPrefixOf` full then readFile full else throwIO (userError \"forbidden\")",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HASKELL-004",
        name="Função Parcial fromJust — Crash em Nothing",
        description="Data.Maybe.fromJust lança uma exceção (error) quando aplicada a Nothing. Em código de produção que processa dados externos (JSON, banco de dados, requisições HTTP), valores ausentes são esperados. fromJust nestes contextos causa crashes do programa, potencialmente um vetor de DoS.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.HASKELL,
        pattern=r'\bfromJust\b',
        remediation="Use pattern matching explícito: case maybeVal of { Just x -> use x; Nothing -> handleError }. Ou use maybe defaultValue id maybeVal. Para erros de programação (valor realmente nunca deveria ser Nothing), documente o invariante e considere fromMaybe com erro descritivo.",
        cwe="CWE-476",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HASKELL-005",
        name="Injeção de Comando via System.Process",
        description="readProcess, callCommand ou createProcess com ShellCommand e argumentos construídos de input externo. callCommand usa /bin/sh -c internamente, tornando-o vulnerável a injeção de shell. readProcess com argumentos dinâmicos pode ser explorado dependendo do executável.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.HASKELL,
        pattern=r'callCommand\s+|readProcess\s+\w+\s+\[|createProcess\s*\(\s*shell\s+',
        remediation="Use createProcess com RawCommand em vez de ShellCommand: createProcess (proc \"/usr/bin/git\" [\"clone\", userUrl]). Nunca use callCommand com input dinâmico — ele passa por shell. Para RawCommand, valide cada argumento individualmente contra uma whitelist.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="HASKELL-006",
        name="Conexão HTTP Não Criptografada em Network.HTTP",
        description="URLs http:// em chamadas de Network.HTTP, http-client ou wreq transmitem dados em texto puro. Em ambientes de cloud e microserviços, interceptação passiva ou ativa de tráfego interno é possível e frequentemente explorada.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.HASKELL,
        pattern=r'(?:simpleHTTP|httpLBS|getWith|postWith)\s+.*["\']http://',
        remediation="Use https:// e o pacote http-client-tls. Importe Network.HTTP.Client.TLS e use tlsManagerSettings: manager <- newManager tlsManagerSettings. Valide certificados e não use NoVerifySSL em produção.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="HASKELL-007",
        name="Hash Criptograficamente Fraco via Crypto.Hash.MD5",
        description="Crypto.Hash.MD5 e Crypto.Hash.SHA1 do pacote cryptonite produzem hashes criptograficamente quebrados. MD5 tem colisões triviais. SHA-1 foi demonstradamente colisionável. Uso para verificação de integridade ou autenticação é inseguro.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.HASKELL,
        pattern=r'Crypto\.Hash\.(?:MD5|SHA1)\b|hash\s+\(\s*Proxy\s+::\s+Proxy\s+(?:MD5|SHA1)',
        remediation="Use Crypto.Hash.SHA256, SHA3_256 ou Blake2b_256 do pacote cryptonite. Para senhas, use Crypto.KDF.BCrypt (pacote bcrypt) ou Crypto.KDF.Argon2 (pacote argon2). Migre hashes MD5 legados com re-hash na próxima autenticação.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="HASKELL-008",
        name="Função Parcial read — Crash em Input Malformado",
        description="A função read :: String -> a é parcial: lança uma exceção de runtime se o input não puder ser parseado para o tipo esperado. Em aplicações web ou de rede, usar read diretamente em dados externos é um vetor de negação de serviço.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.HASKELL,
        pattern=r'\bread\s+\w+|\bread\s*::\s*String',
        remediation="Use reads que retorna [(a, String)] para verificar falhas: case reads input of { [(val, \"\")] -> use val; _ -> handleParseError }. Ou use Text.Read.readMaybe que retorna Maybe a. Para JSON, use aeson com FromJSON.",
        cwe="CWE-20",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HASKELL-009",
        name="unsafeDupablePerformIO — IO Duplicável sem Garantias",
        description="GHC.IO.Unsafe.unsafeDupablePerformIO pode executar a ação IO mais de uma vez em sistemas com sparks (computação especulativa). Além dos riscos de unsafePerformIO, há risco de duplicação de efeitos colaterais como criação de arquivos, envio de emails ou débitos financeiros.",
        severity=Severity.HIGH,
        category=VulnCategory.RACE_CONDITION,
        language=Language.HASKELL,
        pattern=r'\bunsafeDupablePerformIO\b',
        remediation="Substitua por unsafePerformIO se duplicação for inaceitável (com os riscos associados) ou, melhor, reestruture para evitar IO unsafe completamente. Use MVars, TVars ou IORef para estado global de forma segura.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
]
