"""Regras de segurança para HTML / templates web."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

HTML_RULES: list[Rule] = [
    Rule(
        id="HTML-001",
        name="Handler de Evento Inline (onclick, onerror, etc.) — XSS",
        description="Atributos de evento HTML inline como onclick=, onerror=, onload= com dados dinâmicos são vetores primários de XSS armazenado e refletido.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.HTML,
        pattern=r'\bon(?:click|error|load|mouseover|submit|focus|blur|change|keyup|keydown)\s*=\s*["\'][^"\']*\$|\bon\w+\s*=\s*["\'][^"\']*(?:eval|document\.)',
        remediation="Separe JavaScript do HTML usando addEventListener. Nunca interpole dados não sanitizados em event handlers. Use Content Security Policy (CSP) para bloquear inline scripts.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="HTML-002",
        name="target='_blank' sem rel='noopener noreferrer'",
        description="Links com target='_blank' sem rel='noopener noreferrer' permitem que a página destino acesse window.opener da página original, possibilitando redirecionamento malicioso.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.HTML,
        pattern=r'target\s*=\s*["\']_blank["\']',
        negative_pattern=r'rel\s*=\s*["\'](?:[^"\']*\s)?noopener(?:\s[^"\']*)?["\']',
        remediation="Sempre adicione rel=\"noopener noreferrer\" em links target='_blank': <a href=\"...\" target=\"_blank\" rel=\"noopener noreferrer\">",
        cwe="CWE-1022",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="HTML-003",
        name="Formulário sem CSRF Token",
        description="Formulário POST sem campo hidden de CSRF token é vulnerável a ataques Cross-Site Request Forgery. Um atacante pode forjar requisições em nome do usuário autenticado.",
        severity=Severity.HIGH,
        category=VulnCategory.CSRF,
        language=Language.HTML,
        pattern=r'<form\s[^>]*method\s*=\s*["\']post["\']',
        negative_pattern=r'(?:csrf|_token|nonce|authenticity_token)',
        remediation="Adicione token CSRF em todos os formulários POST: <input type=\"hidden\" name=\"csrf_token\" value=\"{{ csrf_token }}\">. Use SameSite=Strict em cookies de sessão.",
        cwe="CWE-352",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HTML-004",
        name="Recurso HTTP em Página HTTPS (Mixed Content)",
        description="Carregar scripts, estilos ou imagens via http:// em página HTTPS (mixed content) permite que atacantes MITM injetem conteúdo malicioso na página segura.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.HTML,
        pattern=r'(?:src|href|action)\s*=\s*["\']http://(?!localhost|127\.0\.0\.1)',
        remediation="Use sempre https:// ou URLs relativas de protocolo //. Configure HSTS no servidor para forçar HTTPS. Use Content Security Policy com upgrade-insecure-requests.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="HTML-005",
        name="input type='password' sem autocomplete='off'",
        description="Campos de senha sem autocomplete='off' podem ser salvos pelo browser em sistemas compartilhados ou comprometidos por extensões maliciosas que leem campos auto-completados.",
        severity=Severity.LOW,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.HTML,
        pattern=r'<input[^>]*type\s*=\s*["\']password["\']',
        negative_pattern=r'autocomplete\s*=\s*["\'](?:off|new-password)["\']',
        remediation="Adicione autocomplete='new-password' em campos de criação de senha e autocomplete='current-password' em campos de login. autocomplete='off' desabilita o preenchimento.",
        cwe="CWE-522",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="HTML-006",
        name="Ausência de Content Security Policy Meta Tag",
        description="Sem Content Security Policy (CSP), o browser aceita scripts de qualquer origem. CSP é a principal defesa contra XSS, limitando de onde scripts podem ser carregados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.HTML,
        pattern=r'<head\b',
        negative_pattern=r'(?:Content-Security-Policy|content-security-policy)',
        remediation="Adicione CSP via header HTTP (mais seguro) ou meta tag: <meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self'\">. Use report-uri para monitorar violações.",
        cwe="CWE-1021",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HTML-007",
        name="Script Inline sem Nonce — XSS via Injeção em Template",
        description="<script> inline (não de arquivo externo) sem nonce CSP não pode ser permitido seletivamente pelo CSP. Qualquer injeção de conteúdo nesse template pode incluir scripts.",
        severity=Severity.MEDIUM,
        category=VulnCategory.XSS,
        language=Language.HTML,
        pattern=r'<script(?!\s+(?:src|nonce))\b[^>]*>(?!.*<\/script>).{0,5}$',
        remediation="Use <script nonce=\"{{ nonce }}\"> com nonce gerado por request. Ou mova todo JavaScript para arquivos externos referenciados por src.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HTML-008",
        name="Ausência de X-Frame-Options / frame-ancestors (Clickjacking)",
        description="Sem proteção contra framing, a página pode ser embutida em um iframe invisível em site malicioso. O usuário pensa estar clicando em algo mas na verdade interage com sua app (Clickjacking).",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.HTML,
        pattern=r'<!DOCTYPE\s+html>',
        negative_pattern=r'(?:X-Frame-Options|frame-ancestors|x-frame-options)',
        remediation="Adicione header X-Frame-Options: DENY ou SAMEORIGIN no servidor. Ou use CSP: Content-Security-Policy: frame-ancestors 'none' (mais granular e moderno).",
        cwe="CWE-1021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="HTML-009",
        name="Uso de document.write() — XSS e Performance",
        description="document.write() em templates HTML inserindo dados não sanitizados é XSS direto. Também bloqueia o parser HTML e degrada performance significativamente.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.HTML,
        pattern=r'document\.write\s*\(',
        remediation="Substitua por createElement/appendChild ou innerHTML com sanitização via DOMPurify. Use frameworks modernos que escapam automaticamente.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="HTML-010",
        name="Meta Refresh para Redirecionamento",
        description="<meta http-equiv='refresh' content='0;url=...'> com URL dinâmica é vulnerável a Open Redirect se a URL contém input do usuário não validado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.HTML,
        pattern=r'<meta[^>]*http-equiv\s*=\s*["\']refresh["\'][^>]*url\s*=',
        remediation="Valide URLs de destino contra uma allowlist de domínios permitidos. Prefira redirecionamentos server-side com validação. Evite meta refresh com URLs dinâmicas.",
        cwe="CWE-601",
        confidence=Confidence.MEDIUM,
    ),
]
