"""Regras de segurança para iOS Info.plist e Entitlements — 8 regras (IPLIST-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

IOS_PLIST_RULES: list[Rule] = [
    Rule(
        id="IPLIST-001",
        name="NSAllowsArbitraryLoads: true — ATS Completamente Desabilitado",
        description="'NSAllowsArbitraryLoads: true' em NSAppTransportSecurity desabilita completamente o App Transport Security, permitindo que o app faça conexões HTTP não criptografadas com qualquer host. ATS foi introduzido no iOS 9 para forçar HTTPS. Desabilitar globalmente elimina essa proteção de privacidade.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.XML,
        pattern=r'NSAllowsArbitraryLoads\s*</key>\s*<true/>',
        remediation="Remova NSAllowsArbitraryLoads. Para exceções legítimas (third-party SDKs que ainda usam HTTP), use NSExceptionDomains com domínios específicos: <key>NSExceptionDomains</key><dict><key>legacy-api.example.com</key><dict><key>NSExceptionAllowsInsecureHTTPLoads</key><true/></dict></dict>.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="IPLIST-002",
        name="NSExceptionAllowsInsecureHTTPLoads para Domínio de Produção",
        description="'NSExceptionAllowsInsecureHTTPLoads: true' para um domínio específico permite HTTP para aquele domínio. Se o domínio é de produção (api.seuapp.com, backend.seuapp.com), dados sensíveis (tokens, dados de usuário) são transmitidos sem criptografia nessas chamadas.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.XML,
        pattern=r'NSExceptionAllowsInsecureHTTPLoads\s*</key>\s*<true/>',
        remediation="Migre o endpoint para HTTPS. Se o servidor não suporta HTTPS, exija que a equipe de backend configure TLS. Como solução temporária, use NSExceptionMinimumTLSVersion para forçar versão mínima em vez de desabilitar completamente. Nunca use NSExceptionAllowsInsecureHTTPLoads em produção.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="IPLIST-003",
        name="UIFileSharingEnabled — Documentos Acessíveis via iTunes",
        description="'UIFileSharingEnabled: true' expõe o diretório Documents/ do app via iTunes e Finder quando o dispositivo está conectado. Um atacante com acesso físico ao dispositivo (ou conexão USB não bloqueada) pode extrair todos os documentos do app, incluindo documentos confidenciais, exports e arquivos de configuração.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.XML,
        pattern=r'UIFileSharingEnabled\s*</key>\s*<true/>',
        remediation="Remova UIFileSharingEnabled ou defina como false. Se compartilhamento de arquivos é necessário (ex: app de documentos), use a API Document Picker do iOS que dá controle ao usuário sobre quais arquivos compartilhar. Nunca armazene dados sensíveis no Documents/ de apps com file sharing habilitado.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="IPLIST-004",
        name="NSLocationAlwaysUsageDescription — Localização em Background",
        description="'NSLocationAlwaysUsageDescription' solicita acesso à localização em background (always), incluindo quando o app está fechado. Este é o nível mais invasivo de acesso à localização. Apps que não precisam genuinamente de rastreamento contínuo não devem solicitar Always, apenas WhenInUse.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.XML,
        pattern=r'NSLocationAlwaysUsageDescription\s*</key>',
        remediation="Use NSLocationWhenInUseUsageDescription se a localização é necessária apenas durante uso ativo do app. Use NSLocationAlwaysAndWhenInUseUsageDescription apenas se houver funcionalidade que requer background location (geofencing, rastreamento de entrega). Justifique claramente na string de descrição.",
        cwe="CWE-250",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="IPLIST-005",
        name="com.apple.security.app-sandbox: false — Sem Sandbox",
        description="Entitlement 'com.apple.security.app-sandbox' definido como false em macOS desabilita a App Sandbox para apps Mac. Sem sandbox, o app tem acesso irrestrito ao filesystem, rede e recursos do sistema como qualquer processo do usuário. A sandbox é obrigatória para Mac App Store e recomendada para apps distribuídos.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'com\.apple\.security\.app-sandbox\s*</key>\s*<false/>',
        remediation="Habilite a sandbox: <key>com.apple.security.app-sandbox</key><true/>. Configure entitlements mínimos necessários: com.apple.security.files.user-selected.read-only para acesso a arquivos selecionados pelo usuário, com.apple.security.network.client para conexões de rede de saída.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="IPLIST-006",
        name="com.apple.security.cs.disable-library-validation — Carregamento de Código Arbitrário",
        description="'com.apple.security.cs.disable-library-validation' desabilita a validação de assinatura de código em bibliotecas carregadas dinamicamente no macOS. Isso permite que o processo carregue qualquer dylib, incluindo injeções maliciosas via DYLD_INSERT_LIBRARIES ou substituição de frameworks.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'com\.apple\.security\.cs\.disable-library-validation\s*</key>\s*<true/>',
        remediation="Remova este entitlement. Se o app carrega plugins de terceiros, use a Hardened Runtime com entitlement específico para plugins: com.apple.security.cs.disable-library-validation somente quando absolutamente necessário e com plugins assinados. Considere usar XPC services para isolar código de terceiros.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="IPLIST-007",
        name="LSApplicationQueriesSchemes com Esquemas Sensíveis",
        description="'LSApplicationQueriesSchemes' declara URL schemes para os quais o app pode verificar existência (canOpenURL). Listar muitos schemes permite fingerprinting de apps instalados no dispositivo. Conhecer quais apps de banco, VPN ou segurança o usuário tem instalado é informação sensível para atacantes.",
        severity=Severity.LOW,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.XML,
        pattern=r'LSApplicationQueriesSchemes\s*</key>\s*<array>(?:\s*<string>[^<]+</string>\s*){5,}',
        remediation="Minimize LSApplicationQueriesSchemes ao mínimo necessário. Documente o propósito de cada scheme. A Apple limita a 50 schemes por app. Desde iOS 15, use Universal Links em vez de custom URL schemes — não requerem LSApplicationQueriesSchemes e são mais seguros contra hijacking.",
        cwe="CWE-200",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="IPLIST-008",
        name="NSAllowsArbitraryLoadsInWebContent — ATS Desabilitado para WebViews",
        description="'NSAllowsArbitraryLoadsInWebContent: true' permite que WKWebView carregue URLs HTTP. Conteúdo web carregado via HTTP em um WebView é vulnerável a MITM: um atacante pode injetar JavaScript malicioso que roda no contexto do app, potencialmente acessando bridges nativas.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.XML,
        pattern=r'NSAllowsArbitraryLoadsInWebContent\s*</key>\s*<true/>',
        remediation="Remova NSAllowsArbitraryLoadsInWebContent. Migre todo conteúdo web para HTTPS. Configure WKWebView com Content Security Policy que rejeita mixed content: webView.configuration.userContentController.add(CSPHandler). Use WKNavigationDelegate para bloquear navegação para URLs HTTP.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
]
