import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

JAVA_RULES: list[Rule] = [
    Rule(
        id="JAVA-001",
        name="SQL Injection via String Concatenation",
        description="SQL query built by concatenating request parameters or user input. Enables SQL injection attacks.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.JAVA,
        pattern=r'(?:executeQuery|executeUpdate|execute|prepareStatement)\s*\(\s*["\'].*["\'\s]\s*\+',
        remediation="Use PreparedStatement with parameter placeholders: PreparedStatement ps = conn.prepareStatement('SELECT * FROM users WHERE id = ?'); ps.setInt(1, userId);",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-002",
        name="SQL Injection via Request Parameter",
        description="Direct use of request.getParameter() in a query string construction.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.JAVA,
        pattern=r'(?:getParameter|getQueryString|getHeader)\s*\([^)]+\).*(?:execute|query)',
        remediation="Use PreparedStatement with bind parameters. Never insert getParameter() results directly into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-003",
        name="Command Injection via Runtime.exec()",
        description="Runtime.getRuntime().exec() or ProcessBuilder with user-controlled input enables OS command injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.JAVA,
        pattern=r'Runtime\.getRuntime\(\)\.exec\s*\(',
        remediation="Validate and allowlist all inputs. Pass command as a String[] array. Avoid executing OS commands from user input.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-004",
        name="Command Injection via ProcessBuilder",
        description="ProcessBuilder with user-controlled arguments enables command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.JAVA,
        pattern=r'\bnew\s+ProcessBuilder\s*\(',
        remediation="Use a fixed command array. Strictly validate all arguments against an allowlist.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-005",
        name="Insecure Deserialization via ObjectInputStream",
        description="Java Object deserialization with ObjectInputStream allows attackers who control the byte stream to execute arbitrary code.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.JAVA,
        pattern=r'\bnew\s+ObjectInputStream\s*\(',
        remediation="Implement a ValidatingObjectInputStream (Apache Commons IO) with an allowlist of permitted classes. Prefer JSON/protobuf.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-006",
        name="Weak Cryptographic Hash (MD5)",
        description="MD5 is cryptographically broken and trivially collides. Do not use for integrity or authentication.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.JAVA,
        pattern=r'MessageDigest\.getInstance\s*\(\s*["\']MD5["\']',
        remediation="Use SHA-256: MessageDigest.getInstance(\"SHA-256\"). For passwords use BCrypt (Spring Security) or Argon2.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-007",
        name="Weak Cryptographic Hash (SHA-1)",
        description="SHA-1 is cryptographically weak. Its use for security purposes is deprecated.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.JAVA,
        pattern=r'MessageDigest\.getInstance\s*\(\s*["\']SHA-?1["\']',
        remediation="Use SHA-256 or SHA-3.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-008",
        name="Weak Cipher (DES/3DES)",
        description="DES and Triple-DES are outdated symmetric ciphers with insufficient key sizes.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.JAVA,
        pattern=r'Cipher\.getInstance\s*\(\s*["\'](?:DES|DESede|TripleDES|3DES)',
        remediation="Use AES-256-GCM: Cipher.getInstance(\"AES/GCM/NoPadding\").",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JAVA-009",
        name="Insecure Random Number Generator",
        description="java.util.Random is not cryptographically secure. Using it for security-sensitive values (tokens, keys) is exploitable.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.JAVA,
        pattern=r'\bnew\s+Random\s*\(\s*\)',
        remediation="Use SecureRandom: SecureRandom random = new SecureRandom();",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-010",
        name="XML External Entity (XXE) — DocumentBuilderFactory",
        description="DocumentBuilderFactory without XXE protection is vulnerable to XXE attacks that can read local files or cause SSRF.",
        severity=Severity.HIGH,
        category=VulnCategory.XXE,
        language=Language.JAVA,
        pattern=r'DocumentBuilderFactory\.newInstance\s*\(',
        negative_pattern=r'setFeature\s*\(\s*["\']http://apache\.org/xml/features/disallow-doctype',
        remediation="Disable DOCTYPE declarations: factory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true);",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-011",
        name="XML External Entity (XXE) — SAXParserFactory",
        description="SAXParserFactory without XXE protections can be exploited for file disclosure or SSRF.",
        severity=Severity.HIGH,
        category=VulnCategory.XXE,
        language=Language.JAVA,
        pattern=r'SAXParserFactory\.newInstance\s*\(',
        negative_pattern=r'setFeature\s*\(\s*["\']http://apache\.org',
        remediation="Set setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true) on the factory.",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-012",
        name="Path Traversal via File Constructor",
        description="File or Path constructed from user-controlled input without path normalization enables directory traversal.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.JAVA,
        pattern=r'new\s+(?:File|FileInputStream|FileOutputStream)\s*\(\s*(?:request\.|getParameter|input)',
        remediation="Use Paths.get(base).resolve(userInput).normalize() and verify the result starts with the base path.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JAVA-013",
        name="LDAP Injection",
        description="User-supplied data embedded in an LDAP filter without escaping allows LDAP injection.",
        severity=Severity.HIGH,
        category=VulnCategory.LDAP_INJECTION,
        language=Language.JAVA,
        pattern=r'(?:search|searchSubtree|SearchControls)\s*\([^)]*\+\s*\w',
        remediation="Escape LDAP special characters using JNDI/OWASP encoding. Use parameterized LDAP queries.",
        cwe="CWE-90",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JAVA-014",
        name="Hard-coded Password in Java",
        description="A password or credential appears hardcoded in Java source code.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.JAVA,
        pattern=r'(?:String|char\[\])\s+\w*[Pp]assword\w*\s*=\s*["\'][^"\']{3,}["\']',
        remediation="Load credentials from environment variables or a secrets manager at runtime.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
        negative_pattern=r'(?:System\.getenv|getProperty|config\.get)',
    ),
    Rule(
        id="JAVA-015",
        name="Server-Side Request Forgery (SSRF)",
        description="URL constructed from user input and opened with HttpURLConnection or similar enables SSRF.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.JAVA,
        pattern=r'new\s+URL\s*\(\s*(?:request\.|getParameter|input)',
        remediation="Validate URLs against an allowlist of permitted hosts/protocols. Block private IP ranges and metadata endpoints.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.HIGH,
    ),
]
