import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

JAVASCRIPT_RULES: list[Rule] = [
    Rule(
        id="JS-001",
        name="eval() Code Injection",
        description="eval() executes arbitrary JavaScript from a string. Passing user-controlled input to eval() results in Remote Code Execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'\beval\s*\(',
        remediation="Remove eval(). Use JSON.parse() for data, or explicit logic. If dynamic execution is unavoidable, use a sandboxed VM.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-002",
        name="new Function() Code Injection",
        description="new Function() is equivalent to eval() and compiles arbitrary JavaScript from a string.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'\bnew\s+Function\s*\(',
        remediation="Replace new Function() with explicit functions or a proper template engine.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-003",
        name="innerHTML XSS Sink",
        description="Assigning user-controlled data to innerHTML without sanitization introduces XSS. The browser parses and executes embedded scripts.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.JAVASCRIPT,
        pattern=r'\.innerHTML\s*=',
        remediation="Use textContent instead of innerHTML for plain text. Use DOMPurify to sanitize HTML before assignment.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JS-004",
        name="outerHTML XSS Sink",
        description="outerHTML with user-controlled data introduces XSS.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.JAVASCRIPT,
        pattern=r'\.outerHTML\s*=',
        remediation="Use DOMPurify.sanitize() before assigning to outerHTML.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JS-005",
        name="document.write() XSS Sink",
        description="document.write() writes raw HTML including scripts. It is a classic XSS sink.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.JAVASCRIPT,
        pattern=r'\bdocument\.write\s*\(',
        remediation="Replace document.write() with DOM manipulation (createElement, appendChild, textContent).",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JS-006",
        name="dangerouslySetInnerHTML (React XSS)",
        description="dangerouslySetInnerHTML bypasses React's XSS protections. Setting it with unsanitized data allows script injection.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.JAVASCRIPT,
        pattern=r'dangerouslySetInnerHTML\s*=',
        remediation="Avoid dangerouslySetInnerHTML. If HTML rendering is required, sanitize with DOMPurify before setting __html.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-007",
        name="child_process.exec() Command Injection",
        description="child_process.exec() passes the command to a shell. User-controlled input enables command injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'(?:child_process|require\s*\(\s*["\']child_process["\']\s*\)).*\.exec\s*\(',
        remediation="Use child_process.execFile() with a fixed executable path and an arguments array. Never interpolate user input.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-008",
        name="child_process.execSync() Command Injection",
        description="execSync() runs a shell command synchronously. User input in the command string leads to injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'\bexecSync\s*\(',
        remediation="Use spawnSync() with an argument array instead of a command string.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-009",
        name="Math.random() Used for Security",
        description="Math.random() is a non-cryptographic PRNG. Its output is predictable and must not be used for tokens, passwords, or session IDs.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.JAVASCRIPT,
        pattern=r'\bMath\.random\s*\(',
        remediation="Use crypto.randomBytes() (Node.js) or window.crypto.getRandomValues() (browser) for security-sensitive randomness.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="JS-010",
        name="Weak Cryptographic Hash (MD5/SHA1)",
        description="MD5 and SHA-1 are cryptographically broken and should not be used for any security-sensitive purpose.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.JAVASCRIPT,
        pattern=r"crypto\.createHash\s*\(\s*['\"](?:md5|sha1|sha-1)['\"]\s*\)",
        remediation="Use SHA-256 or SHA-3: crypto.createHash('sha256'). For passwords use bcrypt/argon2.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JS-011",
        name="SQL Injection via Template Literal",
        description="SQL query built with a template literal interpolating variables is vulnerable to SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'`\s*(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)[^`]*\$\{',
        remediation="Use parameterized queries with prepared statements (node-postgres, mysql2). Never interpolate user values into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JS-012",
        name="SQL Injection via String Concatenation",
        description="SQL query built by concatenating strings with + operator.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'(?:SELECT|INSERT|UPDATE|DELETE)\s+[^;`"\']+["\'\s]\s*\+\s*\w',
        remediation="Use parameterized queries. Example: db.query('SELECT * FROM users WHERE id = $1', [userId])",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JS-013",
        name="Prototype Pollution",
        description="Assignment to __proto__ or constructor.prototype can pollute the Object prototype and affect all objects application-wide.",
        severity=Severity.HIGH,
        category=VulnCategory.PROTOTYPE_POLLUTION,
        language=Language.JAVASCRIPT,
        pattern=r'\[?["\']__proto__["\']\]?\s*=|\bObject\.(?:assign|merge)\s*\([^)]*\{[^}]*__proto__',
        remediation="Validate keys from untrusted sources, deny __proto__/constructor/prototype. Use Object.create(null) for property maps.",
        cwe="CWE-1321",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-014",
        name="Sensitive Data in localStorage / sessionStorage",
        description="Storing sensitive data (tokens, passwords) in localStorage/sessionStorage exposes it to XSS attacks.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.JAVASCRIPT,
        pattern=r'(?:localStorage|sessionStorage)\.setItem\s*\(\s*["\'][^"\']*(?:token|password|secret|key|auth)[^"\']*["\']',
        remediation="Store sensitive tokens in HttpOnly cookies, not Web Storage. Use secure, HttpOnly cookies for auth tokens.",
        cwe="CWE-922",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JS-015",
        name="Hardcoded Secret in JavaScript",
        description="Hardcoded secret, API key, or private key found in JavaScript code that may be served to clients.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.JAVASCRIPT,
        pattern=r'(?:const|let|var)\s+\w*(?:secret|apikey|api_key|privatekey|private_key|authtoken)\w*\s*=\s*["\'][^"\']{8,}["\']',
        remediation="Never embed secrets in frontend JS. Use environment variables at build time and keep secret values server-side only.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="JS-016",
        name="Insecure use of setTimeout/setInterval with String",
        description="Passing a string to setTimeout/setInterval evaluates it like eval(), enabling code injection.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.JAVASCRIPT,
        pattern=r'(?:setTimeout|setInterval)\s*\(\s*["\']',
        remediation="Always pass a function reference to setTimeout/setInterval, never a string.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JS-017",
        name="Open Redirect via window.location",
        description="Assigning user-controlled data to window.location leads to open redirects and potential phishing.",
        severity=Severity.MEDIUM,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.JAVASCRIPT,
        pattern=r'window\.location(?:\.href)?\s*=',
        remediation="Validate redirect targets against an allowlist. Reject or encode values containing :// or /\\.",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="JS-018",
        name="Node.js Path Traversal",
        description="File system operations with user-controlled path segments enable path traversal.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.JAVASCRIPT,
        pattern=r'(?:fs|path)\.(?:readFile|writeFile|readFileSync|writeFileSync|createReadStream|unlink|stat)\s*\(\s*(?:req\.|request\.|params\.|query\.)',
        remediation="Resolve and validate paths: const safe = path.resolve(base, userPath); if (!safe.startsWith(base)) throw new Error().",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
]
