"""Regras de segurança para Julia — 9 regras (JULIA-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

JULIA_RULES: list[Rule] = [
    Rule(
        id="JULIA-001",
        name="Execução de Código Dinâmico via eval() em Julia",
        description="eval() em Julia executa expressões Julia arbitrárias em runtime no módulo corrente. Com input externo convertido em expressão (via Meta.parse), um atacante pode executar qualquer código Julia, incluindo system calls, acesso a arquivos, modificação de variáveis globais e chamadas FFI.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.JULIA,
        pattern=r'\beval\s*\(',
        remediation="Nunca execute eval() com input externo. Para configurações dinâmicas, use dicionários ou estruturas de dados. Para DSLs, implemente um parser seguro com validação antes de qualquer avaliação. Meta.parse + eval é um padrão especialmente perigoso.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JULIA-002",
        name="Injeção de Comando via run() com Interpolação",
        description="run(`cmd $var`) em Julia executa comandos do sistema. A interpolação via $ em backtick strings constrói o comando dinamicamente. Com input não validado, metacaracteres shell podem injetar comandos adicionais ou modificar o comportamento do comando original.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.JULIA,
        pattern=r'run\s*\(`[^`]*\$|readchomp\s*\(`[^`]*\$|pipeline\s*\(`[^`]*\$',
        remediation="Use vetores de strings para separar argumentos: run(`git clone $url`) é seguro SE url não contiver espaços. Para segurança total, use Cmd com ArgumentError: run(Cmd([\"git\", \"clone\", user_url])). Valide inputs com regex antes de interpolar.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JULIA-003",
        name="Acesso Inseguro à Memória via unsafe_load / unsafe_store!",
        description="unsafe_load() e unsafe_store!() acessam memória diretamente via ponteiros sem verificação de bounds. Um ponteiro inválido, nulo ou corrompido causa segfault. Em código que processa dados externos convertidos para ponteiros, pode levar a leitura/escrita de memória arbitrária.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.JULIA,
        pattern=r'\bunsafe_(?:load|store!|copyto!|wrap|pointer_to_objref|string)\s*\(',
        remediation="Use arrays Julia normais com indexação segura sempre que possível. Para interoperabilidade C com FFI, valide que o ponteiro não é nulo: @assert ptr != C_NULL. Use GC.@preserve para garantir que objetos não sejam coletados durante acesso unsafe.",
        cwe="CWE-119",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JULIA-004",
        name="Chamada FFI via ccall sem Verificação de Erro",
        description="ccall() em Julia chama funções C diretamente. Sem verificação de valores de retorno de erro (NULL pointers, códigos de erro negativos), falhas na biblioteca C passam silenciosas e podem resultar em comportamento indefinido, uso de ponteiros nulos ou corrupção de estado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JULIA,
        pattern=r'\bccall\s*\(',
        remediation="Verifique sempre o retorno de ccall para erros: result = ccall((:func, \"lib\"), Ptr{Cvoid}, (Cint,), arg); @assert result != C_NULL \"lib.func falhou\". Use @check_syserr para chamadas POSIX que setam errno.",
        cwe="CWE-252",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="JULIA-005",
        name="Desserialização Insegura via Serialization.deserialize()",
        description="Serialization.deserialize() carrega qualquer objeto Julia serializado, incluindo tipos customizados com métodos __init__ ou finalizers. Dados serializados de fontes externas podem incluir tipos maliciosos cujo construtor executa código arbitrário durante desserialização.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.OBJECTIVEC,
        pattern=r'Serialization\.deserialize\s*\(|deserialize\s*\(\s*IOBuffer|deserialize\s*\(\s*open',
        remediation="Nunca desserialize dados Julia de fontes externas. Use JSON3.jl, BSON.jl ou CSV.jl para intercâmbio de dados com validação de esquema. Para cache local, assine os dados antes de armazenar e verifique a assinatura antes de deserializar.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JULIA-006",
        name="SSRF via Downloads.download() com URL Externa",
        description="Downloads.download(url, dest) faz uma requisição HTTP para a URL especificada e salva o resultado. Com URL construída de input do usuário, pode ser usado para acessar metadados de instâncias cloud (169.254.169.254), serviços internos ou fazer scan da rede interna.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.JULIA,
        pattern=r'Downloads\.download\s*\(\s*(?!["\']\s*https?://[^"\']+["\']\s*,)',
        remediation="Valide URLs antes de download: use URIs.jl para parsear e verifique esquema (somente https), hostname (não é IP privado/localhost) e porta. Implemente allowlist de domínios permitidos: @assert any(endswith(host, d) for d in ALLOWED_DOMAINS).",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JULIA-007",
        name="Parsing e Execução de Código via Meta.parse + eval",
        description="O padrão Meta.parse(user_string) seguido de eval() ou macroexpand() é equivalente a um eval() direto mas mais explícito. Qualquer string que represente código Julia válido será executada com privilégios totais do processo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.JULIA,
        pattern=r'Meta\.parse\s*\(',
        remediation="Use Meta.parse apenas para tooling interno (compiladores, notebooks). Nunca parse strings de input externo como código. Para expressões matemáticas, use Symbolics.jl com operações restritas ou implemente um evaluator de expressões simples com gramática limitada.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="JULIA-008",
        name="Requisição HTTP Não Criptografada via HTTP.jl",
        description="HTTP.request() ou HTTP.get() com URLs http:// transmite dados em texto puro. Em ambientes científicos e de análise de dados onde Julia é popular, credenciais de API, dados de pesquisa e resultados intermediários podem vazar por conexões não criptografadas.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.JULIA,
        pattern=r'HTTP\.(?:request|get|post|put|delete)\s*\(\s*["\']http://',
        remediation="Use https:// em todas as URLs de produção. Verifique que o cliente HTTP.jl verifica certificados SSL (padrão é verificar). Nunca passe verify=false em ambientes de produção. Configure ca_certs para ambientes corporativos com CA interna.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="JULIA-009",
        name="Credencial Hardcoded em Script Julia",
        description="Senhas, tokens ou chaves API definidos como constantes ou variáveis literais em código Julia. Scripts Julia são frequentemente versionados com o código de análise, expondo credenciais em repositórios de dados científicos frequentemente públicos (GitHub, GitLab).",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.JULIA,
        pattern=r'(?:const\s+)?(?:password|passwd|api_key|secret|token|auth)\s*=\s*["\'][^"\']{6,}["\']',
        remediation="Use variáveis de ambiente: api_key = ENV[\"API_KEY\"]. Para notebooks Jupyter/Pluto, use DotEnv.jl: using DotEnv; DotEnv.config(); token = ENV[\"TOKEN\"]. Nunca comite arquivos .env reais — use .env.example como template.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
