"""Regras de segurança para Kubernetes / Helm — 10 regras (K8S-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

K8S_RULES: list[Rule] = [
    Rule(
        id="K8S-001",
        name="Container Privilegiado no Manifesto Kubernetes",
        description="O campo 'privileged: true' no securityContext do container concede ao processo todos os capabilities Linux e acesso irrestrito ao host. Um container privilegiado pode escalar para o nó Kubernetes, comprometer outros Pods e persistir em todo o cluster via acesso ao filesystem do host.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'privileged\s*:\s*true',
        remediation="Remova 'privileged: true'. Para capabilities específicas, use 'capabilities: add: [NET_ADMIN]' com mínimo necessário. Habilite PSA (Pod Security Admission) com perfil 'restricted' no namespace. Configure OPA Gatekeeper para rejeitar Pods privilegiados automaticamente.",
        cwe="CWE-250",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-002",
        name="hostNetwork: true — Container Compartilha Rede do Host",
        description="'hostNetwork: true' faz o Pod usar o namespace de rede do nó Kubernetes. O container pode escutar em todas as interfaces do host, acessar serviços de metadados (169.254.169.254), sniffar tráfego de outros Pods no mesmo nó e fazer binding em portas privilegiadas.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'hostNetwork\s*:\s*true',
        remediation="Remova 'hostNetwork: true'. Use Services do Kubernetes para expor portas de forma controlada. Se o Pod precisa de porta baixa no host, use 'hostPort' apenas para a porta específica. Para acesso à rede do nó (ex: CNI plugins), use DaemonSets com ServiceAccount mínimos.",
        cwe="CWE-668",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-003",
        name="allowPrivilegeEscalation: true — Escalonamento de Privilégios",
        description="'allowPrivilegeEscalation: true' (padrão) permite que processos dentro do container obtenham mais privilégios que o processo pai via setuid/sudo/SUID binaries. Um atacante que compromete o processo principal do container pode escalar para root dentro do container.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'allowPrivilegeEscalation\s*:\s*true',
        remediation="Defina explicitamente 'allowPrivilegeEscalation: false' em todos os securityContexts de containers. Combine com 'runAsNonRoot: true' e 'readOnlyRootFilesystem: true'. No Pod Security Standards, o perfil 'restricted' requer allowPrivilegeEscalation: false.",
        cwe="CWE-269",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-004",
        name="Container sem Resource Limits — Risco de DoS",
        description="Containers sem 'resources.limits' podem consumir toda a CPU e memória do nó, causando OOM kills de outros containers (noisy neighbor). Um atacante que controla input do container pode deliberadamente consumir recursos para causar DoS no cluster.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'containers\s*:\s*\n(?:\s*-[^\n]*\n)*(?:\s+[^\n]+\n)*(?!\s*resources\s*:)',
        remediation="Adicione resource limits: resources: { limits: { cpu: '500m', memory: '512Mi' }, requests: { cpu: '100m', memory: '128Mi' } }. Configure LimitRange no namespace para aplicar defaults. Use VPA (Vertical Pod Autoscaler) para otimização automática. Configure ResourceQuota no namespace.",
        cwe="CWE-400",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="K8S-005",
        name="hostPID / hostIPC: true — Compartilha Namespaces do Host",
        description="'hostPID: true' permite que o container veja todos os processos do host com seus PIDs, podendo enviar sinais para processos do sistema. 'hostIPC: true' permite acesso a segmentos de memória compartilhada do host. Ambos são vetores de escalonamento de container para host.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'host(?:PID|IPC)\s*:\s*true',
        remediation="Remova 'hostPID: true' e 'hostIPC: true'. Para debugging de processos do host, use kubectl debug com ephemeral containers em vez de hostPID. Configure PSA para rejeitar Pods com hostPID/hostIPC no namespace via admission controller.",
        cwe="CWE-668",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-006",
        name="runAsUser: 0 — Container Executando como Root",
        description="'runAsUser: 0' ou ausência de 'runAsNonRoot: true' faz o container executar como root (UID 0). Se o container for comprometido ou houver escape de container, o atacante tem privilégios root no sistema de arquivos mapeado. Muitas vulnerabilidades de container escape requerem root dentro do container.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'runAsUser\s*:\s*0\b',
        remediation="Use 'runAsUser: 1000' (ou outro UID > 0) e 'runAsNonRoot: true'. Construa imagens Docker com USER não-root: USER 1000:1000. Combine com 'readOnlyRootFilesystem: true' e volumes para diretórios que precisam de escrita.",
        cwe="CWE-250",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-007",
        name="Capability Perigosa Adicionada ao Container",
        description="Capabilities Linux como NET_ADMIN, SYS_ADMIN, SYS_PTRACE, DAC_OVERRIDE permitem ao container realizar operações privilegiadas: modificar configurações de rede, montar filesystems, depurar outros processos, ignorar permissões de arquivo. Cada capability amplia a superfície de ataque.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'capabilities\s*:\s*\n\s+add\s*:\s*\n\s+-\s*(?:SYS_ADMIN|NET_ADMIN|SYS_PTRACE|DAC_OVERRIDE|ALL|NET_RAW|SYS_MODULE)',
        remediation="Siga o princípio de menor privilégio: drop: [ALL] e adicione apenas capabilities estritamente necessárias. Prefira soluções sem capabilities: use kubectl port-forward em vez de NET_ADMIN. Audite com 'kubectl get pods -o json | jq .spec.containers[].securityContext.capabilities'.",
        cwe="CWE-250",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="K8S-008",
        name="readOnlyRootFilesystem Ausente — Filesystem Mutável",
        description="Sem 'readOnlyRootFilesystem: true', o container pode modificar seu próprio filesystem em runtime: instalar ferramentas, modificar binários, criar scripts de persistência. Attackers que comprometem o container podem estabelecer persistência modificando executáveis.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'securityContext\s*:(?!\s*\n(?:\s+[^\n]+\n)*\s+readOnlyRootFilesystem\s*:\s*true)',
        remediation="Adicione 'readOnlyRootFilesystem: true' no securityContext. Monte volumes para diretórios que precisam ser writable: /tmp, /var/log, diretórios de cache. Use emptyDir volumes para dados temporários. Teste a imagem com readOnly antes de aplicar em produção.",
        cwe="CWE-732",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="K8S-009",
        name="Namespace 'default' Usado para Workloads de Produção",
        description="Deploy de workloads de produção no namespace 'default' quebra o isolamento de multi-tenancy. O namespace default tem permissões mais amplas por padrão, sem NetworkPolicies específicas, sem ResourceQuotas e com RBAC menos granular, facilitando movimentação lateral entre serviços.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.YAML,
        pattern=r'namespace\s*:\s*default\b',
        remediation="Crie namespaces dedicados por ambiente e serviço: kubectl create namespace app-production. Aplique NetworkPolicies, ResourceQuotas e LimitRanges por namespace. Configure RBAC com mínimo de permissões por namespace. Nunca execute workloads de produção no namespace 'default' ou 'kube-system'.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="K8S-010",
        name="ServiceAccount com automountServiceAccountToken: true",
        description="Por padrão, Kubernetes monta automaticamente o token do ServiceAccount em /var/run/secrets/kubernetes.io/serviceaccount/token. Se o container for comprometido, o atacante pode usar esse token para fazer chamadas à API do Kubernetes com as permissões do ServiceAccount.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.YAML,
        pattern=r'automountServiceAccountToken\s*:\s*true',
        remediation="Defina 'automountServiceAccountToken: false' no Pod spec ou ServiceAccount para workloads que não precisam da API Kubernetes. Se necessário, monte o token manualmente apenas nos containers que precisam: volumeMounts com projected serviceAccountToken e expirationSeconds curto.",
        cwe="CWE-522",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
]
