"""Regras de segurança específicas para Kotlin (Android / JVM)."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

KOTLIN_RULES: list[Rule] = [
    Rule(
        id="KT-001",
        name="Operador !! (Non-null Assertion) — NullPointerException",
        description="O operador !! forçando o unwrap de um nullable pode lançar KotlinNullPointerException em runtime. Equivale ao .unwrap() inseguro de outras linguagens.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.KOTLIN,
        pattern=r'!!\s*(?:[.\[(]|$)',
        remediation="Use safe calls (?.), Elvis operator (?:), let { }, ou verifications explícitas. Jamais use !! em dados que vêm de APIs externas, banco de dados ou intent extras.",
        cwe="CWE-476",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="KT-002",
        name="Log.d/e/i com Dados Sensíveis (Android)",
        description="Log.d() e Log.e() são acessíveis via ADB logcat mesmo em builds release em algumas versões de Android. Dados sensíveis ficam visíveis no log do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.KOTLIN,
        pattern=r'Log\.[dDeEiIwWvV]\s*\([^)]*(?:password|token|secret|key|credential|auth|senha|senha)\b',
        remediation="Nunca logue dados sensíveis. Use if (BuildConfig.DEBUG) para logs de desenvolvimento. Em produção, use frameworks como Timber com filtro de campos sensíveis.",
        cwe="CWE-532",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="KT-003",
        name="SharedPreferences para Dados Sensíveis",
        description="SharedPreferences armazena dados em XML não encriptado. Em dispositivos rooteados ou com backup habilitado, esses dados são acessíveis a terceiros.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.KOTLIN,
        pattern=r'getSharedPreferences\b|sharedPreferences\b.*\.edit\s*\(\s*\)',
        negative_pattern=r'EncryptedSharedPreferences',
        remediation="Use EncryptedSharedPreferences da Jetpack Security library para dados sensíveis. Para tokens críticos, prefira Android Keystore System.",
        cwe="CWE-312",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="KT-004",
        name="WebView com setJavaScriptEnabled(true)",
        description="Habilitar JavaScript em WebView aumenta a superfície de ataque. Se a app carrega conteúdo externo não confiável, JavaScript pode acessar APIs nativas via addJavascriptInterface.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.KOTLIN,
        pattern=r'setJavaScriptEnabled\s*\(\s*true\s*\)',
        remediation="Desabilite JavaScript se possível. Se necessário, implemente ShouldOverrideUrlLoading para validar URLs carregadas. Use @JavascriptInterface com cautela.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="KT-005",
        name="Intent com FLAG_ACTIVITY_NEW_TASK via Dado Externo",
        description="Iniciar Activities com dados de Intents externas sem validação pode causar Intent Redirection — o atacante direciona a app a abrir componentes internos arbitrários.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.KOTLIN,
        pattern=r'Intent\s*\(\s*intent\.(?:getStringExtra|getParcelableExtra|data)',
        remediation="Nunca use dados de Intents externas para construir novas Intents sem validação. Valide URLs e tipos antes de iniciar Activities a partir de dados externos.",
        cwe="CWE-926",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="KT-006",
        name="Hardcoded Secret em Código Kotlin",
        description="API keys, tokens e senhas hardcoded em código Kotlin são extraíveis do APK por descompilação simples com jadx ou apktool.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.KOTLIN,
        pattern=r'(?:val|var|const\s+val)\s+\w*(?:KEY|SECRET|TOKEN|PASSWORD|API)\w*\s*=\s*"[A-Za-z0-9+/=_\-]{16,}"',
        remediation="Armazene segredos no servidor e recupere via API autenticada. Use BuildConfig para injetar segredos no build sem commitar. Nunca exponha chaves diretamente no app.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="KT-007",
        name="Comunicação Cleartext (HTTP) em OkHttp/Retrofit",
        description="URLs HTTP em clientes como OkHttp ou Retrofit transmitem dados sem criptografia. Em redes públicas, qualquer nó intermediário pode ver e modificar o tráfego.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.KOTLIN,
        pattern=r'"http://(?!localhost|127\.0\.0\.1)',
        remediation="Use HTTPS em todas as URLs de API. Configure network_security_config.xml para proibir cleartext. Use OkHttp com TLS 1.2+ e certificate pinning.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="KT-008",
        name="Exportação de Componente Android sem Permissão",
        description="Activity, Service ou BroadcastReceiver com android:exported=true sem android:permission definida pode ser invocada por qualquer app do dispositivo.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.KOTLIN,
        pattern=r'android:exported\s*=\s*"true"',
        negative_pattern=r'android:permission\s*=',
        remediation="Defina android:permission com permissão personalizada ou use SIGNATURE protection level. Exporte apenas componentes que precisam ser acessíveis externamente.",
        cwe="CWE-926",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
]
