"""Regras de segurança para Lua — 9 regras (LUA-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

LUA_RULES: list[Rule] = [
    Rule(
        id="LUA-001",
        name="Execução de Código Dinâmico via load() / loadstring()",
        description="load() e loadstring() compilam e executam código Lua a partir de strings em runtime. Se o argumento vem de input externo (requisição HTTP, arquivo, usuário), o atacante pode executar código Lua arbitrário com todos os privilégios do processo, incluindo acesso ao sistema de arquivos e rede.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.LUA,
        pattern=r'\b(?:load|loadstring)\s*\(',
        remediation="Elimine load/loadstring com dados externos. Para configurações dinâmicas, use tabelas Lua com pares chave-valor. Para DSLs, implemente um parser restrito. Se necessário, use um ambiente sandbox: setfenv(func, {}) para isolar o código carregado.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="LUA-002",
        name="Injeção de Comando OS via os.execute()",
        description="os.execute() passa o argumento diretamente para o shell do sistema (/bin/sh -c no Unix). Com input do usuário não sanitizado, operadores shell (;, |, &&, $()) permitem execução de comandos arbitrários. É o equivalente Lua de system() em C.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.LUA,
        pattern=r'\bos\.execute\s*\(',
        remediation="Evite os.execute com dados externos. Use listas de argumentos quando disponível (LuaJIT com FFI ou bindings). Valide input contra uma whitelist de caracteres seguros: assert(input:match('^[a-zA-Z0-9_-]+$'), 'invalid input'). Escape com shellQuote quando necessário.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="LUA-003",
        name="Injeção de Comando via io.popen()",
        description="io.popen() abre um pipe para um comando shell, executando-o através do interpretador de shell do sistema. Similar ao os.execute(), qualquer input não sanitizado pode ser usado para injetar comandos arbitrários.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.LUA,
        pattern=r'\bio\.popen\s*\(',
        remediation="Construa o comando somente com partes hardcoded e argumentos validados. Implemente escape manual: local safe = input:gsub('[^%w%-_./]', ''). Para operações de arquivo, use a API io diretamente em vez de comandos shell.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="LUA-004",
        name="Path Traversal via dofile() com Caminho Dinâmico",
        description="dofile() carrega e executa um arquivo Lua como código. Com caminho construído a partir de input externo, um atacante pode executar arquivos Lua arbitrários do sistema (dofile('../../../etc/init.lua')) ou ler código sensível de outros módulos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.LUA,
        pattern=r'\bdofile\s*\(\s*(?!["\'])',
        remediation="Nunca passe caminhos dinâmicos para dofile. Use require() com nomes de módulo fixos da whitelist. Se carregamento dinâmico for necessário, normalize o caminho e verifique que está dentro do diretório base antes de carregar.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="LUA-005",
        name="Carregamento de Módulo com Caminho de Input Externo",
        description="require() com string construída de input do usuário pode carregar módulos Lua arbitrários do caminho de busca (package.path), incluindo scripts maliciosos em diretórios com permissão de escrita. Também pode vazar informações sobre o layout do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.LUA,
        pattern=r'\brequire\s*\(\s*(?:[a-zA-Z_]\w*\s*\.\.|[a-zA-Z_]\w*\s*\.\.)',
        remediation="Use require() somente com strings literais fixas. Implemente uma whitelist de módulos permitidos: local allowed = {utils=true, json=true}. assert(allowed[moduleName], 'module not allowed'). require(moduleName).",
        cwe="CWE-94",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="LUA-006",
        name="Divulgação de Informações via debug.getinfo()",
        description="A biblioteca debug do Lua expõe informações internas do runtime: nomes de função, caminhos de arquivo-fonte, números de linha, upvalues e bytecode. Em produção, isso pode vazar a estrutura interna da aplicação, caminhos de arquivo e detalhes de implementação a atacantes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.LUA,
        pattern=r'\bdebug\.(?:getinfo|getupvalue|setupvalue|getlocal|setlocal|traceback|sethook)\s*\(',
        remediation="Remova o uso de funções debug em código de produção. Desabilite a biblioteca debug completamente se não for necessária: package.loaded['debug'] = nil. Para diagnóstico em produção, use logging estruturado com contexto controlado.",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="LUA-007",
        name="Bypass de Metamétodos via rawget / rawset",
        description="rawget() e rawset() acessam campos de tabelas Lua diretamente, bypassando metamétodos __index e __newindex. Em sistemas que usam metamétodos para controle de acesso, validação ou auditoria, rawget/rawset pode ser usado para contornar estas proteções.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.LUA,
        pattern=r'\b(?:rawget|rawset|rawequal)\s*\(',
        remediation="Documente claramente por que rawget/rawset é necessário. Se metamétodos implementam controle de acesso, garanta que rawget/rawset nunca seja exposto em contextos onde o usuário tem controle do objeto ou da chave.",
        cwe="CWE-284",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="LUA-008",
        name="Conexão HTTP Não Criptografada via socket.http",
        description="socket.http.request() com URLs http:// transmite dados em texto puro. Em scripts Lua embarcados em servidores web (Nginx/OpenResty) ou sistemas IoT, credenciais e dados sensíveis trafegam sem criptografia.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.LUA,
        pattern=r'socket\.http\.request\s*\(\s*["\']http://',
        remediation="Use ssl.https para conexões seguras: require('ssl.https'). ssl.https.request('https://api.example.com/...'). Configure certificados CA corretamente. Para OpenResty, use ngx.socket.tcp() com handshake SSL/TLS.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="LUA-009",
        name="Credencial Hardcoded em Script Lua",
        description="Senhas, tokens de API ou chaves de acesso definidos como strings literais em scripts Lua. Arquivos Lua são frequentemente incluídos em repositórios de configuração e estão em texto puro, expondo credenciais a todos com acesso ao código-fonte.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.LUA,
        pattern=r'(?:password|passwd|secret|api_key|apikey|token|auth_key)\s*=\s*["\'][^"\'${}]{6,}["\']',
        remediation="Use variáveis de ambiente: local db_pass = os.getenv('DB_PASSWORD'). Para sistemas embarcados, armazene credenciais em armazenamento seguro do hardware ou use configuração externa não versionada. Nunca comite arquivos com credenciais.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
