"""Regras de segurança para Move (Aptos/Sui) — 8 regras (MOVE-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

MOVE_RULES: list[Rule] = [
    Rule(
        id="MOVE-001",
        name="Resource sem Abilities Adequadas — Token Bloqueado",
        description="Em Move, structs que representam tokens ou assets devem ter a ability 'drop' ou serem consumidos explicitamente. Um resource sem 'drop' que não é retornado ou consumido causa um erro em tempo de execução (panic). Isso pode bloquear fundos permanentemente se o código não tiver um caminho de consumo para todos os casos.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.MOVE,
        pattern=r'struct\s+\w+\s+has\s+(?!.*\bdrop\b)(?:store|copy|key)\s*\{',
        remediation="Revise as abilities do struct: structs que representam assets que devem ser consumidos não devem ter 'drop' (Move force o programador a lidar com eles). Structs auxiliares de curta duração devem ter 'drop'. Documente o ciclo de vida esperado de cada struct. Use 'store' apenas para structs que persistem em global storage.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MOVE-002",
        name="abort sem Código de Erro Descritivo",
        description="'abort 0' ou 'abort 1' em Move fornece informações mínimas sobre o motivo do abort. Códigos de erro numéricos genéricos dificultam debugging e podem obscurecer condições de segurança específicas. Usuários e clientes recebem mensagens de erro não informativas que dificultam diagnóstico.",
        severity=Severity.LOW,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.MOVE,
        pattern=r'\babort\s+\d+\b',
        remediation="Use constantes de erro descritivas: const E_INSUFFICIENT_BALANCE: u64 = 1; const E_NOT_AUTHORIZED: u64 = 2; abort(E_NOT_AUTHORIZED). Em Aptos, use error:: module: abort(error::permission_denied(E_NOT_ADMIN)). Isso fornece contexto semântico nas mensagens de erro do explorer e indexers.",
        cwe="CWE-209",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="MOVE-003",
        name="Função Public sem acquires Declaration",
        description="Funções 'public' em Move que acessam global storage com 'borrow_global' ou 'move_from' devem declarar 'acquires T'. Sem acquires, o type checker pode não detectar conflitos de acesso ao mesmo recurso em chamadas compostas, potencialmente causando aborts inesperados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.MOVE,
        pattern=r'public\s+fun\s+\w+[^{]*\{[^}]*(?:borrow_global|move_from|borrow_global_mut)',
        negative_pattern=r'acquires\s+\w+',
        remediation="Declare acquires para todos os tipos acessados: public fun transfer(from: address) acquires Balance { let bal = borrow_global_mut<Balance>(from); ... }. O compilador Move verifica que acquires é completo e correto. Isso previne aborts não documentados em chamadas compostas.",
        cwe="CWE-703",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="MOVE-004",
        name="move_to sem Verificação de Existência Prévia",
        description="'move_to(account, resource)' em Move falha (abort) se o recurso já existe na conta destino. Sem verificar 'exists<T>(addr)' antes, um ataque de front-running pode criar o recurso antes do código legítimo, causando DoS ao tentar publicar o recurso novamente.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.MOVE,
        pattern=r'move_to\s*\(\s*\w+\s*,',
        negative_pattern=r'exists\s*<',
        remediation="Verifique antes de mover: assert!(!exists<MyResource>(signer::address_of(account)), E_ALREADY_EXISTS); move_to(account, resource). Para upsert pattern, use: if (exists<T>(addr)) { let r = borrow_global_mut<T>(addr); update(r); } else { move_to(account, new_resource); }",
        cwe="CWE-20",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MOVE-005",
        name="vector::borrow sem Verificação de Bounds",
        description="'vector::borrow(v, i)' em Move aborta se o índice está fora dos limites (i >= length(v)). Sem verificar 'i < vector::length(v)' antes, inputs de usuário que controlam o índice causam aborts que podem ser explorados para DoS ou para contornar lógica que segue o borrow.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.MOVE,
        pattern=r'vector::borrow(?:_mut)?\s*\(\s*\w+\s*,\s*(?!\d+\s*\))\w+',
        remediation="Verifique bounds antes de borrow: assert!(index < vector::length(&v), E_INDEX_OUT_OF_BOUNDS); let elem = vector::borrow(&v, index). Para iteração segura, use vector::for_each ou itere com contador verificado. Nunca use índice derivado de input externo sem validação.",
        cwe="CWE-125",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MOVE-006",
        name="Signer Passado Desnecessariamente em Funções Internas",
        description="Passar '&signer' para funções 'public(friend)' ou 'internal' sem usá-lo implica uma superfície de ataque: um caller pode passar qualquer signer que tenha. Se a função eventualmente for tornada pública ou o padrão de chamada mudar, um signer passado mas não verificado pode levar a autorização incorreta.",
        severity=Severity.LOW,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.MOVE,
        pattern=r'fun\s+\w+\s*\([^)]*account\s*:\s*&signer[^)]*\)',
        negative_pattern=r'signer::address_of|sign_and_execute|sign',
        remediation="Passe o address em vez do signer quando autenticação não é necessária: fun process(user_addr: address) em vez de fun process(user: &signer). Reserve &signer para funções que precisam autorizar ações em nome daquele usuário. Isso segue o princípio de least privilege.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MOVE-007",
        name="Endereço Hardcoded em Módulo Move",
        description="Endereços de contrato ou wallet hardcoded como '0x1234...' em código Move são frágeis e potencialmente perigosos. Em testes, podem apontar para endereços de produção. Em produção, podem apontar para endereços de staging. Endereços de admin hardcoded impossibilitam rotação em caso de comprometimento.",
        severity=Severity.MEDIUM,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.MOVE,
        pattern=r'@0x[0-9a-fA-F]{10,}',
        remediation="Use named addresses configuráveis no Move.toml: [addresses]; myapp = '0x...' e referencie como @myapp no código. Para admin addresses, armazene em global storage: move_to(admin, Config { admin_addr: admin_addr }). Isso permite atualização via governance sem redeploy do módulo.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MOVE-008",
        name="table::borrow sem Verificação de Existência",
        description="'table::borrow(&table, key)' em Move aborta se a chave não existe na tabela. Com chaves derivadas de input de usuário, isso é um vetor de DoS: um atacante pode causar aborts fornecendo chaves inexistentes, especialmente em funções críticas como processamento de pagamentos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.MOVE,
        pattern=r'table::borrow(?:_mut)?\s*\(\s*[^,]+,\s*(?!\w+_key\b)',
        negative_pattern=r'table::contains',
        remediation="Verifique existência antes de borrow: assert!(table::contains(&self.data, key), E_KEY_NOT_FOUND); let val = table::borrow(&self.data, key). Use table::borrow_with_default para valores opcionais: let val = table::borrow_with_default(&t, key, &default). Para upsert: use table::upsert().",
        cwe="CWE-20",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
]
