"""Regras de segurança para MySQL DDL — 8 regras (MYDDL-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

MYSQL_DDL_RULES: list[Rule] = [
    Rule(
        id="MYDDL-001",
        name="GRANT ALL PRIVILEGES ON *.* — Superacesso MySQL",
        description="'GRANT ALL PRIVILEGES ON *.* TO user' concede todos os privilégios sobre todos os bancos e tabelas ao usuário, equivalente a root. Com WITH GRANT OPTION, o usuário pode ainda criar outros superusuários. Um usuário comprometido com esse grant tem controle total do servidor MySQL.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'GRANT\s+ALL\s+PRIVILEGES\s+ON\s+\*\s*\.\s*\*',
        remediation="Conceda apenas privilégios necessários por banco: GRANT SELECT, INSERT, UPDATE ON app_db.* TO 'app_user'@'localhost'; Para cada serviço, crie um usuário dedicado com acesso apenas ao banco necessário. Para migrations, crie migration_user com DDL apenas no banco específico.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="MYDDL-002",
        name="Privilege FILE — Leitura/Escrita de Arquivos OS",
        description="'GRANT FILE ON *.*' permite ao usuário MySQL ler qualquer arquivo legível pelo processo mysqld (LOAD DATA INFILE '/etc/passwd') e escrever arquivos (SELECT ... INTO OUTFILE). Isso é um vetor para exfiltração de dados e escrita de webshells em servidores com MySQL e Apache colocalizados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r'GRANT\s+(?:[A-Z,\s]*,\s*)?FILE(?:\s*,|\s+ON)',
        remediation="Nunca conceda FILE privilege a usuários de aplicação: REVOKE FILE ON *.* FROM 'app_user'@'localhost'. Para importação de dados, use LOAD DATA LOCAL INFILE (mais restritivo) ou importe via aplicação. Configure --secure-file-priv para limitar o diretório de leitura/escrita de arquivos.",
        cwe="CWE-732",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="MYDDL-003",
        name="Senha Hardcoded em DDL MySQL",
        description="'CREATE USER ... IDENTIFIED BY \"senha\"' ou 'ALTER USER ... IDENTIFIED BY \"senha\"' com senhas literais em scripts DDL armazenam credenciais em texto claro no repositório git. Scripts de migration com senhas hardcoded são frequentemente commitados e expostos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SQL,
        pattern=r'IDENTIFIED\s+BY\s+["\'][^"\']+["\']',
        remediation="Use variáveis de ambiente: IDENTIFIED BY '${DB_PASSWORD}' (com substituição de variável antes da execução). Gerencie senhas com HashiCorp Vault ou AWS Secrets Manager. Para setups iniciais, gere senhas aleatórias: openssl rand -base64 32. Nunca comite scripts DDL com senhas reais.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="MYDDL-004",
        name="REQUIRE NONE — Conexão MySQL sem SSL Obrigatório",
        description="'REQUIRE NONE' em CREATE USER ou ausência de REQUIRE SSL/X509 permite que o usuário se conecte sem criptografia TLS. Conexões MySQL sem SSL transmitem queries, resultados e credenciais em plaintext. Em redes internas, isso ainda é um vetor de interceptação por ataque MITM.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.SQL,
        pattern=r'REQUIRE\s+NONE',
        remediation="Exija SSL: CREATE USER 'app_user'@'%' IDENTIFIED BY '...' REQUIRE SSL; Para certificados: REQUIRE X509 com verificação de CA. Configure my.cnf: require_secure_transport=ON para forçar SSL em todo o servidor. Use ssl-mode=REQUIRED em connection strings de clientes.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="MYDDL-005",
        name="Usuário root com Acesso Remoto ('%')",
        description="'CREATE USER \"root\"@\"%\"' ou 'GRANT ... TO \"root\"@\"%\"' permite que o usuário root do MySQL aceite conexões de qualquer host. Root com acesso remoto é um alvo primário de ataques de força bruta e deve sempre ser restrito a 'localhost' ou '127.0.0.1' apenas.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r'["\']root["\']@["\']%["\']',
        remediation="Restrinja root a localhost: DELETE FROM mysql.user WHERE User='root' AND Host!='localhost'; FLUSH PRIVILEGES; Para acesso remoto de administração, crie um usuário separado com as permissões necessárias e restrinja ao IP específico: 'admin'@'10.0.0.5'. Use SSH tunnel para acesso remoto.",
        cwe="CWE-284",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="MYDDL-006",
        name="MAX_USER_CONNECTIONS Ausente — Sem Limite de Conexões",
        description="Usuários MySQL sem 'WITH MAX_USER_CONNECTIONS N' podem abrir conexões ilimitadas. Um usuário comprometido ou bug de connection leak pode esgotar o pool de conexões do servidor (max_connections), causando DoS para todos os outros usuários e aplicações.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.SQL,
        pattern=r'CREATE\s+USER\s+["\'](?!root)["\'\w@%.-]+\s+IDENTIFIED',
        negative_pattern=r'MAX_USER_CONNECTIONS|WITH\s+MAX',
        remediation="Configure limites por usuário: CREATE USER 'app_user'@'localhost' IDENTIFIED BY '...' WITH MAX_USER_CONNECTIONS 50 MAX_QUERIES_PER_HOUR 10000 MAX_UPDATES_PER_HOUR 1000. Configure globalmente: SET GLOBAL max_connections=500. Use connection pooling (ProxySQL, pgBouncer) para limitar conexões na camada de aplicação.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="MYDDL-007",
        name="GRANT SUPER — Privilege de Administração MySQL",
        description="'GRANT SUPER' permite ao usuário fazer operações administrativas: matar queries de outros usuários, configurar variáveis globais, PURGE BINARY LOGS, bypass de read_only. Um usuário de aplicação com SUPER pode contornar restrições de segurança e modificar configurações do servidor.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'GRANT\s+(?:[A-Z,\s]*,\s*)?SUPER(?:\s*,|\s+ON)',
        remediation="Substitua SUPER por privileges específicos (MySQL 8.0+): BINLOG_ADMIN, REPLICATION_SLAVE, SET_USER_ID conforme necessário. SUPER foi dividido em múltiplos privileges mais granulares no MySQL 8. Para aplicações, nunca conceda SUPER — apenas para contas de DBA humanas.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="MYDDL-008",
        name="ENGINE=MyISAM — Sem Suporte a Transactions e FK",
        description="Tabelas com 'ENGINE=MyISAM' não suportam transações ACID, foreign keys ou row-level locking. Sem transactions, operações em múltiplas tabelas podem deixar o banco em estado inconsistente se a aplicação falhar. Sem FK, relacionamentos corrompidos não são detectados pelo banco.",
        severity=Severity.LOW,
        category=VulnCategory.TECHNICAL_DEBT,
        language=Language.SQL,
        pattern=r'ENGINE\s*=\s*MyISAM',
        remediation="Migre para InnoDB: ALTER TABLE my_table ENGINE=InnoDB; InnoDB suporta ACID transactions, foreign keys, row-level locking e crash recovery. Para tabelas full-text search, use InnoDB com FULLTEXT index (disponível desde MySQL 5.6). Configure default_storage_engine=InnoDB no my.cnf.",
        cwe="CWE-1188",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
