"""Regras de segurança para Nim — 9 regras (NIM-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

NIM_RULES: list[Rule] = [
    Rule(
        id="NIM-001",
        name="Injeção de Comando via exec() / execProcess()",
        description="exec() e osproc.execProcess() em Nim executam comandos no shell do sistema. Com strings construídas de input externo, metacaracteres shell permitem execução de comandos arbitrários. Nim é usado em sistemas embarcados e utilitários de sistema onde esses riscos são amplificados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.NIM,
        pattern=r'\b(?:exec|execProcess|execCmd)\s*\(',
        remediation="Use execProcess com lista de argumentos explícita: discard execProcess(\"git\", args=[\"clone\", userUrl], options={poUsePath}). Valide cada argumento contra uma whitelist de caracteres permitidos antes de usar. Para saída segura, use osproc.execCmdEx.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NIM-002",
        name="Execução de Shell via gorgeEx / gorge (Compilação e Runtime)",
        description="gorgeEx() e gorge() em Nim executam comandos shell e capturam a saída. gorgeEx é usada em tempo de compilação via macros, criando vulnerabilidades de injeção durante o próprio processo de build. gorge em runtime é vulnerável a injeção de comandos com input externo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.NIM,
        pattern=r'\b(?:gorgeEx|gorge)\s*\(',
        remediation="Elimine gorgeEx/gorge com input dinâmico. Em macros de compile-time, use somente strings hardcoded. Em runtime, use execProcess com lista de argumentos. Documente por que a execução de shell é necessária e revise periodicamente.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NIM-003",
        name="staticExec em Macro — Injeção em Tempo de Compilação",
        description="staticExec() executa comandos durante a compilação Nim. Em projetos com build systems que aceitam opções de usuários ou arquivos de configuração externos, uma injeção em staticExec comprometeria o próprio binário produzido — um vetor de ataque à supply chain.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.NIM,
        pattern=r'\bstaticExec\s*\(',
        remediation="Use staticExec somente com strings completamente hardcoded e controladas. Nunca derive o argumento de variáveis de ambiente, arquivos de configuração externos, ou parâmetros passados pelo usuário ao compilador. Audite todos os usos de staticExec em dependências.",
        cwe="CWE-94",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NIM-004",
        name="Cast Inseguro de Ponteiro via cast[]",
        description="cast[T](value) em Nim converte entre tipos sem verificação, similar ao C-style cast. Reinterpretar ponteiros para tipos incompatíveis causa comportamento indefinido, corrupção de memória e crashes. Em código que processa dados externos, pode ser explorado para leitura/escrita arbitrária de memória.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.NIM,
        pattern=r'\bcast\s*\[\s*(?:ptr|pointer|ByteAddress)',
        remediation="Use conversões de tipo seguras quando disponível. Para interoperabilidade com C, use os tipos corretos de cinterop em vez de cast. Documente cuidadosamente por que o cast é necessário. Use when nimvm para caminhos de code seguro vs unsafe.",
        cwe="CWE-119",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="NIM-005",
        name="Gerenciamento Manual de Memória sem Desalocação",
        description="alloc() e alloc0() em Nim alocam memória no heap sem controle automático do garbage collector. Sem dealloc() correspondente no mesmo escopo, resulta em memory leaks. Em servidores e daemons, leaks acumulados causam negação de serviço por esgotamento de memória.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.NIM,
        pattern=r'\b(?:alloc|alloc0|allocShared0?)\s*\(',
        remediation="Sempre dealloc em um bloco defer: let buf = alloc(size); defer: dealloc(buf). Para buffers, prefira usar arrays/seqs Nim que são gerenciados pelo GC. Se alocação manual é necessária para FFI, use um wrapper RAII com destructor ou finalizer.",
        cwe="CWE-401",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="NIM-006",
        name="Path Traversal via writeFile / readFile com Input Externo",
        description="writeFile() e readFile() em Nim com caminhos construídos de input externo. Sequências ../ em caminhos podem acessar ou sobrescrever arquivos fora do diretório esperado, incluindo arquivos de configuração, binários ou dados sensíveis do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.NIM,
        pattern=r'(?:writeFile|readFile|open)\s*\(\s*(?!["\'])',
        remediation="Normalize e valide caminhos: import os; let base = absolutePath(\"/safe/dir\"); let full = normalizedPath(base / userInput); if not full.startsWith(base): raise newException(IOError, \"path traversal\"). Use expandTilde e absolutePath para normalização completa.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="NIM-007",
        name="Credencial Hardcoded em Código Nim",
        description="Constantes ou variáveis com senhas, tokens ou chaves API definidas como strings literais em código Nim. Binários Nim podem ser inspecionados com strings(1) para extrair strings literais, incluindo credenciais.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.NIM,
        pattern=r'(?:const|let|var)\s+\w*(?:password|passwd|secret|api_key|token|auth)\w*\s*=\s*["\'][^"\']{6,}["\']',
        remediation="Use variáveis de ambiente: let apiKey = getEnv(\"API_KEY\", \"\"); if apiKey == \"\": quit(\"API_KEY not set\", 1). Para aplicações de CLI/desktop, use arquivos de configuração fora do repositório. Use nim-dotenv para gerenciamento de variáveis de ambiente.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="NIM-008",
        name="Conexão HTTP Não Criptografada via httpclient",
        description="newHttpClient().getContent(\"http://...\") ou httpClient.get(\"http://...\") em Nim transmite dados sem criptografia. A biblioteca httpclient do Nim suporta HTTPS, mas http:// pode ser usado inadvertidamente em scripts de automação e ferramentas CLI.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.NIM,
        pattern=r'newHttpClient\s*\(\s*\).*["\']http://|getContent\s*\(\s*["\']http://',
        remediation="Use https:// em todas as URLs. Verifique que sslContext está configurado: let client = newHttpClient(sslContext=newContext()). Para certificados auto-assinados em dev, use um CA bundle específico, nunca desabilite a verificação.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NIM-009",
        name="Pragma {.compile.} / {.link.} com Caminho Dinâmico",
        description="Pragmas {.compile: path.} e {.link: path.} incluem arquivos C externos durante a compilação Nim. Se path vem de variáveis de ambiente ou arquivos de configuração externos não auditados, um atacante pode injetar código C malicioso no binário final — ataque à supply chain via build system.",
        severity=Severity.HIGH,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.NIM,
        pattern=r'\{\s*\.(?:compile|link)\s*:[^}]+\$',
        remediation="Use {.compile.} e {.link.} somente com strings literais hardcoded. Nunca derive caminhos de variáveis de ambiente ou arquivos externos. Faça auditoria de todos os pragmas de compilação em dependências antes de incluir no projeto.",
        cwe="CWE-94",
        confidence=Confidence.MEDIUM,
    ),
]
