"""Regras de segurança para Objective-C — 10 regras (OBJC-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

OBJC_RULES: list[Rule] = [
    Rule(
        id="OBJC-001",
        name="NSLog Expõe Dados Sensíveis em Logs de Produção",
        description="NSLog() em Objective-C escreve no sistema de logs da Apple (Console.app, ASL) e é visível para outras aplicações com permissões adequadas em iOS/macOS. Em builds de produção, NSLog com dados do usuário, tokens ou credenciais vaza informações sensíveis para o log do dispositivo e para ferramentas como idevicesyslog.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.OBJECTIVEC,
        pattern=r'\bNSLog\s*\(@\s*"[^"]*(?:password|token|secret|key|credential|auth)',
        remediation="Remova ou condicione NSLog em builds de produção: #ifdef DEBUG NSLog(@\"...\"); #endif. Use DDLog (CocoaLumberjack) com níveis de log que desabilitam verbose em produção. Nunca logue credenciais mesmo em debug.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="OBJC-002",
        name="Format String Injection via stringWithFormat: / NSString",
        description="[NSString stringWithFormat:userInput] onde userInput é diretamente o format string (não o valor) é uma vulnerabilidade de format string. Um atacante pode usar %@ para acessar objetos do stack, %n para escrever na memória, ou %x para ler valores arbitrários, potencialmente resultando em crash ou vazamento de dados.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.OBJECTIVEC,
        pattern=r'\[NSString\s+stringWithFormat\s*:\s*[a-zA-Z_]\w*\s*\]|stringWithFormat\s*:\s*(?!@\s*")',
        remediation="Sempre use um format string literal: [NSString stringWithFormat:@\"%@\", userInput]. Nunca passe userInput diretamente como format string. Use NSString's stringByAppendingString: para concatenação simples quando não há formatação.",
        cwe="CWE-134",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="OBJC-003",
        name="Injeção SQL em SQLite3 via sqlite3_exec com Concatenação",
        description="sqlite3_exec() ou sqlite3_prepare_v2() com SQL construído por concatenação de strings C permite SQL injection em bancos SQLite locais de aplicações iOS/macOS. Dados do usuário (campos de busca, nomes de arquivo) frequentemente são passados diretamente sem sanitização.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.OBJECTIVEC,
        pattern=r'sqlite3_(?:exec|prepare_v2)\s*\([^,]+,\s*\[.*stringByAppendingString|sqlite3_exec\s*\([^,]+,\s*\[[^\]]+stringWithFormat',
        remediation="Use sqlite3_bind_* com prepared statements: sqlite3_prepare_v2(db, \"SELECT * FROM t WHERE id = ?\", -1, &stmt, NULL); sqlite3_bind_int(stmt, 1, userId); sqlite3_step(stmt). Ou use FMDB que encapsula SQLite com interface Objective-C segura.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="OBJC-004",
        name="Validação SSL Desabilitada: allowsAnyHTTPSCertificateForHost",
        description="+[NSURLRequest allowsAnyHTTPSCertificateForHost:] retorna YES desabilita a validação de certificado TLS para o host especificado (ou todos os hosts). Este método é privado/undocumented na Apple, mas amplamente usado em desenvolvimento. Em código de produção, torna a app vulnerável a MitM.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.OBJECTIVEC,
        pattern=r'allowsAnyHTTPSCertificateForHost|NSURLSessionConfiguration.*TLSMinimumSupportedProtocol',
        remediation="Remova completamente allowsAnyHTTPSCertificateForHost. Para desenvolvimento com certificados self-signed, use NSURLSessionDelegate com -URLSession:didReceiveChallenge:completionHandler: que aceita apenas o CA específico de desenvolvimento. Configure Certificate Pinning para produção com TrustKit.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="OBJC-005",
        name="XSS via UIWebView / WKWebView loadHTMLString sem Sanitização",
        description="[webView loadHTMLString:userContent baseURL:nil] renderiza HTML fornecido pelo usuário sem sanitização. Um atacante pode injetar JavaScript que acessa cookies, localStorage, executa ações na app via URL schemes personalizados ou exfiltra dados via XMLHttpRequest.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.OBJECTIVEC,
        pattern=r'loadHTMLString\s*:\s*(?!@\s*")|loadData\s*:\s*[a-zA-Z_]\w*\s+MIMEType\s*:\s*@"text/html"',
        remediation="Sanitize HTML com uma biblioteca como Google Sanitize HTML ou handlebars-objc antes de renderizar. Para conteúdo totalmente controlado, use loadHTMLString com string literal. Configure WKWebView com content rules para bloquear scripts inline: WKContentRuleListStore.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="OBJC-006",
        name="Keychain com Acessibilidade Insegura: kSecAttrAccessibleAlways",
        description="kSecAttrAccessibleAlways armazena itens do Keychain de forma acessível mesmo quando o dispositivo está bloqueado e antes do primeiro desbloqueio após reboot. Dispositivos com jailbreak ou ferramentas forenses (Cellebrite, GrayKey) podem extrair esses dados sem desbloqueio.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.OBJECTIVEC,
        pattern=r'kSecAttrAccessibleAlways\b',
        remediation="Use kSecAttrAccessibleWhenUnlockedThisDeviceOnly para dados que só precisam ser acessados com o dispositivo desbloqueado. Para dados críticos como chaves de criptografia, use kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly que requer passcode configurado.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="OBJC-007",
        name="Hash Criptograficamente Fraco: CC_MD5 / CC_SHA1",
        description="CC_MD5() e CC_SHA1() do framework CommonCrypto produzem hashes MD5 e SHA-1, ambos criptograficamente quebrados. Em iOS/macOS, são frequentemente usados para hash de senhas (inseguro) ou verificação de integridade de dados (inseguro contra ataques intencionais).",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.OBJECTIVEC,
        pattern=r'\bCC_MD5\s*\(|\bCC_SHA1\s*\(',
        remediation="Use CC_SHA256() no mínimo para hashes. Para senhas, use a API de derivação de chaves: CCKeyDerivationPBKDF(kCCPBKDF2, password, ..., kCCPRFHmacAlgSHA256, iterations, key, keyLen). iOS 13+ oferece CryptoKit com Hashing.SHA256, Bcrypt não existe nativamente — use uma biblioteca.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="OBJC-008",
        name="Gerador de Números Aleatórios Inseguro: arc4random()",
        description="arc4random() em Objective-C gera números pseudoaleatórios adequados para uso geral, mas não é um CSPRNG (Cryptographically Secure Pseudo-Random Number Generator). Para geração de tokens, IDs de sessão, chaves criptográficas ou qualquer uso de segurança, arc4random() é inadequado em sistemas modernos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.OBJECTIVEC,
        pattern=r'\barc4random\s*\(\s*\)|\brand\s*\(\s*\)',
        remediation="Use SecRandomCopyBytes() para geração segura: uint8_t buffer[32]; SecRandomCopyBytes(kSecRandomDefault, 32, buffer). Em iOS 13+/macOS 10.15+, use CryptoKit: let key = SymmetricKey(size: .bits256) que usa o CSPRNG do sistema.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="OBJC-009",
        name="Cookie HTTP sem Flag Secure",
        description="NSHTTPCookie criado sem NSHTTPCookieSecure: @YES transmite o cookie em conexões HTTP não criptografadas. Em redes Wi-Fi públicas, interceptadores passivos podem capturar cookies de sessão e hijack contas do usuário.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.OBJECTIVEC,
        pattern=r'NSHTTPCookie\s+cookieWithProperties\s*:[^;]+(?!NSHTTPCookieSecure)',
        remediation="Defina NSHTTPCookieSecure: @YES em todos os cookies de sessão: NSHTTPCookie *cookie = [NSHTTPCookie cookieWithProperties:@{NSHTTPCookieName:@\"session\", NSHTTPCookieSecure:@YES, NSHTTPCookieHTTPOnly:@YES, ...}].",
        cwe="CWE-614",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="OBJC-010",
        name="Conexão HTTP Não Criptografada em NSURLRequest",
        description="NSURLRequest ou NSURLSession com URL http:// transmite dados em texto puro. iOS 9+ com App Transport Security (ATS) bloqueia HTTP por padrão, mas NSAllowsArbitraryLoads: YES no Info.plist desabilita essa proteção, permitindo conexões HTTP inseguras.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.OBJECTIVEC,
        pattern=r'NSURLRequest\s+requestWithURL\s*:\s*\[NSURL\s+URLWithString\s*:\s*@"http://',
        remediation="Use https:// em todas as URLs. Não adicione NSAllowsArbitraryLoads no Info.plist. Se precisar de exceções específicas para domínios legacy, use NSExceptionDomains com NSExceptionAllowsInsecureHTTPLoads: NO e mínimo de TLS configurado.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
]
