"""Regras de segurança para OpenAPI/Swagger — 9 regras (OAPI-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

OPENAPI_RULES: list[Rule] = [
    Rule(
        id="OAPI-001",
        name="Endpoint OpenAPI sem Esquema de Segurança",
        description="Endpoints definidos em OpenAPI/Swagger sem 'security:' ou sem referência a 'securitySchemes:' no componente global estão documentados como não autenticados. Geradores de código client e ferramentas de teste assumem que esses endpoints não requerem autenticação.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.YAML,
        pattern=r'paths\s*:\s*\n(?:\s+/[^\n]+\n)',
        negative_pattern=r'security\s*:|securitySchemes\s*:',
        remediation="Adicione security schemes em components e aplique globalmente ou por endpoint: security: [{BearerAuth: []}]. Em components/securitySchemes defina: BearerAuth: {type: http, scheme: bearer, bearerFormat: JWT}. Use x-openapi-router-controller para integrar com middleware de autenticação.",
        cwe="CWE-306",
        owasp="A07:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="OAPI-002",
        name="Servidor OpenAPI com URL HTTP (sem HTTPS)",
        description="'servers:' com URLs 'http://' em specs OpenAPI documenta que a API aceita conexões não criptografadas. Clientes gerados automaticamente usam essas URLs, transmitindo tokens, dados de usuário e requests em plaintext. Specs OpenAPI públicas indexadas expõem também o endereço do servidor.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.YAML,
        pattern=r'servers\s*:\s*\n\s+-\s*url\s*:\s*["\']?http://',
        remediation="Use https:// em todas as URLs de servidor: servers: [{url: 'https://api.example.com/v1', description: Production}]. Para desenvolvimento local, use https://localhost com certificado self-signed. Configure redirect de HTTP para HTTPS no gateway e documente isso na spec.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="OAPI-003",
        name="Dados PII em Examples ou Defaults da Spec",
        description="Campos de email, CPF, cartão de crédito, endereço ou outros PII usados como 'example:' ou 'default:' em schemas OpenAPI ficam na spec, que é frequentemente servida publicamente (/swagger.json, /openapi.yaml). Dados reais de usuários em documentação violam LGPD/GDPR.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'example\s*:\s*["\']?(?:\d{3}\.\d{3}\.\d{3}-\d{2}|\d{4}\s?\d{4}\s?\d{4}\s?\d{4}|[a-zA-Z0-9+.-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,})["\']?',
        remediation="Use dados fictícios em examples: email: {example: 'user@example.com'}, cpf: {example: '000.000.000-00'}. Nunca use dados reais de usuários. Para testes automatizados, use libraries de geração de dados fake (Faker.js, faker-python). Configure $ref para reutilizar exemplos padronizados.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="OAPI-004",
        name="API Key em Query Parameter (in: query)",
        description="'in: query' para API keys adiciona credenciais à URL: ?api_key=abc123. URLs são logadas por servidores web, proxies, CDNs e sistemas de monitoramento. API keys em URLs aparecem em browser history, logs de acesso e referrer headers de terceiros.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'in\s*:\s*query\s*\n(?:\s+[^\n]+\n)*\s+name\s*:\s*(?:api.?key|token|auth|secret)',
        remediation="Mova API keys para headers: in: header, name: X-API-Key. Ou use Bearer token no Authorization header: in: header, name: Authorization, schema: {type: string, example: 'Bearer TOKEN'}. Configure seus gateways de API para rejeitar autenticação via query string.",
        cwe="CWE-598",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="OAPI-005",
        name="Endpoint de Lista sem Paginação Documentada",
        description="Endpoints GET que retornam coleções (paths com '/list', '/all', ou response schema com 'type: array') sem parâmetros 'limit', 'page', 'offset' ou 'cursor' documentados podem retornar todo o dataset em uma requisição. Isso é um vetor de DoS e exposição massiva de dados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.YAML,
        pattern=r'/(?:list|all|users|items|records|products|orders)\s*:\s*\n\s+get\s*:\s*\n',
        negative_pattern=r'limit|page|offset|cursor|per_page',
        remediation="Documente parâmetros de paginação: parameters: [{name: limit, in: query, schema: {type: integer, minimum: 1, maximum: 100, default: 20}}, {name: cursor, in: query, schema: {type: string}}]. Implemente paginação cursor-based para datasets grandes. Defina tamanho máximo de página.",
        cwe="CWE-400",
        owasp="A04:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="OAPI-006",
        name="Response 500 sem Mascaramento de Detalhes de Erro",
        description="Responses 500 com schema que inclui campos como 'stack', 'trace', 'internal_error', 'sql_error' ou 'exception' documentam e incentivam a exposição de detalhes de implementação em erros do servidor. Esses detalhes ajudam attackers a planejar ataques direcionados.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.YAML,
        pattern=r"'500'\s*:\s*\n(?:\s+[^\n]+\n)*\s+properties\s*:\s*\n(?:\s+[^\n]+\n)*\s+(?:stack|trace|exception|internal)",
        remediation="Retorne apenas mensagens genéricas em 500: {message: 'Internal server error', request_id: 'abc123'}. Logue detalhes internamente com o request_id para correlação. No schema: properties: {message: {type: string}, request_id: {type: string, format: uuid}}. Nunca exponha stack traces em produção.",
        cwe="CWE-209",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="OAPI-007",
        name="Campo de Senha sem writeOnly: true",
        description="Campos de senha em schemas OpenAPI sem 'writeOnly: true' sugerem que a API pode retornar senhas em responses (GET/read operations). Mesmo que a implementação não retorne senhas, a spec incorreta pode confundir desenvolvedores e levar a implementações que expõem hashes ou tokens.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.YAML,
        pattern=r'(?:password|passwd|secret|token)\s*:\s*\n\s+type\s*:\s*string',
        negative_pattern=r'writeOnly\s*:\s*true',
        remediation="Adicione 'writeOnly: true' em campos de senha: password: {type: string, format: password, writeOnly: true, minLength: 8}. Use 'readOnly: true' para campos que nunca devem ser enviados pelo cliente (id, created_at). Configure validators para rejeitar requests com readOnly fields.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="OAPI-008",
        name="Upload de Arquivo sem Validação de Tipo Documentada",
        description="Endpoints de upload com 'type: string, format: binary' ou 'type: string, format: byte' sem enum de tipos MIME ou validação de tamanho documentada permitem upload de qualquer arquivo. Sem documentação de restrições, implementações podem não validar tipo e tamanho.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.YAML,
        pattern=r'format\s*:\s*binary',
        negative_pattern=r'maxLength|contentMediaType|x-max-file-size',
        remediation="Documente restrições de upload: schema: { type: string, format: binary, contentMediaType: 'image/jpeg,image/png,image/gif', 'x-max-file-size': 5242880 }. Adicione validação no middleware: verifique magic bytes (não apenas extensão) e tamanho máximo. Use antivirus scanning para uploads.",
        cwe="CWE-434",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="OAPI-009",
        name="Spec OpenAPI Servida Publicamente sem Autenticação",
        description="'x-internal: false' ou ausência de autenticação na rota que serve a spec OpenAPI (/swagger.json, /openapi.yaml, /docs) expõe a documentação completa da API publicamente. A spec contém todos os endpoints, schemas, exemplos e pode revelar funcionalidades não intencionalmente públicas.",
        severity=Severity.LOW,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.YAML,
        pattern=r'/(?:swagger(?:-ui)?|openapi|api-docs|redoc)\s*:',
        remediation="Proteja a documentação em produção: configure autenticação básica ou VPN para acessar /swagger-ui ou /redoc. Disable introspection em produção: app.config['DEBUG'] = False. Use diferentes specs para diferentes audiences: spec pública (endpoints públicos apenas) e spec interna (completa).",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
]
