"""
Regras de anti-patterns de performance.
Baseadas em: High Performance Browser Networking (Grigorik),
Java Performance (Scott Oaks), Database Internals (Petrov),
Site Reliability Engineering (Google).
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PERFORMANCE_RULES: list[Rule] = [
    # ── SQL / Banco de Dados ──────────────────────────────────────────────────
    Rule(
        id="PERF-001",
        name="SELECT * — Busca de Colunas Desnecessárias",
        description="SELECT * recupera todas as colunas, incluindo as não utilizadas. Aumenta I/O de rede e disco, impede uso de covering indexes e cria acoplamento frágil ao schema.",
        severity=Severity.MEDIUM,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r'\bSELECT\s+\*\s+FROM\b',
        remediation="Especifique apenas as colunas necessárias: SELECT id, name, email FROM users. Para múltiplas colunas, considere DTOs ou projections.",
        cwe="CWE-1116",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PERF-002",
        name="SELECT sem LIMIT/TOP/FETCH — Resultado Ilimitado",
        description="Query sem cláusula de limitação pode retornar milhões de registros, saturar memória, degradar o banco e causar timeout do request.",
        severity=Severity.HIGH,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r'\bSELECT\b.+\bFROM\b',
        negative_pattern=r'(?:LIMIT\s+\d|TOP\s+\d|FETCH\s+FIRST|ROWNUM\s*<|COUNT\s*\()',
        remediation="Adicione paginação: SELECT ... LIMIT 100 OFFSET 0. Implemente paginação cursor-based para volumes muito grandes.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PERF-003",
        name="Problema N+1 — Query dentro de Loop",
        description="Query de banco de dados executada dentro de loop/iteração. Para N itens, faz N+1 queries ao invés de 1 — causa exponencial de chamadas ao banco com crescimento de dados.",
        severity=Severity.HIGH,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r'(?:for|foreach|while)\s*[^{]*\{[^{}]*(?:\.find\(|\.query\(|\.execute\(|\.get\(|db\.|cursor\.|session\.)',
        remediation="Use JOINs, IN clauses, ou batch loading. Ex: carregue todos os IDs de uma vez com WHERE id IN (...) em vez de uma query por ID.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERF-004",
        name="Operação de I/O dentro de Loop",
        description="Operação de leitura/escrita de arquivo dentro de loop. Cada iteração incorre em overhead de syscall e I/O — deve ser batched.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.GENERIC,
        pattern=r'(?:for|foreach|while)\s*[^{]*\{[^{}]*(?:open\s*\(|write\s*\(|read\s*\(|readFile|writeFile)',
        remediation="Mova I/O para fora do loop. Leia todo o conteúdo antes do loop, processe em memória, e escreva uma vez ao final.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERF-005",
        name="Criação de Objeto Desnecessária em Loop",
        description="Criação de novos objetos dentro de loop que poderiam ser reutilizados. Aumenta pressão sobre o garbage collector e degrada performance.",
        severity=Severity.LOW,
        category=VulnCategory.PERFORMANCE,
        language=Language.GENERIC,
        pattern=r'(?:for|foreach|while)\s*[^{]*\{[^{}]*new\s+(?:ArrayList|HashMap|StringBuilder|StringBuffer|BigDecimal|Date|Random)\s*\(',
        remediation="Mova a criação do objeto para antes do loop. Use object pooling para objetos caros. Reutilize instâncias quando possível.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERF-006",
        name="LIKE com Wildcard no Início — Full Table Scan",
        description="LIKE '%texto' com wildcard no início impede uso de índice B-tree, forçando full table scan mesmo que exista índice na coluna.",
        severity=Severity.HIGH,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r"LIKE\s+['\"]%\w",
        remediation="Restruture a query para usar índice: LIKE 'texto%'. Para busca full-text, use FTS (PostgreSQL tsvector, MySQL FULLTEXT, Elasticsearch).",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PERF-007",
        name="Ausência de Índice na Chave Estrangeira",
        description="Tabela com FK mas sem índice na coluna FK. JOINs e deleções em cascata farão full table scan na tabela filha.",
        severity=Severity.MEDIUM,
        category=VulnCategory.DATABASE_PERF,
        language=Language.SQL,
        pattern=r'FOREIGN\s+KEY\s*\([^)]+\)\s+REFERENCES\s+\w+',
        negative_pattern=r'(?:INDEX|KEY)\s+\w+\s*\([^)]+\)',
        remediation="Crie índice para toda FK: CREATE INDEX idx_orders_user_id ON orders(user_id). A maioria dos ORM não cria índices de FK automaticamente.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PERF-008",
        name="Função em WHERE Clause — Invalida Índice",
        description="Aplicar função a coluna indexada em WHERE (ex: WHERE LOWER(email) =) impede uso do índice, fazendo full scan.",
        severity=Severity.HIGH,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r'WHERE\s+(?:LOWER|UPPER|TRIM|DATE|YEAR|MONTH|CAST|CONVERT|SUBSTRING)\s*\(',
        remediation="Use índices funcionais (computed columns) ou normalize os dados na escrita. Ex: armazene email sempre em lowercase.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PERF-009",
        name="Concatenação em Loop — Python (O(n²))",
        description="Concatenação de string com += em loop Python. Strings são imutáveis — cada operação cria novo objeto, resultando em complexidade quadrática.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'(?:for|while)\s+.+:\s*\n\s+\w+\s*\+=\s*(?:str\(|\w+\s*\+|["\'])',
        remediation="Use lista + join: partes = []; for x in lista: partes.append(str(x)); resultado = ''.join(partes)",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERF-010",
        name="StringBuilder não Usado em Loop Java",
        description="Concatenação de String com + em loop Java. O compilador não otimiza isso completamente — StringBuilder é explicitamente mais eficiente.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.JAVA,
        pattern=r'for\s*\([^)]+\)\s*\{[^}]*String\s+\w+\s*=\s*\w+\s*\+',
        remediation="Use StringBuilder: StringBuilder sb = new StringBuilder(); for (...) { sb.append(x); } return sb.toString();",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERF-011",
        name="Regex Compilado a Cada Chamada",
        description="Padrão regex compilado dentro de loop ou função frequentemente chamada. Compilação de regex é cara — deve acontecer uma única vez.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r're\.(?:compile|match|search|findall|sub)\s*\(\s*(?:r?["\'])',
        remediation="Pré-compile o padrão: PATTERN = re.compile(r'padrão'). Depois use PATTERN.match(texto). A compilação ocorre uma vez na importação do módulo.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PERF-012",
        name="HttpClient Instanciado por Request (Connection Pool Bypass)",
        description="Criar novo HttpClient a cada request não reutiliza o pool de conexões TCP/TLS, causando overhead de handshake e esgotamento de portas (socket exhaustion).",
        severity=Severity.HIGH,
        category=VulnCategory.PERFORMANCE,
        language=Language.CSHARP,
        pattern=r'using\s+(?:var\s+)?(?:client\s*=\s*)?new\s+HttpClient\s*\(',
        remediation="Use IHttpClientFactory (ASP.NET Core) ou HttpClient como singleton/static. IHttpClientFactory gerencia o pool automaticamente.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERF-013",
        name="Busca em Lista quando Set/Dict Seria O(1)",
        description="Verificação de membership (in, contains) em estrutura linear (lista, array) tem complexidade O(n). Para lookup frequente, use Set/HashSet/Dict.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'\bif\s+\w+\s+in\s+\[',
        remediation="Substitua listas por sets para verificações de membership: VALID_IDS = {1, 2, 3, 4}. if id in VALID_IDS é O(1).",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERF-014",
        name="Carregamento Síncrono Bloqueante em Contexto Assíncrono",
        description="Operação de I/O síncrona (leitura de arquivo, query de DB) chamada com .Result ou .Wait() dentro de código async. Causa deadlock em ASP.NET/frameworks com SynchronizationContext.",
        severity=Severity.HIGH,
        category=VulnCategory.PERFORMANCE,
        language=Language.CSHARP,
        pattern=r'\.Result\s*[;.]|\.Wait\s*\(\s*\)',
        remediation="Use await em vez de .Result/.Wait(). Se precisar de sync, use Task.Run() mas entenda os impactos. Deadlock é o risco principal.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERF-015",
        name="Query com OR em Coluna Indexada (Pode Invalidar Índice)",
        description="WHERE col1 = x OR col2 = y pode não usar índices em algumas combinações. O otimizador pode escolher full scan.",
        severity=Severity.LOW,
        category=VulnCategory.DATABASE_PERF,
        language=Language.GENERIC,
        pattern=r'WHERE\s+\w+\s*=\s*.+\s+OR\s+\w+\s*=',
        remediation="Considere UNION ALL de duas queries indexadas, ou reveja se os índices cobrem a query. Use EXPLAIN ANALYZE para verificar o plano de execução.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
