"""Regras de segurança para Perl — 10 regras (PERL-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PERL_RULES: list[Rule] = [
    Rule(
        id="PERL-001",
        name="eval() com String — Execução de Código Dinâmico",
        description="eval EXPR em Perl (em contraste com eval BLOCK) compila e executa uma string como código Perl em runtime. Com dados externos, permite execução de código arbitrário. É historicamente um dos vetores mais explorados em CGI Perl e scripts de administração.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PERL,
        pattern=r'\beval\s+(?:["\'`]|\$)',
        remediation="Substitua eval STRING por eval BLOCK para captura de exceções: eval { risky_operation() }. Para expressões dinâmicas, use módulos como Safe que criam um compartimento restrito. Nunca execute código vindo de input do usuário.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-002",
        name="Injeção de Comando via system()",
        description="system() com uma única string passa o argumento ao shell do sistema para interpretação. Metacaracteres shell (;, |, &&, ``) em dados externos permitem injeção de comandos. system() com lista de argumentos é seguro, mas com string única é perigoso.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PERL,
        pattern=r'\bsystem\s*\(\s*["\'`\$]',
        remediation="Use system() com lista de argumentos para evitar interpretação shell: system('git', 'clone', $user_url). Nunca use system() com string única e input dinâmico. Para capturar output, use open3 com lista de argumentos.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-003",
        name="Injeção de Comando via exec()",
        description="exec() com string única invoca o shell. Similar a system(), mas substitui o processo atual pelo comando — não há retorno após exec(). Com input externo, resulta em execução de código arbitrário com os privilégios do processo Perl.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PERL,
        pattern=r'\bexec\s*\(\s*["\'`\$]',
        remediation="Use exec() com lista de argumentos: exec('ls', '-la', $safe_path). Valide todos os argumentos antes de passar. Considere usar IPC::Open3 ou IPC::Run para controle completo sobre stdin/stdout/stderr do processo filho.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-004",
        name="Execução de Comando via Backtick / qx()",
        description="Expressões com backtick (`cmd`) e qx() executam comandos no shell e retornam a saída. São equivalentes ao system() em termos de risco de injeção, mas o output é capturado. Amplamente usados em scripts de administração Perl para pipelar comandos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PERL,
        pattern=r'`[^`]*\$\{?[a-zA-Z_]|\bqx\s*(?:\{|\[|\(|\|)\s*[^)}\]|]*\$',
        remediation="Substitua backticks por IPC::Open3 ou IPC::Run com listas de argumentos: use IPC::Run qw(run capture); my $out = capture(['git', 'log', '--oneline', $branch]). Nunca interpole variáveis externas em backticks.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERL-005",
        name="Injeção de Shell via open() com Pipe",
        description="open(FH, \"| $cmd\") ou open(FH, \"$cmd |\") passa o argumento ao shell. Se $cmd contém input do usuário, permite injeção de comandos. O modo pipe de open() é uma armadilha clássica em CGI Perl que passou despercebida por anos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PERL,
        pattern=r'\bopen\s*\([^,]+,\s*["\']?\s*\|',
        remediation="Use a forma de 3 ou mais argumentos de open: open(my $fh, '-|', 'git', 'log', $branch) para evitar interpretação shell. Para escrita: open(my $fh, '|-', 'sendmail', '-t'). Nunca use a forma de 2 argumentos com pipe.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-006",
        name="Modo Estrito Desabilitado: no strict / no warnings",
        description="'no strict' desabilita verificações de variáveis declaradas, referências e namespaces. 'no warnings' suprime avisos críticos sobre uso de variáveis não inicializadas, conversões numéricas inseguras e outros problemas. Em código de produção, isso mascara bugs e vulnerabilidades.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PERL,
        pattern=r'\bno\s+(?:strict|warnings)\b',
        remediation="Mantenha 'use strict; use warnings;' em todos os scripts Perl. Se uma operação específica requer desabilitar brevemente, use um escopo: { no strict 'refs'; $ref->() }. Use perlcritic para enforçar políticas de qualidade.",
        cwe="CWE-1109",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PERL-007",
        name="Injeção SQL via DBI com Concatenação de String",
        description="$dbh->do(\"SELECT * FROM users WHERE name = '\" . $input . \"'\") ou $dbh->prepare() com interpolação de variáveis é SQL injection clássico. O módulo DBI do Perl tem suporte nativo a prepared statements, mas é frequentemente usado de forma insegura.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PERL,
        pattern=r'\$dbh\s*->\s*(?:do|prepare|selectrow_array|selectall_arrayref)\s*\(\s*["\'][^"\']*["\']?\s*\.\s*\$',
        remediation="Use prepared statements com placeholders: $sth = $dbh->prepare('SELECT * FROM users WHERE name = ?'). $sth->execute($user_name). Para valores múltiplos: execute($name, $email). Nunca interpole variáveis diretamente em strings SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-008",
        name="Desserialização Insegura via Storable::thaw()",
        description="Storable::thaw() desserializa dados binários Perl (criados por freeze()). Com dados não confiáveis, permite criação arbitrária de objetos Perl, potencialmente executando código via DESTROY, AUTOLOAD ou outros métodos chamados automaticamente durante desserialização.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PERL,
        pattern=r'\bStorable\s*::\s*thaw\s*\(|\bthaw\s*\(\s*\$',
        remediation="Nunca desserialize dados Storable vindos de fontes externas. Use JSON (JSON::XS), YAML::XS ou MessagePack para dados que cruzam fronteiras de confiança. Para cache local, assine os dados com HMAC antes de armazenar: $sig = hmac_sha256_hex($data, $secret_key).",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-009",
        name="Hash Criptograficamente Fraco: Digest::MD5 / Digest::SHA1",
        description="Digest::MD5->hexdigest() e Digest::SHA->new(1)->hexdigest() produzem hashes criptograficamente quebrados. Uso para hash de senhas é especialmente perigoso: tabelas rainbow para MD5 cobrem bilhões de senhas comuns e ataques de colisão são triviais.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.PERL,
        pattern=r'Digest::MD5|Digest::SHA\s*->new\s*\(\s*1\s*\)',
        remediation="Para senhas: use Crypt::Bcrypt ou Crypt::Argon2: Crypt::Bcrypt::bcrypt_check($password, $hash). Para checksums: use Digest::SHA->new(256)->hexdigest($data) no mínimo. Migre hashes MD5 legados com re-hash no próximo login do usuário.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PERL-010",
        name="Parâmetro CGI sem Sanitização em Resposta HTTP",
        description="$query->param('user_input') usado diretamente em output HTML sem escape permite Cross-Site Scripting (XSS) em aplicações CGI Perl. Legado prevalente em sistemas de intranet e portais antigos ainda em produção.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.PERL,
        pattern=r'\$q(?:uery)?\s*->\s*param\s*\([^)]+\)[^;]*(?:print|say)',
        remediation="Escape HTML antes de imprimir: use HTML::Escape qw(escape_html); print escape_html($query->param('name')). Para templates, use Template::Toolkit com sua diretiva FILTER html. Adote um framework moderno como Catalyst ou Mojolicious com auto-escape.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
]
