"""Regras de segurança para PostgreSQL DDL — 9 regras (PGDDL-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PG_DDL_RULES: list[Rule] = [
    Rule(
        id="PGDDL-001",
        name="GRANT ALL em Tabela ou Schema PostgreSQL",
        description="'GRANT ALL' concede todos os privilégios disponíveis (SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER) a um role ou ao público. Em vez de GRANT ALL, aplique o princípio de menor privilégio, concedendo apenas o necessário para cada role de aplicação.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'GRANT\s+ALL\s+(?:PRIVILEGES\s+)?ON\s+',
        remediation="Substitua GRANT ALL por permissões específicas: GRANT SELECT, INSERT, UPDATE ON TABLE users TO app_role; GRANT SELECT ON TABLE audit_log TO readonly_role. Crie roles separados por função: app_user (DML), app_reader (SELECT), migration_user (DDL). Use REVOKE para remover permissões não necessárias.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PGDDL-002",
        name="Tabela com PII sem Row Level Security",
        description="Tabelas que contêm Personally Identifiable Information (nome, email, CPF, endereço) sem 'ALTER TABLE ... ENABLE ROW LEVEL SECURITY' permitem que qualquer role com SELECT veja todos os registros. Em aplicações multi-tenant, todos os usuários podem ver dados de outros tenants.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'CREATE\s+TABLE\s+\w*(?:user|customer|person|client|employee|patient)\w*\s*\(',
        negative_pattern=r'ENABLE ROW LEVEL SECURITY|ROW LEVEL SECURITY',
        remediation="Habilite RLS: ALTER TABLE users ENABLE ROW LEVEL SECURITY; ALTER TABLE users FORCE ROW LEVEL SECURITY; CREATE POLICY tenant_isolation ON users USING (tenant_id = current_setting('app.tenant_id')::UUID). Configure SET app.tenant_id no início de cada transação de aplicação.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PGDDL-003",
        name="Senha Hardcoded em DDL PostgreSQL",
        description="Comandos CREATE USER, ALTER USER ou CREATE ROLE com 'PASSWORD \"literal\"' armazenam senhas em texto claro no script DDL que fica no repositório git. Além de expor a senha, scripts com senhas hardcoded impedem rotação automática de credenciais.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SQL,
        pattern=r'(?:CREATE|ALTER)\s+(?:USER|ROLE)\s+\w+.*PASSWORD\s+["\'][^"\']+["\']',
        remediation="Use variáveis de ambiente em scripts de migração: CREATE USER app_user WITH PASSWORD :'APP_PASSWORD'; e execute com: psql -v APP_PASSWORD=$SECRET_VALUE. Use pg_authid para verificar se o role existe antes de criar. Gerencie credenciais com Vault e rotacione automaticamente.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-004",
        name="Criação de Role SUPERUSER",
        description="'CREATE ROLE ... SUPERUSER' cria um role com bypass de todas as verificações de segurança do PostgreSQL — RLS, permissões de objeto, restrições de conexão. Um SUPERUSER pode ler qualquer dado, modificar qualquer tabela e executar qualquer função, incluindo pg_read_file para ler arquivos do OS.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'CREATE\s+(?:USER|ROLE)\s+\w+.*SUPERUSER|ALTER\s+(?:USER|ROLE)\s+\w+.*SUPERUSER',
        remediation="Evite SUPERUSER em roles de aplicação. Para tarefas específicas, use: CREATEROLE para gerenciar roles, CREATEDB para criar bancos, pg_monitor para monitoramento. Para migrações, use role com permissões DDL específicas. Reserve SUPERUSER para DBA humanos com MFA.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-005",
        name="UNENCRYPTED PASSWORD em PostgreSQL",
        description="'CREATE USER ... UNENCRYPTED PASSWORD' (deprecated mas ainda aceito em versões antigas) ou 'CREATE ROLE ... WITH PASSWORD' sem 'ENCRYPTED' em versões < 10 armazena a senha como MD5 hash fraco (pg_shadow). Hashes MD5 de senhas são facilmente quebrados com rainbow tables.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.SQL,
        pattern=r'UNENCRYPTED\s+PASSWORD|PASSWORD\s+["\'][^"\']+["\'](?!\s*ENCRYPTED)',
        remediation="Use SCRAM-SHA-256: ALTER SYSTEM SET password_encryption = 'scram-sha-256'; Em postgresql.conf: password_encryption = scram-sha-256. Força re-autenticação: ALTER USER app_user WITH PASSWORD 'new_password' (será armazenado com SCRAM). Migre pg_hba.conf de md5 para scram-sha-256.",
        cwe="CWE-916",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-006",
        name="GRANT EXECUTE em Função para PUBLIC",
        description="'GRANT EXECUTE ON FUNCTION nome() TO PUBLIC' permite que qualquer usuário do banco execute a função. Funções PostgreSQL podem ter SECURITY DEFINER (executam como owner), acesso a dados internos e operações privilegiadas. Expor a PUBLIC amplifica drasticamente a superfície de ataque.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'GRANT\s+EXECUTE\s+ON\s+FUNCTION\s+[^;]+\s+TO\s+PUBLIC',
        remediation="Revogue execute de PUBLIC e conceda a roles específicos: REVOKE EXECUTE ON FUNCTION sensitive_func() FROM PUBLIC; GRANT EXECUTE ON FUNCTION sensitive_func() TO app_role. Para funções utilitárias genuinamente públicas, adicione validação de input e limite de rate via pg_rate_limit.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-007",
        name="dblink — Conexão a Banco Externo Sem Controle",
        description="'CREATE EXTENSION dblink' habilita conexões de banco a banco via SQL. dblink pode ser usado para exfiltrar dados para bancos externos, fazer port scanning da rede interna via conexões TCP, e contornar RLS executando queries em bancos remotos com credenciais hardcoded.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r'CREATE\s+EXTENSION\s+(?:IF\s+NOT\s+EXISTS\s+)?dblink',
        remediation="Evite dblink. Use Foreign Data Wrappers (FDW) com controle de acesso por role e auditoria: CREATE FOREIGN TABLE com SERVER configurado com credenciais mínimas. Se dblink for necessário, conceda apenas para roles específicos e monitore via log_statement = 'all'.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-008",
        name="Índice em Campo de Senha / Hash Sensível",
        description="CREATE INDEX em colunas de senha, hash, token ou PII facilita ataques de timing e lookup. Índices B-tree em campos de senha permitem queries de igualdade eficientes: WHERE password_hash = $1 retorna resultado instantâneo, facilitando ataques de validação em batch.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.SQL,
        pattern=r'CREATE\s+(?:UNIQUE\s+)?INDEX\s+\w+\s+ON\s+\w+\s*\([^)]*(?:password|passwd|secret|token|hash|ssn|credit_card)[^)]*\)',
        remediation="Não crie índices em colunas de senha ou hash de senha — queries de lookup de usuário devem usar o campo de username (com índice) para localizar o registro e então comparar o hash em memória. Para tokens de sessão, indexe um hash do token (SHA-256) para lookup mas nunca o token em si.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PGDDL-009",
        name="COPY TO/FROM com Arquivo do Sistema de Arquivos",
        description="'COPY ... TO '/etc/passwd'' ou 'COPY ... FROM '/var/secrets/key.pem'' permite ao PostgreSQL ler e escrever arquivos arbitrários no sistema de arquivos do servidor, executando como o usuário postgres. Isso pode ser usado para exfiltração de dados sensíveis ou escrita de arquivos maliciosos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r"COPY\s+\w+\s+(?:TO|FROM)\s+['\"](?!/tmp/)['\"]",
        remediation="Use COPY TO/FROM STDOUT/STDIN em vez de caminhos de arquivo: COPY users TO STDOUT WITH CSV HEADER. Aplique no nível de aplicação via JDBC/psycopg2 que usam STDIN/STDOUT. Configure pg_hba.conf para limitar roles que podem executar COPY. Revogue pg_read_file de roles de aplicação.",
        cwe="CWE-73",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
