import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PHP_RULES: list[Rule] = [
    Rule(
        id="PHP-001",
        name="eval() Code Injection",
        description="PHP eval() executes arbitrary code. User-controlled input to eval() leads to Remote Code Execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PHP,
        pattern=r'\beval\s*\(',
        remediation="Remove eval(). Use explicit logic, template engines, or sandboxed execution environments.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-002",
        name="Command Injection via system/exec/shell_exec",
        description="PHP functions that execute OS commands with user-controlled input lead to command injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PHP,
        pattern=r'\b(?:system|exec|shell_exec|passthru|popen|proc_open)\s*\(',
        remediation="Avoid OS command execution. If required, use escapeshellarg() and escapeshellcmd(). Validate inputs strictly.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-003",
        name="Local/Remote File Inclusion via User Input",
        description="include/require with user-supplied filenames enables Local File Inclusion (LFI) and potentially Remote File Inclusion (RFI).",
        severity=Severity.CRITICAL,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.PHP,
        pattern=r'\b(?:include|require|include_once|require_once)\s*\(\s*\$_',
        remediation="Never use user input in include/require. Use a whitelist of allowed templates or use a template engine.",
        cwe="CWE-98",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-004",
        name="SQL Injection via mysql_query()",
        description="mysql_query() with unsanitized user input is vulnerable to SQL injection. The mysql_* extension is also deprecated.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PHP,
        pattern=r'mysql_query\s*\(',
        remediation="Migrate to PDO with prepared statements: $stmt = $pdo->prepare('SELECT * FROM users WHERE id = ?'); $stmt->execute([$id]);",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-005",
        name="SQL Injection via Direct Variable Interpolation",
        description="SQL query built using PHP variable interpolation in a string.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PHP,
        pattern=r'(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)\s[^"\']*\$(?:_GET|_POST|_REQUEST|_COOKIE)',
        remediation="Use PDO prepared statements or MySQLi with bind_param(). Never interpolate superglobals into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PHP-006",
        name="Weak Password Hashing (md5/sha1)",
        description="Using md5() or sha1() for password storage is insecure. They are fast hashes designed for throughput, not for resisting brute-force.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.PHP,
        pattern=r'\b(?:md5|sha1)\s*\(\s*\$(?:password|passwd|pwd|pass)',
        remediation="Use password_hash($password, PASSWORD_BCRYPT) for storage and password_verify() for checking.",
        cwe="CWE-916",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PHP-007",
        name="Unserialize with User Input",
        description="PHP unserialize() with attacker-controlled data enables object injection attacks that can lead to RCE via magic methods.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PHP,
        pattern=r'\bunserialize\s*\(\s*\$_',
        remediation="Use JSON (json_decode/json_encode) instead of serialize/unserialize. If PHP serialization is needed, validate with HMAC.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-008",
        name="Reflected XSS via echo/print",
        description="Echoing user input ($_GET, $_POST, $_REQUEST) without escaping enables Reflected XSS.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.PHP,
        pattern=r'(?:echo|print)\s+\$_(?:GET|POST|REQUEST|COOKIE)',
        remediation="Use htmlspecialchars($var, ENT_QUOTES, 'UTF-8') before echoing user input. Consider using a template engine with auto-escaping.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-009",
        name="Open Redirect via header() with User Input",
        description="header('Location: ' . $_GET['url']) with unsanitized input enables open redirect and phishing.",
        severity=Severity.MEDIUM,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.PHP,
        pattern=r'header\s*\(\s*["\']Location:\s*["\'\s]*\.?\s*\$_',
        remediation="Validate redirect targets against a whitelist of allowed URLs or paths.",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-010",
        name="Arbitrary File Upload",
        description="File upload without validation of type, size, or content can allow uploading of malicious scripts.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PHP,
        pattern=r'move_uploaded_file\s*\(',
        negative_pattern=r'(?:mime_content_type|finfo_file|pathinfo.*PATHINFO_EXTENSION)',
        remediation="Validate MIME type using finfo_file(), restrict extensions to a whitelist, rename uploaded files, and store outside webroot.",
        cwe="CWE-434",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PHP-011",
        name="Variable Injection via extract()",
        description="extract($_GET) or extract($_POST) injects arbitrary variables into the current scope, enabling variable overwrite attacks.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PHP,
        pattern=r'\bextract\s*\(\s*\$_',
        remediation="Never use extract() with user-supplied data. Access inputs explicitly: $username = $_POST['username'];",
        cwe="CWE-621",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PHP-012",
        name="SSRF via file_get_contents / curl with User URL",
        description="Fetching URLs from user input without validation enables Server-Side Request Forgery.",
        severity=Severity.HIGH,
        category=VulnCategory.SSRF,
        language=Language.PHP,
        pattern=r'(?:file_get_contents|curl_setopt)\s*\([^)]*\$_',
        remediation="Validate and whitelist URLs. Block private IP ranges (RFC1918), link-local, and cloud metadata endpoints.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.HIGH,
    ),
]
