"""Regras de segurança para PowerShell."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

POWERSHELL_RULES: list[Rule] = [
    Rule(
        id="PS-001",
        name="Invoke-Expression com Variável — Injeção de Código",
        description="Invoke-Expression (IEX) executa strings como código PowerShell. Se a string contém input do usuário ou dado externo, permite execução arbitrária de código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.POWERSHELL,
        pattern=r'\bInvoke-Expression\b|\bIEX\b',
        remediation="Evite Invoke-Expression completamente. Use ScriptBlocks tipados ou cmdlets específicos. Se necessário, valide e sanitize rigorosamente toda string executada.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-002",
        name="ConvertTo-SecureString -AsPlainText — Senha em Texto Simples",
        description="Converter string em texto simples para SecureString com -AsPlainText é antiético: a senha fica na memória como string .NET antes de ser convertida. A flag -Force ignora o warning.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.POWERSHELL,
        pattern=r'ConvertTo-SecureString\b.*-AsPlainText',
        remediation="Use Read-Host -AsSecureString para capturar senhas diretamente como SecureString sem passar por string .NET. Ou use Windows Credential Manager via cmdlets PSCredential.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-003",
        name="Bypass de Execution Policy",
        description="-ExecutionPolicy Bypass ou Unrestricted ignora as políticas de execução configuradas pelo administrador. Pode ser usado para executar scripts maliciosos não assinados.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.POWERSHELL,
        pattern=r'-ExecutionPolicy\s+(?:Bypass|Unrestricted)',
        remediation="Use -ExecutionPolicy RemoteSigned ou AllSigned para ambientes de produção. Assine scripts com certificado de code signing da organização.",
        cwe="CWE-693",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-004",
        name="Credencial Hardcoded em Script PowerShell",
        description="Senhas, tokens ou chaves armazenadas diretamente em scripts PowerShell ficam expostas a qualquer pessoa com acesso ao arquivo ou ao repositório de código.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.POWERSHELL,
        pattern=r'\$\w*(?:Password|Passwd|Secret|Token|APIKey|ApiKey|Key)\w*\s*=\s*["\'][^"\']{8,}["\']',
        remediation="Use SecretManagement module do PowerShell com vault (Azure Key Vault, Secret Server, Windows Credential Manager). Ou use variáveis de ambiente do sistema.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-005",
        name="Invoke-WebRequest / Invoke-RestMethod sem Validação de Certificado",
        description="-SkipCertificateCheck ou -CertificateThumbprint vazio desabilita validação TLS. Scripts que baixam e executam código de URLs não validadas são vetor clássico de ataque.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.POWERSHELL,
        pattern=r'(?:Invoke-WebRequest|Invoke-RestMethod|iwr|irm)\b.*-SkipCertificateCheck',
        remediation="Remova -SkipCertificateCheck em produção. Configure certificados CA corretamente. Para ambientes internos, instale o certificado raiz da organização no store de certificados.",
        cwe="CWE-295",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-006",
        name="Download e Execução Remota de Script (LOLBins)",
        description="Padrão (New-Object Net.WebClient).DownloadString() | IEX é técnica clássica de Living-off-the-Land para download e execução de payloads remotos sem tocar o disco.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.POWERSHELL,
        pattern=r'(?:DownloadString|DownloadFile|WebClient)\b.*(?:Invoke-Expression|IEX|\|\s*\.|\.Invoke)',
        remediation="Nunca baixe e execute código remoto diretamente. Verifique hash do arquivo antes de executar. Use WDAC (Windows Defender Application Control) para bloquear scripts não assinados.",
        cwe="CWE-494",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-007",
        name="Uso de Get-Credential sem Armazenamento Seguro",
        description="Get-Credential captura credenciais mas se o resultado for convertido para texto (.GetNetworkCredential().Password), a senha fica exposta em memória e possivelmente em logs.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.POWERSHELL,
        pattern=r'\.GetNetworkCredential\s*\(\s*\)\.(?:Password|UserName)',
        remediation="Trate credenciais apenas como PSCredential/SecureString. Use o credential apenas onde necessário e não o serialize ou log. Prefira autenticação baseada em certificado.",
        cwe="CWE-312",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-008",
        name="Acesso Direto ao Registro com Dados Externos",
        description="Modificação de registry keys com valores derivados de input externo ou parâmetros pode levar a persistência maliciosa, escalada de privilégio ou instabilidade do sistema.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.POWERSHELL,
        pattern=r'(?:Set-ItemProperty|New-ItemProperty|reg\.exe)\s+.*HKCU:|.*HKLM:',
        remediation="Valide todos os valores antes de escrever no registro. Restrinja escrita em keys sensíveis com privilégio mínimo. Audite modificações de registro com logging.",
        cwe="CWE-78",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PS-009",
        name="Desativação do Windows Defender / AV",
        description="Desabilitar proteções do Windows (Set-MpPreference -DisableRealtimeMonitoring, Add-MpPreference -ExclusionPath) é ação comum em malware e scripts de pentest não autorizados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.POWERSHELL,
        pattern=r'Set-MpPreference\s+.*-Disable|\bAdd-MpPreference\s+.*-Exclusion',
        remediation="Remova qualquer script que desabilite proteções de endpoint. Alterações no Windows Defender requerem justificativa de segurança e aprovação formal.",
        cwe="CWE-693",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PS-010",
        name="Codificação Base64 para Ofuscação (EncodedCommand)",
        description="-EncodedCommand executa código PowerShell codificado em Base64, técnica usada por malware para ofuscar payloads e bypassar análise de logs e AV baseado em assinatura.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.POWERSHELL,
        pattern=r'-(?:EncodedCommand|enc|e)\s+[A-Za-z0-9+/=]{20,}',
        remediation="Proíba o uso de -EncodedCommand em produção via política de PowerShell Constrained Language Mode. Audite todos os usos de EncodedCommand nos logs.",
        cwe="CWE-94",
        confidence=Confidence.HIGH,
    ),
]
