"""Regras de segurança para Protocol Buffers (Protobuf) — 8 regras (PROTO-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PROTO_RULES: list[Rule] = [
    Rule(
        id="PROTO-001",
        name="Campo Sensível em Mensagem Protobuf sem Anotação de Privacidade",
        description="Campos com nomes como 'password', 'secret', 'token', 'ssn', 'credit_card' em mensagens Protobuf sem anotação ou comentário indicando tratamento especial. Esses campos são serializados em logs, traces e mensagens de erro sem mascaramento automático em muitos frameworks.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.PROTOBUF,
        pattern=r'(?:string|bytes)\s+(?:password|passwd|secret|token|api_key|ssn|credit_card|private_key|auth_token)\s*=\s*\d+',
        remediation="Adicione anotações de privacidade: use proto annotations como [(google.api.field_behavior) = SENSITIVE] ou [(buf.validate.field).string.pattern = \"\"]. Implemente um LogSanitizer que mascare campos sensíveis antes de logging. Configure field masks para não retornar campos sensíveis em respostas.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PROTO-002",
        name="Sintaxe proto2 Deprecated com required",
        description="Arquivos usando 'syntax = \"proto2\"' com campos 'required' são problemáticos: campos required em proto2 não podem ser adicionados ou removidos sem quebrar compatibilidade. A semântica de required causa falhas em parsing de mensagens parcialmente populadas, potencialmente usável para DoS.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.PROTOBUF,
        pattern=r'syntax\s*=\s*["\']proto2["\']',
        remediation="Migre para proto3: mude 'syntax = \"proto2\"' para 'syntax = \"proto3\"', remova todos os campos 'required' (não existem em proto3), remova labels 'optional' (são o padrão em proto3) e atualize todos os clientes para a nova definição. Use buf lint para validar.",
        cwe="CWE-1164",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PROTO-003",
        name="Campo Deprecated Ainda em Uso Ativo",
        description="Campos marcados com [deprecated = true] ou comentário '// Deprecated:' em mensagens Protobuf indicam que o campo não deve mais ser usado. Continuar usando campos deprecated implica em comportamento não mantido, possíveis vulnerabilidades de segurança não corrigidas e problemas de compatibilidade futura.",
        severity=Severity.LOW,
        category=VulnCategory.TECHNICAL_DEBT,
        language=Language.PROTOBUF,
        pattern=r'\[deprecated\s*=\s*true\]',
        remediation="Substitua campos deprecated pela alternativa indicada na documentação ou adicione novo campo com semântica correta. Coordene a migração entre todos os produtores e consumidores. Use buf breaking para detectar quebras de compatibilidade durante a migração.",
        cwe="CWE-1164",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PROTO-004",
        name="Mensagem Protobuf sem Limite em Campo repeated",
        description="Campos 'repeated' em Protobuf não têm limite de tamanho por padrão. Um atacante pode enviar uma mensagem com milhares de elementos em um campo repeated (ex: repeated string tags = 1), causando consumo excessivo de memória durante parsing e potencial DoS.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PROTOBUF,
        pattern=r'\brepeated\s+\w+\s+\w+\s*=\s*\d+\s*;',
        remediation="Implemente validação de tamanho no código da aplicação após desserialização: if len(msg.tags) > MAX_TAGS: return error(\"too many tags\"). Use buf validate com regras de tamanho: [(buf.validate.field).repeated.max_items = 100]. Configure limits no gRPC: max_receive_message_length.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PROTO-005",
        name="Tipo bytes para Dados Sensíveis sem Criptografia Indicada",
        description="Campos do tipo 'bytes' em Protobuf frequentemente armazenam dados binários sensíveis como chaves criptográficas, tokens ou dados de PII codificados. Sem documentação explícita sobre criptografia em repouso e em trânsito, esses dados podem ser serializados sem proteção adequada.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.PROTOBUF,
        pattern=r'\bbytes\s+(?:key|cert|credential|private|secret|token|signature|hash)\s*=\s*\d+',
        remediation="Documente explicitamente o mecanismo de criptografia em comentários. Use field masks para excluir campos sensíveis de logs. Configure envelope encryption se dados sensíveis precisam ser armazenados: use Google Tink para envelope encryption de campos bytes sensíveis.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PROTO-006",
        name="Ausência de Versionamento em Service Protobuf",
        description="Services gRPC sem indicação de versão no nome do pacote ou serviço tornam impossível fazer mudanças breaking sem derrubar clientes. Sem versionamento, mudanças de segurança (como adicionar autenticação obrigatória) não podem ser introduzidas gradualmente.",
        severity=Severity.LOW,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.PROTOBUF,
        pattern=r'^package\s+[a-zA-Z][a-zA-Z0-9.]*[^v\d];',
        remediation="Adicione versão ao pacote: 'package myapi.v1;'. Siga as convenções da Google API: 'package google.cloud.storage.v1;'. Use semver implícito: v1 para API estável, v1alpha/v1beta para experimental. Configure buf.yaml com versioning lint rules.",
        cwe="CWE-1164",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PROTO-007",
        name="Tipo Mensagem Recursivo Sem Limite de Profundidade",
        description="Tipos Protobuf com referência circular (message Node { repeated Node children = 1; }) podem ser explorados para DoS via parsing de mensagens profundamente aninhadas. O parser pode esgotar a stack ou consumir memória excessiva tentando desserializar grafos muito profundos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PROTOBUF,
        pattern=r'message\s+(\w+)\s*\{[^}]*\brepeated\s+\1\b',
        remediation="Implemente limite de profundidade no código da aplicação. Configure gRPC MaxRecvMsgSize para limitar tamanho total da mensagem. Use um parser wrapper que conta a profundidade de aninhamento e retorna erro se exceder o limite: MAX_DEPTH = 100.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PROTO-008",
        name="Credencial ou Endpoint Hardcoded em Arquivo Proto",
        description="Comentários ou valores default em campos Protobuf que contêm URLs de serviço, credenciais de teste ou endpoints hardcoded. Esses valores ficam no código-fonte e são distribuídos com a aplicação, podendo expor ambientes de staging/produção.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PROTOBUF,
        pattern=r'//.*(?:password|api_key|secret|token)\s*[=:]\s*\S+|default\s*=\s*["\'][^"\']*(?:key|secret|password)[^"\']*["\']',
        remediation="Remova credenciais de arquivos .proto. Use valores placeholder em defaults: string api_endpoint = 1 [default = \"\"]. Documente configurações necessárias em README. Nunca inclua tokens de API, senhas ou URLs de produção em definições Protobuf.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
]
