"""Regras de segurança para Pulumi (IaC Python/TypeScript) — 8 regras (PULUMI-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PULUMI_RULES: list[Rule] = [
    Rule(
        id="PULUMI-001",
        name="S3 Bucket Pulumi com ACL Pública",
        description="aws.s3.Bucket com 'acl=\"public-read\"' ou 'acl=\"public-read-write\"' em código Pulumi torna objetos do bucket acessíveis publicamente sem autenticação. Código IaC com ACLs públicas pode ser deployado em produção com dados sensíveis inadvertidamente expostos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PYTHON,
        pattern=r'acl\s*=\s*["\']public-(?:read|read-write)["\']',
        remediation="Use acl='private' e configure bucket policies explícitas. Habilite Block Public Access: aws.s3.BucketPublicAccessBlock(resource_name, bucket=bucket.id, block_public_acls=True, block_public_policy=True, ignore_public_acls=True, restrict_public_buckets=True). Para sites estáticos, use CloudFront com OAC.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PULUMI-002",
        name="Security Group Pulumi com Ingresso da Internet",
        description="aws.ec2.SecurityGroup ou azure.network.NetworkSecurityGroup em código Pulumi com 'cidr_blocks=[\"0.0.0.0/0\"]' expõe a porta para toda a internet. O código IaC mal configurado pode ser reutilizado em múltiplos ambientes, propagando a misconfiguration.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PYTHON,
        pattern=r'cidr_blocks\s*=\s*\[\s*["\']0\.0\.0\.0/0["\']',
        remediation="Restrinja CIDR a IPs necessários: cidr_blocks=['10.0.0.0/8'] para acesso interno. Para acesso público legítimo (HTTP/HTTPS), restrinja às portas 80/443 apenas. Use Pulumi Config para tornar CIDRs configuráveis por stack: config.get('allowed_cidr') or '10.0.0.0/8'.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PULUMI-003",
        name="RDS/Banco de Dados Pulumi Acessível Publicamente",
        description="aws.rds.Instance, aws.rds.Cluster ou gcp.sql.DatabaseInstance em Pulumi com 'publicly_accessible=True' ou 'ipv4_enabled=True' expõe o banco de dados diretamente à internet. Bancos de dados nunca devem ter endpoints públicos.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PYTHON,
        pattern=r'publicly_accessible\s*=\s*True|ipv4_enabled\s*=\s*True',
        remediation="Configure publicly_accessible=False. Use Private Endpoints ou VPC Peering para acesso de aplicações. Para acesso de desenvolvimento, use Pulumi ESC ou AWS SSM Session Manager com port forwarding. Coloque instâncias RDS em subnets privadas sem route para Internet Gateway.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PULUMI-004",
        name="IAM Policy Pulumi com Permissões Wildcard",
        description="aws.iam.Policy ou aws.iam.RolePolicy com actions=['*'] ou resources=['*'] em Pulumi concede acesso irrestrito. Código Pulumi com policies permissivas pode ser deployado em múltiplos ambientes, criando múltiplas entidades IAM super-privilegiadas.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.PYTHON,
        pattern=r'actions\s*=\s*\[\s*["\']?\*["\']?\s*\]|resources\s*=\s*\[\s*["\']?\*["\']?\s*\]',
        remediation="Aplique princípio de menor privilégio: actions=['s3:GetObject', 's3:PutObject'], resources=[bucket.arn.apply(lambda arn: f'{arn}/*')]. Use Pulumi CrossGuard (Policy as Code) para rejeitar automaticamente policies com wildcards: if '*' in policy.actions: raise ValueError('Wildcard actions not allowed').",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PULUMI-005",
        name="Credencial Hardcoded em Código Pulumi",
        description="Strings literais de senha, token ou API key em código Pulumi são armazenadas no repositório git e nos state files do Pulumi (que podem estar em S3 público ou Pulumi Cloud). State files do Pulumi contêm todos os inputs de resources, incluindo valores sensíveis.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PYTHON,
        pattern=r'(?:password|secret|api_key|token|private_key)\s*=\s*["\'][^"\'${\s]{8,}["\']',
        remediation="Use pulumi.Config com secrets: config = pulumi.Config(); db_pass = config.require_secret('dbPassword'). Secrets são criptografados no state file com a chave do stack. Para valores externos, use Pulumi ESC (Environment, Secrets, Configuration) que integra com Vault e AWS Secrets Manager.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PULUMI-006",
        name="KMS/Chave Sem Rotação Configurada",
        description="aws.kms.Key em Pulumi sem 'enable_key_rotation=True' nunca rotaciona o material criptográfico. Chaves KMS sem rotação aumentam o risco de comprometimento por acesso interno de longo prazo. AWS KMS suporta rotação automática anual sem impacto nas aplicações.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'aws\.kms\.Key\s*\(',
        negative_pattern=r'enable_key_rotation\s*=\s*True',
        remediation="Adicione enable_key_rotation=True: aws.kms.Key('my-key', description='App encryption key', enable_key_rotation=True). Configure key policies com least privilege. Use Pulumi CrossGuard para rejeitar KMS keys sem rotação: policy que verifica enable_key_rotation.",
        cwe="CWE-320",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PULUMI-007",
        name="Stack Pulumi sem Secrets Provider Configurado",
        description="Stacks Pulumi sem secrets provider explícito usam o provider padrão (Pulumi Service), que criptografa com chave gerenciada pela Pulumi. Para compliance e soberania de dados, organizações devem gerenciar suas próprias chaves de criptografia para state files.",
        severity=Severity.LOW,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'pulumi\.Config\(\)',
        negative_pattern=r'secrets_provider|PULUMI_CONFIG_PASSPHRASE',
        remediation="Configure secrets provider: pulumi stack init --secrets-provider='awskms://arn:aws:kms:us-east-1:123:key/abc'. Para self-managed: pulumi stack init --secrets-provider='passphrase'. Defina PULUMI_CONFIG_PASSPHRASE como variável de ambiente em CI/CD. Use AWS KMS ou HashiCorp Vault como provider.",
        cwe="CWE-311",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="PULUMI-008",
        name="Encryption at Rest Não Configurada em Storage Pulumi",
        description="aws.ebs.Volume, aws.s3.Bucket ou azure.storage.Account em Pulumi sem 'encrypted=True' ou 'server_side_encryption_configuration' armazena dados sem criptografia em repouso. Discos EBS, S3 objects e blobs Azure não são criptografados por padrão em algumas configurações.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'aws\.ebs\.Volume\s*\(',
        negative_pattern=r'encrypted\s*=\s*True|kms_key_id',
        remediation="Habilite criptografia: aws.ebs.Volume('vol', size=20, encrypted=True, kms_key_id=kms_key.arn). Para S3, configure server_side_encryption_configuration com aws:kms. Use Pulumi CrossGuard para rejeitar resources sem criptografia: 'All EBS volumes must be encrypted'.",
        cwe="CWE-311",
        owasp="A02:2021",
        confidence=Confidence.LOW,
    ),
]
