import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

PYTHON_RULES: list[Rule] = [
    Rule(
        id="PY-001",
        name="eval() with Dynamic Input",
        description="eval() executes arbitrary Python code from a string. If the string contains user-controlled data, an attacker can execute any Python code on the server.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PYTHON,
        pattern=r'\beval\s*\(',
        remediation="Replace eval() with ast.literal_eval() for safe parsing of literals, or use a proper parser. Never pass user input to eval().",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-002",
        name="exec() with Dynamic Input",
        description="exec() executes arbitrary Python statements. Usage with dynamic strings enables remote code execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PYTHON,
        pattern=r'\bexec\s*\(',
        remediation="Eliminate exec() from production code. If dynamic logic is needed, use explicit dispatch tables or plugin architectures.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-003",
        name="Insecure Deserialization via pickle",
        description="pickle.loads() / pickle.load() deserializes arbitrary Python objects. Deserializing attacker-controlled data leads to Remote Code Execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PYTHON,
        pattern=r'\bpickle\.(?:loads?|Unpickler)\s*\(',
        remediation="Use JSON, MessagePack, or protobuf for data serialization. If pickle is required, cryptographically sign the payload and verify before deserializing.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-004",
        name="subprocess with shell=True",
        description="subprocess with shell=True passes the command to the OS shell, enabling shell injection if any part of the command is user-controlled.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PYTHON,
        pattern=r'subprocess\.(?:call|run|Popen|check_output|check_call|getoutput|getstatusoutput)\s*\([^)]*shell\s*=\s*True',
        remediation="Pass commands as a list of arguments (never shell=True). Validate and sanitize all inputs. Use shlex.quote() if shell is unavoidable.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-005",
        name="os.system() Command Execution",
        description="os.system() passes a string to the OS shell. User-controlled content leads to command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PYTHON,
        pattern=r'\bos\.system\s*\(',
        remediation="Use subprocess.run() with a list of arguments and shell=False. Never concatenate user input into shell commands.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-006",
        name="os.popen() Command Execution",
        description="os.popen() opens a pipe to a shell command. If the command includes user input, it is vulnerable to command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.PYTHON,
        pattern=r'\bos\.popen\s*\(',
        remediation="Use subprocess.run() with a list argument and capture output via stdout=PIPE.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-007",
        name="SQL Injection via String Formatting",
        description="SQL query constructed using Python f-strings or % formatting. User-controlled variables inserted directly into SQL enable SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PYTHON,
        pattern=r'(?:execute|executemany)\s*\(\s*(?:f["\']|["\'].*\{|.*%\s*(?:\(|\w))',
        remediation="Use parameterized queries: cursor.execute('SELECT ... WHERE id = %s', (user_id,)). Never build SQL with string formatting.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-008",
        name="SQL Injection via String Concatenation",
        description="SQL query built by concatenating strings. Any user-controlled segment makes this vulnerable to SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.PYTHON,
        pattern=r'(?:SELECT|INSERT|UPDATE|DELETE|FROM|WHERE)\s.*["\'\s]\s*\+\s*\w',
        remediation="Use parameterized queries or an ORM (SQLAlchemy, Django ORM). Never concatenate user input into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PY-009",
        name="Weak Hash Algorithm (MD5)",
        description="MD5 is a cryptographically broken hash function. It should not be used for security-sensitive operations like password hashing or data integrity.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'hashlib\.md5\s*\(|md5\s*=\s*hashlib\.new\s*\(\s*["\']md5["\']',
        remediation="Use hashlib.sha256() or hashlib.sha3_256() for integrity. For passwords, use bcrypt, scrypt, or argon2 via the passlib library.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-010",
        name="Weak Hash Algorithm (SHA-1)",
        description="SHA-1 is cryptographically weak and collision-prone. It is deprecated for security use.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'hashlib\.sha1\s*\(|hashlib\.new\s*\(\s*["\']sha1["\']',
        remediation="Use SHA-256, SHA-3, or BLAKE2 via hashlib. For passwords use bcrypt/scrypt/argon2.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-011",
        name="Insecure Randomness (random module)",
        description="The random module uses a PRNG that is not cryptographically secure. Using it for tokens, passwords, or session IDs is exploitable.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.PYTHON,
        pattern=r'\brandom\.(?:random|randint|randrange|choice|choices|shuffle|sample|uniform)\s*\(',
        remediation="Use the secrets module (secrets.token_hex(), secrets.token_urlsafe()) for security-sensitive random values.",
        cwe="CWE-338",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PY-012",
        name="Unsafe YAML Deserialization",
        description="yaml.load() without Loader=yaml.SafeLoader can deserialize arbitrary Python objects, enabling Remote Code Execution.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PYTHON,
        pattern=r'\byaml\.load\s*\(',
        negative_pattern=r'Loader\s*=\s*yaml\.(?:Safe|Base|Full)Loader',
        remediation="Replace yaml.load() with yaml.safe_load() or explicitly pass Loader=yaml.SafeLoader.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-013",
        name="assert Used for Security Checks",
        description="Python assert statements are removed when running with optimization flags (-O). Security checks relying on assert can be silently bypassed.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PYTHON,
        pattern=r'^\s*assert\s+.*(?:auth|permission|access|admin|role|login|token|valid)',
        remediation="Replace assert with explicit if checks that raise appropriate exceptions (PermissionError, ValueError, etc.).",
        cwe="CWE-617",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="PY-014",
        name="Hardcoded Secret Key (Flask/Django)",
        description="Framework secret key hardcoded in source. Used to sign sessions and CSRF tokens; exposure compromises all user sessions.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PYTHON,
        pattern=r'(?:SECRET_KEY|FLASK_SECRET|APP_SECRET)\s*=\s*["\'][^"\']{5,}["\']',
        remediation="Generate secret keys with os.urandom(32) and store in environment variables or a secrets manager.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
        negative_pattern=r'(?:os\.(?:environ|getenv)|secrets\.|environ\.get)',
    ),
    Rule(
        id="PY-015",
        name="Path Traversal via User Input",
        description="File path constructed using os.path.join with user-supplied data may allow path traversal attacks (e.g., ../../../etc/passwd).",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.PYTHON,
        pattern=r'open\s*\(\s*(?:os\.path\.join\s*\(|f["\']|.*request\.|.*input\s*\()',
        remediation="Validate paths with os.path.realpath() and ensure they remain within the intended base directory. Use pathlib.Path.resolve().",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PY-016",
        name="Disabled SSL/TLS Verification",
        description="SSL certificate verification is disabled (verify=False). This enables man-in-the-middle attacks by allowing any certificate.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PYTHON,
        pattern=r'(?:requests\.\w+|session\.(?:get|post|put|delete|patch))\s*\([^)]*verify\s*=\s*False',
        remediation="Never disable SSL verification in production. Use verify=True (default) or provide a custom CA bundle.",
        cwe="CWE-295",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-017",
        name="Insecure Deserialization via marshal",
        description="marshal.loads() can execute arbitrary code when deserializing attacker-controlled bytecode.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.PYTHON,
        pattern=r'\bmarshal\.loads?\s*\(',
        remediation="Do not deserialize untrusted data with marshal. Use JSON or protobuf for safe data interchange.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-018",
        name="Shell Injection via __import__",
        description="Dynamic imports via __import__() or importlib with user input can load arbitrary modules.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.PYTHON,
        pattern=r'__import__\s*\(',
        remediation="Use static imports. If dynamic loading is needed, maintain an allowlist of permitted module names.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PY-019",
        name="XML External Entity (XXE) via ElementTree",
        description="Python's xml.etree.ElementTree is vulnerable to XXE attacks by default in older versions. Parsing untrusted XML may expose local files.",
        severity=Severity.HIGH,
        category=VulnCategory.XXE,
        language=Language.PYTHON,
        pattern=r'xml\.etree\.ElementTree\.(?:parse|fromstring|XML|XMLParser)',
        remediation="Use defusedxml library instead: import defusedxml.ElementTree as ET. It patches all XML parsers against XXE.",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PY-020",
        name="Weak Cipher DES/3DES",
        description="DES and 3DES are deprecated symmetric ciphers vulnerable to brute-force and meet-in-the-middle attacks.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.PYTHON,
        pattern=r'(?:Cryptodome?|Crypto)\.Cipher\.(?:DES|DES3|ARC2|ARC4|Blowfish)\b',
        remediation="Use AES-256-GCM for symmetric encryption via the cryptography library.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-021",
        name="Flask Debug Mode Enabled",
        description="Flask debug mode exposes an interactive debugger in the browser, allowing arbitrary Python code execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.PYTHON,
        pattern=r'app\.run\s*\([^)]*debug\s*=\s*True',
        remediation="Never enable debug=True in production. Use environment variables: FLASK_DEBUG=0.",
        cwe="CWE-94",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="PY-022",
        name="Insecure Cookie (missing secure/httponly flags)",
        description="Cookies set without Secure and HttpOnly flags are vulnerable to interception and XSS-based theft.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.PYTHON,
        pattern=r'response\.set_cookie\s*\(',
        negative_pattern=r'secure\s*=\s*True',
        remediation="Always set secure=True, httponly=True, and samesite='Strict' or 'Lax' on sensitive cookies.",
        cwe="CWE-614",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="PY-023",
        name="Tarfile Path Traversal (zip-slip)",
        description="Extracting tar archives without path validation allows writing files outside the target directory (zip-slip vulnerability).",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.PYTHON,
        pattern=r'tarfile\.open\s*\(|\.extractall\s*\(',
        remediation="Validate each extracted path against the target directory. Check that os.path.realpath(member.name) starts with the expected base path.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
]
