"""
Regras de qualidade genéricas — aplicadas a TODAS as linguagens.
Baseadas em: Clean Code (Robert C. Martin), Code Complete (McConnell),
Refactoring (Fowler), MISRA C, e boas práticas da indústria.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

QUALITY_GENERIC_RULES: list[Rule] = [
    # ── Código morto / Dívida técnica ─────────────────────────────────────────
    Rule(
        id="QG-001",
        name="Código Comentado (Dead Code)",
        description="Código-fonte comentado encontrado. Código morto aumenta dívida técnica, confunde futuros mantenedores e cria divergência com a lógica real. Nunca deve ser mantido no repositório — para isso existe o controle de versão.",
        severity=Severity.INFO,
        category=VulnCategory.DEAD_CODE,
        language=Language.GENERIC,
        pattern=r'(?://|#)\s*(?:(?:if|for|while|return|class|def|function|import|var|const|let|int|String|void)\s+\w|\w+\s*[=\(]\s*\w)',
        remediation="Remova o código comentado. Se precisar revisitar, use 'git log' ou 'git blame'. Para desabilitar código temporariamente, use feature flags.",
        cwe="CWE-1164",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QG-002",
        name="TODO/FIXME sem Referência de Issue",
        description="Comentário TODO ou FIXME sem referência a um ticket/issue rastreável. TODOs não vinculados a issues raramente são resolvidos e acumulam dívida técnica silenciosa.",
        severity=Severity.INFO,
        category=VulnCategory.TECHNICAL_DEBT,
        language=Language.GENERIC,
        pattern=r'(?://|#|/\*)\s*(?:TODO|FIXME|HACK|XXX|BUG|TEMP|WORKAROUND|KLUDGE)(?!\s*[:#\-]?\s*(?:#\d+|\[|\())',
        remediation="Vincule cada TODO a um ticket: TODO(#1234): descrição. Considere ferramentas como 'todo-checker' em CI para bloquear TODOs sem referência.",
        cwe="CWE-1164",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="QG-003",
        name="Statement de Debug em Código de Produção",
        description="Statement de debug (console.log, print, println, var_dump, etc.) encontrado fora de contexto de teste. Expõe detalhes internos, polui logs, pode vazar dados sensíveis e prejudica performance.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.GENERIC,
        pattern=r'\b(?:console\.log|console\.debug|console\.info|console\.warn|console\.error|System\.out\.print|System\.err\.print|printf\s*\(|var_dump\s*\(|print_r\s*\(|NSLog\s*\(|debugPrint\s*\(|dd\s*\(|dump\s*\()\s*\(',
        negative_pattern=r'(?://|#|/\*)',
        remediation="Use um framework de logging estruturado (Log4j, Serilog, structlog, pino) com níveis de severidade. Remova ou substitua chamadas de debug por logs adequados.",
        cwe="CWE-532",
        confidence=Confidence.MEDIUM,
    ),
    # ── Lei de Deméter ────────────────────────────────────────────────────────
    Rule(
        id="QG-004",
        name="Violação da Lei de Deméter (Encadeamento Excessivo)",
        description="Encadeamento de 4+ chamadas de método/propriedade (a.b.c.d.e). Viola a Lei de Deméter: 'talk only to your immediate friends'. Cria acoplamento forte, dificulta mocking em testes e propaga mudanças em cascata.",
        severity=Severity.LOW,
        category=VulnCategory.COUPLING,
        language=Language.GENERIC,
        pattern=r'\w+(?:\.\w+){4,}\s*(?:\(|$)',
        negative_pattern=r'(?:\.|\s)(?:toString|hashCode|equals|getClass|printStackTrace)\s*\(',
        remediation="Aplique o princípio de Tell, Don't Ask. Crie métodos intermediários ou use o padrão Law of Demeter: extraia variáveis locais para as dependências.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    # ── Parâmetros / Funções ──────────────────────────────────────────────────
    Rule(
        id="QG-005",
        name="Lista de Parâmetros Longa (5+ parâmetros)",
        description="Função ou método com 5 ou mais parâmetros. Code smell clássico identificado por Fowler. Indica baixa coesão, dificuldade de memorização da API e possível violação do SRP.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.GENERIC,
        pattern=r'(?:def|function|func|void|int|String|bool)\s+\w+\s*\([^)]*,[^)]*,[^)]*,[^)]*,[^)]*,',
        remediation="Agrupe parâmetros relacionados em objetos de valor (Value Objects). Use o padrão Builder ou Parameter Object. Mais de 3 parâmetros é sinal de alerta.",
        cwe="CWE-1040",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QG-006",
        name="Parâmetro Flag Booleano",
        description="Parâmetro booleano passado diretamente a uma função (ex: doSomething(true)). Martin Fowler chama isso de 'Flag Argument': indica que a função faz duas coisas, violando o SRP.",
        severity=Severity.LOW,
        category=VulnCategory.SOLID_SRP,
        language=Language.GENERIC,
        pattern=r'\w+\s*\(\s*(?:\w+\s*,\s*)*(?:true|false)\s*(?:,|\))',
        remediation="Divida a função em duas funções separadas com nomes expressivos. Ex: em vez de render(true), use renderHtml() e renderText().",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    # ── Nomenclatura ─────────────────────────────────────────────────────────
    Rule(
        id="QG-007",
        name="Nome de Variável Muito Curto (1-2 caracteres, fora de loop)",
        description="Variável de 1-2 caracteres fora de contexto de loop. Viola o princípio do nome revelador de intenção de Clean Code. Reduz legibilidade e dificulta buscas no código.",
        severity=Severity.INFO,
        category=VulnCategory.NAMING,
        language=Language.GENERIC,
        pattern=r'(?:var|let|const|int|String|bool|float|auto)\s+([a-zA-Z]{1,2})\s*[=;]',
        negative_pattern=r'(?:for|while|foreach)\s*\(|[a-z]\s*=\s*0|[a-z]\s*=\s*1|[a-z]\s*\+\+|[a-z]\s*<|[a-z]\s*>',
        remediation="Use nomes que revelem intenção: 'userCount' em vez de 'n', 'isValid' em vez de 'b'. Exceções válidas: 'i/j/k' em loops, 'x/y/z' em matemática.",
        cwe="CWE-1078",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QG-008",
        name="Nome de Variável Booleana Negada",
        description="Variável booleana com nome negativo (isNotX, notValid, noData). Cria dupla negação no código: if (!isNotLoggedIn) — dificulta raciocínio lógico.",
        severity=Severity.INFO,
        category=VulnCategory.NAMING,
        language=Language.GENERIC,
        pattern=r'\b(?:is_not_|isNot|not_|notIs|no[A-Z]|hasNo[A-Z]|isNo[A-Z])\w+\s*[=:]',
        remediation="Use nomes afirmativos: isLoggedIn, hasData, isValid. Se precisar negar, negue no uso: !isLoggedIn em vez de isNotLoggedIn.",
        cwe="CWE-1078",
        confidence=Confidence.LOW,
    ),
    # ── Complexidade ──────────────────────────────────────────────────────────
    Rule(
        id="QG-009",
        name="Expressão Booleana Complexa (4+ condições)",
        description="Expressão booleana com 4 ou mais condições encadeadas. Aumenta a complexidade cognitiva, dificulta leitura, testes e manutenção. Cada condição extra dobra o número de caminhos lógicos.",
        severity=Severity.LOW,
        category=VulnCategory.COMPLEXITY,
        language=Language.GENERIC,
        pattern=r'(?:if|while|assert)\s*\([^)]*(?:&&|\|\|)[^)]*(?:&&|\|\|)[^)]*(?:&&|\|\|)[^)]*(?:&&|\|\|)',
        remediation="Extraia a condição para um método bem nomeado: if (isEligibleForDiscount(user)) { ... }. Use variáveis explicativas para sub-condições.",
        cwe="CWE-1121",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QG-010",
        name="Ternário Aninhado",
        description="Operador ternário dentro de outro ternário. Cria código extremamente difícil de ler e propenso a erros de precedência.",
        severity=Severity.LOW,
        category=VulnCategory.COMPLEXITY,
        language=Language.GENERIC,
        pattern=r'\?[^:?]+\?[^:?]+:',
        remediation="Use if/else explícito. Código claro é superior a código conciso quando a concisão sacrifica a legibilidade.",
        cwe="CWE-1121",
        confidence=Confidence.MEDIUM,
    ),
    # ── Números mágicos ───────────────────────────────────────────────────────
    Rule(
        id="QG-011",
        name="Número Mágico em Expressão",
        description="Literal numérico sem nome simbólico em expressão lógica ou aritmética. Números mágicos não comunicam intenção e são pontos únicos de falha em refatorações.",
        severity=Severity.INFO,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.GENERIC,
        pattern=r'(?:==|!=|>=|<=|>|<|\*|\/\s*)(?!\s*0\b|\s*1\b|\s*-1\b|\s*100\b)\s*\b(?:[2-9]\d{1,}|1\d+)\b',
        negative_pattern=r'(?:HTTP|STATUS|CODE|PORT|SIZE|LIMIT|TIMEOUT|MAX|MIN|BASE|RATE|VERSION)',
        remediation="Extraia para constantes nomeadas: const MAX_RETRY_ATTEMPTS = 3; const SESSION_TIMEOUT_SECONDS = 1800;",
        cwe="CWE-1109",
        confidence=Confidence.LOW,
    ),
    # ── URL e Endpoints Hardcoded ─────────────────────────────────────────────
    Rule(
        id="QG-012",
        name="URL de Endpoint Hardcoded",
        description="URL de API ou serviço externo hardcoded no código-fonte. Dificulta mudanças de ambiente, pode expor endpoints internos e viola o princípio de configuração externa (12-Factor App).",
        severity=Severity.LOW,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.GENERIC,
        pattern=r'["\']https?://(?!(?:localhost|127\.0\.0\.1|example\.com|schema\.org|w3\.org|docs\.|swagger\.|openapi\.))[a-zA-Z0-9][a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}(?:/[^"\']*)?["\']',
        remediation="Mova URLs para variáveis de ambiente ou arquivo de configuração: os.environ.get('API_BASE_URL'). Siga os princípios do 12-Factor App.",
        cwe="CWE-605",
        confidence=Confidence.LOW,
    ),
    # ── Estado Global ─────────────────────────────────────────────────────────
    Rule(
        id="QG-013",
        name="Mutação de Estado Global",
        description="Atribuição a variável global dentro de função/método. Estado global mutável é uma das principais causas de bugs difíceis de reproduzir, especialmente em código concorrente.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.GENERIC,
        pattern=r'^\s*global\s+\w+',
        remediation="Use injeção de dependência ou classes para encapsular estado. Prefira funções puras que não modifiquem estado externo.",
        cwe="CWE-1108",
        confidence=Confidence.HIGH,
    ),
    # ── DRY ───────────────────────────────────────────────────────────────────
    Rule(
        id="QG-014",
        name="String Literal Duplicada",
        description="Strings literais idênticas com 8+ caracteres tendem a se duplicar por copy-paste. Cada cópia é um ponto de falha independente em refatorações.",
        severity=Severity.INFO,
        category=VulnCategory.DRY_PRINCIPLE,
        language=Language.GENERIC,
        pattern=r'["\'][a-zA-Z_/][a-zA-Z0-9_\-/\.]{7,}["\']',
        remediation="Extraia para constante nomeada. Isso garante que uma única alteração propagua para todos os usos.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    # ── Logging ───────────────────────────────────────────────────────────────
    Rule(
        id="QG-015",
        name="Dado Sensível em Log",
        description="Possível exposição de dado sensível (password, token, key, CPF, cartão) em mensagem de log. Logs são frequentemente armazenados em texto plano e acessíveis por múltiplas equipes.",
        severity=Severity.HIGH,
        category=VulnCategory.LOGGING,
        language=Language.GENERIC,
        pattern=r'(?:log|logger|logging|Log)\s*\.\s*\w+\s*\([^)]*(?:password|passwd|token|secret|credit_card|ssn|cpf|cnpj|cvv|pin)[^)]*\)',
        remediation="Nunca logue dados sensíveis. Use mascaramento: log.info('Auth attempt for user: {}', userId) — nunca inclua a senha. Configure log scrubbers.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="QG-016",
        name="Stack Trace Exposto para Usuário Final",
        description="Stack trace ou erro interno sendo retornado diretamente ao usuário/cliente. Expõe detalhes de implementação que auxiliam ataques de engenharia reversa.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.GENERIC,
        pattern=r'(?:printStackTrace|traceback\.print_exc|print_exc|console\.error\(.*(?:err|error|exception))',
        remediation="Log internamente com stack trace completo. Retorne ao usuário apenas uma mensagem genérica de erro com um correlation ID rastreável.",
        cwe="CWE-209",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    # ── API Design ───────────────────────────────────────────────────────────
    Rule(
        id="QG-017",
        name="Retorno Nulo sem Documentação",
        description="Método que pode retornar null/None sem indicar isso no contrato (tipo, docstring ou annotation). Causa NullPointerException em cascata nos chamadores.",
        severity=Severity.MEDIUM,
        category=VulnCategory.API_DESIGN,
        language=Language.GENERIC,
        pattern=r'\breturn\s+(?:null|None|nil)\s*;?\s*$',
        remediation="Use tipos opcionais: Optional<T> (Java), Optional[T] (Python typing), T? (Kotlin/Swift/C#). Documente quando o retorno pode ser nulo. Considere o padrão Null Object.",
        cwe="CWE-476",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QG-018",
        name="Catch Genérico de Exception/Error",
        description="Captura de Exception ou Error de forma genérica. Mascara bugs legítimos, impede diagnóstico preciso e dificulta tratamento diferenciado de diferentes tipos de erros.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.GENERIC,
        pattern=r'catch\s*\(\s*(?:Exception|Error|Throwable|BaseException|StandardError)\s+\w+\s*\)',
        negative_pattern=r'(?:final|log|rethrow|throw|re-throw)',
        remediation="Capture apenas as exceções esperadas. Se precisar capturar Exception, logue imediatamente e relance ou trate explicitamente cada subtipo.",
        cwe="CWE-396",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QG-019",
        name="Bloco Catch/Except Vazio",
        description="Bloco catch ou except que não faz nada (swallows exception). É um dos bugs mais perigosos: silencia erros, torna o sistema imprevisível e dificulta diagnóstico em produção.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.GENERIC,
        pattern=r'catch\s*\([^)]*\)\s*\{\s*\}|except\s*(?:\w+\s*)?:\s*\n\s*pass\s*$',
        remediation="Nunca silenciar uma exceção. No mínimo: log.error('Unexpected error', e); Considere se o erro deve ser relançado, transformado ou se realmente é seguro ignorar.",
        cwe="CWE-390",
        owasp="A09:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QG-020",
        name="Instrução FIXME de Alta Prioridade",
        description="Comentário FIXME indica bug conhecido ou comportamento incorreto que está no código. Diferente de TODO (melhorias), FIXME sinaliza problemas ativos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.TECHNICAL_DEBT,
        language=Language.GENERIC,
        pattern=r'(?://|#|/\*)\s*FIXME',
        remediation="FIXMEs devem ser resolvidos antes do merge em branch principal. Crie um ticket rastreável e resolva antes de entregar a funcionalidade.",
        cwe="CWE-1164",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="QG-021",
        name="Dependência Hardcoded de Classe Concreta (DIP)",
        description="Instanciação direta de classe concreta dentro de outra classe (new NomeClasse()), em vez de receber a dependência via injeção. Viola o Princípio de Inversão de Dependência.",
        severity=Severity.LOW,
        category=VulnCategory.SOLID_DIP,
        language=Language.GENERIC,
        pattern=r'\bthis\.\w+\s*=\s*new\s+\w+(?:Service|Repository|Manager|Client|Handler|Provider|Impl)\s*\(',
        remediation="Use injeção de dependência via construtor: this.service = service (injetado). Programe para interfaces/abstrações, não implementações.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QG-022",
        name="Método de Classe Acessando Dados de Outra Classe (Feature Envy)",
        description="Método que acessa extensivamente dados de outra classe em vez dos próprios. Code smell 'Feature Envy' identificado por Fowler: o método provavelmente pertence à classe cujos dados usa.",
        severity=Severity.LOW,
        category=VulnCategory.FEATURE_ENVY,
        language=Language.GENERIC,
        pattern=r'(?:\w+\.){3,}\w+\s*(?:\(|\s*[+\-*/=])',
        remediation="Mova o método para a classe cujos dados ele usa mais frequentemente. Aplique 'Move Method' do catálogo de refatorações de Fowler.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QG-023",
        name="Importação Wildcard (Poluição de Namespace)",
        description="Importação com wildcard (*) traz todos os símbolos de um módulo para o namespace, criando conflitos ocultos e tornando difícil rastrear a origem de cada símbolo.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.GENERIC,
        pattern=r'\bimport\s+[\w.]+\.\*\s*;|from\s+\w+\s+import\s+\*',
        remediation="Importe explicitamente apenas o que usa: from module import ClassA, function_b. Isso documenta dependências e evita conflitos de nomes.",
        cwe="CWE-1041",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QG-024",
        name="Comparação com Booleano Explícito",
        description="Comparação redundante com true/false/True/False. Além de verboso, indica que o desenvolvedor não confia na semântica booleana da linguagem.",
        severity=Severity.INFO,
        category=VulnCategory.CODE_QUALITY,
        language=Language.GENERIC,
        pattern=r'(?:==|!=)\s*(?:true|false|True|False)\b',
        remediation="Use diretamente o valor booleano: if (isValid) em vez de if (isValid == true). Para negação: if (!isValid) ou if (not is_valid).",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QG-025",
        name="Configuração de Ambiente em Código (12-Factor Violation)",
        description="Valores de configuração específicos de ambiente (porta, host, timeout, feature flag) hardcoded no código-fonte. Viola o princípio III do 12-Factor App: Store config in the environment.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ARCHITECTURE,
        language=Language.GENERIC,
        pattern=r'(?:port|host|timeout|retry|batch_size|max_connections|pool_size|cache_ttl)\s*[=:]\s*\d{2,}',
        negative_pattern=r'(?:env|environ|config|settings|getenv|getProperty|os\.environ)',
        remediation="Use variáveis de ambiente ou sistema de configuração centralizado. A mesma codebase deve rodar em dev/staging/prod sem mudanças.",
        cwe="CWE-15",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
