"""
Regras de qualidade para C# / .NET.
Baseadas em: Microsoft C# Coding Conventions, Effective C# (Wagoner),
.NET Design Guidelines, Roslyn Analyzers CA-series.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

QUALITY_CSHARP_RULES: list[Rule] = [
    Rule(
        id="QCS-001",
        name="Console.WriteLine em Código de Produção",
        description="Console.WriteLine é síncrono, bloqueia a thread e não tem níveis de severidade nem configurabilidade. Inadequado para produção.",
        severity=Severity.MEDIUM,
        category=VulnCategory.LOGGING,
        language=Language.CSHARP,
        pattern=r'\bConsole\.Write(?:Line)?\s*\(',
        remediation="Use Microsoft.Extensions.Logging, Serilog ou NLog: _logger.LogInformation('...'); Injete ILogger<T> via DI.",
        cwe="CWE-532",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QCS-002",
        name="Captura de Exception Genérica sem Rethrow",
        description="catch(Exception) sem relançar mascara bugs de programação (NullReferenceException, etc.) e impede diagnóstico.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CSHARP,
        pattern=r'catch\s*\(\s*Exception\s+\w+\s*\)\s*\{(?!\s*throw)',
        remediation="Capture apenas exceções esperadas e específicas. Se capturar Exception, logue e relance: catch (Exception ex) { _log.Error(ex); throw; }",
        cwe="CWE-390",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QCS-003",
        name="Ausência de using para IDisposable",
        description="Objetos IDisposable (FileStream, SqlConnection, HttpClient) sem bloco using ou await using causam resource leaks.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CSHARP,
        pattern=r'new\s+(?:FileStream|StreamReader|StreamWriter|SqlConnection|HttpClient|MemoryStream|DbContext)\s*\(',
        negative_pattern=r'\busing\b',
        remediation="Use: using var conn = new SqlConnection(connStr); ou using (var conn = ...) { ... } — garante Dispose() mesmo com exceções.",
        cwe="CWE-772",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QCS-004",
        name="Uso de dynamic Desnecessário",
        description="O tipo dynamic bypassa verificação de tipos em tempo de compilação. Erros só aparecem em runtime e performance é significativamente pior.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.CSHARP,
        pattern=r'\bdynamic\s+\w+\s*=',
        remediation="Use tipos estáticos, generics, ou interface/abstração adequada. dynamic só se justifica ao interoperar com COM ou linguagens dinâmicas.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QCS-005",
        name="Thread.Sleep() Bloqueante",
        description="Thread.Sleep() bloqueia a thread completamente, desperdiçando recursos. Em código async, impede que outras tasks executem.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.CSHARP,
        pattern=r'\bThread\.Sleep\s*\(',
        remediation="Use await Task.Delay(...) em código async. Para sincronização, use SemaphoreSlim, ManualResetEventSlim ou CancellationToken.",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QCS-006",
        name="async void (Exceções Não Capturáveis)",
        description="Métodos async void não podem ser awaited e suas exceções não são capturáveis pelo chamador — crasham o AppDomain sem possibilidade de tratamento.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.CSHARP,
        pattern=r'\basync\s+void\s+\w+\s*\(',
        negative_pattern=r'(?:void\s+On\w+|EventHandler)',
        remediation="Use async Task em vez de async void. A única exceção válida são event handlers (async void OnButton_Click).",
        cwe="CWE-755",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QCS-007",
        name="Propriedade Pública sem Encapsulamento",
        description="Campo público mutável sem getter/setter compromete o encapsulamento. Não permite validação, notificação de mudança (INotifyPropertyChanged) ou evolução futura da API.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.CSHARP,
        pattern=r'\bpublic\s+(?!readonly\s+)(?:static\s+)?(?!const\s+)(?!class\s+)(?:string|int|bool|double|float|decimal|long|List|Dictionary)\s+\w+\s*;',
        remediation="Use propriedades auto-implementadas: public string Nome { get; set; } ou propriedades com lógica de validação.",
        cwe="CWE-1041",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QCS-008",
        name="Magic String como Parâmetro ou Chave",
        description="Strings literais usadas como chaves de dicionário, nomes de propriedade ou identificadores criam código frágil a typos e difícil de refatorar.",
        severity=Severity.LOW,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.CSHARP,
        pattern=r'\[?\s*["\'][a-zA-Z][a-zA-Z0-9_]{3,}["\']\s*\]',
        negative_pattern=r'(?:nameof\(|typeof\(|class\s+|attribute\s+|Authorize\()',
        remediation="Use nameof(Propriedade) para nomes de propriedades. Para constantes: defina public const string KEY = 'valor';",
        cwe="CWE-1109",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QCS-009",
        name="Violação OCP: switch em Tipo/Enum para Comportamento",
        description="Switch statement verificando tipo ou enum para determinar comportamento. Cada novo tipo exige modificar o switch — viola o Open/Closed Principle.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SOLID_OCP,
        language=Language.CSHARP,
        pattern=r'switch\s*\(\s*\w+\.(?:Type|Kind|Category)\s*\)',
        remediation="Use polimorfismo com interface ou classe abstrata. Pattern matching (switch expression C# 8+) com interfaces melhora expressividade mantendo OCP.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QCS-010",
        name="Não Usar CancellationToken em Operação Async",
        description="Método async que realiza I/O ou operações longas sem receber CancellationToken não pode ser cancelado, causando goroutine leaks e degradação em timeouts.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CONCURRENCY,
        language=Language.CSHARP,
        pattern=r'public\s+async\s+Task(?:<[^>]+>)?\s+\w+\s*\([^)]*\)',
        negative_pattern=r'CancellationToken',
        remediation="Adicione CancellationToken ct = default como parâmetro e passe para todas as operações internas: await dbContext.SaveChangesAsync(ct);",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
]
