"""
Regras de qualidade para Java, Kotlin e Scala.
Baseadas em: Effective Java (Bloch), Clean Code, Oracle Java Coding Guidelines,
Google Java Style Guide, Kotlin Coding Conventions.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

QUALITY_JAVA_RULES: list[Rule] = [
    Rule(
        id="QJA-001",
        name="Comparação de String com == (Identidade em vez de Igualdade)",
        description="Em Java, == compara referências de objetos, não conteúdo. Duas Strings com mesmo conteúdo podem ter referências diferentes — str1 == str2 pode retornar false mesmo sendo iguais.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVA,
        pattern=r'\bString\b.*==\s*["\']|["\'].*==\s*\w+String|\w+\s*==\s*"\w',
        remediation='Use .equals(): str1.equals(str2). Para null-safety: Objects.equals(str1, str2) ou str1.equalsIgnoreCase(str2).',
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-002",
        name="Bloco catch Vazio",
        description="Bloco catch que não faz nada silencia completamente a exceção. Bugs críticos são descartados sem log ou tratamento, tornando o sistema imprevisível.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVA,
        pattern=r'catch\s*\([^)]+\)\s*\{\s*\}',
        remediation="No mínimo: catch (Exception e) { log.error('Erro inesperado em X', e); } ou relance a exceção. Nunca swallow silenciosamente.",
        cwe="CWE-390",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-003",
        name="System.out.println em Código de Produção",
        description="System.out.println não é thread-safe, não tem níveis de severidade, não é configurável e não pode ser desabilitado sem alteração de código. Viola SRP de logging.",
        severity=Severity.MEDIUM,
        category=VulnCategory.LOGGING,
        language=Language.JAVA,
        pattern=r'\bSystem\.(?:out|err)\.print(?:ln|f)?\s*\(',
        remediation="Use um framework de logging: SLF4J com Logback/Log4j2. private static final Logger log = LoggerFactory.getLogger(MinhaClasse.class);",
        cwe="CWE-532",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-004",
        name="Concatenação de String em Loop (Performance O(n²))",
        description="Strings em Java são imutáveis. Concatenação em loop cria um novo objeto String a cada iteração — comportamento O(n²) que pode ser crítico para grandes volumes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.JAVA,
        pattern=r'for\s*\([^)]+\)\s*\{[^}]*\w+\s*\+=\s*["\']|\w+\s*=\s*\w+\s*\+\s*["\']',
        remediation="Use StringBuilder: StringBuilder sb = new StringBuilder(); for (...) { sb.append(x); } String result = sb.toString();",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-005",
        name="Retorno de null em vez de Optional",
        description="Retornar null de um método força todos os chamadores a verificar null, criando NullPointerExceptions em cascata quando esquecidos. Java 8+ fornece Optional para este caso.",
        severity=Severity.MEDIUM,
        category=VulnCategory.API_DESIGN,
        language=Language.JAVA,
        pattern=r'(?:public|private|protected)\s+\w+\s+\w+\s*\([^)]*\)\s*\{[^}]*return\s+null\s*;',
        remediation="Retorne Optional.empty() ou Optional.of(value). Documente contratos claros sobre quando null pode ocorrer.",
        cwe="CWE-476",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-006",
        name="Uso de Raw Types (Sem Generics)",
        description="Raw types (List, Map, Set sem parâmetro de tipo) perdem a segurança de tipos do Java generics e geram unchecked warnings que ocultam bugs de cast.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVA,
        pattern=r'\b(?:List|Map|Set|Collection|Iterator|ArrayList|HashMap|HashSet)\s+\w+\s*=',
        negative_pattern=r'<\w',
        remediation="Use sempre generic types: List<String>, Map<String, Integer>. Nunca use raw types em código moderno Java.",
        cwe="CWE-1109",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-007",
        name="Campo Estático Público Mutável",
        description="Campo static public mutável é estado global compartilhado entre todas as instâncias. Viola encapsulamento, causa race conditions em código multithreaded e dificulta testes.",
        severity=Severity.HIGH,
        category=VulnCategory.CONCURRENCY,
        language=Language.JAVA,
        pattern=r'\bpublic\s+static\s+(?!final)\s*(?:int|long|double|float|String|boolean|List|Map|Set)\s+\w+',
        remediation="Declare como final para constantes: public static final. Para estado mutável, use ThreadLocal, sincronização ou injeção de dependência.",
        cwe="CWE-362",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-008",
        name="Ausência de @Override em Método Sobreescrito",
        description="Sem @Override, erros de digitação no nome do método criam silenciosamente um novo método em vez de sobreescrever — o bug só aparece em runtime.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVA,
        pattern=r'^\s*public\s+(?:void|boolean|int|String|Object|\w+)\s+(?:equals|hashCode|toString|compareTo|clone|finalize)\s*\(',
        negative_pattern=r'@Override',
        remediation="Sempre use @Override em métodos sobreescritos. Isso faz o compilador verificar se o método realmente sobreescreve algo.",
        cwe="CWE-1109",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-009",
        name="Captura de RuntimeException Genérica",
        description="Capturar RuntimeException mascara NullPointerException, ArrayIndexOutOfBoundsException e outros erros de programação que deveriam ser corrigidos, não tratados.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVA,
        pattern=r'catch\s*\(\s*RuntimeException\s+\w+\s*\)',
        remediation="Capture apenas exceções checked específicas. RuntimeExceptions indicam bugs de programação — corrija a causa raiz em vez de capturar.",
        cwe="CWE-390",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-010",
        name="Instanciação de BigDecimal com Double",
        description="new BigDecimal(0.1) não cria 0.1 exatamente — o double já tem imprecisão de ponto flutuante. Causa erros sutis em cálculos financeiros.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVA,
        pattern=r'new\s+BigDecimal\s*\(\s*0\.\d+\s*\)',
        remediation='Use BigDecimal.valueOf(0.1) ou new BigDecimal("0.1") com String — estes são exatos.',
        cwe="CWE-681",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJA-011",
        name="Thread.sleep() em Testes (Anti-pattern de Timing)",
        description="Thread.sleep() em testes cria testes frágeis (flaky) que falham intermitentemente dependendo da velocidade da máquina. É um indicador de race condition não tratada no código de produção.",
        severity=Severity.MEDIUM,
        category=VulnCategory.TESTING,
        language=Language.JAVA,
        pattern=r'Thread\.sleep\s*\(',
        remediation="Use Awaitility, CompletableFuture ou CountDownLatch para aguardar condições assíncronas. Nunca durma por tempo fixo em testes.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-012",
        name="Violação do Princípio Open/Closed (Switch em Tipo)",
        description="Switch ou if/else encadeado verificando tipos ou enums para selecionar comportamento. Cada novo tipo exige modificar o switch — violação do OCP (aberto para extensão, fechado para modificação).",
        severity=Severity.MEDIUM,
        category=VulnCategory.SOLID_OCP,
        language=Language.JAVA,
        pattern=r'(?:if|else\s+if)\s*\([^)]*instanceof\s+\w+|switch\s*\([^)]*type[^)]*\)',
        remediation="Use polimorfismo: cada tipo implementa uma interface comum. Adicionar novo comportamento = nova classe, sem modificar código existente (OCP).",
        cwe="CWE-1047",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJA-013",
        name="Ausência de finally/try-with-resources para Recursos",
        description="Abertura de Connection, InputStream, FileReader sem try-with-resources garante que o recurso seja fechado mesmo em caso de exceção.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVA,
        pattern=r'new\s+(?:FileInputStream|FileOutputStream|FileReader|FileWriter|BufferedReader|Connection|Statement|ResultSet)\s*\(',
        negative_pattern=r'try\s*\(',
        remediation="Use try-with-resources: try (Connection conn = getConnection()) { ... } — fecha automaticamente ao sair do bloco.",
        cwe="CWE-772",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJA-014",
        name="Uso de Date em vez de java.time (Java 8+)",
        description="java.util.Date e Calendar são thread-unsafe, mal projetadas e depreciadas na prática. Java 8 introduziu java.time com design muito superior.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVA,
        pattern=r'\bjava\.util\.Date\b|\bnew\s+Date\s*\(|\bCalendar\.getInstance\s*\(',
        remediation="Use java.time: LocalDate, LocalDateTime, ZonedDateTime, Instant. São imutáveis, thread-safe e têm API muito mais expressiva.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
]
