"""
Regras de qualidade específicas para Python.
Baseadas em: PEP 8, PEP 20 (Zen of Python), Google Python Style Guide,
Effective Python (Brett Slatkin), Python Anti-Patterns.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

QUALITY_PYTHON_RULES: list[Rule] = [
    Rule(
        id="QPY-001",
        name="Bare Except (Captura Genérica Perigosa)",
        description="`except:` sem tipo de exceção captura TUDO, incluindo SystemExit, KeyboardInterrupt e GeneratorExit — interrompendo encerramento graceful do programa. É considerado um anti-pattern grave em Python.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PYTHON,
        pattern=r'^\s*except\s*:\s*$',
        remediation="Especifique as exceções: except (ValueError, TypeError) as e:. Se precisar capturar tudo, use except Exception as e: e logue o erro.",
        cwe="CWE-396",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-002",
        name="Argumento Padrão Mutável",
        description="Argumento padrão mutável (lista, dict, set) em função Python. O objeto padrão é compartilhado entre TODAS as chamadas da função — modificá-lo persiste entre invocações. Bug clássico Python.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PYTHON,
        pattern=r'def\s+\w+\s*\([^)]*\b\w+\s*=\s*(?:\[\s*\]|\{\s*\}|list\s*\(\s*\)|dict\s*\(\s*\)|set\s*\(\s*\))',
        remediation="Use None como padrão e crie dentro da função: def func(items=None): if items is None: items = []",
        cwe="CWE-668",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-003",
        name="Comparação com None usando ==",
        description="Usar == ou != para comparar com None em vez de `is` ou `is not`. Objetos com __eq__ customizado podem retornar resultados inesperados. PEP 8 explicitamente recomenda `is None`.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PYTHON,
        pattern=r'\b(?:==|!=)\s*None\b|\bNone\s*(?:==|!=)',
        remediation="Use `if value is None:` e `if value is not None:`. Para booleanos, use `if not value:` ou `if value:`.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-004",
        name="Uso da Palavra-chave global em Função",
        description="A palavra-chave `global` indica que a função está mutando estado global. Funções com efeitos colaterais globais são difíceis de testar, reutilizar e raciocinar sobre.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.PYTHON,
        pattern=r'^\s+global\s+\w+',
        remediation="Encapsule o estado em uma classe ou passe como parâmetro/retorno. Prefira funções puras que não dependam de estado externo.",
        cwe="CWE-1108",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-005",
        name="Corpo de Função com apenas pass",
        description="Função ou método com apenas `pass` como corpo. Pode indicar funcionalidade não implementada deixada para produção, violando o princípio de 'fail fast'.",
        severity=Severity.MEDIUM,
        category=VulnCategory.DEAD_CODE,
        language=Language.PYTHON,
        pattern=r'def\s+\w+\s*\([^)]*\)\s*(?:->.*?)?\s*:\s*\n\s*pass\s*$',
        remediation="Implemente a função ou lance NotImplementedError: raise NotImplementedError('TODO: implement method_name'). Nunca deixe pass silencioso em produção.",
        cwe="CWE-1164",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-006",
        name="Lambda Complexa (>1 expressão)",
        description="Lambda com lógica complexa (condicional, chamada de múltiplas funções). Lambdas devem ser simples e descartáveis; lógica complexa merece uma função nomeada.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PYTHON,
        pattern=r'\blambda\s+[^:]+:\s*(?:.*if.*else.*|.*\(.*\()',
        remediation="Substitua lambdas complexas por funções nomeadas com def. Funções nomeadas são mais fáceis de testar, debugar e ler.",
        cwe="CWE-1041",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-007",
        name="Formatação de String com % ou .format() em vez de f-string",
        description="O uso de % ou .format() para formatar strings em código moderno (Python 3.6+) é desnecessariamente verboso e mais lento que f-strings.",
        severity=Severity.INFO,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PYTHON,
        pattern=r'["\'][^"\']*%\s*(?:\w|\()|["\'][^"\']*\{[^}]*\}["\'][^.]*\.format\s*\(',
        remediation="Use f-strings: f'{nome} tem {idade} anos' é mais legível que '{} tem {} anos'.format(nome, idade).",
        cwe="CWE-1041",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-008",
        name="Abertura de Arquivo sem Context Manager",
        description="Abertura de arquivo com open() sem `with`. Se uma exceção ocorrer, o arquivo não será fechado, causando resource leak (file handle não liberado).",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PYTHON,
        pattern=r'(?<!\bwith\b)\s+\w+\s*=\s*open\s*\(',
        remediation="Use sempre context manager: with open('file.txt') as f: — garante fechamento mesmo com exceções (equivale a try/finally).",
        cwe="CWE-772",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-009",
        name="Uso de type() em vez de isinstance()",
        description="Comparação com type() verifica tipo exato e não considera herança. isinstance() é a forma correta para verificação de tipo em Python OOP.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.PYTHON,
        pattern=r'\btype\s*\(\s*\w+\s*\)\s*(?:==|is)\s*\w+',
        remediation="Substitua type(x) == ClasseX por isinstance(x, ClasseX). Para verificar tipo exato (sem herança): type(x) is ClasseX é válido mas deve ser raro.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-010",
        name="Raise Exception sem Mensagem Descritiva",
        description="Lançamento de exceção com mensagem vaga ou sem mensagem. Dificulta diagnóstico em produção.",
        severity=Severity.LOW,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PYTHON,
        pattern=r'raise\s+\w+(?:Error|Exception)\s*\(\s*["\']["\']?\s*\)',
        remediation="Forneça mensagem descritiva: raise ValueError(f'Valor esperado entre 0 e 100, recebido: {value}'). Inclua os valores problemáticos.",
        cwe="CWE-209",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-011",
        name="Except com Relançamento sem Causa (Perde Context)",
        description="raise dentro de except sem usar `raise from` perde o contexto da exceção original, dificultando diagnóstico.",
        severity=Severity.LOW,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PYTHON,
        pattern=r'except\s+\w+\s+as\s+\w+\s*:\s*\n\s+raise\s+\w+',
        negative_pattern=r'\bfrom\b',
        remediation="Use: raise NovaTipo('mensagem') from excecao_original — preserva o contexto completo da exceção original na stack trace.",
        cwe="CWE-396",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-012",
        name="String de Conexão ou DSN Hardcoded",
        description="Connection string ou DSN de banco de dados hardcoded no código Python.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.PYTHON,
        pattern=r'(?:connect|create_engine|MongoClient|redis\.Redis)\s*\(\s*["\'][^"\']*(?:@|password=|pwd=)',
        remediation="Use variáveis de ambiente: os.environ.get('DATABASE_URL'). Use python-dotenv para carregamento local.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-013",
        name="Ausência de __all__ em Módulo com API Pública",
        description="Módulo Python sem __all__ exporta todos os símbolos por padrão, incluindo imports transitivos. Isso polui o namespace de quem importa o módulo.",
        severity=Severity.INFO,
        category=VulnCategory.API_DESIGN,
        language=Language.PYTHON,
        pattern=r'^from\s+\w+\s+import\s+\*',
        remediation="Defina __all__ = ['ClasseA', 'funcao_b'] no topo do módulo para controlar a API pública exportada.",
        cwe="CWE-1041",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-014",
        name="Função Pública sem Docstring",
        description="Função ou método público sem docstring. Dificulta uso correto da API, geração de documentação e compreensão de pré-condições, pós-condições e exceções possíveis.",
        severity=Severity.INFO,
        category=VulnCategory.DOCUMENTATION,
        language=Language.PYTHON,
        pattern=r'^\s*def\s+(?!_)\w+\s*\([^)]*\)\s*(?:->.*?)?\s*:\s*\n\s*(?!(?:["\']|r["\']))',
        remediation="Adicione docstring: def minha_funcao(param): '''Descrição breve. Args: param: descrição. Returns: tipo e descrição. Raises: ExcecaoX se...'''",
        cwe="CWE-1164",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QPY-015",
        name="Uso de assert para Validação de Input em Produção",
        description="assert é removido quando Python roda com -O (otimização). Nunca use para validar entradas de usuário ou invariantes de segurança críticos em produção.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.PYTHON,
        pattern=r'^\s*assert\s+\w+\s*(?:is not None|is None|!=|==|>|<|>=|<=)',
        remediation="Use if/raise explícito: if value is None: raise ValueError('value cannot be None'). Use assert apenas em testes unitários.",
        cwe="CWE-617",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-016",
        name="Uso de time.sleep() em Código de Produção",
        description="time.sleep() bloqueia a thread completamente. Em aplicações web/assíncronas, paralisa outras requisições. Indica geralmente lógica de retry ou pooling inadequada.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'\btime\.sleep\s*\(',
        negative_pattern=r'(?:test|spec|fixture|mock|fake)',
        remediation="Use asyncio.sleep() em código async. Para retries: use exponential backoff com tenacity. Para polling: use eventos/callbacks ao invés de sleep.",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-017",
        name="Concatenação de String em Loop (Performance)",
        description="String concatenation com += em loop cria nova string a cada iteração em Python (strings são imutáveis). Complexidade O(n²) para n strings.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'for\s+\w+\s+in\s+[^:]+:\s*\n\s+\w+\s*\+=\s*(?:["\']|\w+\s*\+)',
        remediation="Use list append + ''.join(): partes = []; for x in itens: partes.append(str(x)); resultado = ''.join(partes)",
        cwe="CWE-400",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QPY-018",
        name="except Exception: pass (Swallowing Silencioso)",
        description="Captura de Exception seguida de pass — o erro mais silencioso e perigoso de Python. Bugs críticos são engolidos sem nenhum registro.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.PYTHON,
        pattern=r'except\s+(?:Exception|BaseException)\s*(?:as\s+\w+)?\s*:\s*\n\s*pass',
        remediation="Nunca swallow exceções. Mínimo aceitável: except Exception as e: logger.error('Erro inesperado', exc_info=True); raise",
        cwe="CWE-390",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QPY-019",
        name="Carregamento Desnecessário de Módulo Pesado em Top-Level",
        description="Import de módulos pesados no topo do arquivo pode aumentar drasticamente o tempo de inicialização da aplicação se só é usado em caminhos específicos.",
        severity=Severity.INFO,
        category=VulnCategory.PERFORMANCE,
        language=Language.PYTHON,
        pattern=r'^import\s+(?:tensorflow|torch|numpy|pandas|scipy|sklearn|cv2|PIL|matplotlib)',
        remediation="Considere lazy imports: importe dentro da função que usa o módulo. Para CLIs, isso melhora dramaticamente o tempo de resposta.",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
]
