"""
Regras de qualidade para JavaScript e TypeScript.
Baseadas em: Airbnb JS Style Guide, TypeScript Handbook, Clean Code JS,
"You Don't Know JS" (Kyle Simpson), ECMA-262.
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

QUALITY_JS_RULES: list[Rule] = [
    Rule(
        id="QJS-001",
        name="Uso de var (Escopo de Função, não de Bloco)",
        description="`var` tem escopo de função e é hoisted, causando comportamentos surpreendentes dentro de loops, closures e condicionais. ES6 introduziu `let` e `const` exatamente para resolver isso.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'\bvar\s+\w+',
        remediation="Use `const` para valores que não mudam, `let` para variáveis reatribuídas. Nunca use `var` em código moderno.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJS-002",
        name="Igualdade Fraca (== em vez de ===)",
        description="O operador == realiza coerção de tipos implícita: [] == 0, '' == false, null == undefined. Causa bugs sutis e difíceis de reproduzir.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'(?<![=!<>])==(?!=)|(?<!=)!=(?!=)',
        negative_pattern=r'(?:===|!==)',
        remediation="Use sempre === e !== para comparação estrita. A coerção implícita do == cria comportamentos não-determinísticos.",
        cwe="CWE-1109",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJS-003",
        name="Tipo any em TypeScript",
        description="O tipo `any` desabilita completamente a verificação de tipos do TypeScript para aquela variável, anulando o benefício do TypeScript. É um escape hatch que indica tipagem não concluída.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.TYPESCRIPT,
        pattern=r':\s*any\b|as\s+any\b|<any>',
        remediation="Use tipos específicos, `unknown` (type-safe any), generics <T>, ou type unions. Se o tipo é realmente desconhecido, use unknown e faça type narrowing.",
        cwe="CWE-1109",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJS-004",
        name="Promise sem .catch() (Unhandled Rejection)",
        description="Promise sem tratamento de rejeição. Unhandled Promise Rejections crasham o processo em Node.js moderno e causam erros silenciosos em browsers.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVASCRIPT,
        pattern=r'\.then\s*\([^)]+\)\s*(?!\s*\.catch)',
        remediation="Adicione .catch(): promise.then(onSuccess).catch(onError). Ou use async/await com try/catch.",
        cwe="CWE-755",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJS-005",
        name="async/await sem try/catch",
        description="Função async sem tratamento de erros. Exceções em funções async se tornam Promises rejeitadas — sem try/catch ficam silenciosas.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVASCRIPT,
        pattern=r'\basync\s+function\s+\w+|\b\w+\s*=\s*async\s+\(',
        negative_pattern=r'try\s*\{',
        remediation="Envolva o corpo de funções async em try/catch: async function f() { try { await ... } catch(e) { handle(e); } }",
        cwe="CWE-755",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJS-006",
        name="Callback Hell (Pirâmide da Destruição)",
        description="Múltiplos callbacks aninhados (3+ níveis). Torna código difícil de ler, testar e tratar erros. Anti-pattern clássico pré-Promise/async-await.",
        severity=Severity.MEDIUM,
        category=VulnCategory.COMPLEXITY,
        language=Language.JAVASCRIPT,
        pattern=r'function\s*\([^)]*\)\s*\{[^{}]*function\s*\([^)]*\)\s*\{[^{}]*function\s*\([^)]*\)\s*\{',
        remediation="Refatore para async/await ou encadeamento de Promises. Use Promise.all() para operações paralelas.",
        cwe="CWE-1121",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJS-007",
        name="Mutação de Parâmetro de Função",
        description="Modificar parâmetros de função cria efeitos colaterais ocultos. Se o chamador não espera a modificação, pode resultar em bugs difíceis de rastrear.",
        severity=Severity.MEDIUM,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'function\s+\w+\s*\(\s*(\w+)[^)]*\)\s*\{[^}]*\1\s*\.\s*\w+\s*=',
        remediation="Não mute parâmetros. Crie uma cópia: const localCopy = { ...param }. Para arrays: const localArr = [...arr];",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJS-008",
        name="setTimeout/setInterval com Zero Delay (Anti-pattern)",
        description="setTimeout(fn, 0) não executa 'imediatamente' — agenda para o próximo tick do event loop. Frequentemente usado como workaround para bugs de timing e indica design problemático.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'(?:setTimeout|setInterval)\s*\([^,]+,\s*0\s*\)',
        remediation="Use queueMicrotask(), Promise.resolve().then(), ou requestAnimationFrame() dependendo do caso de uso. Se for para detectar mudanças, considere MutationObserver.",
        cwe="CWE-362",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJS-009",
        name="Uso de alert/confirm/prompt em Código de Produção",
        description="alert(), confirm() e prompt() bloqueiam a thread principal do browser, não podem ser estilizados e são considerados UX antiquada.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.JAVASCRIPT,
        pattern=r'\b(?:alert|confirm|prompt)\s*\(',
        remediation="Use componentes modais/dialog do framework UI utilizado (Material UI, Tailwind, Bootstrap, etc.) ou Web Components customizados.",
        cwe="CWE-1041",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="QJS-010",
        name="Acesso Direto ao DOM em Componente de Framework",
        description="Manipulação direta do DOM via document.getElementById em componentes React/Vue/Angular. Bypassa o virtual DOM, causando inconsistências de estado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ARCHITECTURE,
        language=Language.JAVASCRIPT,
        pattern=r'document\.(?:getElementById|querySelector|getElementsBy)',
        negative_pattern=r'(?://|#)',
        remediation="Use refs (React: useRef, Vue: ref, Angular: @ViewChild) para acesso ao DOM. Deixe o framework gerenciar o DOM.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJS-011",
        name="JSON.parse() sem try/catch",
        description="JSON.parse() lança SyntaxError se o input não for JSON válido. Sem tratamento de erro, a aplicação crasha ao processar dados externos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.JAVASCRIPT,
        pattern=r'JSON\.parse\s*\(',
        negative_pattern=r'try\s*\{',
        remediation="Envolva em try/catch: try { const data = JSON.parse(input); } catch(e) { /* tratar JSON inválido */ }",
        cwe="CWE-755",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJS-012",
        name="Uso de document.cookie para Dados Sensíveis",
        description="Armazenar dados sensíveis via document.cookie em JavaScript expõe os dados a XSS. Cookies de autenticação devem ser HttpOnly (inacessíveis via JS).",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.JAVASCRIPT,
        pattern=r'document\.cookie\s*=',
        remediation="Cookies de autenticação devem ser definidos pelo servidor com HttpOnly=true, Secure=true, SameSite=Strict. JS não deve ler ou escrever tokens de auth.",
        cwe="CWE-315",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJS-013",
        name="Operador Non-null Assertion sem Verificação (TypeScript)",
        description="O operador ! (non-null assertion) diz ao TypeScript para ignorar verificação de null/undefined. Se o valor for null em runtime, ocorre TypeError.",
        severity=Severity.LOW,
        category=VulnCategory.CODE_QUALITY,
        language=Language.TYPESCRIPT,
        pattern=r'\w+!\.\w+|\w+!\s*\(',
        remediation="Faça verificação explícita: if (value) { value.method() } ou use optional chaining: value?.method(). O ! é um sinal de alerta.",
        cwe="CWE-476",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="QJS-014",
        name="require() dentro de Função (Import Dinâmico Síncrono)",
        description="require() dentro de função é síncrono e pode causar bloqueio de I/O e dificulta tree-shaking. Modulos devem ser importados no topo do arquivo.",
        severity=Severity.LOW,
        category=VulnCategory.PERFORMANCE,
        language=Language.JAVASCRIPT,
        pattern=r'(?:const|let|var)\s+\w+\s*=\s*require\s*\(',
        negative_pattern=r'^\s*(?:const|let|var)',
        remediation="Mova imports para o topo do arquivo. Se lazy loading for necessário, use import() dinâmico assíncrono: const mod = await import('./module');",
        cwe="CWE-400",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="QJS-015",
        name="Número de Versão Hardcoded em Código Fonte",
        description="Número de versão hardcoded em código-fonte (não em package.json). Cria inconsistências quando a versão é atualizada e o código não.",
        severity=Severity.INFO,
        category=VulnCategory.MAINTAINABILITY,
        language=Language.JAVASCRIPT,
        pattern=r'(?:version|VERSION|appVersion)\s*[=:]\s*["\'][0-9]+\.[0-9]+(?:\.[0-9]+)?["\']',
        remediation="Use process.env.npm_package_version ou importe do package.json: import { version } from './package.json'.",
        cwe="CWE-1109",
        confidence=Confidence.MEDIUM,
    ),
]
