"""Regras de segurança para a linguagem R."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

R_RULES: list[Rule] = [
    Rule(
        id="R-001",
        name="eval(parse()) — Execução de Código R Arbitrário",
        description="eval(parse(text = x)) executa qualquer string como código R. Se x contém input do usuário ou dados externos, permite execução de código arbitrário no servidor R / RShiny.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.R,
        pattern=r'\beval\s*\(\s*parse\s*\(',
        remediation="Evite eval/parse completamente. Use match.arg() para parâmetros de opções limitadas. Use funções específicas em vez de código dinâmico.",
        cwe="CWE-94",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-002",
        name="system() / system2() — Command Injection via R",
        description="system() e system2() executam comandos shell. Com input de usuário não sanitizado, permitem command injection diretamente do código R.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.R,
        pattern=r'\bsystem(?:2)?\s*\(',
        remediation="Evite system() com dados externos. Valide e sanitize rigorosamente qualquer input. Use funções R nativas em vez de comandos shell quando possível.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-003",
        name="Credencial Hardcoded em Script R",
        description="Senhas, tokens de API e chaves hardcoded em scripts R ficam expostos em repositórios de código e em logs de ambientes Jupyter/RMarkdown.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.R,
        pattern=r'(?:password|passwd|secret|api_key|token|apikey)\s*(?:<-|=)\s*["\'][^"\']{6,}["\']',
        remediation="Use Sys.getenv(\"DB_PASSWORD\") para credenciais via variável de ambiente. Use o pacote keyring para armazenamento seguro local. Nunca commite credenciais.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-004",
        name="httr / curl sem Verificação de Certificado SSL",
        description="ssl_verifypeer = FALSE ou verify = FALSE em requisições httr/curl desabilita verificação TLS, tornando o R vulnerável a ataques MITM ao comunicar com APIs.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.R,
        pattern=r'ssl_verifypeer\s*=\s*FALSE|ssl\.verifypeer\s*=\s*FALSE|verify\s*=\s*FALSE',
        remediation="Remova essas opções em produção. Configure certificados CA corretamente. Para servidores com certificados auto-assinados, instale o certificado raiz adequado.",
        cwe="CWE-295",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-005",
        name="options(warn = -1) — Supressão Global de Warnings",
        description="options(warn = -1) suprime todos os warnings globalmente. Warnings em R frequentemente indicam problemas de segurança (conversões silenciosas, valores NA em cálculos críticos).",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.R,
        pattern=r'options\s*\(\s*warn\s*=\s*-1\s*\)',
        remediation="Trate warnings específicos com tryCatch ou withCallingHandlers. Nunca suprima warnings globalmente em produção.",
        cwe="CWE-390",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-006",
        name="readRDS / load() com Arquivo Externo Não Confiável",
        description="readRDS() e load() desserializam objetos R arbitrários. Arquivos .rds/.RData maliciosos podem conter código R que executa durante a desserialização.",
        severity=Severity.HIGH,
        category=VulnCategory.INSECURE_DESER,
        language=Language.R,
        pattern=r'\b(?:readRDS|load)\s*\(\s*(?:file\s*=\s*)?(?:input|upload|request|params)',
        remediation="Nunca desserialize objetos RDS de fontes não confiáveis. Para dados externos, use formatos estruturados (CSV, JSON) com validação de schema.",
        cwe="CWE-502",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="R-007",
        name="Saída de Dados Sensíveis via print() / cat() em Shiny",
        description="print() e cat() em aplicações Shiny com dados sensíveis expõem informações em logs do servidor e console, acessíveis a administradores e possivelmente a usuários com acesso a logs.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.R,
        pattern=r'(?:print|cat)\s*\([^)]*(?:password|token|secret|key|credential)',
        remediation="Remova outputs com dados sensíveis. Use logging framework com níveis (logger::log_debug em vez de print). Configure níveis de log por ambiente.",
        cwe="CWE-532",
        confidence=Confidence.HIGH,
    ),
]
