"""Regras de segurança para React Native — 9 regras (RN-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

REACT_NATIVE_RULES: list[Rule] = [
    Rule(
        id="RN-001",
        name="AsyncStorage com Dados Sensíveis",
        description="AsyncStorage em React Native armazena dados em texto claro no filesystem do dispositivo (não criptografado). Senhas, tokens de sessão, dados pessoais e números de cartão armazenados no AsyncStorage são acessíveis a apps maliciosos em dispositivos com root/jailbreak e em backups não criptografados.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.JAVASCRIPT,
        pattern=r"AsyncStorage\s*\.\s*setItem\s*\(\s*['\"][^'\"]*(?:password|token|secret|auth|key|credential|card|ssn)[^'\"]*['\"]",
        remediation="Use react-native-keychain ou Secure Storage para dados sensíveis: Keychain.setGenericPassword('username', password, {service: 'myapp'}). Para iOS usa Keychain Services, Android usa Keystore. Nunca armazene tokens ou senhas no AsyncStorage. Para preferências não sensíveis, AsyncStorage é aceitável.",
        cwe="CWE-312",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="RN-002",
        name="WebView com javaScriptEnabled e Conteúdo Externo",
        description="<WebView javaScriptEnabled={true} source={{uri: userUrl}}> ou com conteúdo HTML de fonte não confiável permite XSS no contexto do app React Native. Em React Native, XSS em WebViews pode acessar bridges nativas (React Native Bridge) se não configurado adequadamente.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.JAVASCRIPT,
        pattern=r'WebView\s[^>]*javaScriptEnabled\s*=\s*\{?\s*true\s*\}?[^>]*source\s*=\s*\{\{?\s*uri',
        remediation="Use javaScriptEnabled={false} para conteúdo estático. Para conteúdo dinâmico confiável, configure allowingReadAccessToURL e originsWhitelist. Habilite isolatedWorld: <WebView javaScriptEnabled={true} webviewDebuggingEnabled={false} injectedJavaScriptBeforeContentLoaded='...' />. Use react-native-webview v13+.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="RN-003",
        name="Linking.openURL sem Validação de Scheme",
        description="Linking.openURL(url) com URL derivada de dados externos (parâmetros de deep link, dados do servidor) pode abrir apps maliciosos via custom schemes, navegar para URLs phishing ou executar javascript: em versões antigas do iOS. URLs com schemes como file://, data: ou javascript: são perigosas.",
        severity=Severity.HIGH,
        category=VulnCategory.OPEN_REDIRECT,
        language=Language.JAVASCRIPT,
        pattern=r'Linking\s*\.\s*openURL\s*\(\s*(?!(?:["\']https?://|["\']tel:|["\']mailto:))',
        remediation="Valide schemes antes de abrir: const ALLOWED_SCHEMES = ['https:', 'http:', 'tel:', 'mailto:']; const parsed = new URL(url); if (ALLOWED_SCHEMES.includes(parsed.protocol)) { Linking.openURL(url); }. Para deep links internos, use navegação interna em vez de Linking.openURL.",
        cwe="CWE-601",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RN-004",
        name="API Key Hardcoded em Código React Native",
        description="API keys, tokens e secrets hardcoded em código React Native são facilmente extraíveis. O bundle JavaScript pode ser extraído com ferramentas como react-native-decompiler ou simplesmente lendo o arquivo bundle dentro do APK/IPA. Não há obfuscação efetiva para secrets em bundles React Native.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.JAVASCRIPT,
        pattern=r"(?:API_KEY|STRIPE_KEY|FIREBASE_KEY|SECRET_KEY|ACCESS_TOKEN|AUTH_TOKEN)\s*[:=]\s*['\"][A-Za-z0-9+/=_\-]{16,}['\"]",
        remediation="Nunca coloque secrets no código React Native ou arquivos .env bundlados. Use APIs de backend como proxy: o app chama sua API, que chama a API de terceiro com a key. Para configuration, use CodePush configs ou Firebase Remote Config. Secrets no bundle são equivalentes a secrets públicos.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RN-005",
        name="console.log com Dados Sensíveis em Produção",
        description="console.log() em código React Native aparece em adb logcat (Android) e Console do Xcode (iOS). Em produção, logs são acessíveis a outros apps com READ_LOGS permission (Android) e a qualquer pessoa com o device conectado. Tokens, dados de usuário e erros detalhados em logs são riscos.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.JAVASCRIPT,
        pattern=r"console\s*\.\s*log\s*\([^)]*(?:password|token|secret|key|auth|credential)[^)]*\)",
        remediation="Remova console.log em produção ou use um logger que desabilita em prod: if (__DEV__) console.log(). Use bibliotecas como react-native-logs que desabilitam em release. Configure ProGuard/R8 para remover calls de console em builds Android. Use o plugin babel-plugin-transform-remove-console.",
        cwe="CWE-532",
        owasp="A09:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="RN-006",
        name="allowFileAccess em WebView — Acesso ao Filesystem",
        description="<WebView allowFileAccess={true}> permite que a WebView leia arquivos do dispositivo via file:// URLs. Se a WebView também carrega conteúdo externo ou tem JavaScript habilitado, isso pode ser explorado para leitura de arquivos locais: file:///data/data/com.app/databases/userdata.db.",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.JAVASCRIPT,
        pattern=r'allowFileAccess\s*=\s*\{?\s*true\s*\}?',
        remediation="Defina allowFileAccess={false} (padrão). Se acesso a arquivos locais é necessário, use react-native-fs para ler o arquivo e passar o conteúdo para a WebView via injectJavaScript ou props, sem expor o filesystem diretamente. Nunca combine allowFileAccess com conteúdo web externo.",
        cwe="CWE-73",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RN-007",
        name="__DEV__ check Ausente em Código de Debug",
        description="Código de debug, endpoints de teste ou configurações inseguras sem verificação de '__DEV__' podem ser incluídos em builds de produção. React Native não remove automaticamente código de debug — o desenvolvedor deve verificar __DEV__ explicitamente ou usar configurações de build.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JAVASCRIPT,
        pattern=r'(?:debugger|DevMenu|reactDevTools|flipper)',
        negative_pattern=r'__DEV__|process\.env\.NODE_ENV',
        remediation="Sempre guard código de debug: if (__DEV__) { enableDebugFeatures(); }. Use babel-plugin-transform-remove-debugger para produção. Configure flavors de build Android ou schemes iOS para diferentes configurações. Verifique com: npx react-native bundle --dev false.",
        cwe="CWE-94",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RN-008",
        name="Uso Inseguro do NativeModules Sem Verificação de Plataforma",
        description="NativeModules que executam código nativo específico de plataforma sem verificação de Platform.OS podem causar crashes ou comportamento inseguro quando executados na plataforma errada. Alguns módulos nativos têm superfícies de ataque diferentes em iOS e Android.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.JAVASCRIPT,
        pattern=r'NativeModules\.\w+(?!\s*&&|\s*\?|\s*=)',
        negative_pattern=r'Platform\.OS|Platform\.select',
        remediation="Verifique a plataforma antes de usar NativeModules específicos: if (Platform.OS === 'android') { NativeModules.AndroidSpecific.doSomething(); }. Use Platform.select para configurações: const config = Platform.select({ ios: iosConfig, android: androidConfig, default: defaultConfig });",
        cwe="CWE-20",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RN-009",
        name="Deep Link sem Validação do Payload",
        description="Handlers de deep link (Linking.addEventListener ou getInitialURL) que processam parâmetros da URL sem validação permitem que apps maliciosos disparem ações no app. Um deep link myapp://transfer?amount=1000&to=attacker pode executar transferências se os parâmetros não forem validados.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.JAVASCRIPT,
        pattern=r'Linking\s*\.\s*(?:addEventListener|getInitialURL)\s*\(',
        negative_pattern=r'validate|sanitize|schema|zod|joi',
        remediation="Valide e sanitize todos os parâmetros de deep link: use uma biblioteca de validação de schema (Zod, Joi) para verificar tipos e valores. Implemente confirmação do usuário para ações críticas iniciadas via deep link. Nunca execute ações financeiras ou destrutivas diretamente de deep link params.",
        cwe="CWE-20",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
]
