import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

RUBY_RULES: list[Rule] = [
    Rule(
        id="RB-001",
        name="eval() / instance_eval() Code Injection",
        description="Ruby eval() and instance_eval() execute arbitrary code from strings. User-controlled input leads to RCE.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.RUBY,
        pattern=r'\b(?:eval|instance_eval|class_eval|module_eval)\s*\(',
        remediation="Replace dynamic eval with explicit logic or use a safe expression evaluator.",
        cwe="CWE-95",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-002",
        name="Command Injection via system/exec/backtick",
        description="Ruby system(), exec(), Kernel.`, %x{} with user input enable command injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.RUBY,
        pattern=r'\b(?:system|exec|spawn|IO\.popen|Open3\.popen)\s*\(',
        remediation="Use array form: system('cmd', arg1, arg2). Validate all inputs. Use Shellwords.escape() if shell is unavoidable.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="RB-003",
        name="Command Injection via Backtick Operator",
        description="The backtick operator executes shell commands. Interpolated user values enable command injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.RUBY,
        pattern=r'`[^`]*#\{',
        remediation="Avoid backtick interpolation. Use Open3.capture2 with an argument array instead.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-004",
        name="SQL Injection via String Interpolation",
        description="ActiveRecord or raw SQL queries with Ruby string interpolation (#{ }) are vulnerable to SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.RUBY,
        pattern=r'(?:where|find_by_sql|execute|select_all|connection\.exec)\s*\(["\'][^"\']*#\{',
        remediation="Use parameterized queries: User.where('name = ?', name) or User.where(name: name). Never interpolate into SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-005",
        name="Unsafe YAML Deserialization",
        description="YAML.load() with untrusted data enables arbitrary Ruby object deserialization and code execution via Psych gadgets.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.RUBY,
        pattern=r'\bYAML\.load\s*\(',
        negative_pattern=r'permitted_classes|safe_load',
        remediation="Use YAML.safe_load() which only deserializes basic types. Never use YAML.load() with untrusted data.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-006",
        name="Insecure Deserialization via Marshal.load()",
        description="Marshal.load() with attacker-controlled data can execute arbitrary Ruby code.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.RUBY,
        pattern=r'\bMarshal\.(?:load|restore)\s*\(',
        remediation="Use JSON for serialization. Never deserialize Marshal data from untrusted sources.",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-007",
        name="Mass Assignment Vulnerability",
        description="Using params directly in ActiveRecord create/update without strong parameters allows attackers to set protected attributes.",
        severity=Severity.HIGH,
        category=VulnCategory.MASS_ASSIGNMENT,
        language=Language.RUBY,
        pattern=r'\b(?:create|update|update_attributes|new)\s*\(\s*params\[',
        remediation="Use strong parameters: params.require(:user).permit(:name, :email). Never pass params directly.",
        cwe="CWE-915",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-008",
        name="send() with User Input (Method Injection)",
        description="Calling Object#send with user-controlled method names allows invoking any method, including private ones.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.RUBY,
        pattern=r'\.send\s*\(\s*(?:params|request|input)',
        remediation="Use an explicit allowlist of permitted method names before calling send().",
        cwe="CWE-749",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-009",
        name="Path Traversal via File Access",
        description="File operations with user-controlled path segments enable directory traversal attacks.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.RUBY,
        pattern=r'(?:File\.read|File\.open|IO\.read|File\.new)\s*\([^)]*(?:params|request)',
        remediation="Use File.expand_path() and validate the result is within the allowed base directory.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RB-010",
        name="Kernel#open with User Input (Command Injection)",
        description="Kernel#open (or just open()) prefixed with | executes a shell command. User-controlled strings can inject commands.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.RUBY,
        pattern=r'\bopen\s*\(\s*["\']?\s*\||\bopen\s*\([^)]*#\{',
        remediation="Use URI.open() from 'open-uri' for HTTP. Use File.open() for files. Never pass pipes to Kernel#open.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
]
