"""Regras de segurança para Rust."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

RUST_RULES: list[Rule] = [
    Rule(
        id="RS-001",
        name="Bloco unsafe — Bypass do Sistema de Segurança do Rust",
        description="Uso de unsafe { } desabilita as garantias de segurança de memória do Rust. Código unsafe pode conter use-after-free, dereferência de ponteiro nulo, data races e acessos fora de bounds.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.RUST,
        pattern=r'\bunsafe\s*\{',
        remediation="Minimize e documente cada unsafe. Use abstrações seguras (Vec, Box, Arc) sempre que possível. Revise todo bloco unsafe com foco em invariantes explícitas.",
        cwe="CWE-676",
    ),
    Rule(
        id="RS-002",
        name=".unwrap() — Panic em Produção",
        description="unwrap() em produção causa panic (crash da thread) ao encontrar None/Err. Erros esperáveis devem ser tratados com ?, match, ou unwrap_or.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.RUST,
        pattern=r'\.unwrap\s*\(\s*\)',
        remediation="Substitua por propagação de erro com ?, ou use unwrap_or, unwrap_or_else, ou map_err. Em testes, .unwrap() é aceitável.",
        cwe="CWE-390",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="RS-003",
        name=".expect() sem Contexto Diagnóstico",
        description="expect() com mensagem genérica dificulta diagnóstico. Ao fazer panic, a mensagem deve explicar qual invariante foi violada e por quê.",
        severity=Severity.LOW,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.RUST,
        pattern=r'\.expect\s*\(\s*"[^"]{0,10}"\s*\)',
        remediation="Use mensagens descritivas: .expect(\"Falha ao abrir arquivo de configuração /etc/app.conf\"). Melhor ainda: trate o erro com ? e retorne Result.",
        cwe="CWE-390",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RS-004",
        name="std::mem::transmute — Reinterpretação Insegura de Memória",
        description="transmute reinterpreta os bytes de um tipo como outro sem conversão. Pode criar referências inválidas, violar aliasing rules e causar comportamento indefinido.",
        severity=Severity.CRITICAL,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.RUST,
        pattern=r'\btransmute\s*(?:::<[^>]*>)?\s*\(',
        remediation="Use conversões explícitas e seguras: From/Into, TryFrom/TryInto, ou as para números. Justifique cada transmute com comentário extenso sobre invariantes.",
        cwe="CWE-704",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RS-005",
        name="std::process::Command com Entrada do Usuário",
        description="Construção de comando shell com dados não sanitizados do usuário. Mesmo sem shell=true, argumentos arbitrários podem causar command injection dependendo do programa chamado.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.RUST,
        pattern=r'Command::new\s*\(|\.arg\s*\(\s*(?:&?\w+|format!)',
        remediation="Valide e sanitize todos os inputs antes de passar como argumento. Use uma allowlist de valores permitidos. Evite passar input do usuário diretamente como argumento.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RS-006",
        name="Aritmética sem Checagem (Overflow Silencioso em Release)",
        description="Em Rust release builds, overflow aritmético em inteiros é wrapping (silencioso). Operações como soma, subtração e multiplicação podem transbordar sem panic.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.RUST,
        pattern=r'\b(?:i8|i16|i32|i64|i128|u8|u16|u32|u64|u128|isize|usize)\s+\w+\s*=\s*.+[+\-\*]',
        remediation="Use métodos checked_add(), checked_sub(), checked_mul() para operações críticas. Ou saturating_add() para saturação. Configure overflow-checks = true no Cargo.toml para profiles de release.",
        cwe="CWE-190",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RS-007",
        name="Uso de from_utf8_unchecked — Bypass de Validação UTF-8",
        description="from_utf8_unchecked assume que os bytes são UTF-8 válido sem verificação. Bytes inválidos causam comportamento indefinido ao serem processados como str.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.RUST,
        pattern=r'\bfrom_utf8_unchecked\s*\(',
        remediation="Use from_utf8() que retorna Result e valida os bytes. Se a performance é crítica, garanta por contrato (e documente) que os bytes são sempre UTF-8 válido.",
        cwe="CWE-20",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RS-008",
        name="Panic em Código de Biblioteca",
        description="panic! ou unreachable! em bibliotecas (não binários) é antiético: força o caller a crashar sem possibilidade de tratamento. Bibliotecas devem retornar Result/Option.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.RUST,
        pattern=r'\bpanic!\s*\(|\bunreachable!\s*\(',
        remediation="Retorne Result<T, E> com erros descritivos. Use thiserror ou anyhow para definir tipos de erro ergonômicos. Reserve panic! para invariantes verdadeiramente impossíveis.",
        cwe="CWE-390",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="RS-009",
        name="Hardcoded Secret em Código Rust",
        description="Credencial, token ou chave privada hardcoded no código fonte. Em Rust, constantes são compiladas no binário e extraíveis por engenharia reversa.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.RUST,
        pattern=r'(?:const|let)\s+\w*(?:KEY|SECRET|PASSWORD|TOKEN|API_KEY|PASSWD)\w*\s*(?::\s*&str\s*)?=\s*"[^"]{8,}"',
        remediation="Use variáveis de ambiente com std::env::var(). Para segredos em produção, use Vault, AWS Secrets Manager ou equivalente.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="RS-010",
        name="Ponteiro Raw Desreferenciado em Unsafe",
        description="Desreferência de ponteiro raw (*const T ou *mut T) é undefined behavior se o ponteiro é nulo, dangling, ou não alinhado.",
        severity=Severity.CRITICAL,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.RUST,
        pattern=r'\*(?:const|mut)\s+\w+|\bderef\s*\(\s*\)',
        remediation="Use referências (&T, &mut T) sempre que possível. Se ponteiros raw são necessários, valide alinhamento e validade antes da desreferência. Documente invariantes.",
        cwe="CWE-476",
        confidence=Confidence.MEDIUM,
    ),
]
