"""Regras de segurança para SAS (Statistical Analysis System)."""
import re

from analyzer.models import Confidence, Language, Severity, VulnCategory
from analyzer.rules.base import Rule

SAS_RULES: list[Rule] = [
    Rule(
        id="SAS-001",
        name="%SYSEXEC / X Statement — Command Injection",
        description="%SYSEXEC e a instrução X executam comandos diretamente no shell do sistema operacional. Se o comando incorporar uma macro-variável com dado externo, um atacante pode injetar comandos arbitrários no servidor SAS.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.SAS,
        pattern=r'(?:%sysexec\b|^\s*x\s+["\']?\S)',
        remediation="Evite %SYSEXEC/X com dados externos ou macro-variáveis não confiáveis. Restrinja XCMD no SAS Server (OPTIONS NOXCMD;) em ambientes multiusuário.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SAS-002",
        name="CALL SYSTEM — Command Injection",
        description="A função CALL SYSTEM() executa um comando do sistema operacional a partir de um DATA step. Concatenar valores de variáveis de dados nesse comando permite command injection.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.SAS,
        pattern=r'\bcall\s+system\s*\(',
        remediation="Não construa comandos de sistema a partir de dados de entrada. Valide e faça allow-list de qualquer valor usado.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SAS-003",
        name="Credencial Hardcoded em Script SAS",
        description="Senhas e credenciais de conexão (LIBNAME/PROC SQL CONNECT) hardcoded em scripts SAS ficam expostas em repositórios de código, logs de execução e catálogos compartilhados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SAS,
        pattern=r'(?:password|pwd|pass)\s*=\s*["\'][^"\']{3,}["\']',
        remediation="Use PROC PWENCODE para ofuscar senhas em scripts, ou melhor, externalize credenciais via variáveis de ambiente do SAS Metadata Server / autenticação integrada (Kerberos/Trusted).",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
        negative_pattern=r'\{sas\d{3}\}|encoded',
    ),
    Rule(
        id="SAS-004",
        name="PROC SQL com Concatenação Dinâmica (SQL Injection)",
        description="Construção de instruções PROC SQL via CALL EXECUTE ou macro-variáveis concatenando input externo diretamente na query permite SQL injection contra a fonte de dados subjacente.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.SAS,
        pattern=r'call\s+execute\s*\(\s*[\'"]?\s*proc\s+sql',
        remediation="Use PROC SQL com parâmetros de macro validados (allow-list) ou passe valores via PROC FCMP/hash lookups em vez de concatenar strings SQL diretamente.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SAS-005",
        name="LIBNAME apontando para Caminho Externo Não Validado",
        description="Um LIBNAME construído a partir de uma macro-variável de input externo (ex.: parâmetro de URL, upload de arquivo) sem validação permite path traversal e acesso a arquivos fora do diretório esperado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.SAS,
        pattern=r'libname\s+\w+\s+["\']?&',
        remediation="Valide/normalize o caminho antes de usá-lo em LIBNAME. Restrinja a um diretório base conhecido com allow-list de caracteres.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
