"""Regras de segurança para Scala — 10 regras (SCALA-001..010)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SCALA_RULES: list[Rule] = [
    Rule(
        id="SCALA-001",
        name="Desserialização Java Insegura via ObjectInputStream",
        description="Uso de ObjectInputStream para desserializar dados externos em Scala. Como Scala roda na JVM, herda a vulnerabilidade crítica de desserialização Java: objetos maliciosos podem executar código arbitrário durante a reconstrução, mesmo antes de qualquer validação.",
        severity=Severity.CRITICAL,
        category=VulnCategory.INSECURE_DESER,
        language=Language.SCALA,
        pattern=r'new\s+ObjectInputStream\s*\(',
        remediation="Substitua por formatos seguros: Circe (JSON), uPickle ou protobuf. Se ObjectInputStream for inevitável, implemente um resolveClass que só aceite classes da whitelist: class SafeObjectInputStream extends ObjectInputStream { override def resolveClass = { case c if whitelist.contains(c.getName) => super.resolveClass(c) case c => throw new InvalidClassException(c.getName) } }",
        cwe="CWE-502",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SCALA-002",
        name="Reflexão Dinâmica com Class.forName",
        description="Class.forName() com valor dinâmico em Scala permite carregar e instanciar classes arbitrárias em runtime. Combinado com desserialização ou parâmetros controlados pelo usuário, pode resultar em execução de código remoto ou bypass de controles de segurança.",
        severity=Severity.HIGH,
        category=VulnCategory.CODE_INJECTION,
        language=Language.SCALA,
        pattern=r'Class\.forName\s*\(\s*(?!\")',
        remediation="Use um Map de classes permitidas: val allowed = Map(\"UserService\" -> classOf[UserService]). Nunca construa nomes de classe a partir de input do usuário. Se precisar de plugins dinâmicos, use um classloader isolado com SecurityManager.",
        cwe="CWE-470",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SCALA-003",
        name="Injeção de Comando via scala.sys.process",
        description="Uso do operador ! ou !! de scala.sys.process com strings construídas dinamicamente permite injeção de comandos OS. A API de process do Scala é ergonômica mas perigosa quando recebe input externo não sanitizado.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.SCALA,
        pattern=r'(?:s\"[^\"]*\$[^\"]*\"|[a-zA-Z_]\w*)\s*\.?!{1,2}|Process\s*\(\s*s\"',
        remediation="Use Seq[String] em vez de String para separar comando de argumentos: Seq(\"ls\", \"-la\", userPath).!. Nunca interpole variáveis de usuário em strings de comando. Valide e sanitize todos os parâmetros antes de passar ao processo.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SCALA-004",
        name="Injeção SQL via Interpolação de String em Query JDBC",
        description="Construção de queries SQL usando interpolação de strings Scala (s\"...$var...\") ou concatenação direta. Queries dinâmicas são o vetor mais comum de SQL Injection em aplicações Scala com JDBC puro ou Slick com sql\"...\" literal incorreto.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.SCALA,
        pattern=r'(?:connection|stmt|jdbcTemplate|session)\.(?:execute|query|update|prepareStatement)\s*\(\s*s["\']',
        remediation="Use interpolação segura do Slick: sql\"SELECT * FROM users WHERE id = $userId\".as[User] — o compilador escapa automaticamente. Para JDBC puro: use PreparedStatement com ? e setString/setInt. Nunca use s\"...\" para montar SQL.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SCALA-005",
        name="XXE via SAXParser sem Proteção",
        description="SAXParserFactory.newInstance() sem desabilitar external entity processing permite XML External Entity attacks. Em Scala, como em Java, a JVM processa DTDs por padrão. Pode resultar em SSRF, leitura de arquivos locais e DoS.",
        severity=Severity.HIGH,
        category=VulnCategory.XXE,
        language=Language.SCALA,
        pattern=r'SAXParserFactory\.newInstance\s*\(\s*\)|DocumentBuilderFactory\.newInstance\s*\(\s*\)',
        remediation="Desabilite external entities imediatamente após criar a factory: factory.setFeature(\"http://apache.org/xml/features/disallow-doctype-decl\", true). Para Scala/Akka XML, use Scala XML com XMLLoader customizado que desabilita DTD.",
        cwe="CWE-611",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SCALA-006",
        name="Await.result com Duration.Inf — Future sem Timeout",
        description="Await.result(future, Duration.Inf) bloqueia indefinidamente esperando um Future completar. Em ambiente de produção, uma dependência externa lenta ou travada causa thread starvation no thread pool da aplicação, levando a negação de serviço.",
        severity=Severity.MEDIUM,
        category=VulnCategory.PERFORMANCE,
        language=Language.SCALA,
        pattern=r'Await\.result\s*\([^,]+,\s*Duration\.Inf\b',
        remediation="Defina um timeout explícito: Await.result(future, 30.seconds). Melhor ainda, use Future.recoverWith + akka.pattern.after para timeout não-bloqueante: Future.firstCompletedOf(Seq(myFuture, timeoutFuture)).",
        cwe="CWE-400",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SCALA-007",
        name="Algoritmo Criptográfico Fraco MD5 / SHA-1",
        description="Uso de MessageDigest.getInstance(\"MD5\") ou MessageDigest.getInstance(\"SHA-1\") para hash de senhas ou integridade de dados. MD5 e SHA-1 são criptograficamente quebrados: colisões podem ser geradas em segundos com hardware comum.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.SCALA,
        pattern=r'MessageDigest\.getInstance\s*\(\s*["\'](?:MD5|SHA-1|SHA1)["\']',
        remediation="Para senhas: use BCrypt (com jBCrypt) ou Argon2 (com argon2-jvm). Para integridade/checksum: use SHA-256 ou SHA-3. MessageDigest.getInstance(\"SHA-256\") é o mínimo aceitável para hashes não-senhas.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SCALA-008",
        name="Credencial Hardcoded em Código Scala",
        description="Senha, token ou chave de API definida como literal String no código-fonte Scala. Credentials hardcoded são expostas a todos com acesso ao repositório git, ficam no histórico permanentemente e não podem ser rotacionadas sem um novo deploy.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SCALA,
        pattern=r'(?:val|var|def)\s+\w*(?:password|passwd|secret|apiKey|api_key|token|credential)\w*\s*=\s*["\'][^"\'$\{]{6,}["\']',
        remediation="Use variáveis de ambiente: sys.env.getOrElse(\"DB_PASSWORD\", throw new RuntimeException(\"DB_PASSWORD not set\")). Para produção, use AWS Secrets Manager, HashiCorp Vault ou Kubernetes Secrets com encriptação at-rest.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SCALA-009",
        name="Path Traversal via Source.fromFile com Input do Usuário",
        description="scala.io.Source.fromFile() ou new java.io.File() com caminho construído a partir de input externo. Sem normalização, um atacante passa ../../../etc/passwd para acessar arquivos arbitrários fora do diretório esperado.",
        severity=Severity.HIGH,
        category=VulnCategory.PATH_TRAVERSAL,
        language=Language.SCALA,
        pattern=r'(?:Source\.fromFile|new\s+File)\s*\(\s*(?:request\.|params\.|body\.|args\.|input)',
        remediation="Normalize e valide o caminho: val base = Paths.get(\"/safe/dir\").toRealPath(). val target = base.resolve(userInput).normalize(). require(target.startsWith(base), \"Path traversal detectado\"). Use Apache Commons IO FileUtils.directoryContains para verificação adicional.",
        cwe="CWE-22",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SCALA-010",
        name="Conexão HTTP Não Criptografada em Akka HTTP / Play",
        description="URLs http:// hardcoded em chamadas de cliente HTTP (Akka HTTP, Play WS, sttp) transmitem dados sensíveis em texto puro. Interceptação passiva por qualquer nó de rede intermediário expõe tokens, PII e dados de negócio.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.SCALA,
        pattern=r'(?:ws\.url|Http\(\)\.singleRequest|sttp\.backend|basicRequest\.get)\s*\(\s*["\']http://',
        remediation="Substitua http:// por https:// em todas as URLs de produção. Configure o cliente HTTP para rejeitar certificados inválidos e não seguir redirects de https para http. Em testes, use http://localhost somente.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
]
