import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SHELL_RULES: list[Rule] = [
    Rule(
        id="SH-001",
        name="eval with User Input",
        description="Shell eval with user-controlled variables or arguments allows arbitrary code execution.",
        severity=Severity.CRITICAL,
        category=VulnCategory.CODE_INJECTION,
        language=Language.SHELL,
        pattern=r'\beval\s+',
        remediation="Remove eval. Use explicit variable assignments and command calls instead.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SH-002",
        name="Unquoted Variable in Command",
        description="Unquoted shell variables in command contexts are subject to word splitting and glob expansion, enabling injection.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.SHELL,
        pattern=r'\b(?:rm|chmod|chown|cp|mv|find|xargs)\s+[^"\']*\$[A-Za-z_]\w*(?!\s*["\'])',
        remediation="Quote all variables: \"$VAR\" instead of $VAR. Use shellcheck to detect unquoted variables.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SH-003",
        name="Curl/Wget Piped to Shell (RCE)",
        description="Downloading and executing scripts directly (curl URL | sh) runs arbitrary remote code without verification.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.SHELL,
        pattern=r'(?:curl|wget)\s+[^\|]+\|\s*(?:su?do\s+)?(?:ba)?sh',
        remediation="Download scripts to a file, inspect them, verify their checksum/signature, then execute explicitly.",
        cwe="CWE-494",
        owasp="A08:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SH-004",
        name="Hardcoded Credentials in Shell Script",
        description="Credentials hardcoded in shell scripts are exposed to anyone with read access to the file.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SHELL,
        pattern=r'(?:PASSWORD|PASSWD|API_KEY|SECRET|TOKEN)\s*=\s*["\'][^"\']{3,}["\']',
        remediation="Use environment variables loaded from a secured .env file not tracked in VCS.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SH-005",
        name="rm -rf with Unquoted Variable",
        description="rm -rf with an unquoted or empty variable can delete unintended directories.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SHELL,
        pattern=r'\brm\s+-[rRf]{2,}\s+["\']?/?\$(?!\{[^}]+:-)',
        remediation="Always quote variables: rm -rf \"$DIR\". Check DIR is non-empty before deletion.",
        cwe="CWE-732",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SH-006",
        name="World-Writable File Creation",
        description="chmod 777 or umask 000 creates world-writable files, enabling unauthorized modification.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SHELL,
        pattern=r'\bchmod\s+(?:a\+w|777|0777)',
        remediation="Use the most restrictive permissions necessary. Prefer 644 for files, 755 for directories.",
        cwe="CWE-732",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SH-007",
        name="Insecure use of /tmp for Sensitive Data",
        description="Storing sensitive data in /tmp can be read by any local user on the system.",
        severity=Severity.MEDIUM,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.SHELL,
        pattern=r'(?:password|token|key|secret|credential)\s*>\s*/tmp/',
        remediation="Use mktemp to create private temp files and use a private directory with restricted permissions.",
        cwe="CWE-377",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SH-008",
        name="sudo Without Path Specification",
        description="Running commands via sudo without an absolute path can be exploited through PATH manipulation.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SHELL,
        pattern=r'\bsudo\s+(?!\/)[a-z][a-zA-Z0-9_-]+\b',
        negative_pattern=r'\bsudo\s+(?:/usr/bin/|/bin/|/sbin/)',
        remediation="Use absolute paths in sudo commands. Restrict sudo rules in /etc/sudoers to specific commands.",
        cwe="CWE-426",
        owasp="A01:2021",
        confidence=Confidence.LOW,
    ),
]
