"""
Regras de detecção de violações dos princípios SOLID e anti-patterns de design clássicos.
Baseadas em: Clean Architecture (Martin), Design Patterns (GoF),
Refactoring (Fowler), Agile Software Development (Martin).
"""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SOLID_RULES: list[Rule] = [
    # ── SRP — Princípio da Responsabilidade Única ─────────────────────────────
    Rule(
        id="SLD-001",
        name="Classe com Muitos Métodos Públicos (God Class — SRP)",
        description="Classe com 15+ métodos públicos detectada. God Classes são o anti-pattern mais comum: a classe conhece demais, faz demais e é o ponto central de mudanças. Violação clara do SRP.",
        severity=Severity.MEDIUM,
        category=VulnCategory.GOD_OBJECT,
        language=Language.GENERIC,
        pattern=r'(?:public\s+\w+\s+\w+\s*\([^)]*\)\s*\{[^{}]*\}[\s\n]*){15,}',
        remediation="Identifique as responsabilidades distintas da classe e extraia cada uma para uma classe separada. Aplique Extract Class do catálogo Fowler.",
        cwe="CWE-1093",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="SLD-002",
        name="Classe de Serviço com Nome Genérico (Manager/Helper/Utils — SRP)",
        description="Classes com sufixo Manager, Helper, Utils, Service sem qualificador específico são indicadores de God Objects que agrupam responsabilidades díspares.",
        severity=Severity.LOW,
        category=VulnCategory.SOLID_SRP,
        language=Language.GENERIC,
        pattern=r'\bclass\s+(?:\w+)?(?:Manager|Helper|Utils|Util|Common|Misc|General|Base|Core)(?!\w)',
        remediation="Nomeie classes por responsabilidade específica: EmailSender em vez de MessageHelper. Se a classe não tem nome específico, provavelmente tem responsabilidades demais.",
        cwe="CWE-1093",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="SLD-003",
        name="Método Muito Longo (SRP de Função)",
        description="Método/função com muitas linhas detectado. Viola o princípio de que cada função deve fazer uma única coisa bem. Aumenta complexidade cognitiva e dificulta testes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.COMPLEXITY,
        language=Language.GENERIC,
        pattern=r'(?:def|function|func|void|public|private|protected)\s+\w+\s*\([^)]*\)[^{]*\{[^}]{2000,}\}',
        remediation="Extraia partes do método em funções privadas com nomes descritivos. Métodos ideais cabem em uma tela (20-30 linhas).",
        cwe="CWE-1121",
        confidence=Confidence.LOW,
    ),
    # ── OCP — Princípio Aberto/Fechado ────────────────────────────────────────
    Rule(
        id="SLD-004",
        name="if/else Encadeado para Seleção de Comportamento por Tipo (OCP)",
        description="Série de if/else verificando tipo ou string para selecionar comportamento. Cada novo tipo exige modificar o método existente — viola o OCP. Indica falta de polimorfismo.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SOLID_OCP,
        language=Language.GENERIC,
        pattern=r'if\s*\([^)]*(?:type|kind|category)\s*(?:==|===|\.equals)\s*["\'](?:\w+)["\'][^)]*\)(?:[^{}]*\{[^{}]*\}[^{}]*)+else\s+if',
        remediation="Use polimorfismo, Strategy Pattern, ou Factory Pattern. Adicionar novo tipo = nova classe, sem modificar o método existente.",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    # ── DIP — Princípio de Inversão de Dependência ───────────────────────────
    Rule(
        id="SLD-005",
        name="Instanciação Direta de Dependência no Construtor (DIP)",
        description="Construtor que instancia suas próprias dependências (new Service(), new Repository()) cria acoplamento concreto. Impossibilita substituição para testes ou ambientes diferentes.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SOLID_DIP,
        language=Language.GENERIC,
        pattern=r'(?:constructor|def\s+__init__)\s*\([^)]*\)[^{]*\{[^}]*new\s+\w+(?:Service|Repository|Manager|Client|Provider|Adapter)\s*\(',
        remediation="Injete dependências pelo construtor: constructor(private service: IService). Use um container de DI (Spring, .NET DI, inversify).",
        cwe="CWE-1047",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SLD-006",
        name="Dependência de Módulo de Alto Nível em Implementação Concreta (DIP)",
        description="Import direto de classe de implementação concreta em módulo de alto nível, sem abstração intermediária (interface ou classe abstrata).",
        severity=Severity.MEDIUM,
        category=VulnCategory.SOLID_DIP,
        language=Language.GENERIC,
        pattern=r'import\s+.*(?:ServiceImpl|RepositoryImpl|DAOImpl|DaoImpl)\b',
        remediation="Importe a interface: import UserService, não UserServiceImpl. Módulos de alto nível não devem conhecer detalhes de implementação.",
        cwe="CWE-1047",
        confidence=Confidence.HIGH,
    ),
    # ── Obsessão por Primitivos ───────────────────────────────────────────────
    Rule(
        id="SLD-007",
        name="Obsessão por Primitivos (Primitive Obsession)",
        description="Múltiplos parâmetros primitivos que representam o mesmo conceito (cpf: String, telefone: String, cep: String) em vez de Value Objects. Dificulta validação, comportamento e semântica.",
        severity=Severity.LOW,
        category=VulnCategory.PRIMITIVE_OBSESSION,
        language=Language.GENERIC,
        pattern=r'(?:def|function|func)\s+\w+\s*\(\s*\w+:\s*(?:string|str|String)\s*,\s*\w+:\s*(?:string|str|String)\s*,\s*\w+:\s*(?:string|str|String)\s*,\s*\w+:\s*(?:string|str|String)',
        remediation="Agrupe primitivos relacionados em Value Objects: Address(street, city, zipCode) em vez de 4 strings separadas. Value Objects adicionam validação e semântica.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    # ── Singleton ─────────────────────────────────────────────────────────────
    Rule(
        id="SLD-008",
        name="Singleton Pattern (Estado Global Oculto)",
        description="O padrão Singleton cria estado global, torna testes impossíveis sem reflection/hacks, e cria acoplamento oculto entre módulos. É o anti-pattern mais abusado do GoF.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ANTI_PATTERN,
        language=Language.GENERIC,
        pattern=r'(?:private|protected)\s+static\s+\w+\s+instance\s*[=;]|getInstance\s*\(\s*\)',
        remediation="Use injeção de dependência com escopo singleton no container de DI. O container garante instância única sem tornar o objeto um Singleton explícito.",
        cwe="CWE-1108",
        confidence=Confidence.MEDIUM,
    ),
    # ── Data Class / Anemic Domain Model ─────────────────────────────────────
    Rule(
        id="SLD-009",
        name="Modelo de Domínio Anêmico (Apenas Getters/Setters)",
        description="Classe com apenas getters e setters sem nenhum comportamento de domínio. Viola OOP ao separar dados de comportamento — todo o comportamento acaba em Services, o que é procedural disfarçado de OO.",
        severity=Severity.LOW,
        category=VulnCategory.ANTI_PATTERN,
        language=Language.GENERIC,
        pattern=r'(?:public\s+\w+\s+get\w+\s*\(\s*\)|private\s+\w+\s+\w+\s*;\s*public\s+void\s+set\w+)',
        remediation="Adicione comportamento ao modelo de domínio. Em vez de pedido.setStatus('APROVADO'), use pedido.aprovar(). Entidades devem encapsular regras de negócio.",
        cwe="CWE-1093",
        confidence=Confidence.LOW,
    ),
    # ── Shotgun Surgery ───────────────────────────────────────────────────────
    Rule(
        id="SLD-010",
        name="Mudança Espalhada em Múltiplos Arquivos (Shotgun Surgery)",
        description="Padrão de múltiplos imports do mesmo módulo em arquivos distintos indica que uma mudança naquele módulo requer alterações espalhadas por todo o codebase.",
        severity=Severity.LOW,
        category=VulnCategory.COUPLING,
        language=Language.GENERIC,
        pattern=r'import\s+.*(?:Constants|Config|GlobalState|SharedState|AppGlobal)',
        remediation="Concentre a dependência em um único local. Use facade ou repositório central. Minimize o número de classes que conhecem detalhes de configuração global.",
        cwe="CWE-1041",
        confidence=Confidence.LOW,
    ),
    # ── LSP ───────────────────────────────────────────────────────────────────
    Rule(
        id="SLD-011",
        name="NotImplementedException em Método de Interface Herdada (LSP)",
        description="Método herdado lançando UnsupportedOperationException ou NotImplementedException. Viola o LSP: subtipos devem ser substituíveis pelos tipos base sem quebrar o contrato.",
        severity=Severity.HIGH,
        category=VulnCategory.SOLID_LSP,
        language=Language.GENERIC,
        pattern=r'throw\s+new\s+(?:UnsupportedOperationException|NotImplementedException|NotSupportedException)\s*\(',
        remediation="Reestruture a hierarquia de herança. Prefira composição sobre herança. Se a subclasse não suporta o comportamento, ela não deveria herdar dessa interface/classe.",
        cwe="CWE-1073",
        confidence=Confidence.HIGH,
    ),
    # ── ISP ───────────────────────────────────────────────────────────────────
    Rule(
        id="SLD-012",
        name="Interface Muito Grande (Interface Segregation)",
        description="Interface com muitos métodos força implementadores a depender de métodos que não usam. Viola o ISP — clientes não devem ser forçados a implementar interfaces que não utilizam.",
        severity=Severity.LOW,
        category=VulnCategory.SOLID_ISP,
        language=Language.GENERIC,
        pattern=r'(?:interface|@protocol|trait)\s+\w+\s*\{(?:\s*\w+[^{}]*\n){12,}',
        remediation="Divida interfaces grandes em interfaces menores e mais focadas. Cada interface deve ter uma única responsabilidade coesa.",
        cwe="CWE-1093",
        confidence=Confidence.LOW,
    ),
]
