"""Regras de segurança para Solidity (smart contracts / blockchain)."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SOLIDITY_RULES: list[Rule] = [
    Rule(
        id="SOL-001",
        name="Reentrância — Ataque Clássico de Smart Contract",
        description="Chamar um contrato externo antes de atualizar o estado interno permite que o contrato chamado re-entre na função e drene fundos repetidamente. O hack do DAO perdeu 60M USD por isso.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'(?:call|send|transfer)\s*\{?[^;]*\}?\s*\([^)]*\)[^;]*;[^}]*(?:balances|_balance|state)\s*\[',
        remediation="Aplique o padrão Checks-Effects-Interactions: 1) valide condições, 2) atualize o estado, 3) chame contratos externos. Use ReentrancyGuard do OpenZeppelin.",
        cwe="CWE-841",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-002",
        name="tx.origin para Autenticação — Phishing Attack",
        description="tx.origin retorna o endereço original da transação (EOA), não o chamador imediato. Um contrato malicioso pode enganar o usuário a enviar uma transação que bypassa checks de tx.origin.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.SOLIDITY,
        pattern=r'\btx\.origin\b',
        remediation="Use msg.sender para autenticação, não tx.origin. tx.origin só é seguro para verificar que a transação originou de um EOA (não um contrato), mas não para controle de acesso.",
        cwe="CWE-807",
        owasp="A07:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SOL-003",
        name="block.timestamp para Aleatoriedade ou Lógica Temporal Crítica",
        description="block.timestamp pode ser manipulado por mineradores/validadores em até ~15 segundos. Usar como fonte de aleatoriedade ou lógica de expiração crítica é explorável.",
        severity=Severity.HIGH,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.SOLIDITY,
        pattern=r'\bblock\.timestamp\b',
        remediation="Para aleatoriedade segura, use Chainlink VRF. Para lógica temporal, use block.number com estimativa de tempo. Documente que manipulação de ~15s é possível.",
        cwe="CWE-330",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-004",
        name="Pragma Flutuante — Versão Solidity Não Fixada",
        description="pragma solidity ^0.8.0 ou >= 0.7.0 permitem compilação com diferentes versões que podem ter bugs diferentes. Contratos em produção devem ter versão exata.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SOLIDITY,
        pattern=r'pragma\s+solidity\s+[^;]*[\^>]',
        remediation="Use versão exata: pragma solidity 0.8.20; Teste exaustivamente com essa versão. Para libraries que devem ser compatíveis, range fechado é aceitável.",
        cwe="CWE-1104",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SOL-005",
        name="Ausência de Controle de Acesso em Função Crítica",
        description="Funções que transferem ETH, alteram ownership, ou modificam parâmetros críticos sem modificador onlyOwner, onlyRole ou equivalente são executáveis por qualquer endereço.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SOLIDITY,
        pattern=r'function\s+(?:withdraw|transfer|mint|burn|setOwner|pause|upgrade)\w*\s*\([^)]*\)\s*(?:public|external)(?!\s+(?:view|pure))',
        negative_pattern=r'(?:onlyOwner|onlyRole|onlyAdmin|require\s*\(|modifier)',
        remediation="Adicione controle de acesso: onlyOwner do Ownable ou AccessControl do OpenZeppelin. Use o princípio de menor privilégio para cada função administrativa.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-006",
        name="Uso de assembly { } — Bypass das Proteções do Solidity",
        description="Blocos assembly em Yul/EVM assembly permitem operações de baixo nível que bypassam verificações de tipo e overflow do Solidity. Alto risco de bugs críticos.",
        severity=Severity.HIGH,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'\bassembly\s*\{',
        remediation="Minimize uso de assembly. Documente cada bloco assembly extensamente. Considere alternativas em Solidity puro. Faça audit formal de qualquer uso de assembly.",
        cwe="CWE-676",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SOL-007",
        name="selfdestruct — Destruição Irreversível do Contrato",
        description="selfdestruct remove o contrato permanentemente e envia todo ETH para um endereço. Se chamável por atacante, causa destruição total do contrato e possível manipulação de contratos que dependem dele.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'\bselfdestruct\s*\(',
        remediation="Evite selfdestruct. Use padrão Upgradeable Proxy com pause() para cenários de emergência. Se necessário, proteja com multisig e timelock.",
        cwe="CWE-284",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SOL-008",
        name="Valor de Retorno de call() Não Verificado",
        description="(bool success, ) = addr.call{value: amount}(\"\") — não verificar o bool success ignora falhas silenciosas. ETH pode ser enviado para contratos que rejeitam transferências.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.SOLIDITY,
        pattern=r'\.call\s*\{[^}]*value[^}]*\}\s*\([^)]*\)\s*;',
        negative_pattern=r'(?:require|revert|assert|bool\s+success|success\s*,)',
        remediation="Sempre verifique o valor de retorno: (bool success, ) = addr.call{value: amount}(\"\"); require(success, \"Transfer failed\");",
        cwe="CWE-252",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-009",
        name="Integer Overflow/Underflow (Solidity < 0.8)",
        description="Em Solidity < 0.8.0, operações aritméticas não verificam overflow/underflow automaticamente. uint256 + 1 pode resultar em 0. SafeMath é necessário.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'\buint(?:256|128|64|32|16|8)?\s+\w+\s*=\s*\w+\s*[+\-\*]',
        negative_pattern=r'(?:SafeMath|using\s+SafeMath|pragma\s+solidity\s+0\.8)',
        remediation="Use Solidity >= 0.8.0 para proteção automática. Para versões antigas, use SafeMath de OpenZeppelin ou checked arithmetic explícito.",
        cwe="CWE-190",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="SOL-010",
        name="Evento Não Emitido em Transferência de Ownership",
        description="Transferência de ownership sem emissão de evento impossibilita rastreamento off-chain. Mudanças críticas de estado devem sempre emitir eventos para auditoria.",
        severity=Severity.MEDIUM,
        category=VulnCategory.LOGGING,
        language=Language.SOLIDITY,
        pattern=r'owner\s*=\s*\w+\s*;',
        negative_pattern=r'emit\s+Ownership',
        remediation="Emita eventos para todas as mudanças de estado críticas: emit OwnershipTransferred(previousOwner, newOwner). Use o padrão Ownable do OpenZeppelin.",
        cwe="CWE-778",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-011",
        name="Dependência de Timestamp para Expiração de Token/NFT",
        description="Usar block.timestamp para expiração de tokens, leilões ou NFTs permite que mineradores manipulem o resultado em leilões onde o timing é crítico.",
        severity=Severity.HIGH,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'block\.timestamp\s*(?:>|<|>=|<=|==)\s*(?:deadline|expiry|expiration|end_time)',
        remediation="Para leilões e lótérias, use Chainlink VRF + block.number. Para expiração de tokens, aceite manipulação de ~15s como tolerável ou use block.number com conversão de tempo.",
        cwe="CWE-330",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SOL-012",
        name="Contrato sem Proteção contra Flash Loan Attack",
        description="Contratos DeFi que calculam preços a partir de balances instantâneos são vulneráveis a manipulação via flash loans — o atacante distorce o preço temporariamente para lucro.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SMART_CONTRACT,
        language=Language.SOLIDITY,
        pattern=r'balance\s*\(\s*address\s*\(\s*this\s*\)\s*\)',
        remediation="Use oráculos de preço resistentes a manipulação (Chainlink, TWAP do Uniswap v3). Não use balances instantâneos para cálculos de preço em contratos DeFi.",
        cwe="CWE-841",
        confidence=Confidence.LOW,
    ),
]
