import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SQL_RULES: list[Rule] = [
    Rule(
        id="SQL-001",
        name="Dynamic SQL via EXEC / EXECUTE",
        description="Executing dynamically built SQL strings (EXEC, EXEC(), EXECUTE) with user-supplied data enables SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.SQL,
        pattern=r'\b(?:EXEC(?:UTE)?)\s*\(\s*@',
        remediation="Use sp_executesql with parameters instead of EXEC with concatenated strings. Validate all inputs.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-002",
        name="Stored Procedure with Dynamic SQL Construction",
        description="Stored procedure builds SQL using SET @sql = '...' + @param pattern, enabling SQL injection.",
        severity=Severity.HIGH,
        category=VulnCategory.SQL_INJECTION,
        language=Language.SQL,
        pattern=r'SET\s+@\w+\s*=\s*(?:N?[\'"]|@\w+)\s*\+',
        remediation="Use sp_executesql with typed parameters: EXEC sp_executesql @sql, N'@id INT', @id = @userInput",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-003",
        name="Excessive Privilege Grant (GRANT ALL)",
        description="GRANT ALL PRIVILEGES gives a database user unrestricted access, violating the principle of least privilege.",
        severity=Severity.MEDIUM,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.SQL,
        pattern=r'\bGRANT\s+ALL\b',
        remediation="Apply least privilege: grant only the specific permissions (SELECT, INSERT, etc.) needed for the application.",
        cwe="CWE-250",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-004",
        name="Commented-Out Password in SQL",
        description="A password value is visible in a SQL comment, exposing credentials.",
        severity=Severity.HIGH,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SQL,
        pattern=r'--.*(?:password|passwd|pwd)\s*=\s*\S+',
        remediation="Remove all credential references from SQL files. Use environment variables or a secrets manager.",
        cwe="CWE-798",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-005",
        name="TRUNCATE TABLE Without Transaction",
        description="TRUNCATE TABLE without a surrounding transaction or in a trigger can irreversibly delete all table data.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r'\bTRUNCATE\s+TABLE\b',
        remediation="Wrap DDL operations in transactions where possible. Use soft deletes for auditable data retention.",
        cwe="CWE-20",
        owasp="A05:2021",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-006",
        name="Unencrypted Password Storage in Schema",
        description="A column named 'password' or 'passwd' defined as plain VARCHAR suggests passwords may be stored in plaintext.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.SQL,
        pattern=r'(?:password|passwd|pwd)\s+(?:VARCHAR|CHAR|TEXT|NVARCHAR)',
        remediation="Store only password hashes (bcrypt, scrypt, argon2). The column should store hash+salt strings (e.g., CHAR(60) for bcrypt).",
        cwe="CWE-256",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="SQL-007",
        name="Missing WHERE Clause in UPDATE/DELETE",
        description="UPDATE or DELETE statement without a WHERE clause modifies all rows, which is often unintentional and catastrophic.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.SQL,
        pattern=r'\b(?:UPDATE\s+\w+\s+SET|DELETE\s+FROM\s+\w+)\s*;',
        remediation="Always include a WHERE clause. Review and test DML statements in a staging environment first.",
        cwe="CWE-20",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
]
