"""Regras de segurança para Swift / iOS."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

SWIFT_RULES: list[Rule] = [
    Rule(
        id="SW-001",
        name="Force Unwrap (!) — Crash em Runtime",
        description="O operador ! força o unwrap de um Optional sem verificação. Se o valor for nil, a aplicação crasha com 'unexpectedly found nil while unwrapping'. Em produção, isso cria instabilidade séria.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.SWIFT,
        pattern=r'(?<!\!)\!(?!\s*=)',
        remediation="Use guard let, if let, ?? (nil coalescing) ou optional chaining (?.). Jamais force-unwrap dados que vêm de input externo, rede ou banco de dados.",
        cwe="CWE-476",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="SW-002",
        name="Force Cast (as!) — Crash por Tipo Incompatível",
        description="Force cast falha com um runtime fatal error se o tipo não for compatível. Em código que processa dados externos ou polimórficos, o tipo pode mudar.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.SWIFT,
        pattern=r'\bas!\s+\w',
        remediation="Use as? para optional cast seguido de guard let / if let. Valide o tipo antes de usar o valor.",
        cwe="CWE-704",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SW-003",
        name="NSLog / print com Dados Sensíveis",
        description="NSLog e print produzem saída no Console.app (Device Logs), acessível a qualquer app com permissão em versões antigas do iOS. Dados sensíveis ficam expostos nos logs.",
        severity=Severity.HIGH,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.SWIFT,
        pattern=r'(?:NSLog|print)\s*\([^)]*(?:password|token|secret|key|credential|auth|PIN|senha)\b',
        remediation="Remova logs com dados sensíveis. Em debug, use #if DEBUG guards. Considere um framework de logging que respeita níveis (os_log com privacidade de dados).",
        cwe="CWE-532",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-004",
        name="URL HTTP sem TLS (ATS Bypass)",
        description="Uso de URL http:// no código Swift. App Transport Security (ATS) bloqueia HTTP por padrão, mas exceções configuradas ou URLs hardcoded bypassam essa proteção.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.SWIFT,
        pattern=r'"http://(?!localhost|127\.0\.0\.1|::1)',
        remediation="Use sempre https://. Se um servidor não suporta TLS, exija a atualização. Não configure NSAllowsArbitraryLoads = true sem justificativa sólida.",
        cwe="CWE-319",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-005",
        name="Hardcoded API Key / Secret em Swift",
        description="Credenciais hardcoded no código fonte iOS são facilmente extraídas do IPA com strings ou análise estática. Qualquer usuário pode obter a chave.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.SWIFT,
        pattern=r'(?:let|var|const)\s+\w*(?:Key|Secret|Token|Password|APIKey|api_key)\w*\s*=\s*"[A-Za-z0-9+/=_\-]{16,}"',
        remediation="Nunca hardcode segredos em apps iOS. Use um servidor de configuração remoto com autenticação, Certificate Pinning, e Keychain para armazenamento local de tokens.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-006",
        name="UserDefaults para Dados Sensíveis",
        description="UserDefaults armazena dados como plist não encriptado. Dados sensíveis (tokens, senhas, PII) são acessíveis em dispositivos jailbroken ou em backups não encriptados.",
        severity=Severity.HIGH,
        category=VulnCategory.SENSITIVE_DATA,
        language=Language.SWIFT,
        pattern=r'UserDefaults\.standard\.set\s*\([^,]+,\s*forKey:\s*"[^"]*(?:token|password|key|secret|auth|credential)',
        remediation="Use Keychain Services para dados sensíveis: kSecClassGenericPassword com kSecAttrAccessibleWhenUnlocked. Considere o framework KeychainSwift para simplificar.",
        cwe="CWE-312",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-007",
        name="MD5 / SHA1 para Hashing de Senha",
        description="MD5 e SHA1 são algoritmos quebrados para criptografia de senha. São rápidos demais para serem seguros — ataques de força bruta são viáveis.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.SWIFT,
        pattern=r'(?:CC_MD5|CC_SHA1|kCCDigestMD5|kCCDigestSHA1)\s*\(',
        remediation="Use bcrypt, scrypt ou PBKDF2 para senhas. Para checksums não-criptográficos use SHA-256+ (CC_SHA256). Use CryptoKit para implementações modernas.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-008",
        name="Certificate Pinning Desabilitado",
        description="Desabilitar SSL pinning ou validação de certificado em URLSession permite ataques Man-in-the-Middle capturando tráfego HTTPS da app.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_AUTH,
        language=Language.SWIFT,
        pattern=r'didReceive\s+challenge.*completionHandler\s*\(\s*\.useCredential',
        remediation="Implemente certificate pinning verificando o certificado do servidor contra um hash conhecido. Use URLSession delegate com validação customizada ou TrustKit.",
        cwe="CWE-295",
        owasp="A07:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="SW-009",
        name="arc4random — Geração Insegura de Números Aleatórios",
        description="arc4random não é CSPRNG (Cryptographically Secure). Não use para geração de tokens, IVs, nonces ou qualquer valor que requer imprevisibilidade criptográfica.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.SWIFT,
        pattern=r'\barc4random(?:_uniform)?\s*\(',
        remediation="Use SecRandomCopyBytes para bytes aleatórios criptograficamente seguros. Para Swift moderno, use SystemRandomNumberGenerator ou CryptoKit.generateSymmetricKey().",
        cwe="CWE-338",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="SW-010",
        name="WebView com JavaScriptEnabled sem Sanitização",
        description="WKWebView com JavaScript habilitado carregando conteúdo não confiável é vulnerável a XSS. Se a app tem acesso a APIs nativas via JavaScript bridge, o impacto é crítico.",
        severity=Severity.HIGH,
        category=VulnCategory.XSS,
        language=Language.SWIFT,
        pattern=r'WKWebView\b|WKUserContentController|addScriptMessageHandler',
        remediation="Carregue apenas conteúdo confiável em WKWebView. Implemente um WKNavigationDelegate que valida URLs antes de carregar. Sanitize qualquer HTML dinâmico.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.LOW,
    ),
]
