"""Regras de segurança para Terraform / HCL."""
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

TERRAFORM_RULES: list[Rule] = [
    Rule(
        id="TF-001",
        name="Security Group Aberto para Todo o Internet (0.0.0.0/0)",
        description="Regra de security group (AWS) ou NSG (Azure) permitindo ingresso de 0.0.0.0/0 expõe o recurso a todo o internet. Qualquer porta aberta para o mundo sem necessidade é uma vulnerabilidade.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'cidr_blocks\s*=\s*\[?\s*"0\.0\.0\.0/0"',
        remediation="Restrinja cidr_blocks ao menor range necessário. Para acesso admin, use VPN ou bastion host. Separe security groups por função (web, app, db).",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-002",
        name="Banco de Dados Publicamente Acessível",
        description="publicly_accessible = true em recursos RDS, Azure SQL ou Cloud SQL expõe o banco de dados diretamente à internet, contornando VPCs e redes privadas.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'publicly_accessible\s*=\s*true',
        remediation="Defina publicly_accessible = false. Acesse o banco apenas via VPC/subnets privadas. Use bastion host ou VPN para acesso de administração.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-003",
        name="Storage / Bucket S3 Público",
        description="ACL público-leitura ou público-leitura-escrita em S3 expõe todos os objetos do bucket. Vazamentos de dados por S3 público são incidentes extremamente comuns.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'acl\s*=\s*"public-(?:read|read-write)"',
        remediation="Use acl = \"private\". Para conteúdo público, use CloudFront como CDN sem expor o S3 diretamente. Habilite aws_s3_bucket_public_access_block com todos os atributos true.",
        cwe="CWE-284",
        owasp="A05:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-004",
        name="Encriptação Desabilitada em Recurso de Armazenamento",
        description="encrypted = false em EBS volumes, RDS, S3 ou equivalentes deixa dados em repouso sem proteção criptográfica, violando requisitos de conformidade (LGPD, GDPR, PCI-DSS).",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.TERRAFORM,
        pattern=r'encrypted\s*=\s*false|storage_encrypted\s*=\s*false',
        remediation="Defina encrypted = true em todos os recursos de armazenamento. Use aws_kms_key ou chaves gerenciadas pelo serviço (SSE-S3 para S3, etc.).",
        cwe="CWE-311",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-005",
        name="IAM Policy com Ações Ilimitadas (Wildcard *)",
        description="Policies IAM com Action: * ou Resource: * concedem permissão para tudo, violando o princípio de menor privilégio. Uma credencial comprometida dá controle total da conta.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.TERRAFORM,
        pattern=r'"Effect"\s*:\s*"Allow"[^}]*"Action"\s*:\s*"\*"',
        remediation="Especifique apenas as ações necessárias: [\"s3:GetObject\", \"s3:PutObject\"]. Use AWS IAM Access Analyzer para identificar e reduzir permissões excessivas.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-006",
        name="Senha Hardcoded em Recurso Terraform",
        description="Senhas de banco de dados, master_password, ou credentials hardcoded em arquivos .tf são commitadas no repositório e ficam expostas em git history e logs de CI/CD.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.TERRAFORM,
        pattern=r'(?:password|master_password|admin_password|db_password)\s*=\s*"[^"${}]{6,}"',
        remediation="Use variáveis Terraform com sensitive = true: var.db_password. Passe via -var ou .tfvars encriptados. Use AWS Secrets Manager com data source aws_secretsmanager_secret.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-007",
        name="Logs / Auditoria Desabilitados",
        description="enable_logging = false, cloudwatch_logs_enabled = false ou equivalente desabilita rastreabilidade de acessos. Requisito de conformidade em PCI-DSS, SOC2 e LGPD.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'(?:enable_logging|logging_enabled|cloudwatch_logs_enabled|audit_log)\s*=\s*false',
        remediation="Habilite logging em todos os recursos críticos. Centralize logs no CloudWatch, Stackdriver ou equivalente. Defina retention policies e alertas em eventos suspeitos.",
        cwe="CWE-778",
        owasp="A09:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TF-008",
        name="Deletion Protection Desabilitada em Banco de Dados",
        description="deletion_protection = false permite que o banco de dados seja deletado acidentalmente ou por terraform destroy. Perda de dados irreversível.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'deletion_protection\s*=\s*false',
        remediation="Defina deletion_protection = true em todos os bancos de dados de produção. Combine com lifecycle { prevent_destroy = true } para proteção adicional.",
        cwe="CWE-693",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="TF-009",
        name="Porta SSH (22) Aberta para Internet",
        description="Ingress na porta 22 de 0.0.0.0/0 expõe o servidor SSH à internet. Brute force, ataques de credential stuffing e exploração de vulnerabilidades SSH são vetores comuns.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TERRAFORM,
        pattern=r'from_port\s*=\s*22[^0-9].*to_port\s*=\s*22|from_port\s*=\s*0\s.*to_port\s*=\s*65535',
        remediation="Restrinja SSH a IPs específicos ou use AWS Systems Manager Session Manager para acesso sem porta 22 aberta. Use VPN ou bastion host para acesso interno.",
        cwe="CWE-284",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="TF-010",
        name="Versão do Terraform Provider Não Fixada",
        description="version = \">= 1.0\" sem limite superior permite que atualizações de provider quebrem a infraestrutura silenciosamente ou introduzam mudanças breaking.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SUPPLY_CHAIN,
        language=Language.TERRAFORM,
        pattern=r'version\s*=\s*">=\s*[\d.]+"(?!\s*,\s*"<)',
        remediation="Use versão exata ou range fechado: version = \"~> 5.0\" ou version = \">= 5.0, < 6.0\". Execute terraform init -upgrade controlado com revisão de mudanças.",
        cwe="CWE-1104",
        confidence=Confidence.MEDIUM,
    ),
]
