"""Regras de segurança para T-SQL Stored Procedures — 9 regras (TSQLP-001..009)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

TSQL_PROC_RULES: list[Rule] = [
    Rule(
        id="TSQLP-001",
        name="SQL Dinâmico com EXEC() / EXECUTE() — SQL Injection",
        description="'EXEC(@sql)' ou 'EXECUTE(@variavel)' em T-SQL executa uma string construída dinamicamente. Com partes da string derivadas de input externo (parâmetros de stored procedure, dados de tabela), é possível injetar SQL arbitrário com as permissões do contexto de execução da procedure.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.TSQL,
        pattern=r'EXEC(?:UTE)?\s*\(\s*@\w+',
        remediation="Use sp_executesql com parâmetros: EXEC sp_executesql @sql, N'@id INT', @id = @InputId. Defina a query como template: SET @sql = N'SELECT * FROM Orders WHERE Id = @id'. Nunca concatene input do usuário na string SQL. Use QUOTENAME() para nomes de objetos dinâmicos.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TSQLP-002",
        name="xp_cmdshell — Execução de Comandos OS no SQL Server",
        description="'xp_cmdshell' executa comandos do sistema operacional com as permissões da conta de serviço do SQL Server (geralmente LocalSystem ou uma conta de domínio). Qualquer usuário com EXECUTE on xp_cmdshell pode executar comandos arbitrários no servidor, instalar backdoors e exfiltrar dados.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.TSQL,
        pattern=r'\bxp_cmdshell\b',
        remediation="Desabilite xp_cmdshell: EXEC sp_configure 'xp_cmdshell', 0; RECONFIGURE; Para operações que precisam do OS (mover arquivos, executar scripts), use SQL Server Agent jobs com contas de serviço dedicadas e auditadas. Considere SQLCLR apenas se xp_cmdshell for absolutamente necessário.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="TSQLP-003",
        name="sp_OACreate — Automação COM no SQL Server",
        description="'sp_OACreate' e 'sp_OAMethod' habilitam OLE Automation no SQL Server, permitindo instanciar objetos COM como WScript.Shell, ADODB.Stream e MSXML2.XMLHTTP. Isso é um vetor clássico de webshell e privilege escalation que contorna todos os controles de SQL Server.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.TSQL,
        pattern=r'\bsp_OA(?:Create|Method|GetProperty|SetProperty|Stop|Destroy)\b',
        remediation="Desabilite OLE Automation: EXEC sp_configure 'Ole Automation Procedures', 0; RECONFIGURE; Para operações que precisavam de sp_OA (ex: HTTP calls), use SQLCLR com código .NET controlado, SQL Server Integration Services (SSIS), ou serviços externos. Monitore com triggers de DDL.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-004",
        name="OPENROWSET / OPENDATASOURCE — Conexão a Fontes Externas",
        description="'OPENROWSET' e 'OPENDATASOURCE' permitem conexões ad-hoc a fontes de dados externas (outros SQL Servers, Excel, CSV). Podem ser usados para conectar a servidores externos, fazer SSRF dentro da rede, acessar o filesystem e exfiltrar dados via conexões não autorizadas.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TSQL,
        pattern=r'\bOPEN(?:ROWSET|DATASOURCE)\s*\(',
        remediation="Desabilite OPENROWSET: EXEC sp_configure 'Ad Hoc Distributed Queries', 0; RECONFIGURE; Para acesso a fontes externas legítimas, use Linked Servers configurados pelo DBA com credenciais mínimas e monitore via SQL Server Audit. Revogue permissão de ad hoc queries para usuários de aplicação.",
        cwe="CWE-918",
        owasp="A10:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-005",
        name="BULK INSERT de Arquivo Externo",
        description="'BULK INSERT ... FROM \"caminho\"' lê arquivos diretamente do filesystem do servidor SQL (ou de compartilhamentos de rede UNC). Com input controlado, pode ler arquivos arbitrários do sistema. Também pode ser usado para ataques NTLM relay via UNC paths: FROM '\\\\attacker\\share\\data.csv'.",
        severity=Severity.HIGH,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TSQL,
        pattern=r'BULK\s+INSERT\s+\w+\s+FROM\s+["\']',
        remediation="Substitua BULK INSERT por OPENROWSET com arquivo fixo: OPENROWSET(BULK N'C:\\SafeDir\\data.csv', SINGLE_CLOB). Restrinja com BULK INSERT apenas a diretórios pré-aprovados via permissão de filesystem. Prefira SqlBulkCopy via aplicação .NET que processa o arquivo no lado do cliente.",
        cwe="CWE-73",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-006",
        name="Linked Server com Credenciais Hardcoded",
        description="'sp_addlinkedserver' com 'sp_addlinkedsrvlogin ... @rmtpassword' expõe credenciais de servidores remotos no código T-SQL. Scripts de configuração com essas chamadas armazenam senhas em texto claro em repositórios de código ou histórico de queries do SQL Server.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.TSQL,
        pattern=r'sp_addlinkedsrvlogin\s+[^,]+,[^,]+,[^,]+,[^,]+,\s*["\'][^"\']+["\']',
        remediation="Use self-mapping (credenciais do contexto atual): sp_addlinkedsrvlogin @rmtsrvname=N'Server2', @useself=N'True'. Para contas dedicadas, use SQL Server Credential Store em vez de hardcode. Audite linked servers existentes: SELECT * FROM sys.linked_logins sl JOIN sys.servers s ON sl.server_id=s.server_id.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-007",
        name="CATCH sem Logging de Erro — Exception Swallowing",
        description="Blocos BEGIN CATCH sem RAISERROR, THROW ou logging da mensagem de erro silenciam exceções. Erros de constraint, deadlocks e falhas de integridade desaparecem sem trace. Em stored procedures de segurança (login, autorização), erros silenciados podem permitir bypass de controles.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.TSQL,
        pattern=r'BEGIN\s+CATCH\s*\n\s*(?:--[^\n]*\n\s*)*END\s+CATCH',
        remediation="Sempre re-lance ou logue erros no CATCH: BEGIN CATCH; DECLARE @msg NVARCHAR(MAX) = ERROR_MESSAGE(); INSERT INTO ErrorLog(Message, ProcedureName, LineNumber) VALUES(@msg, ERROR_PROCEDURE(), ERROR_LINE()); THROW; END CATCH. Use THROW sem parâmetros para re-lançar o erro original com contexto.",
        cwe="CWE-390",
        owasp="A05:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-008",
        name="WITH EXECUTE AS — Impersonation Perigosa",
        description="'WITH EXECUTE AS \"dbo\"' ou 'WITH EXECUTE AS OWNER' em stored procedures executam a procedure com um contexto de segurança diferente do chamador. Se a procedure não valida input adequadamente, um usuário não privilegiado pode executar operações com permissões elevadas (dbo, sysadmin).",
        severity=Severity.HIGH,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.TSQL,
        pattern=r'WITH\s+EXECUTE\s+AS\s+(?:["\'](?:dbo|sa|sysadmin|owner)["\']|OWNER\b)',
        remediation="Prefira EXECUTE AS CALLER (padrão) para que a procedure use as permissões do chamador. Se EXECUTE AS é necessário para acesso a recursos específicos, use um login de baixo privilégio dedicado: WITH EXECUTE AS 'limited_service_account'. Audite procedures com EXECUTE AS via sys.sql_modules.",
        cwe="CWE-269",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
    Rule(
        id="TSQLP-009",
        name="Cursor Sem FAST_FORWARD ou READ_ONLY",
        description="Cursores T-SQL sem 'FAST_FORWARD' ou 'READ_ONLY' são cursores bidirecional mutáveis por padrão, permitindo UPDATE via cursor ('WHERE CURRENT OF cursor'). Em procedures que processam dados de usuário, um cursor updatable pode ser usado para modificar dados de outros registros se o filtro for contornado.",
        severity=Severity.LOW,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.TSQL,
        pattern=r'DECLARE\s+\w+\s+CURSOR\s+FOR',
        negative_pattern=r'FAST_FORWARD|READ_ONLY|STATIC',
        remediation="Use cursores somente-leitura quando não for necessário atualizar: DECLARE cur CURSOR FAST_FORWARD FOR SELECT ... Para performance e segurança, prefira operações set-based (SELECT, UPDATE com WHERE) em vez de cursores. Se atualização for necessária, use CURSOR FORWARD_ONLY UPDATE OF col1.",
        cwe="CWE-269",
        confidence=Confidence.LOW,
        flags=re.IGNORECASE,
    ),
]
