"""Regras de segurança para Visual Basic / VB.NET."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

VB_RULES: list[Rule] = [
    Rule(
        id="VB-001",
        name="SqlCommand com Concatenação de String — SQL Injection",
        description="SqlCommand com concatenação de strings em queries SQL é o vetor mais comum de SQL Injection em aplicações .NET legadas. Dados do usuário não parameterizados são executados como código SQL.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SQL_INJECTION,
        language=Language.VBNET,
        pattern=r'New\s+SqlCommand\s*\([^,)]*&\s*\w+|ExecuteQuery\s*\([^)]*&|"SELECT\s+.*"\s*&',
        remediation="Use SqlParameter: cmd.Parameters.AddWithValue(\"@param\", valor). Ou use ORM como Entity Framework com LINQ para parameterização automática.",
        cwe="CWE-89",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-002",
        name="Process.Start com Input do Usuário — Command Injection",
        description="Process.Start com argumentos derivados de input do usuário permite execução de comandos arbitrários no servidor.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.VBNET,
        pattern=r'Process\.Start\s*\([^)]*(?:Request\.|txtInput|userInput|\bparam\b)',
        remediation="Nunca passe input de usuário diretamente a Process.Start. Use uma allowlist estrita de comandos e argumentos permitidos. Prefira APIs .NET nativas.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-003",
        name="Response.Write com Request — XSS Refletido",
        description="Response.Write(Request.QueryString(\"x\")) ou Response.Write(Request.Form(\"x\")) reflete input do usuário diretamente na resposta HTML sem encoding. XSS clássico de ASP/VB.",
        severity=Severity.CRITICAL,
        category=VulnCategory.XSS,
        language=Language.VBNET,
        pattern=r'Response\.Write\s*\([^)]*Request\.',
        remediation="Use Server.HtmlEncode() ou HttpUtility.HtmlEncode() antes de exibir qualquer input do usuário. Melhor ainda: use controles ASP.NET que encodam automaticamente.",
        cwe="CWE-79",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-004",
        name="Senha Hardcoded em VB.NET",
        description="Credenciais hardcoded em código VB.NET são commitadas no repositório e extraíveis de assemblies .NET compilados com decompiladores como ILSpy.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.VBNET,
        pattern=r'(?:Dim|Const)\s+\w*(?:Password|Senha|Secret|APIKey|Token)\w*\s+As\s+String\s*=\s*"[^"]{6,}"',
        remediation="Use System.Configuration.ConfigurationManager com seção encriptada, ou Azure Key Vault / AWS Secrets Manager. Nunca hardcode credenciais.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-005",
        name="MD5/SHA1 para Hash de Senha",
        description="MD5 e SHA1 são algoritmos criptográficos quebrados para hashing de senhas. São rápidos demais e sujeitos a rainbow tables.",
        severity=Severity.HIGH,
        category=VulnCategory.CRYPTO,
        language=Language.VBNET,
        pattern=r'MD5\.Create\s*\(\s*\)|SHA1\.Create\s*\(\s*\)|New\s+MD5CryptoServiceProvider',
        remediation="Use BCrypt.Net-Next ou Argon2 para hashing de senhas. Para checksums não-criptográficos, use SHA-256 ou SHA-512.",
        cwe="CWE-327",
        owasp="A02:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-006",
        name="Catch Genérico sem Tratamento — Exception Swallowing",
        description="Catch sem tipo específico captura todas as exceções silenciosamente, escondendo erros de segurança e bugs críticos. Erros são perdidos sem logging adequado.",
        severity=Severity.MEDIUM,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.VBNET,
        pattern=r'Catch\s+(?:ex|e|exception|err)\s+As\s+Exception\s*$',
        negative_pattern=r'(?:Throw|log|Log|Logger)',
        remediation="Capture exceções específicas (SqlException, IOException, etc.). Se capturar Exception, sempre logue e re-lance ou trate adequadamente. Nunca engula exceções silenciosamente.",
        cwe="CWE-390",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VB-007",
        name="Shell() Sem Sanitização — Command Injection",
        description="A função Shell() do Visual Basic executa comandos no sistema operacional. Com input do usuário não sanitizado, permite execução de comandos arbitrários.",
        severity=Severity.CRITICAL,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.VBNET,
        pattern=r'\bShell\s*\([^)]*(?:&|\+|txtInput|Request\.|userInput)',
        remediation="Evite Shell(). Use Process.Start com argumentos como lista (não string concatenada) e valide rigorosamente cada argumento contra uma allowlist.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VB-008",
        name="Número Aleatório Inseguro (Rnd() / New Random)",
        description="Rnd() e New Random() em VB.NET não são criptograficamente seguros. Predictibilidade compromete tokens de sessão, UUIDs, ou qualquer valor que requer imprevisibilidade.",
        severity=Severity.MEDIUM,
        category=VulnCategory.WEAK_RANDOMNESS,
        language=Language.VBNET,
        pattern=r'\bRnd\s*\(\s*\)|\bNew\s+Random\s*\(\s*\)',
        remediation="Use System.Security.Cryptography.RandomNumberGenerator para operações de segurança. Ou RNGCryptoServiceProvider.GetBytes() para gerar tokens criptograficamente seguros.",
        cwe="CWE-338",
        confidence=Confidence.MEDIUM,
    ),
]
