"""Regras de segurança para Vyper (Smart Contracts EVM) — 8 regras (VYPER-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

VYPER_RULES: list[Rule] = [
    Rule(
        id="VYPER-001",
        name="Função Payable sem Proteção contra Reentrância",
        description="Funções payable em Vyper que enviam ETH (send, raw_call com value) sem o decorator @nonreentrant são vulneráveis a ataques de reentrância. Um contrato malicioso pode chamar de volta a função durante a execução do send, antes de o estado ser atualizado, drenando o contrato.",
        severity=Severity.CRITICAL,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.VYPER,
        pattern=r'@payable\s*\ndef\s+\w+[^:]*:(?:[^@])*(?:send\s*\(|raw_call\s*\([^)]*value\s*=)',
        negative_pattern=r'@nonreentrant',
        remediation="Adicione @nonreentrant('lock') em todas as funções que enviam ETH: @nonreentrant('lock'); @payable; @external; def withdraw(): send(msg.sender, amount). Siga o padrão Checks-Effects-Interactions: verifique condições, atualize state, depois envie ETH. Vyper tem proteção built-in de reentrância com o decorator.",
        cwe="CWE-362",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VYPER-002",
        name="raw_call sem Verificação de Retorno",
        description="'raw_call(addr, data)' em Vyper faz uma call de baixo nível para outro contrato. Sem 'assert raw_call(...)' ou verificação do bool de retorno, falhas silenciosas passam despercebidas. Um contrato destino que falha em processar a call não reverte a transação do contrato chamador.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.VYPER,
        pattern=r'raw_call\s*\([^)]+\)(?!\s*\n\s*assert)',
        remediation="Sempre verifique o retorno: success: bool = raw_call(target, data, max_outsize=0); assert success, 'Call failed'. Para transferências de ETH, prefira send() que automaticamente reverte em falha. Use a sintaxe de higher-level call quando possível em vez de raw_call.",
        cwe="CWE-252",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VYPER-003",
        name="selfdestruct — Destruição Permanente do Contrato",
        description="'selfdestruct(recipient)' em Vyper destrói o contrato permanentemente e envia todo ETH para o recipient. Se chamável por qualquer conta (sem controle de acesso), um atacante pode destruir o contrato e roubar todos os fundos. Mesmo com controle de acesso, é uma operação irreversível de alto risco.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.VYPER,
        pattern=r'\bselfdestruct\s*\(',
        remediation="Evite selfdestruct — é deprecated no EIP-6780 (Ethereum após Cancun). Para desabilitação de contrato, use um pattern de 'pause': implements owner check, sets paused=True, rejeita chamadas. Para upgrade de contrato, use proxy patterns. Se selfdestruct é necessário, restrinja a multisig com timelock.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.HIGH,
    ),
    Rule(
        id="VYPER-004",
        name="block.timestamp para Lógica Crítica",
        description="'block.timestamp' em Vyper pode ser manipulado pelo miner/validator em até ~15 segundos (regra de consenso). Para lógica crítica como expiração de leilões, janelas de votação ou releases de vesting, essa manipulação pode alterar o resultado a favor do validator que propõe o bloco.",
        severity=Severity.MEDIUM,
        category=VulnCategory.SECURITY_MISCONFIG,
        language=Language.VYPER,
        pattern=r'block\.timestamp\s*(?:==|!=|>|<|>=|<=)',
        remediation="Para janelas de tempo com precisão necessária, use block.number como referência (12s/bloco no Ethereum). Para VRF (randomness), use Chainlink VRF em vez de block.timestamp ou block.hash. Aceite uma janela de tolerância de 15-30 segundos em verificações de timestamp para resistir à manipulação do miner.",
        cwe="CWE-330",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VYPER-005",
        name="Aritmética sem Verificação de Overflow (Unsafe Math)",
        description="Em Vyper, por padrão as operações aritméticas revertam em overflow/underflow. Mas ao usar 'unsafe_add', 'unsafe_sub', 'unsafe_mul', 'unsafe_div' ou conversões de tipo explícitas (convert), o programador assume responsabilidade pela verificação. Overflow não detectado leva a estados incorretos.",
        severity=Severity.HIGH,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.VYPER,
        pattern=r'\bunsafe_(?:add|sub|mul|div)\s*\(',
        remediation="Use operações aritméticas padrão de Vyper que revertem automaticamente em overflow: balance += amount em vez de unsafe_add(balance, amount). Use unsafe_ apenas em loops internos onde você pode provar matematicamente que overflow é impossível (ex: contadores de array indexados por len()). Documente o raciocínio.",
        cwe="CWE-190",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VYPER-006",
        name="Controle de Acesso Ausente em Função Administrativa",
        description="Funções que transferem ownership, upgrades de implementação, pausam o contrato ou alteram parâmetros críticos sem verificação de 'msg.sender == owner' ou similar podem ser chamadas por qualquer endereço. Perda de controle administrativo pode resultar em drenagem de fundos ou manipulação do protocolo.",
        severity=Severity.CRITICAL,
        category=VulnCategory.BROKEN_ACCESS,
        language=Language.VYPER,
        pattern=r'def\s+(?:set_owner|transfer_ownership|upgrade|pause|update_fee|set_admin|withdraw_all)\s*\(',
        negative_pattern=r'assert\s+msg\.sender\s*==\s*(?:self\.owner|owner|admin)',
        remediation="Sempre verifique permissões: @external; def set_owner(new_owner: address): assert msg.sender == self.owner, 'Not owner'; self.owner = new_owner. Para operações críticas, use multisig como owner (Gnosis Safe). Implemente timelock para mudanças de parâmetros: proposta + delay + execução.",
        cwe="CWE-284",
        owasp="A01:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="VYPER-007",
        name="Variável de Storage com Visibilidade Public Desnecessária",
        description="Variáveis de storage marcadas como 'public' em Vyper geram automaticamente getter functions externas. Variáveis com dados sensíveis (keys, salts internos, parâmetros de protocolo privados) marcadas como public expõem informações que podem ser usadas para construir ataques.",
        severity=Severity.LOW,
        category=VulnCategory.INFO_DISCLOSURE,
        language=Language.VYPER,
        pattern=r'(?:fee_numerator|internal_key|salt|nonce_tracker|_operator|emergency_key)\s*:\s*public\s*\(',
        remediation="Remova 'public()' de variáveis que não precisam de getter externo. Em Vyper, variáveis sem public() são apenas acessíveis internamente e via funções explícitas com controle de acesso. Revise todas as variáveis public() e questione se a exposição é necessária.",
        cwe="CWE-200",
        owasp="A05:2021",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="VYPER-008",
        name="Uso de ERC20 Transfer sem Verificação de Retorno",
        description="Tokens ERC20 antigos (USDT, BNB) não revertam na falha de transfer — retornam false. Chamar token.transfer(addr, amount) sem verificar o bool de retorno resulta em transferências que 'silenciosamente falham': o contrato pensa que transferiu mas o token não foi movido, causando inconsistência de estado.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.VYPER,
        pattern=r'ERC20\s*\(\s*\w+\s*\)\s*\.\s*transfer\s*\([^)]+\)(?!\s*,)',
        remediation="Verifique o retorno: success: bool = ERC20(token).transfer(recipient, amount); assert success, 'Transfer failed'. Considere usar SafeERC20 patterns ou uma interface que assume revert on failure (tokens modernos). Para tokens que não retornam bool, use raw_call e parse o returndata.",
        cwe="CWE-252",
        owasp="A04:2021",
        confidence=Confidence.MEDIUM,
    ),
]
