"""Regras de segurança para Zig — 8 regras (ZIG-001..008)."""
import re
from analyzer.models import Severity, Confidence, Language, VulnCategory
from analyzer.rules.base import Rule

ZIG_RULES: list[Rule] = [
    Rule(
        id="ZIG-001",
        name="Cast Inseguro de Ponteiro via @ptrCast",
        description="@ptrCast() em Zig converte um ponteiro de um tipo para outro sem verificação. Se os alinhamentos ou tamanhos dos tipos forem incompatíveis, causa comportamento indefinido. Em código que interage com dados externos (parsing de protocolo, FFI), pode resultar em leitura de dados fora dos limites esperados.",
        severity=Severity.HIGH,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.ZIG,
        pattern=r'@ptrCast\s*\(',
        remediation="Use @alignCast em conjunto com @ptrCast quando necessário: const ptr = @ptrCast(*T, @alignCast(@alignOf(T), raw_ptr)). Prefira std.mem.bytesAsValue(T, &bytes) que verifica alinhamento. Para FFI, use tipos C explícitos de std.os.linux.",
        cwe="CWE-704",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ZIG-002",
        name="Conversão Insegura de Inteiro para Ponteiro via @intToPtr",
        description="@intToPtr(T, addr) cria um ponteiro a partir de um endereço inteiro. Se addr vem de input externo ou cálculo não verificado, o ponteiro pode apontar para qualquer endereço de memória — nulo, fora dos limites ou em região privilegiada, causando crash ou acesso não autorizado.",
        severity=Severity.CRITICAL,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.ZIG,
        pattern=r'@intToPtr\s*\(',
        remediation="Evite @intToPtr com valores externos. Para hardware registers (embarcado), documente o endereço base e use comptime const verificados: const BASE: usize = 0x4000_0000; // verified address. Nunca use @intToPtr com valores calculados de input do usuário.",
        cwe="CWE-119",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ZIG-003",
        name="Uso de 'undefined' em Valor Não Inicializado",
        description="var x: T = undefined em Zig cria um valor não inicializado. Em modo ReleaseFast e ReleaseSmall, não há detecção de uso de undefined — ler um valor undefined é comportamento indefinido que pode resultar em dados sensíveis de memória sendo expostos ou comportamento imprevisível.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.ZIG,
        pattern=r'=\s*undefined\b',
        remediation="Inicialize variáveis explicitamente: var buf: [256]u8 = std.mem.zeroes([256]u8). Para buffers, use @memset: @memset(&buf, 0). Se undefined é necessário por performance, certifique-se de escrever antes de ler e use comentário documentando o invariante.",
        cwe="CWE-457",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ZIG-004",
        name="Injeção de Comando via std.ChildProcess.exec / std.process.exec",
        description="std.ChildProcess.exec() e std.process.exec() executam programas externos. Com argv construído a partir de input externo não validado, um atacante pode modificar argumentos para explorar comportamentos do executável chamado ou executar binários diferentes.",
        severity=Severity.HIGH,
        category=VulnCategory.COMMAND_INJECTION,
        language=Language.ZIG,
        pattern=r'std\.ChildProcess\.(?:exec|spawn|run)|std\.process\.exec\s*\(',
        remediation="Valide cada elemento do argv contra uma whitelist antes de executar: for (argv) |arg| { if (!isAllowed(arg)) return error.ForbiddenArg; }. Use caminhos absolutos para executáveis e verifique que o arquivo existe e é executável antes de spawnar.",
        cwe="CWE-78",
        owasp="A03:2021",
        confidence=Confidence.MEDIUM,
    ),
    Rule(
        id="ZIG-005",
        name="Truncamento Silencioso via @truncate sem Validação",
        description="@truncate(T, value) descarta bits de ordem superior sem aviso. Em código que processa comprimentos de dados, offsets ou índices de array vindos de input externo, truncamento silencioso pode causar integer underflow/overflow e acesso fora dos limites.",
        severity=Severity.MEDIUM,
        category=VulnCategory.IMPROPER_VALIDATION,
        language=Language.ZIG,
        pattern=r'@truncate\s*\(',
        remediation="Verifique que o valor cabe no tipo alvo antes de truncar: if (value > std.math.maxInt(u16)) return error.Overflow; const small = @intCast(u16, value). Use @intCast que causa panic se o valor não cabe, fornecendo proteção automática.",
        cwe="CWE-190",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ZIG-006",
        name="Cast de Alinhamento Inseguro via @alignCast",
        description="@alignCast(alignment, ptr) em Zig reinterpreta um ponteiro com alinhamento diferente. Se o ponteiro de origem não satisfaz o alinhamento requerido, o comportamento é indefinido em modo Release. Em Debug, um panic de runtime é gerado, mas em Release o acesso misaligned causa UB.",
        severity=Severity.MEDIUM,
        category=VulnCategory.MEMORY_SAFETY,
        language=Language.ZIG,
        pattern=r'@alignCast\s*\(',
        remediation="Verifique o alinhamento antes do cast: std.debug.assert(std.mem.isAligned(@ptrToInt(ptr), @alignOf(T))). Para dados de rede/arquivo que podem não estar alinhados, use std.mem.readIntSliceLittle(T, slice) para leitura segura.",
        cwe="CWE-704",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ZIG-007",
        name="'unreachable' em Código de Release — Comportamento Indefinido",
        description="unreachable em Zig causa panic em Debug/ReleaseSafe, mas em ReleaseFast e ReleaseSmall resulta em comportamento indefinido puro. Se um caminho de código marcado como unreachable for atingido com input externo inesperado, o resultado é totalmente imprevisível e explorável.",
        severity=Severity.HIGH,
        category=VulnCategory.ERROR_HANDLING,
        language=Language.ZIG,
        pattern=r'\bunreachable\b',
        remediation="Use @panic(\"mensagem\") para condições que nunca devem ocorrer mas onde você quer um crash controlado em todos os modos de build. Ou use um error return: return error.UnexpectedState. Evite unreachable em caminhos de código que processam input externo.",
        cwe="CWE-617",
        confidence=Confidence.LOW,
    ),
    Rule(
        id="ZIG-008",
        name="Credencial Hardcoded em Código Zig",
        description="Constantes ou arrays de bytes com senhas, tokens ou chaves API definidos como comptime em código Zig. Binários Zig podem ser analisados com ferramentas de engenharia reversa para extrair strings constantes, expondo credenciais.",
        severity=Severity.CRITICAL,
        category=VulnCategory.HARDCODED_SECRETS,
        language=Language.ZIG,
        pattern=r'(?:const|var)\s+\w*(?:password|secret|api_key|token|auth)\w*\s*=\s*["\\\w]+',
        remediation="Leia credenciais em runtime de variáveis de ambiente: const api_key = std.os.getenv(\"API_KEY\") orelse @panic(\"API_KEY not set\"). Para aplicações embarcadas sem SO, use um bootloader seguro que injeta credenciais em memória protegida.",
        cwe="CWE-798",
        owasp="A02:2021",
        confidence=Confidence.MEDIUM,
        flags=re.IGNORECASE,
    ),
]
